Feature/generator_minetest
ignfab/voxatile pull request #1
Opened 2023-11-10 17:38 UTC by zhak5388

**Première version du générateur de carte minetest.** 

- Le programme génère un dossier qui sera reconnu comme une carte par Minetest s'il est placé dans le bon dossier.
- La classe `SampleImplementation` est une classe qui génère une carte d'une représentation d'un modèle numérique de terrain) afin d'avoir une idée de comment le programme fonctionne

**Maven**
- `pom.xml `contient les instructions nécessaire pour faire un jar qui permet de lancer la classe SampleImplemention
- Example commande pour lancer la classe SampleImplementation:
`mvn compile exec:java -Dexec.mainClass="com.ignfab.minalac.generator.SampleImplementation" -Dexec.args="/home/john/.minetest/worlds/map/ https://data.geopf.fr/wms-r/wms?LAYERS=RGEALTI-MNT_PYR-ZIP_FXX_LAMB93_WMS&FORMAT=image/x-bil;bits=32&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&STYLES=&CRS=EPSG:2154&BBOX=595000,6335000,605000,6345000&WIDTH=1000&HEIGHT=1000"`

2023-11-23 15:57 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelFactory.java
> +        if (semanticType == SemanticType.Grass) {
Ici ça pourrait être un switch au lieu des ifs

2023-11-23 15:57 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        String wxsUrl = "https://wxs.ign.fr/altimetrie/geoportail/r/wms?LAYERS=RGEALTI-MNT_PYR-ZIP_FXX_LAMB93_WMS&FORMAT=image/x-bil;bits=32&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&STYLES=&CRS=EPSG:
Tu peux passer BBOX, WIDTH, HEIGHT dans les paramètres de la ligne de commande (args), pour pouvoir tester plusieurs trucs.

2023-11-23 15:57 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +    private static void createMShape(VoxelWorld world, int sizeShape) {
On peut déjà virer ces fonctions de test et ne garder que la partie MNT qui est suffisante pour tester.

2023-11-23 15:57 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/Block.java
> +        int i = z * 16 * 16 + y * 16 + x;
Il faudrait vérifier que chacun des paramètres est compris entre 0 et 15 et lever une exception sinon

2023-11-23 15:57 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelWorld.java
> +    public void set(int x, int y, int z, MTVoxelType voxel) {
Ici aussi, il faudrait contrôler que les paramètres sont bien entre -32768 et +32767 (vérifier dans la doc MT les valeurs)
Ou alors, si java le permet, utiliser des int 32 bits.

2023-11-23 15:57 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelWorld.java
> +        Block block = blocks.get(pos);
```suggestion
        Block block = blocks.get(getPos(x / 16, y / 16, z / 16));
```

2023-11-23 15:57 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelWorld.java
> +        }
```suggestion
        if (block == null) {
            block = new Block();
        }
        //Node/voxel's coordinates relatively to the block
        block.set(x % 16, y % 16, z % 16, voxel);
        this.blocks.put(pos, block);
```

2023-11-23 15:57 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelWorld.java
> +            database.insertBlock(pos, block);
```suggestion
            database.insertBlock(entry.getKey(), entry.getValue());
```

2023-11-23 15:57 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +        byte[] newArray = new byte[array.length * 2];
Je ne sais pas comment faire (ni si c'est possible) mais ça serait bien mieux d'éviter une copie ici.

2023-12-08 15:43 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        String wxsUrl = "https://wxs.ign.fr/altimetrie/geoportail/r/wms?LAYERS=RGEALTI-MNT_PYR-ZIP_FXX_LAMB93_WMS&FORMAT=image/x-bil;bits=32&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&STYLES=&CRS=EPSG:
Pour l'instant c'est l’entièreté de l'URL qui est passée en paramètre, ça va évoluer quand les requesters seront intégrés

2023-12-08 15:52 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelWorld.java
> +    public void set(int x, int y, int z, MTVoxelType voxel) {
Les valeurs semblent être -30912 et 30912, ces valeurs ne sont d'une source primaire de données (elles viennent du wiki). J'ai mis ces valeurs en attendant. La vérification se fait sur la méthode place() de MTVoxelType car c'est celle qui appelle set() de MTVoxelWorld

2023-12-14 09:11 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelFactory.java
> +        }
(à discuter) Tu peux mettre ça dans la méthode createVoxelType, un truc du genre:
``` 
        switch (semanticType) {
            case Grass:
                return new MTSimpleVoxelType(this.world, "default:dirt_with_grass");
            case Stone:
                return new MTSimpleVoxelType(this.world, "default:stone");
            ...
```
J'imagine que plus tard on va finir par arriver à un truc comme ça quand on aura plusieurs classes de Voxel Type.

2023-12-14 09:11 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +        byte[] newArray = new byte[array.length * 2];
à y regarder de plus près, on peut effectivement éviter la copie en écrivant directement dans le stream.

2023-12-14 09:11 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelWorld.java
> +    public int getNodeRelativePosition(int p) {
Cette méthode peut être privée

2023-12-14 09:11 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelWorld.java
> +    public int getBlockPosition(int p) {
Idem, elle peut être privée (en revanche, pour les tests, je ne sais pas)

2023-12-14 09:11 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelWorld.java
> +    public int getPosValue(int x, int y, int z) {
Cette méthode peut être privée, et c'est mieux comme on ne vérifie pas les bornes ici.

2023-12-14 09:11 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/voxelType/MTVoxelType.java
> +            throw new OutOfWorldException();
Ce test devrait plutôt être dans le `get` de `MTVoxelWorld`, ça serait plus logique que ce soit le monde qui vérifie les limites.

2023-12-14 09:11 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/voxelType/MTVoxelType.java
> +    protected byte param2;
On va laisser ça comme ça pour l'instant mais c'est possible que dans le futur ces éléments migrent vers des classe enfant (on n'est pas sûr que chaque type corresponde à une seule combinaison de ces éléments).

2024-02-01 10:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            //Example "https://wxs.ign.fr/altimetrie/geoportail/r/wms?LAYERS=RGEALTI-MNT_PYR-ZIP_FXX_LAMB93_WMS&FORMAT=image/x-bil;bits=32&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&STYLES=&CRS=EPSG:21
Essayer avec "https://data.geopf.fr/wms-r/wms?LAYERS=RGEALTI-MNT_PYR-ZIP_FXX_LAMB93_WMS&FORMAT=image/x-bil;bits=32&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&STYLES=&CRS=EPSG:2154&BBOX=595000,6335000,605000,6345000&WIDTH=1000&HEIGHT=1000" et si ça marche, mettre à jour le commentaire.

2024-02-01 10:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            world.getFactory().createVoxelType(SemanticType.Grass).place(x, (y - 1), z);
```suggestion
            VoxelType grassVT = world.getFactory().createVoxelType(SemanticType.Grass);
            grassVT.place(x, y, z);
            grassVT.place(x, (y - 1), z);
```
Ça ressemblera plus à l'usage habituel je pense

2024-02-01 10:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                    world.getFactory().createVoxelType(SemanticType.RiverWater).place(x, y_water, z);
```suggestion
                VoxelType waterVT = world.getFactory().createVoxelType(SemanticType.Water);
                while (y_water > y) {
                    waterVT.place(x, y_water, z);
```
Idem

2024-02-01 10:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                while (y_water > y) {
```suggestion
                for (int y_water = min + waterHeight; y_water > y; y_water--) {
```

2024-02-01 10:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        }
```suggestion
        for (Float x : tab) {
            if (x < min) min = x;
        }
```
à tester

2024-02-01 10:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SemanticType.java
> +    Grass, Stone, Wood, Air, RiverWater, WaterLily
Je garderai Grass, Stone, Air et Water (pas RiverWater)

2024-02-01 10:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/Block.java
> +        if (nameIdMapping.containsValue(voxel.getType())) {
```suggestion
        if (idNameMapping.containsKey(voxel.getType())) {
```
Cela devrait être plus rapide, je suppose que le HashMap est optimisé pour trouver une clé mais pas forcément pour trouver une valeur (début d'explication [ici](https://stackoverflow.com/a/16757380)).

2024-02-01 10:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelFactory.java
> +                return "flowers:waterlily";
```suggestion
            case Water:
                return "default:water_source";
```

2024-02-01 10:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +        stream.write(bytes);
```suggestion
        stream.write((byte) (value & 0xFF));
```
À tester !
Peut être même qu'il n'y a pas besoin de caster, ou de filtrer.

2024-02-01 10:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +        stream.write(bytes);
```suggestion
        stream.write((byte) ((value >> 8) & 0xFF));
        stream.write(bytes[1] = (byte) (value & 0xFF));
```
Idem, à tester

2024-02-01 10:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +        stream.write(bytes);
```suggestion
        stream.write((byte) ((value >> 24) & 0xFF));
        stream.write((byte) ((value >> 16) & 0xFF));
        stream.write((byte) ((value >> 8) & 0xFF));
        stream.write((byte) (value & 0xFF));
```

2024-02-01 10:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/SqlMapCreator.java
> +            System.out.println(e.getMessage());
Vaudrait mieux jetter l'exception. Là, tout va continuer comme si de rien n'était et planter au moment du insertBlock, ça risque de rendre le debug plus compliqué.
De plus, plutôt qu'un println ici, il faudrait un Logger

2024-02-01 10:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/SqlMapCreator.java
> +            throw new RuntimeException(e);
Pas sûr pour la RuntimeException. Avoir une exception plus précise (genre "pas possible d'ecrire la map") permettrait de mieux la gérer en amont.

2024-02-01 11:02 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelWorld.java
> +    public int getPosValue(int x, int y, int z) {
Oui, j'ai utilise la reflexion pour les tests

2024-02-01 12:48 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            //Example "https://wxs.ign.fr/altimetrie/geoportail/r/wms?LAYERS=RGEALTI-MNT_PYR-ZIP_FXX_LAMB93_WMS&FORMAT=image/x-bil;bits=32&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&STYLES=&CRS=EPSG:21
Il y a juste besoin du proxy pour la nouvelle url

2024-02-01 12:51 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelFactory.java
> +        }
Je sais pas, ça me parait mieux de séparer les fonctions (dans le sens qu'il y a une fonction chargée de faire un switch et l'autre d'instancier)

2024-02-01 13:24 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +        stream.write(bytes);
Ca marche bien!

2024-02-01 13:45 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +        byte[] newArray = new byte[array.length * 2];
Oui! J'ai fait une fonction qui écrit directement

2024-02-02 13:05 UTC, pyrollo requested changes
Quelques trucs de style mais rien de particulier.
Pour l'exception, peut être que MapWriteException est plus adéquat.

2024-02-02 13:05 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            System.out.println("They must be two arguments : directoryPath and url");
```suggestion
            System.out.println("There must be two arguments : directoryPath and url");
```

2024-02-02 13:05 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/Block.java
> +        int i = z * 16 * 16 + y * 16 + x;
```suggestion
        int i = z * 256 + y * 16 + x;
```
Ou même (mais c'est moins lisible):
```suggestion
        int i = z << 8 | y << 4 | x;
```
(dans ce dernier cas, vérifier la précédence des opérations, je n'en suis pas sûr)

2024-02-02 13:05 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +            stream.write((byte) (param0 & 0xff));
```suggestion
            write16Bits(stream, param0);
```

2024-02-02 13:05 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +            stream.write(nodeTypeName.getBytes());
Il y a moyen d'itérer sur le HashMap directement, voici un exemple pris [ici](https://sentry.io/answers/iterate-hashmap-java/);
```suggestion
        this.block.getNameIdMapping().forEach((name, id) -> {
            //u16 : id
            write16Bits(stream, id);

            //u16 : name_len
            write16Bits(stream, name.length());

            //u8[name_len]
            stream.write(name.getBytes());
    });
```

2024-02-02 13:05 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +        write16Bits(stream, mapSize);
```suggestion
        write16Bits(stream, this.block.getNameIdMapping().size());
```
Car en iterant directement sur le HashMap, on n'a plus besoin de mapSize.

2024-02-02 13:05 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/SqlMapCreator.java
> +            throw new RuntimeException("Failed to insert blocks into map");
Faudrait utiliser ici aussi `MapCreationException`.

2024-02-02 13:39 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +            stream.write(nodeTypeName.getBytes());
L'expression lambda ne force à utiliser un try catch et j'ai essaye un for each et j'ai une erreur lors de l'ouverture de la carte sur minetest. Je laisse le code tel quel et j'y reviens plus tard

2024-02-02 13:59 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +            stream.write(nodeTypeName.getBytes());
Ok!

2024-02-07 08:58 UTC, pyrollo reviewed
Remarques sur la doc

2024-02-07 08:58 UTC, pyrollo commented on src/doc/QuickStart.md
> +# Example with Minetes
```suggestion
# Minetest example
```

2024-02-07 08:58 UTC, pyrollo commented on src/doc/QuickStart.md
> +
```suggestion
```

2024-02-07 08:58 UTC, pyrollo commented on src/doc/resources/Sample_VoxelInGameLocation_Noon.png
Ce fichier n'a pas l'air utilisé. En revanche, il me parait plus clair que celui qui est dans la doc.

2024-02-07 08:58 UTC, pyrollo commented on src/doc/QuickStart.md
> +### Generating the file map
```suggestion
### Generating the map file
```

2024-02-07 08:58 UTC, pyrollo commented on src/doc/QuickStart.md
> +# How to add new voxel
```suggestion
# How to add new voxel types
```

2024-02-07 08:58 UTC, pyrollo commented on src/doc/QuickStart.md
> +### Voxel positionning
```suggestion
### Voxel placing
```

2024-02-07 08:58 UTC, pyrollo commented on src/doc/QuickStart.md
> +In Minetest, the terms "nodes" is used to refer to its voxel. There are various of types of nodes, such as Dirt with Grass, Sand, etc.
```suggestion
In Minetest, the term "nodes" is used to refer to its voxels. There are various of types of nodes, such as Dirt with Grass, Sand, etc.
```

2024-02-07 08:58 UTC, pyrollo commented on src/doc/QuickStart.md
> +The way how `SemanticType` are associated with nodes can be found in the `MTVoxelFactory` class.
```suggestion
The way `SemanticType` are associated with nodes is found in the `MTVoxelFactory` class.
```

2024-02-07 16:36 UTC, pyrollo requested changes

2024-02-07 16:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/Block.java
> +    }
Ces deux méthodes vont être inutiles (à virer).

2024-02-07 16:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +    public void mapV28Serializer(OutputStream stream) throws IOException {
```suggestion
    public byte[] serialize(Block block) throws IOException {
        ByteArrayOutputStream stream = new ByteArrayOutputStream();

```

2024-02-07 16:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +    }
```suggestion
        return stream.toByteArray();    
    }
```

2024-02-07 16:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/SqlMapCreator.java
> +
```suggestion
    private Serializer serializer;

```

2024-02-07 16:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/SqlMapCreator.java
> +        this.sqlFileConnector = createAndConnectToFileDB(directoryFullPath);
```suggestion
        this.sqlFileConnector = createAndConnectToFileDB(directoryFullPath);
        this.serialize = new Serializer();
```

2024-02-07 16:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/SqlMapCreator.java
> +            statement.setBytes(2, block.blobData());
```suggestion
            statement.setBytes(2, serializer.serialize(block));
```

2024-02-07 16:39 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +    }
```suggestion
    public Serializer() {
    }
```

2024-02-07 16:53 UTC, pyrollo commented
Autre à faire :
- Ajouter le fichier world.mt
- Dans le démonstrateur:
   - Virer l'eau (si tu veux)
   - Virer le socle à 0
   - Utiliser des colonnes herbe, terre, pierre (x20) pour le mnt

2024-02-08 10:20 UTC, zhak5388 commented on src/doc/resources/Sample_VoxelInGameLocation_Noon.png
J'ai inclus les deux fichiers au final

2024-02-08 10:22 UTC, zhak5388 commented on src/doc/QuickStart.md
> +The way how `SemanticType` are associated with nodes can be found in the `MTVoxelFactory` class.
Alors, je peux me tromper, mais la première formulation me parait plus adaptée

2024-02-08 13:04 UTC, pyrollo commented on src/doc/QuickStart.md
> +The way how `SemanticType` are associated with nodes can be found in the `MTVoxelFactory` class.
Ok!

2024-02-08 13:30 UTC, pyrollo requested changes
Juste du style et du nommage

2024-02-08 13:30 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/VoxelFactory.java
> +public interface VoxelFactory {
Ce serait plus exact de l'appeler `VoxelTypeFactory` puisque cette classe fabrique des `VoxelType`.

2024-02-08 13:30 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelWorld.java
> +
```suggestion
```

2024-02-08 13:30 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/utils/Serializer.java
> +    public byte[] serializer(Block block) throws IOException {
```suggestion
    public byte[] serialize(Block block) throws IOException {
```
(plutôt un verbe qu'un nom pour une méthode)

2024-02-08 14:25 UTC, pyrollo commented
NOTE: Pour que ça marche derrière le proxy:
```
mvn compile exec:java \
  -Djava.net.useSystemProxies=true \
  ....
```

2024-02-09 08:32 UTC, pyrollo requested changes
Une (nouvelle) dernière broutille sur le nommage d'une méthode à changer.

2024-02-09 08:32 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/minetest/MTVoxelWorld.java
> +    private void fileCreator(String path, String content) throws MapWriteException {
```suggestion
    private void createFile(String path, String content) throws MapWriteException {
```
Plutôt des verbes pour les méthodes, des noms pour les objets (les objets sont des acteurs, les méthodes des actions).

2024-02-09 14:38 UTC, pyrollo requested changes
La der des der je pense !

2024-02-09 14:38 UTC, pyrollo commented on pom.xml
> +        </dependency>
```suggestion
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.9</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.9</version>
        </dependency>
```
Pour éviter les messages:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

```
Je ne sais pas qui en a besoin d'ailleurs de ce truc.

2024-02-09 15:13 UTC, pyrollo approved these changes

2024-02-09 15:17 UTC, merged