Add Minecraft output format
ignfab/voxatile pull request #11
Opened 2024-05-31 13:24 UTC by indyteo

Tests unitaires à venir, en attendant on peut review le code qui ne devrait pas (ou peu, quelques commentaires) changer.

2024-06-04 08:20 UTC, pyrollo requested changes
Deux trucs importants à changer:
- Ne pas remaper quand on est en Minetest, c'est vraiment gênant pour travailler dessus;
- Ajouter des commentaires aux commentaires (aux lignes de code commentées)

2024-06-04 08:20 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            int z = remap(element.getValue(), map.getMin(), map.getMax(), 64, 255); // Temporary workaround to generate Minecraft worlds
Même si c'est temporaire, ce serait bien plus logique de faire l'opération dans `createGroundHeightMap`.

EDIT: Pas si simple, ça se mord la queue. Faudrait plutôt, mais dans une autre PR, ajouter une méthode `remap` à `HeightMap` pour effectuer l'opperation.

2024-06-04 08:20 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            VoxelWorld world = FORMATS.get(format).get();
Un simple `if format == "minecraft" elsif format == "minetest"` faisait le job étant donné qu'on est dans du jetable ici.

2024-06-04 08:20 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            metadata.setSpawn(0, 0, remap(heightMap.get(0, 0) + 1, heightMap.getMin(), heightMap.getMax(), 64, 255)); // Tmp for Minecraft
Faudrait le conditionner au format, ça va gêner le travail côté Minetest de remapper.

2024-06-04 08:20 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            int z = remap(element.getValue(), map.getMin(), map.getMax(), 64, 255); // Temporary workaround to generate Minecraft worlds
Faudrait conditionner ça au format, ça va gêner le travail côté Minetest de remapper.

2024-06-04 08:20 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        public int getMin() {
Ça pourrait être un getBbox3d à la place des deux méthodes.

2024-06-04 08:20 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/outputs/minecraft/MCVoxelWorld.java
> +//                    dataPacks.put("Disabled", new ListTag<>(StringTag.class));
Il faut un commentaire pour expliquer ce commentaire.

2024-06-04 08:20 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/outputs/minecraft/MCVoxelWorld.java
> +                    //gameRules.putString("blockExplosionDropDecay", "true");
Idem pour ces commentaire, il faut expliquer pourquoi il sont là.

2024-06-04 08:20 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/outputs/minetest/MTVoxelWorld.java
> +        try (FileWriter fileWriter = new FileWriter(file); PrintWriter printWriter = new PrintWriter(fileWriter)) {
Peut-être plus clair comme ça ?
```suggestion
        try (
                FileWriter fileWriter = new FileWriter(file);
                PrintWriter printWriter = new PrintWriter(fileWriter)) {
```

2024-06-04 08:20 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world3d/WorldBBox3d.java
> +public class WorldBBox3d implements Iterable<WorldCoords3d> {
Je ne sais plus pourquoi on n'avait pas implémenté itérable sur la 2d, peut être parce que c'est inutile.

Dans tous les cas, il faudrait faire la même en 2d et 3d (l'ajouter ou l'enlever).

2024-06-04 08:31 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            int z = remap(element.getValue(), map.getMin(), map.getMax(), 64, 255); // Temporary workaround to generate Minecraft worlds
J'ai essayé justement de faire que pour Minecraft, mais c'était pas aussi évident que j'aurais voulu, du coup vu que c'est temporaire, j'ai laissé ça, mais on peut aussi le retirer et tant qu'on n'a pas intégrer les contraintes de hauteur proprement on ne génère plus en Minecraft

2024-06-04 08:37 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        public int getMin() {
Vu qu'il y a déjà la bbox2d dans l'ArrayChunk2d on pourrait effectivement combiner tout ça en 3d, après est-ce qu'on en aura besoin aucune idée, et de toute façon, les bbox étant immutables, il vaudra mieux stocker en minZ / maxZ. J'ajoute la méthode, on verra bien si elle est utile, elle coûte pas grand chose

2024-06-04 08:46 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/world3d/WorldBBox3d.java
> +public class WorldBBox3d implements Iterable<WorldCoords3d> {
Ah oui j'ai oublié de l'ajouter en 2D aussi. C'est peut-être pas utilisé, mais vu que la classe en est capable, c'est bien de le spécifier, pour éviter que le jour où on en ai besoin, on se rende pas compte qu'elle en était capable, et qu'on fasse autrement

2024-06-04 08:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            int z = remap(element.getValue(), map.getMin(), map.getMax(), 64, 255); // Temporary workaround to generate Minecraft worlds
Au final il faudra un système intelligent qui prend les contraines du format et qui les gère (avec éventuellement une politique : clip / scale / ??).

2024-06-04 09:10 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            int z = remap(element.getValue(), map.getMin(), map.getMax(), 64, 255); // Temporary workaround to generate Minecraft worlds
Oui, et il y a clairement plein de façons de le faire, pas forcément toutes bonnes, donc ça mérite réflexion et c'est pour ça que je propose de juste ignorer ces contraintes pour l'instant, quitte à ajouter un clamp/clip/scale directement dans le format Minecraft pour l'instant si on veut quand même générer sans OutOfWorldException

2024-06-04 14:41 UTC, pyrollo reviewed
Je ne vois rien à redire, je voudrais juste que Zen lise et approuve (avec ma bénédiction) s'il ne voit rien non plus.

2024-06-04 14:48 UTC, pyrollo submitted a review, later dismissed

2024-06-05 11:25 UTC, zhak5388 reviewed
Alors, pas grand chose à redire! Juste, j'ai repéré deux typos sur la doc : `WorldBBOX2d` pour la 3d et aditional (Je te met des commentaires pour que ça soit plus facile à trouver)

Une réflexion que je me suis faite en lisant, c'est que ça pourrait bien d'ajouter quelques rapides explications à l'avenir pour les classes `MTVoxelWorld` et `MCVoxelWorld` sur comment le format est "structuré". Comme je suis pas familier avec le format Minecraft ça m'a pris un petit temps de renter dedans, d'autant plus que j'avais les repères de minetest. Par exemple, je comprenais pas pourquoi spécifiquement 1024 chunks dans `save()` de `Region` avant de comprendre que (1 Region = 32x32 chunks, 1 Chunk = 16x16x(~320) voxels/blocks)

2024-06-05 11:25 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world3d/WorldBBox3d.java
> + * The {@code WorldBBox2d} class represents a three-dimensional bounding box that surrounds an area of the voxel world.
*`The {@code WorldBBox3d}`

2024-06-05 11:25 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world3d/WorldBBox3d.java
> +     * Create a new {@link WorldBBox3d} from an existing {@link WorldBBox2d} and aditional components along the z-axis.
*additional

2024-06-05 11:25 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldCoords2d.java
> +     * Convert this {@link WorldCoords2d} to {@link WorldCoords3d}, with an aditional {@code z} value.
Pareil ici additional

2024-06-05 11:25 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldSize2d.java
> +     * Convert this {@link WorldSize2d} to {@link WorldSize3d}, with an aditional size along the {@code z}-axis.
Ici aussi

2024-06-05 11:25 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world3d/WorldSize3d.java
> +     * Create a new {@link WorldSize3d} from an existing {@link WorldSize2d} and an aditional size along the {@code z}-axis.
Et enfin ici : )

2024-06-06 08:00 UTC, zhak5388 approved these changes

2024-06-06 08:05 UTC, merged