feat(world2d): Add world2d utility classes
ignfab/voxatile pull request #2
Opened 2024-03-05 15:35 UTC by pyrollo

Cette PR n'est pas tout à fait terminée.

Elle vise à créer des classes pour manipuler des morceaux de cartes 2d en voxels.

Deux interfaces importantes:
`ReadableVoxel2dMap` : objet contenant des données 2d voxelisées que l'on peut lire.
`WritableVoxel2dMap` : objet contenant des données 2d voxelisées que l'on peut écrire.

`Voxel2dMap` implémente ces deux interfaces et pourra nous servir au moins à jouer avec et à tester.

Au final, on aura d'autres objets qui implémentent `ReadableVoxel2dMap`. Par exemple, on pourrait encapsuer `Graphics2d` dans un `ReadableVoxel2dMap` pour le rendu des features (Selon le GML on écrit dans un `Graphics2d` et on l'expose via `ReadableVoxel2dMap` au renderers qui vont pouvoir modifier le VoxelWorld).

Les `ReadableVoxel2dMap` ont une valeur par défaut qui est la valeur à laquelle elles sont initialisées. Cette valeur peut aussi signifier que la cellule n'est pas concernée par la carte (en dehors de la feature par exemple).

Exemple de `ReadableVoxel2dMap` :
```
0 0 1 0 0
0 1 0 1 0
1 0 0 0 1
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
```
Si sa valeur par défaut est 0, on va pouvoir utiliser un iterateur pour ne dessiner que le "A" que forment les 1.

Ainsi, le code pour écrire la `ReadableVoxel2dMap` dans le monde peut être très simple:
```java
map.iter().forEachRemaining(
      (coord) -> {
          stoneVoxel.place(coord.x(), coord.y(), 0);
      }
);
```
`map` est un `ReadableVoxel2dMap` et `stoneVoxel` un `voxelType`.
L'itérateur va se cantonner aux 1.

Il reste à créer des `ReadableVoxel2dMap` qui contiennent nos données. On peut déjà facilement, avec `VoxelMap2d`, créer des petites images pour tester.

`VoxelMap2d` devrait aussi pouvoir être dérivée pour stocker les différentes HeightMap (ou, du moins, les HeightMaps pourraient implémenter les interfaces `ReadableVoxel2dMap`  et `WritableVoxel2dMap`)

2024-04-05 09:43 UTC, pyrollo reviewed
Quelques commentaires

2024-04-05 09:43 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/voxel2d/HeightMap.java
> +    }
Je voyais plutôt un truc qui teste le max de value et de l'existant pour le mettre.
Peut être `raise` n'est pas le bon terme pour ce que j'imaginais.
--> Comme vu ensemble, on va virer `raise` pour l'instant et ajouter ce qu'il manque au moment où on en aura besoin.

2024-04-05 09:43 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        int scale = (int) Math.sqrt(((parseBBOXParams(urlString)[2] - parseBBOXParams(urlString)[0]) / width) * ((parseBBOXParams(urlString)[3] - parseBBOXParams(urlString)[1]) / height));
Attention, en faisant ça, tu fais 4 fois l'analyse des paramètres (et 4 fois l'allocation du résultat) pour rien.
```suggestion
        int box = parseBBOXParams(urlString);
        int scale = (int) Math.sqrt(((box[2] - box[0]) / width) * ((box[3] - box[1]) / height));
```

2024-04-05 09:43 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            params[i] = Integer.parseInt(part[1].split(",")[i]);
Ici aussi tu dois pouvoir te simplifier la vie en ne faisant qu'une fois le split au lieu de le faire pour chaque paramètre.

2024-04-05 09:43 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        String[] part = url.split("BBOX=");
Tu peux simplifier comme ça:
```suggestion
        String param = url.split("BBOX=")[1];
```
et utiliser `param` après au lieu de `part[1]`

Je me demande comment cela réagit si le paramètre n'est pas présent.

2024-04-05 09:43 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        params[3] = Integer.parseInt(part[1].split(",")[3].split("&")[0]);
Je pense que ce sont des fonctions "jetables" mais y a moyen de faire mieux (doit y avoir des libs pour parser les URL je suppose). Ici, si le paramètre est en dernier dans la liste, tu n'auras pas de "&" par exemple.

2024-04-05 09:43 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/BaseChunk2D.java
> +public abstract class BaseChunk2D implements IterableChunk2D, WritableChunk2d {
Ya un mix entre 2D et 2d, va falloir choisir :)

Pourquoi "abstract" ?

2024-04-05 09:43 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/HeightMap.java
> +    }
Je voyais plutôt une fonction qui met le max entre l'existant et ce qui est demandé (on va en avoir besoin pour la MAX heightMap). Le nom `raise` n'est peut être pas le bon. Comme discuté, on peut virer ces méthodes en attendant d'en avoir besoin.

2024-04-05 09:43 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/world2d/TestSimpleChunk2d.java
Ces tests préjugent du modèle interne de stockage.
Si on le modifie mais que le chunk marche toujours bien, le test va échouer.
Je ne sais pas si c'est ok.
Un moyen de l'éviter est de garnir les chunks de test avec des `set` plutôt que d'aller taper dans les zones privées.

2024-04-10 15:51 UTC, pyrollo reviewed
- Quelques petites idées.
- Il faudrait vérifier la correspondance Height/Width avec x/y (peut être, pour éviter les confusions, remplacer par sizeX/sizeY ?)

Je n'ai pas encore revu les tests.

2024-04-10 15:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        HeightMap heightMap = new HeightMap(-height / 2, -width / 2, height, width, 0);
En déclarant :
```
int x0 = -width / 2;
int y0 = -height / 2;
```
Tu te simplifie le code ensuite.

2024-04-10 15:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        HeightMap heightMap = new HeightMap(-height / 2, -width / 2, height, width, 0);
```suggestion
        HeightMap heightMap = new HeightMap(-width / 2, -height / 2, width, height, 0);
```
Ya une inversion height/width non ?

2024-04-10 15:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/BaseChunk2d.java
> +        assert this.bbox.contains(x, y);
On pourrait le mettre dans `index` pour éviter les répétitions.

2024-04-10 15:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dIteratorAllMode.java
> +public class Chunk2dIteratorAllMode implements Chunk2dIterator {
J'hésite à proposer `Chunk2dIteratorAll` tout court.

2024-04-10 15:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dIteratorSkipMode.java
> +public class Chunk2dIteratorSkipMode implements Chunk2dIterator {
... et ici `Chunk2dIteratorSkip`

2024-04-11 07:26 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/HeightMap.java
La classe HeightMap n'est pas pour moi à proprement parler une partie de utils/world2d car elle est plutôt appliquée que générique.
Peut être vraudrait il mieux la mettre dans un package correspondant au GenerationContext (`generation` je crois)

2024-04-11 07:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/HeightMap.java
À y repenser, la HeightMap pourrait être dans ta PR suivante plutôt que celle ci.

2024-04-15 09:15 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/world2d/iterator/TestChunk2DIteratorAll.java
> +        }
Pour les tests de l'itérateur All, vaudrait mieux le voir apparaitre avec un new. Ici, tout dépend de ce que HeightMap nous renvoie. Je propose plutôt :
```suggestion
        SimpleChunk2d chunk = new SimpleChunk2d(1, 2, 3, 4, -1);
        Chunk2dIteratorAll iterator = new Chunk2dIteratorAll(chunk);
        while(iterator.hasNext()) {
            Chunk2dElement element = iterator.next();
            chunk.set(element.getX(), element.getY(), element.getX() + element.getY() * 3);    
```
Ici l'itérateur peut être simplement remplacé par des boucles sur `x` et `y` (on est juste dans la préparation du jeu de données). Cela pourrait donner:
```suggestion
        SimpleChunk2d chunk = new SimpleChunk2d(1, 2, 3, 4, -1);
        for (int x = 1; x <= 3; x++) {
            for (int y = 2; y <= 6; y++) {
                chunk.set(x, y, x + y * 3);
            }
        }
```

2024-04-15 09:15 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/world2d/iterator/TestChunk2DIteratorAll.java
> +        for (Chunk2dElement element : map) {
```suggestion
        Chunk2dIteratorAll iterator = new Chunk2dIteratorAll(chunk);
        while(iterator.hasNext()) {
            Chunk2dElement element = iterator.next();
```
(Si iterator n'est pas déjà déclaré)
En bonus, on teste le `hasNext`.

2024-04-15 09:15 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/world2d/iterator/TestChunk2DIteratorAll.java
> +        int[] count = {0}; // Avoid "local variables referenced from a lambda expression must be final"
```suggestion
        int count = 0;
```
Comme on n'utilise plus de fixture, on n'a plus le problème de final.

2024-04-15 09:15 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/world2d/iterator/TestChunk2DIteratorAll.java
> +            count[0]++;
```suggestion
            count++;
```

2024-04-15 09:15 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/world2d/iterator/TestChunk2DIteratorAll.java
> +        assert count[0] == 3 * 4 : "Too many iterations: " + count;
```suggestion
        assert count == 3 * 4 : "Too many iterations: " + count;
```

2024-04-15 09:15 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/world2d/iterator/TestChunk2DIteratorSkip.java
> +public class TestChunk2DIteratorSkip {
Ici, même remarques que pour l'itérateur All:
* Ne pas faire confiance au chunk  pour renvoyer l'iterateur à tester (cela peut changer)
* Effectuer un remplissage bourrin avec des boucles sur les coordonnées (peut être plus direct/lisbile)
* Supprimer le `[0]` du `count` qui est devenu inutile.

2024-04-15 09:15 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/world2d/iterator/TestWorldBBox2dIterator.java
> +        bbox.iterator().forEachRemaining(
On peut aussi utiliser ici le while hasNext / next pour homogénéiser et tester les deux méthodes.

2024-04-15 09:15 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/SimpleChunk2d.java
> +    private int skipValue;
Ne pas gérer de skip value spécifique pour l'instant dans SimpleChunk (mais garder l'itérateur avec). Juste passer la defaultValue à l'itérateur.

2024-04-16 12:13 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/voxel2d/ReadableVoxelMap2d.java
Alors, c'est un détail, mais je pense que ça serait pas mal que cette classe étend la classe `Iterator`. De cette manière, on pourrait avoir un `for-loop` "natif" au lieu du `map.iter().forEachRemaining`.

```
for (VoxelMap2dIteratorResult result : map){
	stoneVoxel.place(result.x(), result.y(), 0);
}
```

2024-04-16 12:13 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/voxel2d/ReadableVoxelMap2d.java
> +public interface ReadableVoxelMap2d {
```
public interface ReadableVoxelMap2d extends Iterable<VoxelMap2dIteratorResult>
```

2024-04-16 12:13 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/voxel2d/ReadableVoxelMap2d.java
> +    default public VoxelMap2dIterator iter()
```
default public VoxelMap2dIterator iterator()
```
(`Iterable` impose `iterator()`)

2024-04-16 12:13 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dIteratorAllMode.java
> +public class Chunk2dIteratorAllMode implements Chunk2dIterator {
Je suis d'accord avec ça, je viens d'effectuer la modification !

2024-04-16 12:13 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        HeightMap heightMap = new HeightMap(-height / 2, -width / 2, height, width, 0);
Alors oui ! C'était en quelque sorte intentionnel, ça produit un monde "tourné" de 90°, ça me paraissait plus simple à visualiser, avec mapserver, quand je testais que celui sans inversion du width/height (qui produit un monde "tourné" de 180°).
Je viens de faire une version avec un changement de repère avec l'axe des x en eastern et y en northing. (Qui me semble plus proche de ce qu'on fera notamment le fait que le x dans Minetest correspond à l'axe soleil) Il est peut-être moins intuitif, dis moi ce que tu en penses (sinon je peux mettre un x_w = x + x0 et y_w = y + y0)

J'ai ajouté des constructeurs pour les chunks prenant `WorldCoords2d` et `WorldSize2d` en paramètres.

Ca m'a fait penser à 2 changements que je pense être bien et j'aimerais ton avis : méthode `place()` de `MTVoxelType` et le nom `origin` pour les bbox. Je te fais deux commentaires.

**Edit :** Desole, mais je viens de voir que mes commentaires se font comme si c'était une revue en haut. (En fait je voulais faire mention du code et non être en mode revue)

2024-04-16 12:13 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +    public WorldBBox2d(WorldCoords2d origin, WorldSize2d size) {
A y repenser le nom `origin` pour le paramètre des constructeurs des chunks et bbox ne me parait plus adapté. Je me dis que min est mieux. Pour une bbox avec comme `origin` (-5, -7) de taille (3, 2) ne contient pas le point (0, 0) qui est .. l'origine par définition. Du coup je me dis que c'est mieux de passer de origin à min (surtout que ça peut prêter à confusion)

2024-04-16 12:13 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/outputs/minetest/voxelType/MTVoxelType.java
>      protected MTVoxelWorld world;
J'ai envie de changer la méthode `place()` de `MTVoxelType`. L'idée c'est qu'elle prenne des x, y, z world et qu'elle fasse elle-même la correspondance (x->x, y->z, z-> y).
```
public void place(int x, int y, int z) throws OutOfWorldException {
    this.world.set(x, y, z, this);
}
```
en 
```
public void place(int x, int y, int z) throws OutOfWorldException {
    this.world.set(x, z, y, this);
}
```
Et passer la méthode `public set()` de `MTVoxelWorld` en protected et déplacer MTVoxelType dans le package `minetest`au lieu `minetest.voxelType` (comme ça `set()` de world n'est pas accessible depuis les classes externes à Minetest)

2024-04-16 12:13 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/HeightMap.java
Je suis plutôt de ton avis, mais il me faut un `Chunk` concret avec un iterateur all

2024-04-16 13:21 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/outputs/minetest/voxelType/MTVoxelType.java
>      protected MTVoxelWorld world;
J'ai fait la modification, je met ce commentaire pour que tu le saches

2024-04-17 16:11 UTC, naulan-chrzaszcz requested changes
C'est ici le barbecue ?

2024-04-17 16:11 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +import com.ignfab.minalac.generator.utils.world2d.iterator.Chunk2dIteratorAll;
```suggestion
import com.ignfab.minalac.generator.utils.world2d.*;
import com.ignfab.minalac.generator.utils.world2d.iterator.*;
```

2024-04-17 16:11 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/BaseChunk2d.java
> +    }
```suggestion
    private BaseChunk2d(int defaultValue) {
        this.defaultValue = defaultValue;
        this.values = new int[this.bbox.getSize().getX() * this.bbox.getSize().getY()];
        Arrays.fill(this.values, this.defaultValue);
    }

    protected BaseChunk2d(int originX, int originY, int sizeX, int sizeY, int defaultValue) {
        this.bbox = new WorldBBox2d(originX, originY, sizeX, sizeY);
        this(defaultValue);
    }

    protected BaseChunk2d(WorldBBox2d bbox, int defaultValue) {
        this.bbox = bbox;
        this(defaultValue);
    }

    protected BaseChunk2d(WorldCoords2d coords, WorldSize2d size, int defaultValue) {
        this.bbox = new WorldBBox2d(coords, size);
        this(defaultValue);
    }
```

2024-04-17 16:11 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +        );
```suggestion
        this.max = new WorldCoords2d(
            this.min.getX() + this.size.getX() - 1,
            this.min.getY() + this.size.getY() - 1
        );
```

2024-04-18 14:54 UTC, pyrollo reviewed
Commentaires sur la doc

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/SimpleChunk2d.java
> + * {@code SimpleChunk2d} represents an iterable and writable chunk.
```suggestion
 * {@code SimpleChunk2d} is a base implementation of an iterable and writable chunk.
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> + * This BBOX is defined by a minimum point (bottom-left) and a maximum point (top-right). These points are included on the BBOX.
```suggestion
 * {@code WorldBBox2d} represents a two-dimensional bounding box that surrounds an area on the surface of (xy-plane) of the voxel world.
 * This BBOX is defined by a minimum point (bottom-left) and a maximum point (top-right). These points are included in the BBOX.
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +     * @param size   The BBOX's size
```suggestion
     * @param origin The starting position coordinates (minimum point)
     * @param size   The BBOX size
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +     * Returns {@code true} if and only if {@code WorldBBox2d} contains the point at the position (x, y).
J'aurais mis une explications plus synthétique du genre:
```suggestion
     * Tells if given coordinates are in the bounding box.
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +     * {@code false} otherwise
```suggestion
     * @return {@code true} if coordinates are in the bbox, {@code false} otherwise
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +     * @return a {@code WorldSize2d} that encapsulates the BBOX size along the x-axis and y-axis.
Parail, ça peut être plus direct je pense:
```suggestion
     * @return size of the bounding box
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldSize2d.java
> + * Size can not be less or equals to zero.
```suggestion
 * Size is always greater than zero.
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ArrayChunk2d.java
> +     * @throws IndexOutOfBoundsException if the coordinates provided are outside the chunk's BBOX
```suggestion
     * @throws IndexOutOfBoundsException if provided coordinates are outside the chunk
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ArrayChunk2d.java
> +     * @throws IndexOutOfBoundsException if the coordinates provided are outside the chunk's BBOX
```suggestion
     * @throws IndexOutOfBoundsException if provided coordinates are outside the chunk
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ArrayChunk2d.java
> +     * @throws IndexOutOfBoundsException if the coordinates provided are outside the chunk's BBOX
```suggestion
     * @throws IndexOutOfBoundsException if provided coordinates are outside the chunk
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ArrayChunk2d.java
> +     * @throws IndexOutOfBoundsException if the coordinates provided are outside the chunk's BBOX
```suggestion
     * @throws IndexOutOfBoundsException if provided coordinates are outside the chunk
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ReadableChunk2d.java
> +     * The bounding box covers the totality of the chunk.
Tu peux faire très simplement:
```suggestion
     * Returns the bounding box of the chunk.
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ReadableChunk2d.java
> +     * @return the corresponding {@code WorldBBox2d}.
Et pourquoi pas remettre le lien ici du coup:
```suggestion
     * @return bounding box as a {@link com.ignfab.minalac.generator.utils.world2d.WorldBBox2d}
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ReadableChunk2d.java
> +     * @return the {@code int} value associated at the position (x, y).
```suggestion
     * @return the {@code int} value at the position (x, y).
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ReadableChunk2d.java
> +     * @return the {@code int} value associated at the provided point's coordinates.
```suggestion
     * @return the {@code int} value at the provided coordinates.
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ReadableChunk2d.java
> + */
Faudrait ajouter un truc du genre:
```
Coordinates in {@code ReadableChunk2d} methods are relative to world, not to chunk.
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/WritableChunk2d.java
> + */
Idem ici, ajouter le fait que les coordonnées soient absolue (i.e. relative au monde et pas au chunk).

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/WritableChunk2d.java
> +     * The bounding box covers the totality of the chunk.
```suggestion
     * Returns chunk bounding box
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dElement.java
> + * This class is typically used to encapsulate the result of a {@code ReadableChunk2d} iterator.
```suggestion
 * {@code Chunk2dElement} is returned by {@code Chunk2dIterator}. It encapsulates coordinates (x, y) and associated {@code int} value.
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dElement.java
> +    public Chunk2dElement(WorldCoords2d coords, int value) {
Peut être cela vaut il le coup de mettre le constructeur en protected.

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dElement.java
> +     * @return the value associated.
```suggestion
     * @return the value at coordinates.
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dElement.java
> +     * @return the x-coordinate value.
```suggestion
     * @return the x coordinate.
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dElement.java
> +     * @return the y-coordinate value.
```suggestion
     * @return the y coordinate.
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dIteratorAll.java
> + * It iterates over all the elements.
```suggestion
 * An iterator over all elements of a {@code ReadableChunk2d}.
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dIteratorSkip.java
> +     * @param skipValue The matching value for skipping
```suggestion
     * @param skipValue Value to skip
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dIteratorSkip.java
> +     * @param chunk     The {@code ReadableChunk2d} to iterate over
```suggestion
     * @param chunk     {@code ReadableChunk2d} to iterate over
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dIteratorSkip.java
> +     * @param chunk     The {@code ReadableChunk2d} to iterate over
Pas sûr s'il faut mettre ou pas les "The" partout. Voir ce qu'il se fait.

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/WorldBBox2dIterator.java
> + * An iterator over the coordinates of the points contained in a {@code WorldBBox2d}.
```suggestion
 * An iterator over all coordinates in a {@code WorldBBox2d}.
```

2024-04-18 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/world/VoxelType.java
> +    //TODO : add the javadoc that explicitly define the coordinate system used + change the QuickStart.md accordingly
TODO!

2024-04-19 15:05 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dElement.java
> +     * @return the x-coordinate value.
Bon, les deux usages se valent. Il semblerait que celui avec un tiret est plus courant dans un contexte de repère géométrique, je vais l'utiliser et être consistant avec

2024-04-19 15:40 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dIteratorSkip.java
> +     * @param chunk     The {@code ReadableChunk2d} to iterate over
J'ai jetté un oeil (BufferedImage, Arrays, Connection), il semble que l'usage et de mettre un article devant. Pour la ponctuation, on dirait que BufferedImage et Arrays ne mettent pour les params (et uniquement params). J'ai uniformisé la ponctuation sur les methodes. (Par contre Connection en met sur params et pas throws), du coup j'ai l'impression qu'on doit choisir

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +     * Returns {@code true} if and only if {@code WorldBBox2d} contains the point at the position {@code WorldCoords2d}.
```suggestion
     * Tells if given coordinates are in the bounding box. 
```

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +     * @param coords the coordinates of the point to be checked
```suggestion
     * @param coords the coordinates to be checked
```

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +     * @return {@code true} is that is the case;
```suggestion
     * @return {@code true} is coordinates are in the bounding box;
```

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> + * This BBOX is defined by a minimum point (bottom-left) and a maximum point (top-right). These points are included in the BBOX.
```suggestion
 * This  bounding box is defined by a minimum point and a maximum point. These points are included in the box.
```
J'enlèverai la référence à top/left/right/bottom qui, d'une part donnent une verticalité la la boite, et d'autre part orientent les axes a priori (pour l'instant on ne sait pas trop ce qui est à droite, en bas ou à gauche).

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> + * In the voxel world, coordinates are defined by three axes (x, y, z) where the z-axis represents the altitude, and increments correspond to the size of a voxel.
C'est déjà expliqué dans WorldCoords2d.

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ArrayChunk2d.java
> + * Data is both written and read from an array.
```suggestion
 * A readable and writable 2d chunk of world map based on an array.
```

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ArrayChunk2d.java
> +        return this.bbox;
```suggestion
        return bbox;
```

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ArrayChunk2d.java
> +        this.values[this.index(x, y)] = value;
```suggestion
        values[this.index(x, y)] = value;
```

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ArrayChunk2d.java
> +        this.values[this.index(coords.getX(), coords.getY())] = value;
```suggestion
        values[this.index(coords.getX(), coords.getY())] = value;
```

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ArrayChunk2d.java
> +        return this.values[this.index(x, y)];
```suggestion
        return values[this.index(x, y)];
```

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ArrayChunk2d.java
> +        return this.values[this.index(coords.getX(), coords.getY())];
```suggestion
        return values[this.index(coords.getX(), coords.getY())];
```

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dIteratorSkip.java
> +            this.current = null;
```suggestion
                value = chunk.get(coords);
            } while (value == skipValue);

            current = new Chunk2dElement(coords, value);
        } catch (NoSuchElementException e) {
            current = null;
```

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dIteratorSkip.java
> +        return this.current != null;
```suggestion
        return current != null;
```

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dIteratorSkip.java
> +        Chunk2dElement result = this.current;
```suggestion
        Chunk2dElement result = current;
```

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/WorldBBox2dIterator.java
> +                this.hasNext = false;
```suggestion
        x++;
        if (x > bbox.getMax().getX()) {
            x = bbox.getMin().getX();
            y++;
            if (y > bbox.getMax().getY())
                hasNext = false;
```

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/WorldBBox2dIterator.java
> +        return this.hasNext;
```suggestion
        return hasNext;
```

2024-04-23 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/WorldBBox2dIterator.java
> +        WorldCoords2d result = new WorldCoords2d(this.x, this.y);
```suggestion
        if (!hasNext)
            throw new NoSuchElementException();
        WorldCoords2d result = new WorldCoords2d(x, y);
```

2024-04-23 11:41 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        deleteDirectory(dir);
```suggestion
        deleteDirectory(new File(directory));
```

2024-04-23 11:41 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ArrayChunk2d.java
> +    }
```suggestion
    private ArrayChunk2d(int defaultValue) {
        this.defaultValue = defaultValue;
        this.values = new int[this.bbox.getSize().getX() * this.bbox.getSize().getY()];
        Arrays.fill(this.values, defaultValue);
    }

    /**
     * Constructs a new {@code ArrayChunk2d}.
     *
     * @param originX      the x-coordinate of the starting position
     * @param originY      the y-coordinate of the starting position
     * @param sizeX        the size along the x-axis of the {@code ArrayChunk2d}
     * @param sizeY        the size along the y-axis of the {@code ArrayChunk2d}
     * @param defaultValue the defaultValue associated to all the points
     * @throws IllegalArgumentException if either {@code sizeX} or {@code sizeY} is less than or equal to 0.
     */
    public ArrayChunk2d(int originX, int originY, int sizeX, int sizeY, int defaultValue) {
        this.bbox = new WorldBBox2d(originX, originY, sizeX, sizeY);
        this(defaultValue);
    }

    /**
     * Constructs a new {@code ArrayChunk2d}.
     *
     * @param bbox         the bounding box covering the totality of the chunk.
     * @param defaultValue the defaultValue associated to all the points
     */
    public ArrayChunk2d(WorldBBox2d bbox, int defaultValue) {
        this.bbox = bbox;
        this(defaultValue);
    }

    /**
     * Constructs a new {@code ArrayChunk2d}.
     *
     * @param coords       the coordinate of the starting position
     * @param size         the size of the {@code ArrayChunk2d}
     * @param defaultValue the defaultValue associated to all the points
     */
    public ArrayChunk2d(WorldCoords2d coords, WorldSize2d size, int defaultValue) {
        this.bbox = new WorldBBox2d(coords, size);
        this(defaultValue);
    }
```

2024-04-24 08:15 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/BaseChunk2d.java
> +    }
Je clos car ce commentaire est présent ailleurs

2024-04-24 12:02 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dIteratorSkip.java
> +     * @param chunk     The {@code ReadableChunk2d} to iterate over
Au final, j'ai mis des points partout. Je trouve que c'est mieux que de mettre des exceptions

2024-04-24 12:03 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +     * {@code false} otherwise
~~J'avais vu ce format là pour les méthodes renvoyant des booléens, je trouve que c'est pas mal en visibilité~~
Edit: Commentaire plus d'actualite

2024-04-24 12:05 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +     * @return a {@code WorldSize2d} that encapsulates the BBOX size along the x-axis and y-axis.
Personnellement je trouve que c'est mieux de spécifier le type dans le @return (Et d'etre plus vague dans la description si elle existe)

2024-04-24 12:42 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +        );
Alors, quand il s'agit d'une expression sur une line, j'ai l'impression que la convention est de 8 espaces. Mais je me trompe peut etre

2024-04-24 13:47 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +     * @return a {@code WorldSize2d} that encapsulates the BBOX size along the x-axis and y-axis.
Ok dans ce cas: 
Parail, ça peut être plus direct je pense:
```suggestion
     * @return size of the bounding box as a {@code WorldSize2d}
```

2024-04-25 08:37 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +     * @return {@code true} is coordinates are in the bounding box.
```suggestion
     * @return {@code true} if coordinates are in the bounding box.
```

2024-04-25 08:37 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +     * @return {@code true} is coordinates are in the bounding box.
```suggestion
     * @return {@code true} if coordinates are in the bounding box.
```

2024-04-25 08:37 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/ReadableChunk2d.java
> + * @see WorldCoords2d
Il y a une redondance. A voir comment ça rend mais je vois deux possibilités:
```suggestion
 * An explanation of the voxel world coordinates system can be found on {@link com.ignfab.minalac.generator.utils.world2d.WorldCoords2d}.
```
Celle là serait pas mal si ça rend bien:
```suggestion
 * @see WorldCoords2d for an explanation of the voxel world coordinates system.
```

2024-04-25 08:37 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/chunk/WritableChunk2d.java
> + * An explanation of the voxel world coordinates system can be found on {@link com.ignfab.minalac.generator.utils.world2d.WorldCoords2d}.
Pareil que dans ReadableChunk2d.

2024-04-25 08:37 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/Chunk2dIteratorSkip.java
> +     * Indicates if there is more elements.
```suggestion
     * Indicates if there are more elements.
```

2024-04-25 08:37 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/iterator/WorldBBox2dIterator.java
> +     * Indicates if there is more elements.
```suggestion
     * Indicates if there are more elements.
```

2024-04-25 12:07 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldSize2d.java
> +        }
```suggestion
        if (sizeX <= 0 || sizeY <= 0)
            throw new IllegalArgumentException("Invalid dimensions : sizeX and sizeY must be greater than 0");
```

2024-04-25 12:07 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        }
```suggestion
        if (allContents != null)
            for (File file : allContents)
                deleteDirectory(file);
```
Ou limite mais je pense que c'est pas correct (nv code style):
```suggestion
        if (allContents != null) for (File file : allContents)
            deleteDirectory(file);
```

2024-04-25 12:07 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/outputs/minetest/MTVoxelWorld.java
> +    protected void set(int x, int y, int z, MTVoxelType voxel) throws OutOfWorldException {
```suggestion
    protected void set(MTVoxelType voxel, int x, int y, int z) throws OutOfWorldException {
```
Vraiment la c'est du shipotage mais c'ets pour avoir le `this` au debut des args

2024-04-25 12:08 UTC, naulan-chrzaszcz approved these changes

2024-04-25 12:52 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        }
Ok, je mets le premier! (Pour le deuxième c'est sympa, mais comme je ne l'ai pas utilise ailleurs, je prefere utiliser le premier pour la cohérence)

2024-04-25 13:03 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/outputs/minetest/MTVoxelWorld.java
> +    protected void set(int x, int y, int z, MTVoxelType voxel) throws OutOfWorldException {
Je t'avoue que je ne suis pas vraiment chaud de faire cette modification. C'est du code d'une autre feature, je m'étais permis de faire une légère modification en inversant un y et z sur place() de MTVoxelType pour que ça soit cohérent avec notre choix de repere. (Vu qu'il y a de la javadoc qui explique les axes dans WorldCoord2d) Et le placement en protected c'est pour que la méthode ne soit accessible que package et enfants.

Du coup, ca te va de ne pas faire cette modification et d'en discuter dans une autre PR? (Je pense qu'il y aura une PR pour ajouter de la javadoc sur la feature des VoxelsType dans le future)

2024-04-25 14:11 UTC, zhak5388 approved these changes

2024-04-25 14:12 UTC, merged