feat(alti): Put altitude and ground stuff in provider/model/renderer …
ignfab/voxatile pull request #22
Opened 2024-07-18 08:17 UTC by pyrollo

### Changes

This pull request aims to move altitude map retrieving and rendering out of `SampleImplementation`.

#### Feature description

No new feature, it's a matter of code organization.

This should work the same as before.

#### Technical changes

Basically, replace `placeVoxelFromHeightMap` and `createGroundHeightMap` methods by `HeightMapRenderer` and `GroundRenderer` classes.

This implied:
- Many additions to `CoordsConverter` (mostly ability to perform reverse conversion)
- Creation of a `WMSDataProvider` to download altitude data
- Creation of `FloatMatrixModel` to hold it and `FloatMatrixChunk` to "voxelize" it.

### Reason

Move draft code from `SampleImplementation` into clean classes.

### Self-checks

- [X] The code has unit tests associated
- [X] The code has Javadoc Comments associated
- [X] Complex / Unexpected code is explained / justified with a small comment
- ~~Relevant documentation inside the `/docs` folder has been updated~~
- [X] All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)
- [X] Git history is clean (each commit accomplish a single task and describe it accordingly)
- ~~The texts have been proofread (documentation, error messages, logs, comments...)~~

2024-07-23 16:31 UTC, zhak5388 requested changes
C'est un première rapide relecture, j'ai principalement mis des commentaires sur l'absence de javadoc (Comme dans l'autre PR, je sais pas si c'est normal que `checkstyle ne l'a pas flagé)

2024-07-23 16:31 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/inputs/WMSDataProvider.java
> +public class WMSDataProvider {
Il manque de la javadoc sur la classe et les 4 méthodes publiques

2024-07-23 16:31 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/FloatMatrixModel.java
> +public class FloatMatrixModel implements Model, Rasterizable {
Pareil ici (+Constructeur)

2024-07-23 16:31 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/FloatMatrixModel.java
> +    public IterableChunk2d getChunk() {
Peut-être mettre un `@Override` ici ?

2024-07-24 07:29 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/inputs/WMSDataProvider.java
> +public class WMSDataProvider {
Il faut qu'on fasse en sorte que le codestyle ne laisse pas passer ça.

2024-07-24 07:47 UTC, naulan-chrzaszcz requested changes

2024-07-24 07:47 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/generation/CoordsConverter.java
> +     public CoordsConverter(AffineTransformation preTransform, MathTransform crsTransform, AffineTransformation postTransform) {
```suggestion
    public CoordsConverter(AffineTransformation preTransform, MathTransform crsTransform, AffineTransformation postTransform) {
```

2024-07-24 13:07 UTC, zhak5388 requested changes
Alors, je ferai une autre passe, là c'était histoire de comprendre comment ça fonctionne. J'ai mis des remarques sur de la ~~wolrd~~ typo : )

2024-07-24 13:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/FloatMatrixChunk.java
> + * A chunk embedding a float mattrix.
Petite typo : ) *matrix

2024-07-24 13:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/FloatMatrixChunk.java
> +            throw new IllegalArgumentException("data lenght must correspond to given sizes product");
*length

2024-07-24 13:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/FloatMatrixChunk.java
> +        // +/- 0.5 to ensure we realy have voxels on edge (or we may an entire line of non computable voxels)
*really

2024-07-24 13:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/FloatMatrixChunk.java
> +     * @param converter Converter to use to convert from matrix coordinates to wolrd coordinates (must be invertible)
world : )

2024-07-24 13:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/CoordsConverter.java
> +     * @param preTransform Affine transformation applied before CRS transformation (usualy for translation).
*usually

2024-07-24 13:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/CoordsConverter.java
> +        } catch (NoninvertibleTransformationException | NoninvertibleTransformException e) {
Je sais que ça date d'une précédente PR, mais c'est voulu d'avoir un catch sans rien ?

2024-07-24 13:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            FloatMatrixModel altimodel = new FloatMatrixModel(altiprovider.getFloatMatrix(), altiprovider.getWidth(), altiprovider.getHeight(), new CoordsConverter(
Un détail, c'est mieux d'utiliser un camelCase non pour `altimodel` et `altiprovider`?

2024-07-24 13:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            ).render();
De manière grossière, ce que je comprends, c'est que : le renderer a un model, lequel peut fournir un chunk, et quand on lit les valeurs du chunk via le `get` il y a de l'interpolation. J'ai pas encore tout compris de l'interpolation, mais pourquoi il y a un besoin de faire de l'interpolation? (Est ce que c'est entre autre lié au fait que la taille du monde ne matche pas forcément la taille du chunk? Et que dans ce cas, on aurait besoin de "calculer" la valeur probable a un point donnée ?)

2024-07-24 13:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/coordinates/Coords2d.java
> + * The {@code Coords2d} class represents two dimentional decimal (double float) coordinates.
*dimensional

2024-07-24 13:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/coordinates/Coords2d.java
> +    public Coordinate toCoordinate() {
Juste une reflexion, mais j'ai l'impression que c'est facile de s'embrouiller entre `Coordinates` de JTS et nos `Coords2d`

2024-07-24 13:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/CoordsConverter.java
> +     * This is usefull to handle millivoxels for example (with factor 1000).
*useful

2024-07-24 13:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/CoordsConverter.java
> +        return invertible;
Juste par inversible, est ce que on entend le fait qu'il existe un convertisseur permettant de revenir aux coordonnées initiales après conversion ?

2024-07-24 13:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/CoordsConverter.java
> +     * Converts wolrd coordinates back into map coordinates.
*world : )

2024-07-24 13:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/CoordsConverter.java
> +     * Converts wolrd coordinates back into map coordinates applying a factor.
*world : )

2024-07-26 08:55 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/coordinates/Coords2d.java
> +    public Coordinate toCoordinate() {
Oui et il ya `Position` aussi. En gros, un type de coordonnée par bibliothèque + nos types à nous

2024-07-26 09:08 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            ).render();
Le premier besoin est de pouvoir faire de la rotation. Ensuite effectivement, on peut imaginer des sources incapables de fournir des MNT à la résolution de notre monde. L'interpolation résoud tout ces problèmes (moyennant du temps de calcul).

2024-08-19 09:47 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/CoordsConverter.java
> +        } catch (NoninvertibleTransformationException | NoninvertibleTransformException e) {
Oui, dans ce cas, `invertible` reste à `false`, le convertisseur ne fera pas de transformation inverse.

2024-08-19 09:49 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/CoordsConverter.java
> +        return invertible;
Cela signifie que le convertisseur peut effectuer la transformation inverse (via les méthodes `reverse`)

2024-08-23 15:14 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/inputs/WMSDataProvider.java
> +     * @param baseURL base URL of the service (should include `service=` parameter but no other)
J'aurais mis `{@code service=}` si tu cherchais à avoir le formatage du markdown avec double ` (enfin si c'est ça que tu voulais)

2024-08-23 15:14 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/CoordsConverter.java
> +     * @param preTransform Affine transformation applied before CRS transformation (usualy for translation).
*usually

2024-08-23 15:14 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/FloatMatrixModel.java
> + * A model bassed on a matrix of floats (usually a heightmap model).
*based je crois

2024-08-23 15:59 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/inputs/WMSDataProvider.java
> +     * @param baseURL base URL of the service (should include `service=` parameter but no other)
Rha, c'est la vieille habitude du MD, quel dommage que cela n'existait pas quand ils ont inventé les javadoc!

2024-08-23 16:00 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/inputs/WMSDataProvider.java
> +     * @param baseURL base URL of the service (should include `service=` parameter but no other)
Oui : (

2024-08-26 14:06 UTC, zhak5388 approved these changes

2024-09-13 12:50 UTC, pyrollo commented
Cette PR va attendre que #43 soit mergée.
Le rebase est commencé sur la branche [feat/mntrenderers-rebase](https://github.com/ignfab/minalac-generator/tree/feat/mntrenderers-rebase)

2024-09-17 12:21 UTC, closed without merging