feat(parser) : Add ParamsParser utility classes
ignfab/voxatile pull request #23
Opened 2024-07-18 14:16 UTC by pyrollo

### Type of modification

Types:
- Code
  - Inputs
- Documentation
  - Javadoc Comments
  - Markdown Files
- Other:
  - Example file

### Changes

Move all generation parameters from command line to Json/Yaml file/variable.

#### Feature description

With this pull request, all generation parameters are passed apart, in Json or Yaml format. Only two command line arguments remains : 
- the output path;
- the path of a file containing generation arguments.

An example of such a file can be found in examples/default.yaml.

#### Technical changes

This pull request consists in adding classes in utils/paramsparser. These classes perfoms deserialization of Json or Yaml content into a Generation object.

A `MinalacGeneratorCLI` class improves command line argument parsing and offers different ways to pass generation parameters.

This pull request was first initiated by Zen and rebased/improved by Pyrollo (main commit tree has been completely rewritten meanwhile).

#### Showcase

Use provided example file:
```
mvn -DskipTests=true clean package && java -jar target/Generator.jar -p examples/default.yaml $HOME/.minetest/worlds/minalac
```

Pass arguments in Json using environement:
```
mvn -DskipTests=true clean package && MINALAC_PARAMS='{"verticalScale":1.0,"horizontalScale":1.0,"area":{"center":{"latitude":44.1519,"longitude":1.7499},"extendX":1000,"extendY":1000},"crs":"EPSG:2154","format":"minetest"}' java -jar target/Generator.jar $HOME/.minetest/worlds/minalac
```

Print help message:
```
mvn -DskipTests=true clean package && java -jar target/Generator.jar -h
```

### Reason

Because it's much better!

### Self-checks

- [X] The code has unit tests associated
- [X] The code has Javadoc Comments associated
- ~~Complex / Unexpected code is explained / justified with a small comment~~
- [X] Relevant documentation inside the `/docs` folder has been updated
- [X] All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)
- [X] Git history is clean (each commit accomplish a single task and describe it accordingly)
- [X] The texts have been proofread (documentation, error messages, logs, comments...)

2024-07-19 16:38 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/MinalacGeneratorCLI.java
> +    private static final String PARAMRSENVVARNAME = "MINALAC_PARAMS";
```suggestion
    private static final String PARAMS_ENVVAR_NAME = "MINALAC_PARAMS";
```

2024-07-20 13:20 UTC, indyteo requested changes

2024-07-20 13:20 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +These parameters generates a map of 1000x1000 voxels around IGN building at Saint-Mandé (FR), in Minetest format, with 1 metter voxels in each directions:
```suggestion
These parameters generate a map of 1000x1000 voxels around IGN building at Saint-Mandé (FR), in Minetest format, with 1 meter voxels in every direction:
```

2024-07-20 13:20 UTC, indyteo commented on docs/usage/GenerationParameters.md
> + - `horizontalScal`: Horizontal size of voxels (in map units, usually metters)
```suggestion
 - `verticalScale`: Vertical size of voxels (in map units, usually meters)
 - `horizontalScale`: Horizontal size of voxels (in map units, usually meters)
```

2024-07-20 13:20 UTC, indyteo commented on docs/usage/Run.md
> +`-p path` `--param-file path` read generation parameters from given path. If ommited, parameters are read from `MINALAC_PARAMS` environement variable.
```suggestion
`-p path` `--param-file path` read generation parameters from given path. If omitted, parameters are read from `MINALAC_PARAMS` environment variable.
```

2024-07-20 13:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/MinalacGeneratorCLI.java
> + * GeneratorCommandLine performs parsing, basic validation and some basic tasks such as retreiving generation parameters.
```suggestion
 * MinalacGeneratorCLI performs parsing, basic validation and some basic tasks such as retrieving generation parameters.
```

2024-07-20 13:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/MinalacGeneratorCLI.java
> +            }
```suggestion
            try {
                parameters = Files.readString(Path.of(parametersPath));
            } catch (IOException e) {
                e.printStackTrace();
                System.exit(1);
            }
```
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/file/Files.html#readString(java.nio.file.Path)

2024-07-20 13:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/MinalacGeneratorCLI.java
> +        } catch (ParseException e) {
Est-ce qu'il ne serait pas intéressant de print l'exception ici pour aiguiller l'utilisateur sur ce qu'il a mal fait ? (bien sûr seulement si le message d'erreur a du sens, il faut tester)

2024-07-20 13:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/MinalacGeneratorCLI.java
> +    private String parametersPath;
Peut-être intéressant de remplacer `String` par `Path` ou `File`, plus pratique à utiliser (et garanti que c'est un chemin valide, c'est à dire pas de caractère impossible dans un nom de fichier par exemple)

2024-07-20 13:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parsing/ParamsParser.java
> +        world.getMetadata().setBbox(new WorldBBox3d(-rawParams.area.extendX / 2,
```suggestion
        world.getMetadata().setBbox(new WorldBBox3d(
            -rawParams.area.extendX / 2,
```

2024-07-20 13:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
Déplacer les classes `Area` et `Center` en classe imbriquée de `RawParams` (en Java on évite vraiment d'avoir plusieurs classes à la racine d'un même fichier, car ça cause des inconsistances entre les builds, ça restreint la visibilité de ces classes de manière forcée, et ça n'est jamais nécessaire de vouloir faire ça. C'est une "fonctionnalité" historique qui date d'avant les classes imbriquées et qui n'est restée que pour des raisons de rétro-compatibilité)

2024-07-20 13:20 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parsing/TestParamsParser.java
Ajouter un test au format YAML histoire de valider que le format est bien prit en charge

2024-07-22 13:01 UTC, indyteo reviewed
À plusieurs endroit lors de la gestion d'exception tu utilises des façons différentes d'afficher l'erreur. En Java, si on veut simplement afficher l'erreur avec des le plus d'info utile on utilise `e.printStackTrace();`.
Si on a une raison particulière ne d'afficher que le message et pas la stack trace d'accord, mais bien souvent il vaut mieux juste afficher tout, c'est plus utile...
Le cas où on peut laisser seulement le message est éventuellement la ligne 50 de `MinalacGeneratorCLI`, si le message se suffit à lui-même

2024-07-22 13:01 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/MinalacGeneratorCLI.java
> +                System.out.println(parametersPath.toString() + " does not exist");
```suggestion
                System.out.println(parametersPath + " does not exist");
```
(Pareil lignes 107, 112 et 119)

2024-07-22 13:01 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parsing/ParamsParserTest.java
> +            """;
L'indentation de ce JSON est bizarre :
```suggestion
    private static final String WORKING_JSON = """
            {
                "verticalScale": 3,
                "horizontalScale": 4,
                "area": {
                    "center": {
                        "latitude": 5.8,
                        "longitude": 2.4
                    },
                    "extendX": 500,
                    "extendY": 2500
                },
                "crs": "EPSG:5643",
                "format": "minetest"
            }
            """;
```

2024-07-22 13:01 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parsing/ParamsParserTest.java
> +            """));
Ce `"""` semble mal placé (à cause de lui, tout le string est indenté par 4 espace), ou alors il faut retirer 4 espaces à toute l'indentation du string, c'est au choix

2024-07-22 13:01 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parsing/ParamsParserTest.java
> +        });
```suggestion
        Generation generation = assertDoesNotThrow(() -> new ParamsParser(WORKING_JSON).createGeneration());
```

2024-07-22 13:01 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parsing/ParamsParserTest.java
> +        // Nothing much to test for now :'(
`world.getMetadata().getBbox()` ?

2024-07-22 13:16 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +These parameters generate a map of 1000x1000 voxels around IGN building at Saint-Mandé (FR), in Minetest format, with 1 meter voxels in every directions:
```suggestion
These parameters generate a map of 1000x1000 voxels around IGN building at Saint-Mandé (FR), in Minetest format, with 1 meter voxels in every direction:
```

2024-07-22 13:16 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/MinalacGeneratorCLI.java
> +    private Options options;
```suggestion
    private final Options options;
```

2024-07-22 13:16 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/MinalacGeneratorCLI.java
> +            System.out.println(String.format("Please provide generation parameters (either with -p option or using %s environment variable)", PARAMS_ENVVAR_NAME));
```suggestion
            System.out.printf("Please provide generation parameters (either with -p option or using %s environment variable)%n", PARAMS_ENVVAR_NAME);
```

2024-07-22 13:16 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parsing/ParamsParserTest.java
> +    public void testCreateGeneration() throws ParseException {
```suggestion
    public void testCreateGeneration() {
```

2024-07-22 13:16 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parsing/ParamsParserTest.java
> +    public void testCreateVoxelWorld() throws ParseException {
```suggestion
    public void testCreateVoxelWorld() {
```

2024-07-22 13:16 UTC, indyteo commented on pom.xml
> +        <!-- Jackson (Yaml/Json deserialisation) -->
```suggestion
        <!-- Jackson (Yaml/Json deserialization) -->
```

2024-07-22 14:37 UTC, zhak5388 reviewed
Alors, c'est juste une lecture rapide pour l'instant. Il y a deux points qui, il me semble, n'avaient pas été completement tranchés la dernière fois quand j'avais fait la PR.
1) La création ou non d'une classe "`ObjectCreator`" qui ferait les objets `Generation` et `VoxelWorld` à partir des paramètres parsés ([Lien](https://github.com/ignfab/minalac-generator/pull/4#discussion_r1644070429))
2) Si la validation des paramètres ne devrait pas se faire via une méthode dans `RawParams` au lieu qu'elle se fasse dans le constructeur de `ParamsParser` ([Lien](https://github.com/ignfab/minalac-generator/pull/4#discussion_r1639817810))

Vu que j'étais pas sur si la structure allait changer, je n'avais pas inclus de javadoc pour `ParamsParser`

2024-07-23 11:25 UTC, pyrollo commented
> À plusieurs endroit lors de la gestion d'exception tu utilises des façons différentes d'afficher l'erreur. En Java, si on veut simplement afficher l'erreur avec des le plus d'info utile on utilise `e.printStackTrace();`. Si on a une raison particulière ne d'afficher que le message et pas la stack trace d'accord, mais bien souvent il vaut mieux juste afficher tout, c'est plus utile... Le cas où on peut laisser seulement le message est éventuellement la ligne 50 de `MinalacGeneratorCLI`, si le message se suffit à lui-même

Je vais vérifier ce que j'ai fait mais pour moi, la stacktrace ne doit s'afficher que si l'on a un comportement imprévu. En l'occurence, la plupart des erreurs venant de la ligne de commande ne devait pas l'afficher.

2024-07-23 11:44 UTC, pyrollo commented
> * La création ou non d'une classe "`ObjectCreator`" qui ferait les objets `Generation` et `VoxelWorld` à partir des paramètres parsés ([Lien](https://github.com/ignfab/minalac-generator/pull/4#discussion_r1644070429))
> 
> * Si la validation des paramètres ne devrait pas se faire via une méthode dans `RawParams` au lieu qu'elle se fasse dans le constructeur de `ParamsParser` ([Lien](https://github.com/ignfab/minalac-generator/pull/4#discussion_r1639817810))

J'ai l'impression que ces question vont revenir de façon plus précises quand on va implémenter les factories pour les renderers et les patterns. Peut être remettre ça à ce moment là ?

2024-07-23 12:38 UTC, indyteo reviewed
Il y a encore quelques soucis d'indentation de JSON dans les tests, notamment sur les accolades fermantes.

2024-07-23 12:38 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parsing/ParamsParserTest.java
> +                    "longitude": 2.4
```suggestion
                        "latitude": 5.8,
                        "longitude": 2.4
```

2024-07-23 12:38 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parsing/ParamsParserTest.java
> +                  },
```suggestion
                },
```

2024-07-23 12:38 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parsing/ParamsParserTest.java
> +                },
```suggestion
              },
```

2024-07-23 12:38 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parsing/ParamsParserTest.java
> +        });
```suggestion
        VoxelWorld world = assertDoesNotThrow(() -> new ParamsParser(WORKING_JSON).createVoxelWorld());
```

2024-07-23 12:38 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/MinalacGeneratorCLI.java
> +            } catch (IOException e) {
Là ça me paraît important d'avoir l'erreur affichée (avec éventuellement la stack trace) car c'est pas normal de ne pas réussir à lire les paramètres sachant qu'on a validé le chemin avant

2024-07-23 12:38 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/MinalacGeneratorCLI.java
> +            } catch (InvalidPathException e) {
Le message ici est intéressant pour l'utilisateur. Exemple :
```java
Paths.get("path/to/inval?d/file") // Illegal char <?> at index 13: path/to/inval?d/file
```
(Même chose ligne 78)

2024-07-23 16:04 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/MinalacGeneratorCLI.java
> +            } catch (InvalidPathException e) {
J'avais pas réussi à générer l'erreur sous Linux.

2024-07-23 16:22 UTC, zhak5388 requested changes
C'est un peu étrange le `checkstyle` a laissé passer l'absence de javadoc.. Du coup, je mets des commentaires là ou il y en a pas.

**Edit** : Je viens de voir que `<module name="MissingJavadocMethod"/>` était commenté haha

2024-07-23 16:22 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parsing/ParamsParser.java
> +public class ParamsParser {
Manque de la javadoc

2024-07-23 16:22 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parsing/ParamsParser.java
> +    public ParamsParser(String serialized) throws ParseException {
Ici aussi

2024-07-23 16:22 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parsing/ParamsParser.java
> +    public Generation createGeneration() {
Ici aussi

2024-07-23 16:22 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parsing/ParamsParser.java
> +    public VoxelWorld createVoxelWorld() {
Ici aussi

2024-07-23 16:22 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parsing/ParseException.java
> +public class ParseException extends Exception {
Je ne suis plus sur si il est d'usage de mettre de la javadoc pour les exceptions aussi

2024-07-24 07:51 UTC, pyrollo commented
> C'est un peu étrange le `checkstyle` a laissé passer l'absence de javadoc.. Du coup, je mets des commentaires là ou il y en a pas.

J'ai regardé, c'est assez facile à ajouter, en revanche je n'ai pas creusé pour évtier que cela râle sur les tests aussi. 
Il manque pas mal de javadoc un peu partout déjà :'(.

2024-07-24 07:58 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parsing/ParseException.java
> +public class ParseException extends Exception {
Cela ne mange pas de pain et c'est mieux pour celui qui devra débugger (même si le javadoc est un peu basique).

2024-07-24 08:31 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        String crsName = "EPSG:2154";
La projection sera donc toujours sur `EPSG:2154` ? Si, l'utilisateur utilise les données d'OpenStreetMap, la projection doit changer ?
Il y aura un `yaml` pour ce genre de truc ?

2024-07-24 09:40 UTC, zhak5388 requested changes
Bon, en fait il y a quelques coquilles ^^

2024-07-24 09:40 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parsing/ParamsParser.java
> + * A Json/Yaml parser able to decode paremeters into Generation and World objects.
*parameters

2024-07-24 09:40 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parsing/ParseException.java
> + * Exception throw if a problem occured during parsing.
*occurred
et peut être "Exception thrown when/if "

2024-07-24 09:46 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        String crsName = "EPSG:2154";
Plus tard les projections pourront changer. Selon la source pour la source et selon le lieu pour la cible.
(ne pas oublier que tout ce qui est dans `SampleImplementation` est du brouillon appelé à être modifié)

2024-07-24 09:48 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        String crsName = "EPSG:2154";
D'ailleurs on pourrait l'appeler `DraftImplementation`.

2024-07-24 09:49 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        String crsName = "EPSG:2154";
Ça me va comme nouveau nom : )

2024-07-24 09:58 UTC, zhak5388 submitted a review, later dismissed

2024-07-24 13:19 UTC, indyteo reviewed
Dernière coquille et puis on est bon

2024-07-24 13:19 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/MinalacGeneratorCLI.java
> +                System.out.println(e.getStackTrace());
```suggestion
                e.printStackTrace();
```
Actuellement, `System.out.println(e.getStackTrace());` affiche : `[Ljava.lang.StackTraceElement;@a1b2c3d4`

2024-07-24 13:19 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
> +         * Logitude and latitude coordinates.
```suggestion
         * Longitude and latitude coordinates.
```

2024-07-24 13:19 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
> +             * @param longitude the latitude of the center.
```suggestion
             * @param longitude the longitude of the center.
```

2024-07-25 08:23 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
> +         * Logitude and latitude coordinates.
Pourtant Ségolène Royal disait : "Ça manque de logitude tout ça."

2024-07-25 11:48 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/MinalacGeneratorCLI.java
> +                e.printStackTrace();
```suggestion
                e.printStackTrace();
```
`printStackTrace` affiche déjà le message, là il est affiché en double

2024-07-25 18:56 UTC, indyteo approved these changes

2024-07-26 08:02 UTC, merged