Nivellement de models et rendu des bâtiments
ignfab/voxatile pull request #24
Opened 2024-07-19 08:27 UTC by naulan-chrzaszcz

### Type of modification

Types:
- Documentation
  - Javadoc Comments
  - Markdown Files
- Code
  - Outputs
  - Renderers
  - Parameters
- Tests

### Changes

Rendu des batiments selon leurs hauteurs

Nivellement de models

#### Feature description

- Nivellement avec un block X de models
- Murs des batiments
- Fenêtres des batiments
- Sol des etages des batiments

#### Showcase

![image](https://github.com/user-attachments/assets/85637e10-6de0-4f68-8e03-b8089b6f7eea)

### Self-checks

- [x] The code has unit tests associated
- [x] The code has Javadoc Comments associated
- [x] Complex / Unexpected code is explained / justified with a small comment
- [x] Relevant documentation inside the `/docs` folder has been updated
- [x] All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)
- [x] Git history is clean (each commit accomplish a single task and describe it accordingly)
- [x] The texts have been proofread (documentation, error messages, logs, comments...)

2024-07-19 09:36 UTC, pyrollo requested changes

2024-07-19 09:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                        VoxelType vt;
```suggestion
```
Plus besoin de ça, c'était dans le VectorRenderer pour :
1 - choisir le voxeltype
2 - faire place(x,y,z)

Maintenant tu peux plus simplement faire:
```java
switch(element.getValue()) {
    case GeometryModel.INSIDE -> {
        (traitement des sols)
        inside.place(...);
    }
    case GeometryModel.BORDER -> {
       (traitement des façades)
       ....
       ....
    }
}
```

2024-07-19 09:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                                vt = edge;
```suggestion
```
la variable intermédiaire `vt` devient inutile

2024-07-19 09:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                                        vt.place(c.x(), c.y(), z);
```suggestion
                                        edge.place(c.x(), c.y(), z);
```

2024-07-19 09:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                            } // Should never get there
```suggestion
```

2024-07-19 09:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                        vt.place(c.x(), c.y(), zMax);
```suggestion
```

2024-07-19 09:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +            }
Ce n'est pas utile d'itérer une première fois pour copier la liste puis itérer 2 fois sur cette liste.
Tu peux plus simplement itérer 2 fois sur le chunk.
```suggestion
```

2024-07-19 09:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +            for (Chunk2dElement element : BboxElements) {
```suggestion
            for (Chunk2dElement element : chunk) {
```

2024-07-19 09:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +            for (Chunk2dElement element : BboxElements) {
```suggestion
            for (Chunk2dElement element : chunk) {
```

2024-07-19 09:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +                        e.printStackTrace();
```suggestion
```
Ça ne sert pas à grand chose et on va pouvoir l'éviter plus tard.

2024-07-19 09:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +                    zMax = z;
```suggestion
                zMax = Math.max(Zmax, heightMap.get(element.getCoords());
```

2024-07-19 09:39 UTC, pyrollo requested changes
Pour le titre, il ne s'agit pas d'une amélioration du vector renderer mais de créer un building renderer et un leveling renderer

2024-07-19 09:39 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +            }
```suggestion
```

2024-07-19 09:39 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +            for (Chunk2dElement element : bboxElements) {
```suggestion
            for (Chunk2dElement element : chunk) {
```

2024-07-19 13:50 UTC, pyrollo requested changes
Quelques bricoles et des suggestions de noms.

2024-07-19 13:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        this.edge = edge;
```suggestion
        this.roof = roof;
        this.walls = walls;
```

2024-07-19 13:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +     *                  and lines)
```suggestion
     * @param roof      Voxel type for roof
     * @param walls     Voxel type for walls
```

2024-07-19 13:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                                for (int z = zMin; z < zMax; z++)
Pour éviter que les fenêtres de ton immeuble soient toujours à la même altitude et que, du coup, tu soies obligé de tester si elle ne sont pas trop près du toit ou du sol, tu peux utiliser un `z` relatif à la hauteur de l'immeuble:
```java
for (int z = 1; z < MAX_BUILDING_HEIGHT; z++)
    if (z % 4 ...
       .... place(c.x(), c.y(), z + zMin)
   ...
```
Et tu peux virer `zMax` qui ne te sera plus utile.

2024-07-19 13:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +     * @param heightMap Height map of the ground (on which features will be placed)
```suggestion
     * @param heightMap Height map of the ground, will be updated according to leveling
```

2024-07-19 13:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +     * @param outside   Voxel type to draw outside geometries
```suggestion
     * @param filling   Voxel type for filling leveled areas
```
ou
```suggestion
     * @param stuffing  Voxel type for filling leveled areas
```

2024-07-19 13:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +            int zMax = 0;
```suggestion
            int zMax = Integer.MIN_VALUE;
```
Sinon ça va bugger en dessous de l'altitude 0.

2024-07-19 13:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +                    }
```suggestion
                    for (int z = heightMap.get(c); z <= zMax; z++) {
                        try {
                            outside.place(c.x(), c.y(), z);
                        } catch (OutOfWorldException e) {}
                    }
                    heightMap.set(c, zMax);
```
En mettant le `set` à la fin tu t'économises deux ligne et une variable.

2024-07-19 15:40 UTC, naulan-chrzaszcz commented
note: refaire le premier commit mal squash

2024-07-22 12:11 UTC, zhak5388 submitted a review, later dismissed
Bon, c'est juste des remarques qui me sont venues en lisant : )

2024-07-22 12:11 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +    private static final int MAX_BUILDING_HEIGTH = 19;
Question bête, pourquoi c'est spécifiquement 19 ? (Si c'est un truc temporaire, hmm peut-être mettre un commentaire ?)

2024-07-22 12:11 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +     * @param models    Models to be rendered (only Rasterizable ones will be)
J'aurais mis `Rasterizable` en lien (`{@link Rasterizable}`)

2024-07-22 12:11 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +    public void render() {
J'imagine que ça a été discuté mais si tous les `Renderer` ont une méthode `render()`, est ce qu'il faudrait pas mettre une interface `Renderer` ? (Je me trompe peut-être c'est peut etre de la surconception haha)

2024-07-22 12:11 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +            }
Question un peu générale, mais est ce qu'il peut y avoir des `Models` non rasterizable mais renderable ?

2024-07-22 12:16 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +    private static final int MAX_BUILDING_HEIGTH = 19;
Oui, ta raison.
La valeur 19 est purement aléatoire et c'est temporaire pour plus tard, implémenter ce qu'on a parlé ce matin.

2024-07-22 12:17 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +    public void render() {
Je voulais faire pareil, mais je ne sais plus ce que @pyrollo m'avait dit

2024-07-22 12:39 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +    public void render() {
Oui on va en faire une, il y en a effectivement une "de fait". Je pense qu'on va la créer quand on crééra le "RendererStore", là où l'on va ranger les différents renderer à appeler.

2024-07-22 12:41 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +            }
Oui, par exemple un modèle en 3 dimensions (le rasteriser reviendrait à l'applatir).
Plus tard, on aura plus de "rasterizable" mais que des "voxelizable". Là encore, on peut se laisser la possibilité d'avoir des modèles non voxelisables (des données autres ?).

2024-07-22 13:01 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +            }
Ok, d'accord ! Ce qui me gênait ici, c'est le fait que sur chacune des méthodes `render()` il y a la même vérification rasterizable et chunk iterable

2024-07-23 12:36 UTC, pyrollo requested changes
- [ ] The code has unit tests associated

C'est un peu compliqué pour les renderers. Il y a un "TestingVoxelWorld" pour ça. Tu créés un tout petit monde et une heightMap correspondante.
Pour le leveling renderer tu lances ton renderer avec un modèle et tu peux vérifier l'effet sur la heightmap.
Pour le building renderer, il faut aller voir le monde.
   
- [ ] The code has Javadoc Comments associated

  --> Ça c'est à faire. On fait des javadoc sur ce qui est "public" seulement.
  
- [ ] Relevant documentation inside the /docs folder has been updated

  --> Si tu n'as pas de doc à ajouter ou modifier, tu peux barrer.

- [ ] All examples in docs/usage/Examples.md work the same (or have been adapted if subject to changes in this PR)

  --> Idem, tu peux barrer, on n'a pas encore d'exemples.
  
- [ ] The texts have been proofread (documentation, error messages, logs, comments...)

  --> Bon là c'est plus chaud.

2024-07-23 12:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> + * TODO.
DOIT :)

2024-07-23 12:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +            }
Tout ça va changer avec #25. Il n'y aura déjà plus qu'une interface à tester. Le test pourrait peut être être déporté dans le model store.

2024-07-23 12:50 UTC, indyteo commented
> --> Bon là c'est plus chaud.

Booooh, il suffit de se relire :)
Après moi perso j'utilise la correction orthographique intégrée à l'IDE, c'est très puissant et ça indique intelligemment les fautes d'orthographe, de syntaxe, et de grammaire, dans tous les strings / commentaires / javadoc, et optionnellement dans les noms de variable, classe, etc... Je dis "intelligemment" parce que ça tiens compte du contexte "langage de programmation" donc par exemple `executiontime` est une erreur, `executionTime` non. `ExectionTime` indique une erreur sur la partie `Exection` en suggérant de la remplacer par `Execution`, sans toucher à `Time` qui est correct.

Il me semble @naulan-chrzaszcz que tu utilises aussi IntelliJ, du coup tu devrais pouvoir en profiter, ça aide beaucoup à voir et comprendre des petites erreurs d'anglais ^^

2024-07-23 13:16 UTC, naulan-chrzaszcz commented
> > --> Bon là c'est plus chaud.
> 
> Booooh, il suffit de se relire :) Après moi perso j'utilise la correction orthographique intégrée à l'IDE, c'est très puissant et ça indique intelligemment les fautes d'orthographe, de syntaxe, et de grammaire, dans tous les strings / commentaires / javadoc, et optionnellement dans les noms de variable, classe, etc... Je dis "intelligemment" parce que ça tiens compte du contexte "langage de programmation" donc par exemple `executiontime` est une erreur, `executionTime` non. `ExectionTime` indique une erreur sur la partie `Exection` en suggérant de la remplacer par `Execution`, sans toucher à `Time` qui est correct.
> 
> Il me semble @naulan-chrzaszcz que tu utilises aussi IntelliJ, du coup tu devrais pouvoir en profiter, ça aide beaucoup à voir et comprendre des petites erreurs d'anglais ^^

Team VS code ✋🏻

2024-08-26 14:10 UTC, pyrollo commented
Va falloir rebaser cette PR une fois la #29 mergée et voir enfin le résultat !

2024-10-01 12:03 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        scheduler.schedule("renderers.buildings", () -> {
Attention, c'est un doublon.

2024-10-01 12:03 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/outputs/testing/TestingVoxelWorld.java
> +        return voxels[index(pos.x(), pos.y(), pos.z())];
Duplication de code ici

2024-10-01 13:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            log("Levelling for buildings");
```suggestion
            log("Leveling for buildings");
```
(Même chose en dessous)

2024-10-01 13:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/outputs/minecraft/MCVoxelTypeFactory.java
> +            case GLASS -> "minecraft::glass";
```suggestion
            case GLASS -> "minecraft:glass";
```

2024-10-01 13:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> + * Allows the level of the floor.
?
Tu es sûr d'avoir utilisé le bon verbe ? :laughing:

2024-10-01 13:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +     * @param heightmap Height map of the ground, will be updated according to
```suggestion
     * @param heightmap Heightmap of the ground, will be updated according to
```

2024-10-01 13:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +    private final VoxelType filling;
```suggestion
    private final VoxelType fill;
```

2024-10-01 13:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +     * @param filling   Voxel type for filling leveled areas
```suggestion
     * @param filling   Voxel type to fill leveled areas
```

2024-10-01 13:20 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +                    assertEquals("dirt", world.get(pos), "%s: shoud be dirt".formatted(pos));
Il n'y a pas une méthode intégrée plutôt ?
Genre :
```suggestion
                    world.assertVoxel(pos, "dirt");
```

2024-10-01 13:59 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +     * @param filling   Voxel type for filling leveled areas
Peut être même :
```suggestion
     * @param filling   Voxel type to fill leveled areas with
```

2024-10-01 14:00 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +    private final VoxelType filling;
Pour moi c'est plutôt `filling`

2024-10-01 14:08 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +    private final VoxelType filling;
Hmm oui ça dépend sous quel angle on voit la chose, après c'est pas dramatique ça va bouger probablement quand on aura les `Placeable`s pour uniformiser les noms de ces objets

2024-10-01 14:16 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +    private final VoxelType filling;
Je pensais comme ça : `fill` c'est l'action, `filling` c'est plutôt ce avec quoi on remplit.

2024-10-01 14:17 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +    private final VoxelType filling;
Mais oui, ça va bouger :)

2024-10-01 14:24 UTC, pyrollo requested changes
Il y a une duplication de code à corriger.
Tu peux mettre l'ajout du SuppressWarning dans un même commit qu'autre chose.
Je ne peux pas vérifier ici si ton premier commit fonctionne. Si ce n'est pas le cas, tu peux tout mettre dans un seul commit.

2024-10-02 08:51 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/outputs/testing/TestingVoxelWorld.java
> +        return voxels[index(pos.x(), pos.y(), pos.z())];
@pyrollo, j'ai corrigé : 
```java
/**
 * Get voxel string value at a given position.
 *
 * @param x X-coordinates of position to get
 * @param y Y-coordinates of position to get
 * @param z Z-coordinates of position to get
 * @return Voxel value at this position
 */
public String get(int x, int y, int z) {
    return get(new WorldCoords3d(x, y, z));
}
```

2024-10-02 08:57 UTC, naulan-chrzaszcz commented
Il me manque dans le rendu des bâtiments, les étages a généré et les tests associés du rendu (Faut que je médite la dessus)

2024-10-02 09:40 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/outputs/testing/TestingVoxelWorld.java
> +        return get(new WorldCoords3d(x, y, z));
Que penses-tu de faire l'inverse : get(pos) appelle get(x,y,z) ?
Vois-tu un avantage à un sens plutôt qu'à l'autre ?
(au delà du fait que tu modifies un code qui marchait bien)

2024-10-02 10:05 UTC, pyrollo commented
> Il me manque dans le rendu des bâtiments, les étages a généré et les tests associés du rendu (Faut que je médite la dessus)

Pour les tests du rendu, fait un truc très simple. Quand tu as généré une carte et lancé le jeu, tu as bien vu que ça fonctionnait bien.

Donc les tests vont surtout servir à verifier que persenne ne va casser ton renderer. Une vérification de base suffit : un tout petit batiment carré avec au moins un voxel d'intéreur sur un sol plat et on vérifie qu'on a bien un toit, des murs, des étages et des vitres.

Eventuellement un test supplémentaire pour vérifier que la metadata est bien traitée.

2024-10-02 10:13 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            log("Levelling for buildings done");
```suggestion
            log("Leveling for buildings done");
```

2024-10-02 10:13 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> + * Allows the floor to be level.
Ok j'ai compris ce que tu voulais dire mais c'est un peu bizarre en anglais, peut-être plus simplement :
```suggestion
 * Alters floor level to guarantee flat surface under each model.
 * The final floor height is equals to the greatest floor height over all the model's surface.
```

2024-10-02 10:13 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +                    world.assertVoxel(null, pos);
```suggestion
                    world.assertVoxelNull(pos);
```
(Même chose en dessous)

2024-10-02 10:18 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> + * Allows the floor to be level.
Ah oui, la phrase corrigée de Naulan doit être : 
```suggestion
 * Allows the floor to be leveled.
```
En général je ne suis pas fan des "allows to" ou "permet de", ce sont des mots qui ne servent absolument à rien (sauf si on gère effectivement une notion de permissions).

Donc, "Permet de niveler le sol" -> "Nivelle le sol"  et, de même, comme le proposait Théo : "Allows the floor to be leveled" -> "Levels the floor"

2024-10-02 11:45 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/outputs/testing/TestingVoxelWorld.java
> +        return get(new WorldCoords3d(x, y, z));
Ouais c'est vrai, j'évite de crée un objet dans l'argument `get`

2024-10-07 16:17 UTC, indyteo submitted a review, later dismissed

2024-10-07 18:42 UTC, naulan-chrzaszcz commented
J'vais attendre la PR #38 et les revues des autres avant de merge, je pense

2024-10-07 18:49 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +                    world.assertVoxel("brick", c);
TODO: Manque le check pout les endroits où il y a rien

2024-10-08 08:05 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +     * @param window    Voxel type to draw window inside geometries
```suggestion
     * @param roof      Voxel type for roofs
     * @param wall      Voxel type for walls
     * @param window    Voxel type for windows
```

2024-10-08 08:05 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
Ajouter un test sans la metadata pour vérifier que le comportement est bien celui attendu (à déterminer du coup).

2024-10-08 10:12 UTC, zhak5388 reviewed
Bon quelques broutilles (pas encore vu les tests)

2024-10-08 10:12 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +     *                  leveling
C'est volontaire ce saut à la ligne?

2024-10-08 10:12 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                        roof.place(c.x(), c.y(), zMin + z);
Bon, c'est du détail, mais tu penses quoi de cette manière: 
```java
for (int z = 2; z < maxBuildingHeight; z = z + 4)
    roof.place(c.x(), c.y(), zMin + z);
```

2024-10-08 10:12 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                    ((z % 4 == 0) ? window : wall).place(c.x(), c.y(), zMin + z);
Je me demande si c'est bien de mettre en dur le `4` si c'est à deux endroits différents (Je ne sais pas en vrai)
Et puis je me demande si c'est pas une bonne idée d'ajouter un commentaire pour dire 1 étage = 3 voxels (histoire que lorsque on re-ouvre le code plus tard, on sache d’où ça vient le 4)

2024-10-08 10:24 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +     *                  leveling
Yes

2024-10-08 10:24 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +     *                  leveling
C'est le formatage de VS

2024-10-08 10:25 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                        roof.place(c.x(), c.y(), zMin + z);
Pas mal, j'vais test

2024-10-08 13:26 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                    ((z % 4 == 0) ? window : wall).place(c.x(), c.y(), zMin + z);
Tu crois qu'on pourrais utiliser le VoxelPattern dans le rendu des buildings ?

2024-10-08 13:32 UTC, zhak5388 reviewed
Broutilles 1.0.1

2024-10-08 13:32 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +                if (x == 0 && y == 0 && world.get(x, y, z) != "air")
Du coup, c'était le truc sur le `equals` et `==` avec les objets sur java

2024-10-08 13:32 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +                assertEquals(expectedHeight, heightmap.get(pos), "%s: unexpected value".formatted(pos));
C'est plus une préférence personnelle mais j'aurais mis `1` en dur sur le `assertEquals`
**Edit:** Ah autant pour moi, j'avais pas vu que c'était à deux endroits différents

2024-10-08 13:37 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +                assertEquals(expectedHeight, heightmap.get(pos), "%s: unexpected value".formatted(pos));
Resolve ?

2024-10-08 15:35 UTC, zhak5388 commented
J'ai merge ma PR, du coup désolé ça t'ajoute des classes à faire :sweat_smile: 
Du coup maintenant quand un `Renderer` est crée, les étapes c'est:
1) Créer sa classe des paramètres dans `parameters.renderers` (Il y a un [how-to](https://github.com/ignfab/minalac-generator/blob/main/docs/dev/Renderer.md) dans `docs.dev`)
2) Mettre à jour la documentation : 
   + `GenerationParameters.md`
   + `default.yaml` et `minecraft.yaml`
3) Dans SampleImplementation l'enregister avec `registerRenderer()`
 
Pour la structure tu pourras t'inspirer des classes existantes `Params`!

2024-10-08 16:07 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                    ((z % 4 == 0) ? window : wall).place(c.x(), c.y(), zMin + z);
Dans l'état non, mais ça fera l'objet de travaux futurs. Le but sera d'avoir des voxel patterns qui sont capables de s'adapter à leur environnement (en gros un pattern où on dit "place-toi le long de cet axe", ou alors "place-toi avec répétition jusqu'à tel endroit").

Pour l'instant, je pense que l'objet de cette PR est surtout de montrer comment on peut exploiter les attributs des données pour les rendre plus belles (hauteur des bâtiments) et aussi des traitements indépendants comme la mise à niveau du terrain. Vous allez probablement aborder le sujet des voxel patterns juste après que cette PR soit mergée, d'ailleurs 😄

2024-10-08 16:28 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                    ((z % 4 == 0) ? window : wall).place(c.x(), c.y(), zMin + z);
Je pense pas que ça soit nécessaire de mettre des `VoxelPattern` sur cette PR, ça a l'air prématuré (après je sais pas ce que en pense Pierre-Yves) et comme a dit Théo ça sera certainement des travaux futurs
Et puis il y a aussi le fait qu'on ne désérialise pas encore les `VoxelPattern` (il faudra virer les `SemanticType` et faire en sorte de désérialiser des `VoxelType` en fonction de la valeur du format avant j'imagine) [Dans la précédente PR il y a pas les paramètres pour `GroundRenderer`  à cause du pattern pas encore pris en charge]
Mon commentaire c'était plus par rapport à lisibilité en vrai

2024-10-09 13:29 UTC, indyteo commented on examples/default.yaml
> +  leveling:
Je l'aurais appelé `building-leveling` car il n'y a pas qu'un seul leveling qui peut avoir lieu (on pourrait vouloir le faire sous les routes aussi par exemple)

2024-10-09 13:29 UTC, indyteo commented on examples/default.yaml
> +    window: GLASS
Il faut modifier aussi ces valeurs dans `minecraft.yaml`

2024-10-09 13:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        scheduler.schedule("renderers.leveling", () -> {
Le renderer des buildings (ci-dessous `renderers.buildings`) doit s'exécuter après celui-ci

2024-10-09 13:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParams.java
> +     * The type of models to render.
Copié/collé

2024-10-09 13:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParams.java
> +     * The semantic type of voxel used to fill the space beneath the building geometry,
Ce n'est pas forcément un building

2024-10-09 13:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParams.java
> +     * @param filling   the voxel type for fill leveled areas with.
```suggestion
     * @param filling   the voxel type to fill leveled areas with.
```

2024-10-09 13:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +public class BuildingRenderer implements Renderer {
Il existe un type de `ModelRenderer` pour ça

2024-10-09 13:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                maxBuildingHeight = ((Number) maxBuildingHeightObject).intValue();
Je ne suis pas forcément convaincu du choix d'une valeur par défaut ici, éventuellement je serais plutôt d'avis d'ignorer le modèle, parce qu'il ne peut pas être rendu. Et plus tard, comme pour le check du type de voxelizable juste au dessus, le mécanisme de filtre pourra ne renvoyer que les modèles qui sont conformes aux demandes de métadonnées du renderer (et donc il suffira d'un appel à getMetadata sans aucune vérification supplémentaire)

2024-10-09 13:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                wall.place(c.x(), c.y(), zMax);
Cette opération est inutile, le voxel va être écrasé par le toit

Éventuellement, pour améliorer légèrement les performances (éviter une boucle supplémentaire, et donc une voxelisation puisqu'elles sont faites à la volée), tu peux mettre directement le voxel de toit ici, et pareil dans la boucle sur inside, mettre le voxel de toit tout en haut, et tu n'auras plus besoin de ta boucle dédiée au toit

2024-10-09 13:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +public class LevelingRenderer implements Renderer {
Même chose, ModelRenderer

2024-10-09 14:18 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                maxBuildingHeight = ((Number) maxBuildingHeightObject).intValue();
Du coup, j'me dit que le `LevelingRenderer` peut terraformer des "bâtiments" qui n'auront pas de hauteur

2024-10-09 14:31 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParams.java
> +     * The semantic type of voxel used to fill the space beneath the building geometry,
J'ai remplacé par `model`

2024-10-09 14:32 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        scheduler.schedule("renderers.leveling", () -> {
J'suis pas sur d'avoir bien compris, j'ai fait la modification sur ce que j'ai cru comprendre

2024-10-09 14:48 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                maxBuildingHeight = ((Number) maxBuildingHeightObject).intValue();
Sauf qu'en réalité, aucun bâtiment ne sortira de la chaîne de traitement des modèles sans hauteur. Soit ils en auront reçu une par défaut, soit ils auront été supprimés.

Et si c'était vraiment un problème, on pourrait aussi envisager de donner la possibilité de placer un filtre en entrée du leveling renderer, mais ça me semble inutile (ceci dit peut-être que ça deviendra possible sans aucun code supplémentaire plus tard en fonction des solutions qu'on utilise pour la désérialisation).

2024-10-09 14:48 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                maxBuildingHeight = ((Number) maxBuildingHeightObject).intValue();
J'ai juste ajouté une condition dans le rendu de `LevelingRenderer` : 
```java
if (model.getMetadata("height") == null)
    return;
```
J'pense que c'est good

2024-10-09 14:54 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +                maxBuildingHeight = ((Number) maxBuildingHeightObject).intValue();
> Sauf qu'en réalité, aucun bâtiment ne sortira de la chaîne de traitement des modèles sans hauteur. Soit ils en auront reçu une par défaut, soit ils auront été supprimés.
> 
> Et si c'était vraiment un problème, on pourrait aussi envisager de donner la possibilité de placer un filtre en entrée du leveling renderer, mais ça me semble inutile (ceci dit peut-être que ça deviendra possible sans aucun code supplémentaire plus tard en fonction des solutions qu'on utilise pour la désérialisation).

GitHub n'a pas refresh la conv, j'avais pas vu
La condition que j'ai ajouté sert donc à rien ?

2024-10-09 15:09 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        parser.registerRenderer("building-leveling", LevelingRendererParams.class);
Ah non je parlais pas du type du renderer, seulement son nom (l'identifiant qui sert de clé pour référencer l'instance du renderer)

2024-10-09 15:09 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        scheduler.schedule("renderers.leveling", () -> {
Oui voilà c'est ça, parce que sinon tu comprends, si le bâtiment est rendu avant la mise à niveau du terrain, il fini (partiellement) sous le sol. Et pire, si les deux s'entremêlent, un bout du bâtiment peut se mettre sur le terrain brut, et un autre bout sur le terrain nivellé, et donc un rendu incorrect

2024-10-09 15:09 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParams.java
> +     * The type of models to leveling.
```suggestion
     * The type of models to use to perform leveling.
```

2024-10-09 15:09 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParams.java
> +                generation.world().getFactory().createVoxelType(filling));
Pour être cohérent avec le code-style ((mal?)heureusement les checks couvrent pas très bien les questions d'indentation et de wrapping)
```suggestion
        return new LevelingRenderer(
            new ModelSelection(generation.models(), modelType),
            generation.heightmaps().get(heightmap),
            generation.world().getFactory().createVoxelType(filling)
        );
```
(Même chose sur le BuildingRendererParams)

2024-10-09 15:09 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        int maxBuildingHeight = ((Number) maxBuildingHeightObject).intValue();
Autre façon de l'écrire :
```suggestion
        if (!(model.getMetadata("height") instanceof Number maxBuildingHeightNumber))
            return;
        int maxBuildingHeight = maxBuildingHeightNumber.intValue();
```
Mais encore une fois je suis convaincu qu'à terme on écrira juste :
```java
int maxBuildingHeight = model.getMetadata("height");
```
Parce qu'à ce stade de l'exécution, on est certain que la métadonnée existe et a le bon type, sinon c'est une erreur de configuration de la part de l'utilisateur (configurateur des sources de données notamment, pas utilisateur final)

2024-10-09 15:09 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +            return;
Non par contre ça n'a rien à faire ici selon moi, ça sera un filtre exprimé au niveau du ModelSelection reçu en paramètre éventuellement (mais pour moi c'est pas quelque chose qui doit être fait dans cette PR)

Au passage, ce code est toujours faux (pour les bâtiments) car dans tous les cas il y a un post-processeur (temporaire) qui fait planter la génération si la valeur est absente ou invalide : https://github.com/ignfab/minalac-generator/blob/main/src/main/java/com/ignfab/minalac/generator/SampleImplementation.java#L162

2024-10-09 15:13 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParams.java
> +                generation.world().getFactory().createVoxelType(filling));
Pour être sur que le check du code style ne plante pas, je fait "format document" avec Visual Studio Code
Je ferait plus attention la prochaine fois a ce genre de petite erreur

2024-10-09 15:16 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParams.java
> +                generation.world().getFactory().createVoxelType(filling));
Essaye de voir si tu trouve un plugin VS Code qui est compatible avec le fichier de configuration de Checkstyle peut-être ? Comme ça il reformatte ce qui ne va pas selon ces règles, et ne touche pas au reste ? Je ne sais pas si ça existe

2024-10-10 07:39 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +            return;
Je suis d'accord avec @indyteo, ici on fait du nivellement, la hauteur des immeubles n'a rien à voir. Imagine qu'on veuille niveler des terrains de sport ou des parkings, ça marchera comment ?

Plus généralement, la réécriture du projet a été lancée pour abandonner le plat de spaghetti qu'était la v1. L'idée est donc de rester le plus générique que possible et éviter d'hardcoder des trucs de ce genre.

2024-10-10 07:44 UTC, pyrollo requested changes
>     * ~Relevant documentation inside the `/docs` folder has been updated~
> 
>     * ~All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)~

Ces deux points ne devraiement pas être barrés.

Pour le second, rien à faire, ça marche.

Pour le premier, il manque la doc sur ces renderers dans `doc/usage/GenerationParameters.md`.

2024-10-10 08:15 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        parser.registerRenderer("building-leveling", LevelingRendererParams.class);
Normalement c'est corrigé

2024-10-10 08:16 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParams.java
> +                generation.world().getFactory().createVoxelType(filling));
Aucune idée, je vais regarder

2024-10-10 08:19 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        int maxBuildingHeight = ((Number) maxBuildingHeightObject).intValue();
Je pensais que cela allait fonctionner mais j'ai une exception  :
`Caused by: java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Integer (java.lang.Double and java.lang.Integer are in module java.base of loader 'bootstrap')`
Au pire, on peut juste remettre comme avant avec le cast `Number` ?

Car, la height c'est un float lorsqu'on l'obtient depuis la source

2024-10-10 09:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        int maxBuildingHeight = ((Number) maxBuildingHeightObject).intValue();
Ah oui le post-processeur est configuré pour convertir la valeur en double actuellement. Tu n'as qu'à faire en sorte qu'il convertisse en int, ou alors ajouter un post-processeur d'arrondi. Ça te fera te pencher sur leur mécanisme rapidement

Et sinon bien sûr tu peux aussi récupérer la hauteur en double plutôt que int ici, je sais pas si ça a un intérêt (je pense que c'est mieux l'autre solution)

Attention si tu décides de changer le parsing en int, il faudra probablement faire un parsing en double puis arrondir / tronquer, donc je pense qu'il est plus intéressant de mettre un post-processeur dédié à l'arrondi

Et au fait tu penseras à retirer le post-processeur temporaire dans le SampleImplementation qui servait de validation en attendant cette PR justement

2024-10-10 12:04 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        int maxBuildingHeight = ((Number) maxBuildingHeightObject).intValue();
Okay, je vois le PostProcesseur fait en sorte d'avoir toujours des données fiables

~~J'ai pas encore push~~, mais j'ai quand même ajouté ce genre de vérification car dans les tests, j'ai un NullPointerException quand les données sont mal set :
```java
        // It is possible that there are errors in the data sources
        // and a model does not have the "height" metadata.
        if (!(model.getMetadata("height") instanceof Number maxBuildingHeightNumber))
            return;
        int maxBuildingHeight = maxBuildingHeightNumber.intValue();
        // It is possible that the height is not well specified,
        // therefore either negative to represent a basement or something like that.
        //
        // This rendering of buildings is not for the moment designed for negative
        // heights so, stop the execution of the function here.
        //
        // The value 0 of the "height" metadata can correspond to a flat terrain,
        // therefore, does not render the model.
        if (maxBuildingHeight <= 0)
            return;
```

L'anglais ne vient pas de moi (je pense que cela se remarque) ca vient de Reverso
J'ai expliquer le pourquoi j'ai ajouté ces conditions

2024-10-10 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        int maxBuildingHeight = ((Number) maxBuildingHeightObject).intValue();
Je ne sais pas ce qu'en pense @pyrollo, mais selon moi, le renderer NE GÈRE PAS les possibles problèmes sur les données. Si elles sont invalides, il y aura une erreur, ou alors peut-être que ça marchera, mais mal, mais on s'en fiche.

On suppose que les données sont correctes en entrée du renderer. Il n'y a pas à faire de tests unitaires sur les cas problématiques selon moi (vu que le but du test est de valider les spécifications, et on spécifie que "si les données ne sont pas valides, le comportement n'est pas spécifié", donc pas de test)

2024-10-10 17:22 UTC, indyteo reviewed
Et du coup comme j'ai dis dans l'autre discussion plus haut, il faut simplifier la récupération de la métadonnée.

Je ne vois pas la modification de la chaîne de traitement des bâtiments avec l'ajout d'un post-processeur d'arrondi (et il faut retirer celui qui était temporaire)

2024-10-10 17:22 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +- `modelType`: The type of models to render.
Copié/collé

2024-10-11 06:58 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        int maxBuildingHeight = ((Number) maxBuildingHeightObject).intValue();
Pour moi le test est ok : un batiment à hauteur négative n'est pas rendu (c'est relativement logique). Sauf le jour où on voudra faire des parkings souterrains mais on n'y est pas.

Toujours selon moi, généralement, sauf s'il y a une vraie raison (genre le renderer ne peut pas savoir quoi faire), les renderers devraient faire le job sans erreur, quite à faire de la m**.

2024-10-11 07:02 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        int maxBuildingHeight = ((Number) maxBuildingHeightObject).intValue();
Ou alors, faudrait faire comme dans les sources: des exceptions ignorable ?

Après pour ne pas polluer les renderers avec des `instanceof`, on pourrait avoir des méthodes genre `getMetadataInt` qui renverrai un nombre si possible, rien (ou un default) sinon.

2024-10-11 07:04 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        int maxBuildingHeight = ((Number) maxBuildingHeightObject).intValue();
... et pour ce qui est du texte en commentaire dans le code que tu as mis Naulan, il serait peut être intéressant d'exposer une partie de l'explicaiton (genre "pas de rendu si hauteur absente ou <= 0") dans le mode d'emploi du renderer.

2024-10-11 08:26 UTC, pyrollo requested changes
Voilà, pas mal de commentaires:
- Sur la doc
- Du code style
- Des simplifications dans les tests

2024-10-11 08:26 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `heightmap`: The name of the heightmap to use. It must exist.
```suggestion
- `heightmap`: The name of the heightmap to use. It must exist and it will be updated.
```
Idéalement, il faudrait expliquer à quoi sert cette heightmap.

2024-10-11 08:26 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +
Proposition de descriptioon:
```suggestion
Levels ground under selected models.

Ground height is given by `heightmap`. If it's not flat under a model, it will be risen enough to be flat over model surface. `filling` voxels will be added to world and `heightmap` will be updated accordingly.
```

2024-10-11 08:26 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +
Proposition vite fait de description:
```suggestion
Renders buildings using selected models as buildings footprint. 

Building height is given by `height` metadata (if negative or zero, no building is rendered).

```

2024-10-11 08:26 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `window`: The semantic type of voxel used to render the windows of the models.
Si tu n'indiques pas la metadata, personne ne va deviner comment se servir de ton renderer:

```suggestion
- `window`: The semantic type of voxel used to render the windows of the models.

Model metadata:
- `height`: Height of building to render (no rendering if negative or zero)
```

2024-10-11 08:26 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        // therefore, does not render the model.
Un peu long comme commentaire pour dire qu'on ne fait pas de rendu si la hauteur est négtive.

Le fait qu'on ne fasse pas ce rendu est à mettre dans la documentation, ça devrait intéresser l'utilisateur.

2024-10-11 08:26 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        // and a model does not have the "height" metadata.
Pareil ici, suffit de dire que sans hauteur, pas de rendu.

2024-10-11 08:26 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +            int zMax = zMin + maxBuildingHeight;
La variable `zMax` n'est pas très utile vu qu'elle n'est utilisée qu'une seule fois.

2024-10-11 08:26 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +            int zMax = zMin + maxBuildingHeight;
Pareil ici

2024-10-11 08:26 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        int maxBuildingHeight = maxBuildingHeightNumber.intValue();
sauf si tu aimes taper des trucs au clavier, tu peux simplement appeler ces variables `height` et `heightNumber`

2024-10-11 08:26 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +     * Heightmap of the ground, will be updated according to leveling.
Vu que tu as des beaux commentaires ici, tu peux t'en inspirer pour ta doc.

2024-10-11 08:26 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +            // Update the heightmap to reflect the terraforming
```suggestion
            // Update the heightmap to reflect the leveling
```

2024-10-11 08:26 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +            // The building is always above the terraforming
Pas bien compris ce que tu veux dire ici. Déjà on ne fait pas (encore) de terraformation.
Si tu veux parler du nivelage, je pense qu'on s'en fout ici. On teste juste un batiment sur un terrain plat.

2024-10-11 08:26 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +            if (z != 0) {
Un *early return* (version *continue*) peut te faire économiser ta touche `tab`:
```suggestion
            if (z == 0)
               continue;
```

2024-10-11 08:26 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +                "Building height not the same, excepted: " + expectedHeight + ", have: " + actualHeight);
Cela n'échouera jamais avec les tests que tu as fait avant.

2024-10-11 08:26 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +                    world.set(x, y, z, "air");
Ce n'est pas forcément nécessaire de replir d'air, tu peux tester `null` comme pour le LevelingRenderer. Ça t'évite cette initialisation.

2024-10-11 08:26 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +                        .render(bbox));
Pour être homogène avec l'autre test:
```suggestion
        assertDoesNotThrow(() -> new LevelingRenderer(
                new ModelSelection(models, "building"),
                heightmap,
                world.getFactory().createVoxelType(SemanticType.DIRT)
            ).render(bbox));
```

2024-10-11 08:26 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +                world.getFactory().createVoxelType(SemanticType.GLASS)).render(bbox));
Je mettrais bien le .render à la ligne histoire qu'on le voit bien.
```suggestion
                world.getFactory().createVoxelType(SemanticType.GLASS)
            ).render(bbox));
```

2024-10-11 08:26 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +        model.setMetadata("height", 1);
Il ne devrait pas y avoir de lien avec la hauteur dans ce renderer:
```suggestion
        Model model = new TestingRectangleShapeVoxelizable2dModel(modelBbox);
```

2024-10-11 08:26 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +        models.add("building", model);
Ici tu mets "building" mais n'importe quel type pourrait marcher, comme "test" par exemple.

2024-10-11 08:26 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +            }
```suggestion
            // Renderers fills from ground (included) to leveled height (1 here)
            if (modelBbox.contains(pos.to2d()) && pos.z() >= heightFormula(pos.to2d()) && pos.z() <= expectedHeight) {
                world.assertVoxel("dirt", pos);
            } else {
                world.assertVoxelNull(pos);
            }
```

2024-10-11 09:32 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        int maxBuildingHeight = ((Number) maxBuildingHeightObject).intValue();
Je suis d'accord, et je pense qu'il n'y aura même pas besoin d'ajouter de méthodes de metadata int ou autre, car ce renderer a besoin d'un attribut height. C'est un fait, c'est une contrainte technique. Il faut une hauteur pour rendre un bâtiment. De la même manière il faut que les modèles soient ShapesVoxelizable.

Donc je pense qu'on pourra ajouter un type de filtre au ModelSelection qui ne prend que les modèles qui possèdent une metadata (et avec le bon type éventuellement). Et quand on implémentera ça, on verra pour que le ModelSelection lui-même puisse éventuellement, si un modèle ne correspond pas à la demande, soit le rejeter, soit faire une IgnorableException (exemple : Sélection par type de modèle (on rejette le reste), sélection par interface implémentée (on fait une IgnorableException si un modèle avait le bon type, mais n'implémentait pas l'interface demandée, ce qui était le cas avec le test instanceof dans chaque renderer), et même chose pour la sélection par métadonnée)

En somme, je suis d'accord que ça devra être vérifié, mais pas à la main dans le renderer (après est-ce qu'on le laisse pour l'instant comme ça et on remplacera plus tard ?). Justement dans le but que le renderer puisse faire le job demandé, même si il est absurde et ne fonctionnera pas ou mal (exemple une valeur négative)

2024-10-11 11:51 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +        model.setMetadata("height", 1);
La variable est utilisée dans tes conditions (c'est toi qui avais fait le test du leveling pendant mon absence)
La variable correspond à la hauteur non du modèle mais du nivellement, je pense

2024-10-11 11:52 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +        model.setMetadata("height", 1);
C'est pour ca je pense que je l'avais pas mis la variable en argument de `setMetadata`

2024-10-11 11:54 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +                    world.set(x, y, z, "air");
~~J'avais déjà essayé, mais cela ne fonctionnait pas~~

2024-10-11 11:55 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +                    world.set(x, y, z, "air");
~~Je vais réessayer et mettre l'erreur ici (si elle réapparait)~~

2024-10-11 11:58 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +                    world.set(x, y, z, "air");
`BuildingRendererTest.testBuildingRenderingWithoutMetadata:121 Voxel mismatch at (0, 0, 0) ==> expected: java.lang.String@5abf1a59<null> but was: <null>`

Bon, c'est plutôt moi qui a pas bien lu

2024-10-11 12:14 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +        models.add("building", model);
J'ai mit "model", c'est générique

2024-10-11 12:32 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +            // The building is always above the terraforming
C'est pour expliquer pourquoi le bâtiment commence a z = 1

2024-10-11 12:32 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        // and a model does not have the "height" metadata.
J'ai ecrit ceci : 
```
When there is no height or negative height, there is no rendering.
```

2024-11-19 16:52 UTC, naulan-chrzaszcz commented
J'ai encore de la documentation a actualiser puis ensuite elle doit être bon

2024-11-20 13:17 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +## Leveling Renderer
Uniformisation :
```suggestion
## Leveling renderer
```
(même chose sur le 2ème)

2024-11-20 13:17 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +- `height`: Height of building to render (no rendering if negative or zero)
Plutôt que "Model metadata" je mettrais quelque chose du style "Model requirements", qui laisse la possibilité de donner des contraintes sur les métadonnées comme ici, mais aussi sur les capacités de voxelisation (concept bien présent dans le code mais pour l'instant non documenté parce qu'on n'a pas trouvé de façon simple pour l'expliquer à l'utilisateur)

2024-11-20 13:17 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +- `heightmap`: The name of the heightmap to use. It must exist and it will be updated.- `roof`: The semantic type of voxel used to render the roof of the models.
```suggestion
- `heightmap`: The name of the heightmap to use. It must exist and it will be updated.
- `roof`: The semantic type of voxel used to render the roof of the models.
```

2024-11-20 13:17 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +- `type`: Must be the value `building`.
Le type est écrit juste au dessus, est là on est dans les "extra parameters", sous-entendu "en plus du type", ça n'apporte pas grand chose de le réécrire ici

2024-11-20 13:17 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/BuildingRendererParams.java
> +            SemanticType window) {
Code-style
```suggestion
    public BuildingRendererParams(
        String modelType,
        String heightmap,
        SemanticType roof,
        SemanticType wall,
        SemanticType window
    ) {
```
(Même remarque sur le constructeur du leveling)

2024-11-20 13:17 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +    // or even closures (one for inside, one for edge and another for init).
Vieux commentaire copié collé qui n'est plus d'actualité (ça sera des placeables maintenant)

2024-11-20 13:17 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +            VoxelType window) {
Même remarque de code-style

2024-11-20 13:17 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +     * @param selection Mdels selection to be leveled
```suggestion
     * @param selection Models selection to be leveled
```

2024-11-20 13:17 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +        if (!(model instanceof ShapesVoxelizable2d voxelizable)) {
Tu n'as aucune raison d'imposer que ça soit *shapes*-voxelizable

2024-11-20 13:17 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/GenerationParamsTest.java
> +        );
```suggestion
            SemanticType.GLASS
        ));
```

2024-11-20 13:17 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +        int bboxSizeZ = 22;
À quoi servent les variables ? Elles ne sont utilisées qu'une seule fois

2024-11-20 13:17 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +                world.getFactory().createVoxelType(SemanticType.GLASS)).render(bbox));
```suggestion
        assertDoesNotThrow(() -> new BuildingRenderer(
            new ModelSelection(models, "building"),
            heightmap,
            world.getFactory().createVoxelType(SemanticType.COBBLE),
            world.getFactory().createVoxelType(SemanticType.BRICK),
            world.getFactory().createVoxelType(SemanticType.GLASS)
        ).render(bbox));
```

2024-11-20 13:17 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +            // The building is always above the terraforming
Dans ce cas si tu veux expliquer quelque chose, le mieux c'est de l'expliquer. :upside_down_face:

```suggestion
            // The building is always above the terrain.
            // In this test, the (flat) ground is at z = 0,
            // thus the building starts at z = 1
```

2024-11-20 13:17 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +                world.getFactory().createVoxelType(SemanticType.GLASS)).render(bbox));
Même remarque sur le code-style

2024-11-20 13:17 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +    }
Je mettrais juste un petit commentaire qui explique à quoi sert cette fonction (il suffit de dire que ça permet de simuler un terrain non plat)

2024-11-20 13:17 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
> +            world.assertVoxel(null, c);
```suggestion
            world.assertVoxelNull(c);
```
Même chose à plusieurs endroits dans ce fichier

2024-11-20 14:58 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/LevelingRenderer.java
> +            System.err.println("Ignoring non shapesvoxelizable model. Type: " + model.getClass());
```suggestion
            System.err.println("Ignoring non voxelizable model. Type: " + model.getClass());
```

2024-11-20 15:04 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +    }
Est-ce que le commentaire te convient ?

2024-11-20 15:24 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +     * @param pos represents a component on the surface (xy-plane) in the voxel world.
```suggestion
     * @param pos Horizontal position in the voxel world.
```

2024-11-20 15:25 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +     * @return A random height
```suggestion
     * @return A random height
```
Random ?

2024-11-20 15:28 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParams.java
> + * {@link LevelingRenderer}.
```suggestion
 * Parameters for {@link LevelingRenderer}.
```

2024-11-20 15:29 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParams.java
> +     * The semantic type of voxel used to fill the space beneath the model,
```suggestion
     * Type of voxel used to fill the space beneath the model,
```

2024-11-20 15:31 UTC, indyteo reviewed
Euh, par contre si tu déclares les champs des paramètres en `final` Jackson risque d'avoir bien plus de mal à écrire leur valeur...

2024-11-20 15:31 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/DataSourceParams.java
> +    public void validate() throws IllegalArgumentException {
Au passage peut-être valider `modelType` histoire d'avoir une validation complète, je l'avais pas vu (juste `!isBlank` ça suffira)

2024-11-20 15:31 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/renderers/LevelingRendererTest.java
> +    }
C'est pas random ? Arbitraire plutôt tu voulais dire non ?

2024-11-20 15:31 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
Tu as encore des `assertVoxel(null)` à remplacer ici

2024-11-20 15:41 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/DataSourceParams.java
> +    public void validate() throws IllegalArgumentException {
J'avais pas rebase ma PR, mais j'vais le faire dans #57

2024-11-20 16:26 UTC, naulan-chrzaszcz commented
> Euh, par contre si tu déclares les champs des paramètres en `final` Jackson risque d'avoir bien plus de mal à écrire leur valeur...

Ah bon ?

2024-11-20 17:21 UTC, indyteo commented
Un champ final est par définition un champ constant, dont la valeur ne change pas (et la valeur par défaut si le champ n'est pas initialisé est `null`, donc tes champs sont nulls et le resteront à jamais (bon c'est pas 100% vrai mais en principe oui)

2024-11-22 14:23 UTC, naulan-chrzaszcz commented
Je viens de mettre à jour le code avec un test supplémentaire pour la désérialisation et j'ai supprimé le mot-clé `final` sur tous les params.

2024-11-25 09:37 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/BuildingRendererParamsTest.java
> +        });
Quand une assertion échoue, une erreur se produit (`AssertionFailureException` ou un truc du genre). Donc là, tu assert que tes assert passent.
```suggestion
        BuildingRendererParams params = assertDoesNotThrow(() -> mapper.readValue(requiredFields, BuildingRendererParams.class));
        assertEquals("building", params.modelType);
        assertEquals("ground", params.heightmap);
        assertEquals(SemanticType.COBBLE, params.roof);
        assertEquals(SemanticType.BRICK, params.wall);
        assertEquals(SemanticType.GLASS, params.window);
```

2024-11-25 09:38 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParamsTest.java
> +        });
Même remarque ici

2024-11-25 09:39 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/renderers/BuildingRendererTest.java
Ctrl + F `.assertVoxel(null`

2025-02-10 15:51 UTC, pyrollo requested changes
Remarques avant "refresh"!

2025-02-10 15:51 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `filling`: [Placeable](#placeables) are used to position the space beneath the model, ensuring it connects to the ground and does not appear to float.
```suggestion
- `filling`: [Placeable](#placeables) placed beneath the model, ensuring it connects to the ground and does not appear to float.
```

2025-02-10 15:51 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `heightmap`: The name of the heightmap to use. It must exist and it will be updated.
```suggestion
- `heightmap`: The name of the heightmap to use. It must exist.
```
(pas de mise à jour dans le building renderer)

2025-02-10 15:51 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `window`: [Placeable](#placeables) are used to render the windows of the models.
```suggestion
- `roof`: [Placeable](#placeables) used to render roofs
- `wall`: [Placeable](#placeables) used to render walls.
- `window`: [Placeable](#placeables) used to render windows.
```

2025-02-10 15:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParams.java
> +    }
```suggestion
        filling.validate();
    }
```

2025-02-10 15:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParams.java
> +     * @param modelType type of models to leveling.
```suggestion
     * @param modelType type of models to level.
```

2025-02-10 15:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        // TODO remove this condition when the parser post-processor is merged
It is merged !

2025-02-10 15:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        int height = Double.valueOf(heightString).intValue();
Pourquoi pas directement Integer.valueOf ?

2025-02-10 16:00 UTC, indyteo reviewed
Attention il va y avoir des modifications à faire si #69 est mergée avant. Sinon ça sera le contraire

2025-02-10 16:00 UTC, indyteo commented on examples/minecraft.yaml
> +      STONE: 10
Rebase raté

2025-02-10 16:00 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +- `roof`: [Placeable](#placeables) are used to render the roof of the models.
Cette valeur n'est pas présente dans l'exemple juste au dessus ni dans les `examples/*.yaml` alors qu'elle est marqué comme obligatoire. Je ne comprends pas comment tu arrives à le faire fonctionner chez toi ?

2025-02-10 16:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/LevelingRendererParams.java
> +    }
```suggestion
        filling.validate();
    }
```

2025-02-10 16:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> + * The building generated have a custom height, floors and windows.
```suggestion
 * The generated buildings have a custom height, floors and windows.
```
Ou
```suggestion
 * The generated building has a custom height, floors and windows.
```
(Je pense que le 1er est plus logique puisque ta 1ère ligne parle des "buildings" au pluriel)

2025-02-10 16:02 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        int height = Double.valueOf(heightString).intValue();
Pour autoriser un nombre décimal qui sera ensuite tronqué. La vraie question est plutôt pourquoi tronquer plutôt qu'arrondir :)

2025-02-11 11:01 UTC, indyteo commented
@naulan-chrzaszcz tu as gagné le droit de rebase et tu pourras simplifier quelques morceaux de ton code grâce aux nouveautés (notamment sur le `ModelRenderer` par exemple)

2025-02-11 16:40 UTC, pyrollo requested changes
Pas encore vu les tests :'(

2025-02-11 16:40 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +**Model requirements**:
```suggestion
#### Required model metadata
```

2025-02-11 16:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        }
Il faut trouver une solution basée sur la PR Model Selection pour ne pas avoir à mettre ce code ici (il faudrait peut être une classe de Modèles ShapeVoxelizable2d ?)

2025-02-12 00:29 UTC, indyteo commented on examples/default.yaml
>        - source:bati
Ici c'est pas faux mais ces deux dépendences sont nécessairement couvertes par `renderer:building-leveling` (pour faire le nivellement des bâtiments, il faut connaître le sol et les bâtiments... oui)

Au passage comme remarque générale : Je suis d'avis à mettre les dépendences `sources:*` et ensuite les `renderer:*` dans l'ordre le plus logique possible pour faciliter la lecture.

(Même remarque sur `examples/minecraft.yaml`)

2025-02-12 00:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        }
Si seulement c'était déjà codé mais que @naulan-chrzaszcz ne s'en était pas rendu compte... Imagine ! :)

Concrètement, quand tu as rebase, tu n'as pas trouvé quelque chose d'un peu bizarre vis à vis de la classe `ModelRenderer` et la façon dont tu l'as utilisé ici Naulan ? (Indice en lignes 19 et 56)

PS : Surtout que tu l'as fait pour le `LevelingRenderer` en plus :eyes:

2025-02-12 00:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +            return;
![john-cena-are-you-sure-about-that-meme-s9f6qr014547prub](https://github.com/user-attachments/assets/341328b0-5223-4fe5-b995-2ad022737990)

2025-02-12 00:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +            return;
Blague à part : Certes, si l'utilisateur a fait une config qui ne respecte pas les contraintes évoquées dans la doc, ça peut se produire. Cependant, dans ce cas, une erreur se produira, et ça me paraît tout à fait acceptable ("l'utilisateur demande une erreur, je fais une erreur")

Pour moi tout ceci se résume simplement à `int height = model.getMetadata("height");`

Au passage, la même remarque s'applique sur la ligne du dessous, qui n'a pas lieu d'être (c'est dans la config via les `ModelSelection` qu'on décide si ce modèle doit être rendu ou non, et pas ici). Le renderer doit render ce qu'on lui demande de render, et si il n'y arrive pas, boum peut-être erreur ("undefined behavior").

2025-02-12 08:36 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        }
Si je comprend bien la remarque, tu souhaite que je fasse pareil que le `LevelingRenderer` pour eviter l'instanceof dans la fonction `render`, le problème :

Je n'ai pas les métadonnées du modèle dans l'objet `ShapesVoxelizable2d`.
Le `LevelingRenderer` n'a pas besoin des métadonnées du modèle, donc j'ai pu le rebaser proprement.

Sauf erreur de ma part, il n'y a pas actuellement d'objet qui puisse gérer ce cas de figure (discuté avec @pyrollo). Je dois donc trouver une solution pour éviter de réécrire ce code déjà présent dans `ModelRenderer`.

2025-02-12 09:00 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        }
Il nous faut une interface qui fasse ShapesVoxelizable2d + Métadata (Model).
Cela peut être : 
- une sous classe de `Model`
- l'interface `ShapesVoxelizable2d` qui étendrait une interface gérant les Metadata
- une interface spécifique qui étendrait `ShapesVoxelizable2d` et une interface gérant les Metadata
- Faire de `ShapesVoxelizable2d` une sous classe de `Model` ? (on ne devrait pas avoir de Voxelizables non Models je pense)
- autre chose ?

2025-02-12 09:30 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +            return;
Pour ma part toutes les options se valent.
Je lis la proposition de Naulan comme: si je ne trouve pas de hauteur, c'est un batiment sans hauteur (donc 0) donc je rend ainsi (donc ça ne fait pas de rendu).
La tienne se vaut aussi : je ne sais pas quoi faire avec ce que tu me donnes donc je rale et j'arrête.
Il y a une troisième possibilité : je fais comme Naulan mais je rale.
C'est une question de choix et quelque soit le choix, ça doit être documenté.

2025-02-12 09:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        }
Ah oui notre hiérarchie de modèle n'est... Pas hiérarchique :thinking: 

Il existe une manière en Java de demander un type d'objet possédant plusieurs interfaces sans que cette interface commune n'existe, mais dans notre cas on a besoin de passer un type concrèt au super-constructeur ligne 56 donc malheureusement ça ne suffit pas.
Pour info, c'est comme ça que ça s'écrit (exemple simplifié avec une fonction) :
```java
public <T extends Model & ShapesVoxelizable2d> void doSomething(T model) { /* ... */ }
```

Bon après ici effectivement la solution n'est pas difficile, il suffit de transformer `Model` en interface (avec juste les signatures) et d'en faire une implémentation basique (`SimpleModel`, `ModelImpl`...) et faire `interface Voxelizable2/3d extends Model` (c'est l'équivalent de ta proposition 2 en disant que "une interface gérant les metadata" c'est un `Model`, et en plus ça découple l'implémentation par défaut qui stocke les metadata dans une `Map` et on pourrait imaginer d'autres implémentations spécifiques qui les calculent à la volée / les stockent autrement (j'ai déjà des avantages qui me viennent à l'esprit (il faut que j'arrête les parenthèses imbriquées (vraiment))))

2025-02-12 10:02 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +            return;
L'avantage que je vois au choix 2 c'est qu'il est dans la philosophie du reste du générateur : On fait précisément et simplement ce que l'utilisateur nous demande faire, même si ça n'a aucun sens, dans quel cas 2 choses peuvent se produire :
1. Sérendipité : le code était capable de le faire, et ça nous a permis de découvrir quelque chose d'intéressant
2. Erreur : le code n'était pas capable techniquement d'exécuter la demande de l'utilisateur, une erreur se produit

Et l'éventualité 2 est tout à fait acceptable car on peut facilement documenter dans quel cas ce comportement non défini (undefined behavior) se produit, l'utilisateur a tout à fait moyen d'empêcher ce cas (depuis sa config*), et ça laisse la porte ouverte à une heureuse surprise potentielle.

*Il est peut-être nécessaire d'ajouter une classe de `ModelSelection` qui filtre selon une relation d'ordre. Pas très dur à coder et toujours utile pour la suite !

2025-02-12 10:05 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +            return;
(Et en bonus le code est beaucoup plus simple : Il n'y a qu'une ligne qui lit la valeur de la métadonnée en imposant qu'elle soit bonne)

2025-02-12 10:14 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        }
Ceci dit si on veut pas faire de hiérarchie et qu'on veut vraiment faire comme c'est actuellement, on pourrait garder la solution avec `<T extends Model & ShapesVoxelizable2d>` et modifier la classe `ModelRenderer` pour qu'elle prenne une liste de classes à vérifier à la place d'une seule, et pouvoir donner au constructeur `Model.class`, `ShapesVoxelizable2d.class`... Bon perso je vois pas trop l'intérêt parce que je suis d'accord avec ta remarque dans le point 4 comme quoi on n'aura je pense pas de `Voxelizable`-like non `Model`.
(Mais je viens d'y penser alors je le partage quand même au cas où)

2025-02-12 10:22 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/BuildingRenderer.java
> +        }
Oui, je pense qu'on peut postuler que tous nos voxelizables sont des modèles, ça simplifie. Donc on aurait les interfaces:
* `Model` (soit avec les metadata directement dedans, soit implémentant une interface metadata)
* `ShapesVoxelizable2d` extends `Model`

Et les classes:
* `ModelImpl` implements `Model`
* `JTSGeometryModel` extends `ModelImpl` implements `ShapesVoxelizable2d`, `ShapesVoxelizable3d`

2025-02-13 10:46 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/ModelImpl.java
> +    public boolean hasMetadata(String name) {
```suggestion
    @Override
    public boolean hasMetadata(String name) {
```

2025-02-13 10:46 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/ModelImpl.java
> +    public <T> T getMetadata(String name) {
```suggestion
    @Override
    public <T> T getMetadata(String name) {
```

2025-02-13 10:46 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/ModelImpl.java
> +    public void setMetadata(String name, Object value) {
```suggestion
    @Override
    public void setMetadata(String name, Object value) {
```

2025-02-13 11:02 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/ShapesVoxelizable2d.java
> +public interface ShapesVoxelizable2d extends Model, Voxelizable2d {
Ça peut de mettre sur Voxelizable2d tant qu'à faire.

2025-02-13 11:03 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/ShapesVoxelizable3d.java
> +public interface ShapesVoxelizable3d extends Model, Voxelizable3d {
Et ici sur Voxelizable3d.

2025-02-13 11:06 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/ParamsTester.java
> +     * Deserializes parameters with "Testing" mapper.
```suggestion
     * Deserializes parameters with "Testing" output format and given mapper.
```

2025-02-13 11:31 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
>   * This {@code class} is intended to evolve. Models are objects that can be
It evolved!

Et en plus ce n'est plus une classe. Je pense qu'on peut retirer cette phrase et juste dire "Models are objects that can be rendered. They optionally can have some metadata attached to them."

2025-02-13 11:31 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> -    public abstract String salt();
Pourquoi ne pas avoir laissé le sel dans l'interface ?

2025-02-13 11:31 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/ShapesVoxelizable2d.java
>   * An object (likely a model) voxelizable by {@code ShapesVoxelizer2d}.
It's more than likely, it is certain :smile: 
```suggestion
 * An object voxelizable by {@code ShapesVoxelizer2d}.
```
Même remarque en 3d

2025-02-13 16:23 UTC, naulan-chrzaszcz commented
Aucune idée si je le fait dans cette PR ou pas mais ce commit : https://github.com/ignfab/minalac-generator/pull/24/commits/aea394d4f320696fbc35af6676f5b254a0834a4d

...permet de rendre les rendereurs completement bête, et c'est a nous grace au `ModelFilter`, de lui passer les bon models.

2025-02-13 20:21 UTC, indyteo commented
Je suis personnellement pour le concept, mais la réalisation me semble bien plus compliqué que nécessaire. En fait, il n'y avait besoin que d'un seul ajout pour couvrir toutes les situations : `<` (`ModelFilterMetadataLowerThan`) avec un code très simple (`metadata` pour le nom de la métadonnée et `value` pour la valeur avec laquelle comparer, et éventuellement `as` pour préciser le type de ce qu'on veut comparer, mais on peut ne gérer que les nombres pour l'instant)

En combinant avec les autres filtres que nous avions déjà, nous pouvions faire `==` (déjà possible), `<` (nouveau filtre), `<=` (`< or ==`), `>` (`not <=`) et `>=` (`not <`). C'est un peu le même principe qu'en C++ où pour définir tous ces opérateurs, on ne défini généralement que `==` et `<` et tous les autres sont construits automatiquement (bon, maintenant il y a le "spaceship operator" `<=>`, mais l'idée est là).

Par contre, il est lourd / pas forcément naturel pour l'utilisateur d'écrire :
```yml
filter:
  not:
    metadata: height
    lowerThan: 0
```
Donc on peut définir des classes de params qui couvrent les différents cas. Ceci dit, ça mériterait d'avoir une vraie syntaxe étendue de filtrage, pour pouvoir écrire quelque chose du style `classification in ["toto", "tata", "titi"] && height > 0`, mais ça demandera bien plus d'effort, et il faut évaluer si ça en vaudra la peine ou non

2025-02-14 10:03 UTC, naulan-chrzaszcz commented
> Je suis personnellement pour le concept, mais la réalisation me semble bien plus compliqué que nécessaire.

Je suis d'accord, je suis allé trop loin. Je n'ai pas correctement pris en compte ce qu'il y avait autour...

> Par contre, il est lourd / pas forcément naturel pour l'utilisateur d'écrire :
> 
> ```yaml
> filter:
>   not:
>     metadata: height
>     lowerThan: 0
> ```
> 
> Donc on peut définir des classes de params qui couvrent les différents cas. Ceci dit, ça mériterait d'avoir une vraie syntaxe étendue de filtrage, pour pouvoir écrire quelque chose du style `classification in ["toto", "tata", "titi"] && height > 0`, mais ça demandera bien plus d'effort, et il faut évaluer si ça en vaudra la peine ou non

Pour le moment, je l'ai fait de la manière la plus simple possible, ce filtre (grâce à ton exemple). À voir si ça convient pour le moment, même si ce n'est pas forcément naturel.

2025-02-14 11:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterMetadataLowerThanParams.java
> +    // On pourra pas comparer des String plus bas que d'autre String
Si, on *peut* : `String#compareTo(String)`. La question est plutôt : Est-ce qu'on *veut* ?

Pour l'instant si tu veux rester simple tu peux ne gérer que les nombres (et ne pas mettre de `ValueParser`), mais à terme on pourra gérer n'importe quel `Comparable` si on veut

2025-02-14 11:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterMetadataLowerThan.java
> +        return ((Number) parser.parse(model.getMetadata(metadata))).doubleValue() < ((Number) parser.parse(lowerThan)).doubleValue();
En ne gérant que les nombres, tu peux simplifier ça comme ça :
```suggestion
        return ((Number) model.getMetadata(metadata)).doubleValue() < lowerThan;
```
En prenant directement `lowerThan` comme un `double`, et ça ne fonctionnerait que si la métadonnée est un nombre (comportement à documenter)

Je pense que dans un premier temps, ça permet d'avoir une version simple

2025-02-14 11:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
>   * This {@code class} is intended to evolve. Models are objects that can be
Tu as resolve mais tu n'as pas mis à jour la javadoc

2025-02-14 11:57 UTC, indyteo commented on examples/default.yaml
> +      - renderer:building-leveling
Ici mon idée était de dire qu'il n'y a qu'une seule dépendence qui est nécessaire : `renderer:building-leveling`
Les autres étant déjà des dépendences transitives

2025-02-14 11:57 UTC, indyteo commented on examples/default.yaml
> +          lowerThan: 0
Attention, que renvoie ton filtre dans le cas où la métadonnée est absente ? Ce qui est impossible avec les post-processeurs actuels, je te l'accorde, mais dans le principe, on pourrait imaginer que `height < 0` soit toujours faux si `height` est absent par exemple, donc avec ta négatif, le filtre deviendrait toujorus vrai ! Bon, ici je pense surtout qu'il y aurait une erreur (`NullPointerException`) si la métadonnée était absente, mais ça ne se produit jamais avec la config actuelle

2025-02-14 11:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/ShapesVoxelizable2d.java
> - * An object (likely a model) voxelizable by {@code ShapesVoxelizer2d}.
Je pense que la même modif est nécessaire sur la version 3d

2025-02-14 13:46 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> -    public abstract String salt();
Aucune idée, je viens de le déplacer

2025-02-14 14:30 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +- `height`: Height of building to render (no rendering if negative or zero)
```suggestion
- `height`: Height of building to render (must be a positive integer)
```

2025-02-14 14:30 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +Building height is given by `height` metadata (if negative or zero, no building is rendered).
```suggestion
Building height is given by `height` metadata (the behavior of this renderer is undefined if value is missing, negative or zero).
```

2025-02-14 14:30 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterMetadataLowerThan.java
> +    private final Double lowerThan;
```suggestion
    private final double lowerThan;
```
(À propager partout, tu n'as pas besoin d'un objet ici, le type primitif suffit)

2025-02-14 14:30 UTC, indyteo commented on examples/default.yaml
> +          lowerThan: 0
D'ailleurs, je viens de tilter mais est-ce qu'on veut que les modèles `height == 0` soient inclus ou pas ?
```suggestion
        not:
          or:
            - metadata: height
              lowerThan: 0
            - metadata: height
              equals: 0
```

2025-02-17 12:59 UTC, naulan-chrzaszcz commented on examples/default.yaml
> +          lowerThan: 0
C'est une bonne question, je ne sais pas ce que pourrait vouloir dire un bâtiment sans hauteur.

2025-02-17 13:43 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +Returns true if the given metadata value is strictly less than the specified threshold.
Il y avait une erreur dans la doc des autres filtres, ça aurait dû être:
```suggestion
Selects model with given metadata value is strictly less than the specified threshold.
```

2025-02-17 13:44 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/ShapesVoxelizable2d.java
> + * An object voxelizable by {@code ShapesVoxelizer2d}.
```suggestion
 * A model voxelizable by {@code ShapesVoxelizer2d}.
```

2025-02-17 13:44 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/ShapesVoxelizable3d.java
> + * An object voxelizable by {@code ShapesVoxelizer3d}.
```suggestion
 * A model voxelizable by {@code ShapesVoxelizer3d}.
```

2025-02-17 13:45 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/Voxelizable2d.java
>   * This interface usually applies to models.
```suggestion
 * Represents a model that can be transformed into 2d voxels using a voxelizer.
```

2025-02-17 13:46 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/Voxelizable2d.java
>       * Provides a voxelizer that returns voxels representing this object in 2d.
```suggestion
     * Provides a voxelizer that returns voxels representing this model in 2d.
```

2025-02-17 13:46 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/Voxelizable3d.java
>   * Most objects representable in 3d can also be represented in 2d, but this is not always the case!
```suggestion
 * Most models representable in 3d can also be represented in 2d, but this is not always the case!
```
+ changer object en model au dessus.

2025-02-17 13:47 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/Voxelizable3d.java
>       * Provides a voxelizer that returns voxels representing this object in 3d.
```suggestion
     * Provides a voxelizer that returns voxels representing this model in 3d.
```

2025-02-17 13:49 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterMetadataLowerThan.java
> +public class ModelFilterMetadataLowerThan implements Predicate<Model> {
On va gader comme ça mais en faisant un "ModelFilterMetadataCompare" avec un parametre lower/greater, tu faisais deux filtres pour le prix d'un.
Voire en faisant un truc encore plus générique (qui prend une closure) tu pouvais déléguer au paramètres le soin de filer la bonne opération.

2025-02-17 14:02 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterMetadataLowerThan.java
> +        return ((Number) model.getMetadata(metadata)).doubleValue() < lowerThan;
Comment ça se passe si la metadata est null ou absente ? Si elle n'est pas casteable en number ?

2025-02-17 14:04 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/filters/ModelFilterMetadataLowerThanTest.java
> +public class ModelFilterMetadataLowerThanTest {
Il faudrait tester avec metadata absente, et avec metadata d'un autre type.

2025-02-17 16:07 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +Returns true if the given metadata value is strictly less than the specified threshold.
J'ai écrit ma documentation comme ca car, je voulais respecter le format d’écriture des autres filtres.

2025-02-17 16:09 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterMetadataLowerThan.java
> +        return ((Number) model.getMetadata(metadata)).doubleValue() < lowerThan;
J'ai ajouté des conditions dans la fonction qui permet de ne pas avoir d'exceptions dans c'est cas là.

2025-02-18 08:13 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +Returns true if the given metadata value is strictly less than the specified threshold.
Mets tout de même select car "return true" est une erreur. Comme ça, quand on harmonisera, on saura qu'il faut changer ça.

2025-02-18 09:39 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterMetadataLowerThan.java
> +        return (obj == null || !(obj instanceof Number number)) ? false : number.doubleValue() < lowerThan;
Un peu plus lisible :
```suggestion
        return obj instanceof Number number && number.doubleValue() < lowerThan;
```
(`instanceof` => `!null` : https://stackoverflow.com/questions/2950319/is-null-check-needed-before-calling-instanceof)

2025-02-18 09:59 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +    public static final ValueParser<Integer> INTEGER = new ValueParser<>(Integer.class, obj -> (int) Double.valueOf(obj.toString()).doubleValue());
Je pense que vous ne serez pas d'accord avec moi sur cette modification, @indyteo et @pyrollo.

2025-02-18 10:00 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +    public static final ValueParser<Integer> INTEGER = new ValueParser<>(Integer.class, obj -> (int) Double.valueOf(obj.toString()).doubleValue());
https://stackoverflow.com/questions/9102318/cast-double-to-integer

2025-02-18 10:08 UTC, indyteo commented on examples/default.yaml
> +            equals: 0
`(!(h < 0)) <=> (h >= 0)` donc `(!(h < 0) || h == 0) <=> (h >= 0 || h == 0)`. Est-ce que tu es sûr que c'est ce que tu veux ?

Déjà, `(h >= 0) <=> (h > 0 || h == 0)`, donc tu as littéralement écrit `h > 0 || h == 0 || h == 0`, et ensuite, un bâtiment de hauteur 0, est-ce qu'on a un rendu pertinent à faire ? Je ne pense pas que ça soit le cas. Tu veux donc écrire `(h > 0) <=> (!(h <= 0)) <=> (!(h < 0 || h == 0))`, ce qui n'est pas loin de ce que tu as écris, mais il faut échanger ton `or` et ton `not`

N'oublie pas de mettre à jour `minecraft.yaml` aussi

2025-02-18 10:08 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +    public static final ValueParser<Integer> INTEGER = new ValueParser<>(Integer.class, obj -> (int) Double.valueOf(obj.toString()).doubleValue());
```suggestion
    public static final ValueParser<Integer> INTEGER = new ValueParser<>(Integer.class, obj -> Double.valueOf(obj.toString()).intValue());
```

2025-02-18 10:08 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +    public static final ValueParser<Integer> INTEGER = new ValueParser<>(Integer.class, obj -> (int) Double.valueOf(obj.toString()).doubleValue());
Pourquoi cette modification ?
Le parser n'arrive pas à convertir la chaîne de caractères "21.5" en Integer.

2025-02-18 10:12 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +    public static final ValueParser<Integer> INTEGER = new ValueParser<>(Integer.class, obj -> (int) Double.valueOf(obj.toString()).doubleValue());
En théorie, il serait probablement plus propre d'expliciter l'arrondi (éventuellement par le biais d'un post-processeur qui fasse l'arrondi, et ainsi faire "parse as double then round to int"), mais en pratique ça fait l'affaire pour l'instant, à moins que tu aimes cette PR au point de continuer à vouloir la faire vivre, mais à part ma micro simplification à ce sujet que je t'ai mis plus bas, ça me paraît acceptable pour l'instant

2025-02-18 10:13 UTC, naulan-chrzaszcz commented on examples/default.yaml
> +            equals: 0
Je ne pensais pas que la négation de `<` était `>=` (je pensais juste que c'était `>` 😅)

2025-02-18 12:07 UTC, naulan-chrzaszcz commented
Pour les suggestions de modifications à faire plus tard, j'ai mis des TODO un peu partout.
Je ne sais pas si c'est bon comme ça ou non ?

2025-02-18 12:20 UTC, indyteo submitted a review, later dismissed

2025-02-18 13:16 UTC, indyteo commented
D'ailleurs remarque générale si tu veux faire un peu plus propre, tu pourrais refaire tes commits pour isoler :
- Le refactor de `Model`
- L'ajout du filtre `metadata < value`
- Tes deux commits actuels

2025-02-18 17:14 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +    public static final ValueParser<Integer> INTEGER = new ValueParser<>(Integer.class, obj -> Double.valueOf(obj.toString()).intValue());
Heu, on veut vraiment changer le comportement du parser ?
Genre pouvoir faire:
```yaml
value: 3.8
as: intgerer
```
Quel est le lien avec la PR ?

2025-02-18 17:21 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +    public static final ValueParser<Integer> INTEGER = new ValueParser<>(Integer.class, obj -> Double.valueOf(obj.toString()).intValue());
J'ai changé le comportement car ça me crée des problèmes lors du parse des valeurs des metadonnee.
Est-ce que ça vaut le coup maintenant de faire le post processeur qui fait les arrondis dans cette PR ? (Pour évité ce changement)

2025-02-19 10:10 UTC, indyteo approved these changes

2025-02-19 15:15 UTC, pyrollo approved these changes

2025-02-19 15:20 UTC, naulan-chrzaszcz commented
Il y a tellement de message que je ne vois pas quel message n'est pas resolve

2025-02-19 15:34 UTC, merged