feat(parser): Add parameters for HeightMaps
ignfab/voxatile pull request #28
Opened 2024-07-29 13:26 UTC by zhak5388

### Type of modification

Types:
- Code
  - Inputs
- Documentation
  - Javadoc Comments
- Other
  - Example file

### Changes

Add support for deserializing the `heightMaps` parameter and instantiation of all `HeightMap` in `Generation`.

[Jira ticket](https://ignfab.atlassian.net/browse/MINALAC-57?atlOrigin=eyJpIjoiNTY4ZGMxMjcwZDI2NDBmNGEyMWIyMzM5OTA5YmViNzMiLCJwIjoiaiJ9)

#### Feature description
The `heightMaps` parameter is an optional list, where each element will be instantiated into a `HeightMap` with the specified `default` value. All of the instantiated `HeightMap` are stored in a `HashMap` of `Generation` where the `name` of each `HeightMap` is the key.

The fields `name` and `default` are mandatory for each element. The `name` must be unique and `default` must be a string integer, "min" or "max" (For now the parser transforms "min"/"max" value into `Integer.MIN_VALUE`/`Integer.MAX_VALUE`)

```yaml
heightMaps:
  - name: altitude
    default: min
  - name: ground
    default: 0
```

#### Technical changes
This PR consists mainly of modifying the classes `ParamsParser`, `RawParams` and `Generation` by adding new structures/functions.

#### Showcase
The command used remains the same : 
```bash
mvn -DskipTests=true clean package && java -jar target/Generator.jar -p examples/default.yaml $HOME/.minetest/worlds/minalac
```

Or, by passing arguments in JSON via the environment : 
```bash
mvn -DskipTests=true clean package && MINALAC_PARAMS='{"heightMaps":[{"name":"ground","default":0}],"verticalScale":1,"horizontalScale":1,"area":{"center":{"latitude":48.845,"longitude":2.425},"extendX":1000,"extendY":1000},"crs":"EPSG:2154","format":"minetest"}' java -jar target/Generator.jar $HOME/.minetest/worlds/minalac
```

### Reason

This part will be needed when adding `Renderer` declaration into the configuration file.

### Self-checks

- [x] The code has unit tests associated
- [x] The code has Javadoc Comments associated
- [x] Complex / Unexpected code is explained / justified with a small comment
- [x] Relevant documentation inside the `/docs` folder has been updated
- [x] All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)
- [x] Git history is clean (each commit accomplish a single task and describe it accordingly)
- [x] The texts have been proofread (documentation, error messages, logs, comments...)

2024-07-29 14:57 UTC, naulan-chrzaszcz requested changes

2024-07-29 14:57 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +      default: 0
```suggestion
  - name: ground
    default: 0
```

2024-07-29 14:57 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        return heightMaps.get(name);
```suggestion
        return heightMaps.getOrDefault(name, throw new NoSuchElementException("This heightMap does not exist : " + name));
```
Aucune idée si cela fonctionne.

2024-07-29 14:57 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        if (heightMaps.containsKey(name) || name == null)
```suggestion
        if (name == null || heightMaps.containsKey(name))
```
Plus facile de commencer par la condition == null que l'appel de fonction

2024-07-29 14:57 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
> +                case "min" -> Integer.MIN_VALUE;
Ca valide aussi le cas où c'est ecrit `minimal` ?

2024-07-29 14:57 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
> +                case "max" -> Integer.MAX_VALUE;
Pareil, quand c'est ecrit `maximal` ?

2024-07-29 14:57 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
> +                        yield Integer.parseInt(defaultValue);
C'est quoi `yield` ?

2024-07-29 15:00 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
> +                case "min" -> Integer.MIN_VALUE;
Non, c'est uniquement "min", "max" ou bien un int. Pourquoi ?

2024-07-29 15:01 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        if (heightMaps.containsKey(name) || name == null)
Yes : )

2024-07-29 15:02 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parsing/RawParamsTest.java
> +            """
Cette ligne est mal indenté par rapport aux autres lignes ?

2024-07-29 15:03 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
> +                case "min" -> Integer.MIN_VALUE;
Sur le ticket Jira, c'est écrit `minimal`

2024-07-29 15:07 UTC, naulan-chrzaszcz requested changes

2024-07-29 15:07 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parsing/ParamsParser.java
>              convertedCoords[0],
```suggestion
        Generation generation = new Generation(
            targetCrs,
            convertedCoords[0],
```

2024-07-29 15:10 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
> +                        yield Integer.parseInt(defaultValue);
C'est pour dire que la valeur du switch est `Integer.parseInt(defaultValue)` (Comme je fait un return de quelque chose qui doit avoir une valeur) et ça quitte le switch

2024-07-29 15:11 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        return heightMaps.get(name);
J'arrive pas à comprendre.. Le deuxième parametre dans `heightMaps.getOrDefault` c'est pas censé être une `HeightMap`?

2024-07-29 15:12 UTC, naulan-chrzaszcz requested changes
Ma dernière passe

2024-07-29 15:12 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parsing/ParamsParser.java
> +                generation.addHeightMap(heightMapParams.name, new HeightMap(generation.getWorldBBox2d(), heightMapParams.defaultValue));
```suggestion
            for (final RawParams.HeightMapParams heightMapParams : rawParams.heightMaps)
                generation.addHeightMap(heightMapParams.name, new HeightMap(generation.getWorldBBox2d(), heightMapParams.defaultValue));
```

2024-07-29 15:16 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        return heightMaps.get(name);
`getOrDefault(Object key, V defaultValue)`

Ouais, normalement... Mais, je me suis demandé si on pouvais pas simplifier le truc sur une ligne.
P'têt qu'on perd on visibilité si on simplifie ?

2024-07-29 15:18 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parsing/RawParamsTest.java
> +            """
Ah non, pas au bon endroit ~~J'ai corrigé normalement!~~

2024-07-29 15:24 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parsing/RawParamsTest.java
> +            """
C'est pas censé être une indentation de 4 pour la ligne14?

2024-07-29 15:26 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
> +                case "min" -> Integer.MIN_VALUE;
Ah oui, effectivement.. Je serai partant pour les appeler `min` et `max` plutôt, mais je peux faire la modification pour `minimal` et `maximal`

2024-07-29 15:27 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        return heightMaps.get(name);
Mais `NoSuchElementException`, c'est pas une `HeighMap`? (Ou bien j'ai raté quelque chose?)

2024-07-29 15:28 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parsing/ParamsParser.java
> +                generation.addHeightMap(heightMapParams.name, new HeightMap(generation.getWorldBBox2d(), heightMapParams.defaultValue));
Qu'est ce que ça permet de faire?

2024-07-29 15:58 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parsing/ParamsParser.java
> +                generation.addHeightMap(heightMapParams.name, new HeightMap(generation.getWorldBBox2d(), heightMapParams.defaultValue));
De dire que `heightMapParams` est en read-only

2024-07-29 15:59 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parsing/ParamsParser.java
> +                generation.addHeightMap(heightMapParams.name, new HeightMap(generation.getWorldBBox2d(), heightMapParams.defaultValue));
Tu ne le modifie la variable `heightMapParams` dans la boucle `for`

2024-07-29 16:04 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
> +                case "min" -> Integer.MIN_VALUE;
Le truc c'est... Qu'il y a pas @pyrollo pour trancher 💀 
Moi, j'aurais suivi les instructions du ticket, mais apres, `min` et `max` est pas mal non plus. (Ca reste standard je suppose)

2024-07-29 16:06 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parsing/RawParamsTest.java
> +            """
La ligne est mal choisi mb
C'était les lignes en dessous que ta corrigé

2024-07-30 00:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        return heightMaps.get(name);
La syntaxe que tu cherches à faire n'existe pas, en revanche "l'optimisation" possible (je met des guillemets parce que c'est minime) c'est de faire le `.get(key)` puis tester si le résultat est `null`, ensuite `throw` (ce qui évite de parcourir une première fois la `Map` pour savoir si la clé existe, puis ensuite récupérer la valeur associée (même si ces opérations sont très rapides, et cette optimisation n'aurait de sens que si la `Map` contenait des millions voire des milliards d'entrées)

2024-07-30 00:23 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
> +                case "min" -> Integer.MIN_VALUE;
Je suis d'avis que `min` et `max` sont bien, ceci dit ça ne coûte rien d'y ajouter la forme complète (`case "min", "minimal" -> ...`)

2024-07-30 00:36 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parsing/ParamsParser.java
> +                generation.addHeightMap(heightMapParams.name, new HeightMap(generation.getWorldBBox2d(), heightMapParams.defaultValue));
Ce genre de chose est utilisé (quasi-)exclusivement par le compilateur (qui va potentiellement pouvoir faire une micro-optimisation), mais ça allourdi beaucoup le code pour rien (donc on évite)

Surtout que ça donne l'impression que la variable représente un objet immutable, alors qu'il ne s'agit que de l'assignation (on ne peut pas réassigner la variable, c'est à dire `heightMapParams = ...`)

En principe on n'a très peu de raison de le mettre, on le fait soit quand on a vraiment besoin d'optimisation critique (c'est le cas dans la lib standard vu que c'est la lib standard), ou qu'on veut garantir que la variable n'est pas réassignée par erreur, ce qui a de très très faible chance d'arriver (et il faudrait le mettre partout du coup si on voulait vraiment se protéger contre cette erreur)

2024-07-30 01:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +    private HashMap<String, HeightMap> heightMaps;
```suggestion
    private final Map<String, HeightMap> heightMaps = new HashMap<>();
```

2024-07-30 01:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        heightMaps = new HashMap<>();
Supprimer (initialisation en ligne bien plus lisible)

2024-07-30 01:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +     * Adds a new {@link HeightMap} to the HashMap of heightmaps.
L'utilisateur n'en a que faire de savoir qu'il s'agit d'une `HashMap` en interne qui stocke ça. En plus, ça pourrait changer dans le futur (pourquoi pas ?) donc il ne faut pas en parler dans la doc. La phrase pourrait juste être quelque chose dans le genre :
> Adds a new heightmap to the registered heightmaps.

ou encore plus simplement :
> Registers a new heightmap with the given name.

2024-07-30 01:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +     * Note that this method does not check for ambiguous names such as names that differ only by case.
Plus explicite : Tu peux dire "Name must be unique, case-sensitive"

2024-07-30 01:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +     * Returns the {@link HeightMap} to which the specified name is associated.
```suggestion
     * Returns the {@link HeightMap} associated to the given name.
```

2024-07-30 01:00 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parsing/RawParamsTest.java
C'est moi ou tu test Jackson ?

2024-07-30 09:42 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        return heightMaps.get(name);
Ok, bien noté merci!

2024-07-30 09:42 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
> +                case "min" -> Integer.MIN_VALUE;
Oui, c'est vrai haha
J'ai pris la suggestion de Théo, j'ai fait des modifications pour que ça soit à la fois `min` et `minimal` (Naulan je te laisse le dernier mot, si tu penses que c'est mieux que ça reconnaisse juste `minimal` et `maximal`, tu me dis et je revert les modifs :))

2024-07-30 09:44 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +     * Adds a new {@link HeightMap} to the HashMap of heightmaps.
Oui, c'est vrai, je prends ta deuxième suggestion!

2024-07-30 09:45 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parsing/RawParamsTest.java
Je voulais tester la méthode privée `parseDefaultValue()` appelée dans le constructeur et m'assurer en quelque sorte qu'elle in'nterfere pas avec le processus de deserialisation.
C'est vrai que ça donne l'impression que je teste la librairie.. J'ai tout regroupé dans une seule méthode `testHeightMapParamsDefaultValueDeserialization()`, viré les asserts sur le champ `name` et ajouté un commentaire pour préciser; je pense que ça devrait être plus clair

2024-07-30 18:54 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parsing/RawParams.java
> +                case "min" -> Integer.MIN_VALUE;
C'est good 👍🏻

2024-07-30 18:58 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        return heightMaps.get(name);
C'est pas modifié selon la suggestion de @indyteo, du coup ?

2024-07-31 10:01 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        return heightMaps.get(name);
J'avais pas fait la modification parce que de ce que j'ai compris l'optimisation est minime. (En regardant rapidement `HashMap`, `containsKey()` vérifie si `getNode() != null` et `get()` fait cette même vérification avant de renvoyer la valeur associée) Du coup ça évite un parcours de `heightMaps` supplémentaire (mais je ne pense pas que `heightMaps` est amené à avoir beaucoup d'entrées ou être parcouru plusieurs fois)
Ceci dit, j'ai fait une modif, dis moi ce que tu en penses : )

2024-08-05 09:36 UTC, naulan-chrzaszcz approved these changes
LGTM 🚀

2024-08-05 10:15 UTC, merged