Mettre des metadonnées dans `Model`
ignfab/voxatile pull request #29
Opened 2024-07-31 14:10 UTC by naulan-chrzaszcz

### Type of modification

Types:
- Code
  - General
  - Inputs
- Tests
### Issue
MINALAC-55

### Changes

- `Model` become a `class`
- `Model` store additional data (metadata)
- Heights of building getted and stored in models

#### Feature description
- Add `metadata` variable in `Model` with getter and setter functions
- Add informations about the height of building in the model

### TODOs
- JUnit if needed and possible
- Manage several building heights 

### Self-checks

- [ ] The code has unit tests associated
- [x] The code has Javadoc Comments associated
~~Complex / Unexpected code is explained / justified with a small comment~~
~~Relevant documentation inside the `/docs` folder has been updated~~
- [ ] All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)
- [x] Git history is clean (each commit accomplish a single task and describe it accordingly)
- [ ] The texts have been proofread (documentation, error messages, logs, comments...)

2024-07-31 15:05 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                int finalHeight = 20; // 20 = default value
Juste une remarque avant que j'oublie, mais je pense que c'est le renderer de bâtiment qui aura une hauteur par défaut (Si la metadata n'existe pas ou invalide, ça rend avec la hauteur par défaut) mais je suis pas sur à 100%

2024-08-01 13:56 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                int finalHeight = 20; // 20 = default value
Donc, tu pense que je met `null` dans les meta-data (voir du coup, je n'appelle pas la fonction `.put`) et le renderer est en charge de mettre la hauteur par défaut ?

2024-08-01 14:51 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                int finalHeight = 20; // 20 = default value
Oui, je me dis que ça permet une souplesse au `BuildingRenderer`, ça permettrait de facilement distinguer le cas ou la metadonnée est absente. Mais, encore une fois, je ne suis pas sur de moi.
Le préprocesseur il aurait pour rôle "d'harmoniser" les métadonnées (Je dis peut-être une betise, mais si on a une propriété "height" et "hauteur", elle serait en charge de faire en sorte que ça soit par exemple le même nom de clé)
De toute façon, comme c'est dans la classe `SampleImplementation`, c'est un peu le brouillon, donc c'est pas un soucis de mettre la hauteur par défaut là dans tous les cas. (Je faisais surtout la remarque parce que je pense que c'est toi qui fait les `BuildingRenderer` ?)

2024-08-01 14:53 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                int finalHeight = 20; // 20 = default value
En relisant le jira là, j'arrive pas à savoir si le `BuildingRenderer` fait l'objet de ta PR, on dirait que non, n'est ce pas? Et, autant pour moi, on dirait bien que c'est en initialisant le `Model` que l'on passe la hauteur par défaut

2024-08-01 14:57 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                int finalHeight = 20; // 20 = default value
C'est en lien avec le BuildingRenderer

2024-08-01 14:57 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                int finalHeight = 20; // 20 = default value
> En relisant le jira là, j'arrive pas à savoir si le `BuildingRenderer` fait l'objet de ta PR, on dirait que non, n'est ce pas? Et, autant pour moi, on dirait bien que c'est en initialisant le `Model` que l'on passe la hauteur par défaut

Okay

2024-08-02 08:00 UTC, zhak5388 requested changes
Quelques commentaires : )

**Edit**: Je supprime mon premier commentaire vu que c'est quasiment les mêmes infos que dans le jira

2024-08-02 08:00 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                }
Question bête mais il peut y avoir plusieurs hauteur par feature?

2024-08-02 08:00 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +     * Store additional data about the model.
J'aurais mis `Additional data about the model.` (J'ai l'impression que les verbes sont plus pour les méthodes par convention)

2024-08-02 08:00 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +        metadata.put(key, value);
Du coup, ça remplace la valeur si la clé existe déjà? Si c'est le cas, ça vaut le coup d'ajouter dans la javadoc, quelque chose comme: `The old value is replaced if the key already exists`

2024-08-02 08:00 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public String getMetadata(String key) {
J'aurais mis un truc comme : 
```
Returns the metadata value associated with the specified key.

@param key the metadata key
@return the associated metadata value if the specified key exists or {@code null} otherwise
```

Je pinaille un peu mais techniquement ça peut renvoyer `null` avec une clé existante (Genre `setMetadata("tata", null)`) Bon c'est peut-être du détail

2024-08-02 08:00 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +     * @param key   Name of the metadata
Ca me parait bien de dire que la clé c'est le nom de la metadata. C'est juste une reflexion, je me demande si ça vaut pas le coup de changer la signature de la fonction en `setMetadata(String name, String value)`, je trouve que ça serait plus clair que metadata key.

Sinon j'aurais mis : `Sets a metadata by providing the key and the value.`

2024-08-02 08:26 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                }
Dans mes souvenir, d'apres Pierre, il a dit qu'on peux avoir plusieurs hauteurs.

2024-08-09 16:15 UTC, naulan-chrzaszcz commented
Alors, j'ai tenté de faire un truc @zhak5388 
Regarde le `Model` quand t'aura le temps et dis-moi ce que tu en penses ;)

Pour les tests unitaires, j'en ai aucune idée de comment tester ça...

2024-08-09 16:25 UTC, naulan-chrzaszcz commented
Si @indyteo passe part là, 🙃 
Je crois bien que j'ai fait une erreur de débutant :)

2024-08-09 16:32 UTC, naulan-chrzaszcz commented
J'ai laissé en virgule la hauteur des bâtiments (de base, je voulais l'arrondir au supérieur).
Je pense, si on veux utiliser le générateur sûr d'autres plateforme... C'est mieux de le laisser en virgule et de l'arrondir dans les rendereurs MC et MT ?
Vous en pensez quoi ?

2024-08-09 16:42 UTC, indyteo commented
C'est à dire ? Une erreur de débutant, mais encore ?

2024-08-09 16:51 UTC, naulan-chrzaszcz commented
> C'est à dire ? Une erreur de débutant, mais encore ?

😆 Oui, sur la fonction `setMetadata`
P.S: Et même sur le `setDefaultValuesMetadata`

(Je veux dire par là que, je ne sais pas si c'est une bonne pratique de faire un code ecrit comme je l'ai fait)

2024-08-09 17:49 UTC, indyteo reviewed
Je ne sais pas si ça répond à ton interrogation, mais du coup j'ai tout review

2024-08-09 17:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                GeometryModel geoModel = new GeometryModel((Geometry) splFeat.getDefaultGeometry(), converter, limits);
On paye pas au caractère, Java est un langage (semi-)compilé, donc les noms des variables peuvent être en entier, ils sont de toute façon remplacés par des "IDs" en quelque sorte. Il vaut mieux utiliser des noms complets, sauf quand les abréviations sont vraiment évidentes (genre "URL", "HTTP"...)

2024-08-09 17:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                geoModel.setMetadata("height", splFeat.getProperties("hauteur").iterator().next().getValue());
Pour l'instant c'est du brouillon, mais ça me paraît un peu étrange comme façon de procéder pour récupérer la valeur

2024-08-09 17:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> + * This interface is intended to evolve. Models are objects that can be
C'est plus une interface du coup

2024-08-09 17:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    private final HashMap<String, String> metadata;
```suggestion
    private final Map<String, Object> metadata;
```
Utiliser les interfaces au lieu des implémentation, et stocker directement les objets

2024-08-09 17:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    }
Je comprends pas ce que vient faire cette méthode ici ?

2024-08-12 12:09 UTC, zhak5388 requested changes
Quelques commentaires en plus : )
Pour les tests, j'aurais fait une classe `TestModel` avec un test des set/get en alterné (un truc comme get sur une metadata qui n'existe pas, set/get sur existante, set/get sur existante modifié, set avec `null`); ceci dit je pense pas que ça soit des test unitaires à strictement parler.
Et pour ce qui est du `setDefaultValuesMetadata()`, je pense que ça devrait se faire pour l'instant dans `SampleImplementation`, en mettant cette méthode dans `Model`, j'ai l'impression que l'on "force" tous les `Model` à avoir une metadata `hauteur`

2024-08-12 12:09 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +     * will be updated.
*Creates
Sinon en plus concis `Creates a new metadata with the given name or updates the existing one.`

2024-08-12 12:09 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public void setMetadata(String name, Object value) {
Pourquoi passer un `Object` plutôt qu'un `String`? (Sinon on pourrait passer un générique genre `T getMetadata(String key)` `void setMetadata(String key, T value)`, mais pas sur)

2024-08-12 13:17 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public void setMetadata(String name, Object value) {
Le type générique peut avoir du sens sur le `get` pour "dissimuler" le cast, mais en revanche aucun intérêt dans le `set`, il faut garder `Object`

2024-08-19 08:36 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public void setMetadata(String name, Object value) {
> Pourquoi passer un `Object` plutôt qu'un `String`? (Sinon on pourrait passer un générique genre `T getMetadata(String key)` `void setMetadata(String key, T value)`, mais pas sur)

L'ancienne signature de la fonction étais la suivante : 
```java
setMetadata(String name, String value);
```

Mais le problème, c'est que j'étais obliger de cast en `String` manuellement en dur dans le code... Pour avoir un code plus lisible j'ai décidé de mettre le type `Object` a la place (Type d'ailleurs present dans les données géographique, tout est générique) et de cast en String dans le set.

2024-08-19 08:39 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    }
Okay, j'écris tous dans le constructeur

2024-08-19 08:40 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public void setMetadata(String name, Object value) {
Mais du coup, @indyteo je cast que dans le get ?

2024-08-19 08:59 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public void setMetadata(String name, Object value) {
Pour ma part j'ai l'impression qu'un string est amplement suffisant pour les metadata. Peut être faudrait-il avoir une methode Object qui servira de temps en temps pour les cas plus complexes et une autre pour String qui servira tout le temps ?

EDIT: Vu avec @indyteo , on reste sur Object + get générique avec commentaire.

2024-08-19 08:59 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                geometryModel.setMetadata("height", simpleFeature.getProperties("hauteur").iterator().next().getValue());
Ça réagit comment s'il n'y a pas de metadata "hauteur" ?

2024-08-19 09:00 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                geometryModel.setMetadata("height", simpleFeature.getProperties("hauteur").iterator().next().getValue());
Elle est définie par défaut dans le constructeur du Model

2024-08-19 09:02 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public void setMetadata(String name, Object value) {
Deux solutions :
- Soit tu ne fais rien et tu laisses l'utilisateur se débrouiller, et tu lui renvois un `Object` (signature `public Object getMetadata(String name)`), et l'utilisateur devra faire un cast explicite (exemple si c'est un string `String value = (String) model.getMetadata("toto")`)
- Soit tu simplifies la vie de l'utilisateur, mais en lui tendant un piège par la même occasion si il ne connaît pas et que c'est pas bien documenté (mais il suffit de bien l'expliquer et c'est réglé, normalement), et tu lui renvois ce qu'il veut, c'est à dire concrètement toujours un objet, mais directement dans le type demandé. Pour ça, il faut utiliser un type "générique", c'est à dire `public <T> T getMetadata(String name)`, et l'utilisateur pourra écrire simplement `String value = model.getMetadata("toto")`. En réalité, ce qu'il se passe c'est que ta fonction renvoie toujours un objet, mais le compilateur va automatiquement ajouter un cast sur le type de retour. Le "problème", c'est que si l'utilisateur ne sait pas ce qu'il fait, il peut très vite se retrouver avec une `ClassCastException` sans comprendre pourquoi, vu qu'il n'aura pas écrit de cast

2024-08-19 09:02 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                geometryModel.setMetadata("height", simpleFeature.getProperties("hauteur").iterator().next().getValue());
Ah ! Tu veux dire les données de la source, désolé.

2024-08-19 09:03 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                geometryModel.setMetadata("height", simpleFeature.getProperties("hauteur").iterator().next().getValue());
Mais le `.next().getValue()` va marcher ?

2024-08-19 09:03 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                geometryModel.setMetadata("height", simpleFeature.getProperties("hauteur").iterator().next().getValue());
J'vais prevoir un truc 👍🏻

2024-08-19 09:21 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                GeometryModel geoModel = new GeometryModel((Geometry) splFeat.getDefaultGeometry(), converter, limits);
Tu as oublié `geoModel`

2024-08-19 09:27 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    }
Non tu m'as mal compris. Pourquoi la classe `Model` a une metadata "hauteur" par défaut ? Et pourquoi une valeur de "20" ? De manière plus générale, ce n'est pas au modèle de gérer ses valeurs par défaut, puisque le modèle n'est qu'une "coquille" qui enveloppe les données, mais il n'a pas d'intelligence, il peut y avoir des modèles qui n'ont pas de hauteur (c'est quoi la hauteur d'une route ?), et d'autres qui ont peut-être une hauteur mais donc la valeur 20 par défaut n'a aucun sens (t'as déjà vu un lampadaire de 20m ?)

Pour l'instant, cette valeur par défaut peut être appliquée dans le `SampleImplementation` vu que c'est du brouillon. Ensuite, plus tard ça se transformera en pre-processor, quelque chose comme `DefaultValuesPreProcessor`, quand on aura la chaîne d'import complète

2024-08-19 09:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> + * This interface is intended to evolve. Models are objects that can be
C'est plus une "classe" qu'un "objet". L'objet est l'instance de la classe

2024-08-19 09:31 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                GeometryModel geoModel = new GeometryModel((Geometry) splFeat.getDefaultGeometry(), converter, limits);
> Tu as oublié `geoModel`

T'es sur ?

2024-08-19 09:33 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                GeometryModel geoModel = new GeometryModel((Geometry) splFeat.getDefaultGeometry(), converter, limits);
J'avais pas vu le 2nd force-push, autant pour moi 👍

2024-08-19 12:06 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    }
Je voyais uniquement pour la hauteur -> les bâtiments, j'avais oublié au moment que j'écrivais mon code qu'il y a d'autres models autres que les bâtiments.
Est-ce que je set quand même une hauteur par défaut dans le SampleImplementation où j'oublie cette idée ?

2024-08-19 13:07 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    }
Oui tu peux mettre une hauteur par défaut actuellement dans le SampleImplementation puisqu'il ne fait que des bâtiments pour l'instant. Tu peux mettre un commentaire dessus en disant que c'est seulement une valeur par défaut pour les bâtiments d'ailleurs aussi

2024-08-19 14:06 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public void setMetadata(String name, Object value) {
J'ai opté pour la premier solution, merci ;)

2024-08-19 14:07 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                geometryModel.setMetadata("height", simpleFeature.getProperties("hauteur").iterator().next().getValue());
J'ai ajouté une condition pour résoudre le problème

2024-08-19 14:11 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public void setMetadata(String name, Object value) {
Maintenant que tu as réussi à faire la 1ère solution, tu peux essayer de faire la 2ème 🙂

2024-08-19 14:17 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public void setMetadata(String name, Object value) {
Okay 🤔

2024-08-19 14:18 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                geoModel.setMetadata("height", splFeat.getProperties("hauteur").iterator().next().getValue());
C'est bien ce qu'il me semblait, j'ai jeté un œil à la JavaDoc côté GeoTools, et il y a quand même nettement plus simple :
https://docs.geotools.org/stable/javadocs/org/geotools/api/feature/simple/SimpleFeature.html#getAttribute(java.lang.String)

2024-08-19 14:19 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public void setMetadata(String name, Object value) {
```java
    public <T> T getMetadata(String name) {
        return (T) metadata.get(name);
    }
```

```java
                    String test = geometryModel.getMetadata(type);
```

Mais bon, je reste sur ma position.

2024-08-19 14:21 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                geoModel.setMetadata("height", splFeat.getProperties("hauteur").iterator().next().getValue());
J'ai essayé de chercher dans leurs JavaDoc et mais ta reussi a trouvé avant moi
C'est un bordel...

2024-08-19 14:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public void setMetadata(String name, Object value) {
Voilà, et normalement le compilateur doit t'indiquer un warning au niveau de ton cast, c'est exactement ce que j'expliquais plus haut. Du coup, une fois que tu as compris ce warning, tu peux lui mettre `@SuppressWarning("unchecked")` (sur la méthode directement) et un petit commentaire explicatif

2024-08-19 14:25 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    }
Attention (bon ça va changer vu que tu peux largement simplifier avec `feature.getAttribute()`, mais je te le dis quand même), est-ce que tu es sûr que tu as mis la valeur par défaut ? Actuellement, elle n'y est que si l'objet a une propriété "hauteur" mais qui vaut `null` (ce qui est peu probable, en principe c'est plutôt quand la propriété est absente qu'on a besoin d'une valeur par défaut)

2024-08-19 14:26 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public void setMetadata(String name, Object value) {
Tu veux donc que je fasse ta deuxieme proposition pour cette PR ?

2024-08-19 14:29 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                geometryModel.setMetadata("height", simpleFeature.getProperties("hauteur").iterator().next().getValue());
@indyteo a résolu le problème grâce à la documentation 
https://github.com/ignfab/minalac-generator/pull/29#discussion_r1721870418

2024-08-19 14:38 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public void setMetadata(String name, Object value) {
Oui, on en a discuté avec @pyrollo et c'est le plus pratique à faire, sans oublier bien sûr le petit commentaire explicatif pour si jamais quelqu'un a un problème un jour avec ça

2024-08-19 14:40 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    public void setMetadata(String name, Object value) {
Okay, fallait me le dire tout de suite 😆

2024-08-20 07:06 UTC, pyrollo requested changes
Il faudrait quand même un minimum de tests sur les metadata, et peut être qu'une méthode `hasMetadata` pourrait être utile.

2024-08-20 12:21 UTC, pyrollo requested changes
Quelques remarques déjà

2024-08-20 12:21 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                SimpleFeature simpleFeature = iterator.next();
Proposition:
```suggestion
                SimpleFeature feature = iterator.next();
```

2024-08-20 12:21 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                GeometryModel geometryModel = new GeometryModel((Geometry) simpleFeature.getDefaultGeometry(), converter, limits);
Proposition:
```suggestion
                GeometryModel model = new GeometryModel((Geometry) simpleFeature.getDefaultGeometry(), converter, limits);
```

2024-08-20 12:21 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            }
Il faut toujours avoir une valeur par défaut, ici ce n'est pas le cas.

2024-08-20 12:21 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                Property heightProperty = simpleFeature.getProperty("hauteur");
Pourquoi pas `getAttribute` comme proposé par @indyteo ? (https://github.com/ignfab/minalac-generator/pull/29#discussion_r1721870418)

2024-08-20 12:30 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                Property heightProperty = simpleFeature.getProperty("hauteur");
Exactement

2024-08-20 15:27 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +    }
Tu peux virer le constructeur en initialisant le champ d'instance en ligne

2024-08-20 15:27 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +     * @param <T>  The type of return value to cast
En principe on le met plutôt en dessous lui (en dessous du `@return`, mais au dessus du `@throws` selon moi), après tu peux essayer de regarder dans le code de Java si il y a des exemples

2024-08-20 20:54 UTC, indyteo reviewed
> feat(model): Add building height metadata to the `Model`

Le scope me semble incorrect (et le message inexact aussi au passage puisque "to the model" c'est... vague)

2024-08-20 20:54 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                }
Cherchez l'erreur

2024-08-22 10:38 UTC, indyteo reviewed
Derniers détails puis on sera bon !

PS : Tu n'as pas modifié le scope du 2ème commit (`buildings` par exemple ?)

2024-08-22 10:38 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +     * @return Returns {@code true} or {@code false} if a value is associated with the name
```suggestion
     * @return Returns {@code true} if a value is associated with the name, {@code false} otherwise
```

2024-08-22 10:38 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +            if (hasMetadata(name))
Techniquement pas très utile vu que si il essaye de la retirer et qu'elle n'existe pas il ne se passera rien, mais c'est pas faux non plus

2024-08-22 10:38 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +     *              the name already exists. When the value is {@code null}, the key
```suggestion
     *              the name already exists. When the value is {@code null}, the name
```

2024-08-22 10:38 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +                "Test if the \"setMetadata\" method has assigned the value \"dummy\" to the \"test\" key in the metadata");
Tu fais des longs messages ici alors que c'est pas le bon endroit je dirais, si tu utilises plutôt `@DisplayName("...")` sur la méthode, c'est plus logique. Et du coup pas besoin de message pour une assertion aussi simple

2024-08-22 10:38 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +                "Verify that the metadata is deleted and that the \"hasMetadata\" function does not find the key");
Tu testes la suppression là. Tu devrais laisser la métadata, et en tester une autre plutôt

2024-08-22 12:24 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +                "Verify that the metadata is deleted and that the \"hasMetadata\" function does not find the key");
J'ai fait une erreur car les messages dans les `assertXxxx` s'affiche lors d'une erreur, j'ai donc laissé les messages et j'ai modifier le texte pour les erreurs

2024-08-22 12:27 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +                "Verify that the metadata is deleted and that the \"hasMetadata\" function does not find the key");
A voir si c'est pertinent de le faire

2024-08-22 12:29 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : "20");
Pourquoi stocker la hauteur en String puisqu'on peut la stoquer en numérique ?

2024-08-22 12:32 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : "20");
Yes

2024-08-22 12:32 UTC, pyrollo reviewed
Quelques suggestions

2024-08-22 12:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    @DisplayName("Test if the \"setMetadata\" method has assigned the value \"dummy\" to the \"test\" key in the metadata")
Plus simplement:
```suggestion
    @DisplayName("Test \"setMetadata\" method")
```

2024-08-22 12:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    @DisplayName("Verify that when we set the value to \"null\", it removes well the key that is associated with the value")
```suggestion
    @DisplayName("Verify that \"null\" value removes metadata")
```

2024-08-22 12:34 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +        assertEquals("dummy", (String) model.getMetadata("testGetter"),
Les messages sont plutôt inutiles car assertEquals va te dire la même chose.

2024-08-22 12:35 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +        assertEquals("dummy", (String) model.getMetadata("testGetter"),
Okay
J'enlève les messages sur tous les assert ?

2024-08-22 12:37 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +        assertEquals("dummy", (String) model.getMetadata("testGetter"),
Quand ils ne disent rien de plus intéressant que le Assert, oui.

(Essaye de faire foirer un assert, tu vas voir, c'est plutôt clair)

2024-08-22 12:38 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
`height` est bien un `int` ?

2024-08-22 12:39 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
C'est un float

2024-08-22 12:40 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
(Quand j'ai sout la valeur)

2024-08-22 12:42 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
Oui, c'était donc un float dans ce cas là. Mais est-tu sûr que ce sera toujours un float ?

2024-08-22 12:44 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
Non, il est aussi null pour des rare cas

2024-08-22 12:45 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +                "Verify that the metadata is deleted and that the \"hasMetadata\" function does not find the key");
https://github.com/ignfab/minalac-generator/pull/29#discussion_r1726976096

2024-08-22 12:46 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +        assertEquals("dummy", (String) model.getMetadata("testGetter"),
Ouais, okay

2024-08-22 12:48 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
Je ne sais pas comment tu peux savoir ça à l'avance

2024-08-22 12:49 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
`provider` peut te fournir n'importe quoi, et mettre ce qu'il veut dans l'attribut.

2024-08-22 12:53 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
> Je ne sais pas comment tu peux savoir ça à l'avance

J'ai sout la valeur avec ma version de mon code, mais c'est vrai que ce n'est pas une verification fiable.

2024-08-22 12:54 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
> `provider` peut te fournir n'importe quoi, et mettre ce qu'il veut dans l'attribut.

Tu penses que je dois écrire une condition `instanceof` ?

2024-08-22 13:02 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
Ce serait mieux, en tout cas, d'avoir un code qui soit capable de réagir correctement dans tous les cas.

2024-08-22 13:02 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
> > Je ne sais pas comment tu peux savoir ça à l'avance
> 
> J'ai sout la valeur avec ma version de mon code, mais c'est vrai que ce n'est pas une verification fiable.

Sauf à tester toutes les valeurs possibles de tout l'univers (en l'occurence, de toutes les sources possibles de données actuelles et futures, ce qui, étant moins étendu que l'univers, reste considérable).

2024-08-22 13:14 UTC, indyteo reviewed
(Tu n'as toujours pas renommé le commit)

2024-08-22 13:14 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    }
Il faudrait tester que `hasMetadata` renvoie bien `false` quand elle n'existe pas.

Conseil quand tu écris un test unitaire (pour une méthode relativement basique), imagine que c'est un énoncé que tu donnes à quelqu'un. Là, tu lui demande de coder une fonction qui doit renvoyer `true`. Donc si il code ça, ton test passe :
```java
public boolean hasMetadata(String name) {
    return true;
}
```
Donc qu'est-ce que tu dois ajouter comme assertion(s) dans ton test pour que ça ne soit plus le cas, et qu'il soit complet ?

2024-08-22 13:14 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +        assertNull((String) model.getMetadata("testGetter"));
Ce cast n'a aucun intérêt, ta valeur est censée être `null`, et `assertNull()` prend un `Object` en paramètre. Alors oui avant c'était un `String`, et techniquement tu peux cast `null` en n'importe quel type, mais là c'est comme si j'écrivais `assertNull((SampleImplementation) model.getMetadata("testGetter"));`, oui mon test va passer, mais ça n'a aucun sens 😄 

Et même si on réfléchi plus loin, si le teste échoue, c'est donc que ta valeur n'est pas `null`, donc à part si c'est justement par hasard un `String`, n'importe quel autre type causerait une `ClassCastException` au lieu de marquer le test en échec, donc plus dur de comprendre du 1er coup que c'est juste le test qui ne passe pas !

2024-08-22 13:14 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +        assertFalse(model.hasMetadata("testHasMetadata"));
Il y a un truc qui m'échappe, qu'est-ce que tu testes là concrètement ?

2024-08-22 14:16 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +        assertFalse(model.hasMetadata("testHasMetadata"));
Verifier avec la fonction `hasMetadata` la suppression de "testHasMetadata"

2024-08-22 14:21 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
Je viens de mettre a jour le code, est-ce que cela suffit ?

2024-08-22 14:22 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +        assertFalse(model.hasMetadata("testHasMetadata"));
Mais tu l'as testé juste au dessus ? Ou alors c'est la moitié du dessus à enlever peut-être, ou alors si tu veux t'assurer qu'après suppression `get() == null` et `has() == false`, autant pas se prendre la tête à le faire en 2x, et juste faire :
```
set()
assert(get()) // par principe
set(null)
assert(has())
assert(get())
```

2024-08-22 14:23 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +        assertFalse(model.hasMetadata("testHasMetadata"));
Apres relecture, je pense que c'est le même test que `testHasMetadata` ?

2024-08-22 14:23 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +        assertFalse(model.hasMetadata("testHasMetadata"));
C'est nul GitHub, on vois pas les messages en temps réel

2024-08-22 14:27 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                    model.setMetadata("height", (height != null) ? height : 20);
Tu as ré-introduit ton problème d'origine, la valeur par défaut n'est pas mise si le type n'est pas bon

2024-08-22 14:27 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +        assertFalse(model.hasMetadata("testHasMetadata"));
Et en réalité le fait de vérifier que la valeur a été mise après le `set()` c'est pas ton problème, c'est le test du `set()` (que tu as appelé `testAddMetadata()`)

2024-08-22 15:06 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null && height instanceof Float) ? height : 20);
`(null instanceof Object) == false` (toujours)

2024-08-22 15:15 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null && height instanceof Float) ? height : 20);
Ah ? Je savais pas

2024-08-23 07:27 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
Ça me parait mieux.
Ton literal est encore en Int en revanche.
Je laisse @indyteo valider l'aspect Java.
Au final on fera encore mieux: si c'est un objet "parsable" en float, on le convertira.

2024-08-23 07:40 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
Pour être tranquille tu peux valider que ça soit un `Number`, et utiliser `.floatValue()` (c'est probablement le genre de truc qui sera fait dans la version définitive)

2024-08-23 07:47 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    private static DummyModel model;
Ce champ ne devrait pas être `static` puisqu'il est propre à chaque test (dans l'état ça ne ferait pas de problème, mais si un jour on configure l'exécution parallèle des tests, ça peut poser problème)

2024-08-23 08:21 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height instanceof Float) ? height : 20);
Il y a un comportement qui me parait étrange.
En lancant le programme, j'ai remarqué que `height instanceof Float`est toujours faux (`height instanceof Integer` est aussi toujours faux et `height instanceof String` est toujours vrai). Du coup toutes des `metadata` height sont à 20.

2024-08-23 08:21 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +     * Check if there is a value associated with the given name.
J'aurais mis `Checks`

2024-08-23 10:51 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height instanceof Float) ? height : 20);
Mince

2024-08-23 12:12 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height instanceof Float) ? height : 20);
C'est ça de pousser sans tester :D

2024-08-23 12:21 UTC, pyrollo reviewed
Juste des suggestions pour simplifier les javadocs

2024-08-23 12:21 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +     *                            {@code Model} cast to an {@code Integer}
```suggestion
     * @param name Metadata name
     * @return Metadata value or {@code null} if it does not exist
     * @param <T> Wanted type of return value
     * @throws {@code ClassCastException} if value can not be cast to wanted type
```

2024-08-23 12:21 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +     *              name associated is deleted
```suggestion
     * @param name Metadata name to create or update
     * @param value Value to set (existing value is replaced) or {@code null} to delete metadata
```

2024-08-23 12:21 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +     * Creates a new metadata with the given name or updates the existing one.
```suggestion
     * Creates or replaces metadata with the given name.
```

2024-08-23 12:21 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +     * Check if there is a value associated with the given name.
```suggestion
     * Tells if a metadata exists.
```

2024-08-23 12:21 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +     *         {@code false} otherwise
```suggestion
     * @param name Metadata name
     * @return {@code true} if metadata exists with this name
```

2024-08-23 12:26 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    private static DummyModel model;
La classe `Model` pourrait même ne pas être abstraite après tout : un modèle sans rien dedans mais avec des metadata quand même. Cela éviterai d'avoir à la dériver ici.

2024-08-23 13:10 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height instanceof Float) ? height : 20);
🗿 Désolé chef j'ai glissé ca a push tout seul

2024-08-23 13:11 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height instanceof Float) ? height : 20);
C'est mon chat qui a push (_j'ai pas de chat_)

2024-08-23 13:13 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height instanceof Float) ? height : 20);
Oui, je peux témoigner, j’étais là, c'est la faute au chat

2024-08-23 13:14 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                model.setMetadata("height", (height != null) ? height : 20);
Je viens de voir le commentaire, j'imagine que je ne garde pas ce bout de code dans `SampleImplementation.java` :
```java
try {
    model.setMetadata("height", (height instanceof String) ? Float.valueOf(height.toString()) : 20.);
} catch (NumberFormatException e) {
    model.setMetadata("height", 20.);
}
```

2024-08-23 13:26 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                    model.setMetadata("height", (height instanceof String) ? Float.valueOf(height.toString()) : 20.);
Tu es sûr que `20.` est un `float` ? Ou alors, dans l'autre sens, tu es sûr de vouloir précisément un `float` ?

2024-08-23 13:33 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                    model.setMetadata("height", (height instanceof String) ? Float.valueOf(height.toString()) : 20.);
Et si height était un float ou un int, tu l'ignorerais pour mettre la valeur par défaut ?

2024-08-23 13:34 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                    model.setMetadata("height", (height instanceof String) ? Float.valueOf(height.toString()) : 20.);
Faut que tu m'explique car je comprend pas les resultats
Lorsque je cast en float, les valeurs sont plus précis (ex: 17.65400248) mais quand j'ai testé avec le type Double, j'ai l'impression qui round (ex: 17.6) 
Je ne sais pas si le Float fait des bêtises car c'est moins précis ou bien c'est la bonne valeur

2024-08-23 13:35 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                    model.setMetadata("height", (height instanceof String) ? Float.valueOf(height.toString()) : 20.);
Et pour la valeur `20.`, non je suis pas sûr que ca soit un float. Je pense qu'il faut add un `f` plutôt

2024-08-23 13:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                    model.setMetadata("height", (height instanceof String) ? Float.valueOf(height.toString()) : 20.);
Tu as essayé de regarder dans les données tout simplement ? La différence de précision entre un float et un double pour des valeurs autour de 17 doit être de l'ordre du 1e-10 au moins je pense. Donc non, ça n'explique pas le comportement que tu observes.
Dans l'absolu je sais pas si ça vaut le temps de s'arracher les cheveux à avoir un système parfait ici dans le SampleImplementation, compte tenu de ce qui va venir, @pyrollo. Faire en sorte que ça fonctionne avec notre seule source de données utilisée dans le sample impl puisqu'elle nous renvoie des strings, et pour moi ça suffit (puisque ça n'est déjà plus un problème sur ma branche `feat/processors`)

2024-08-23 13:53 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    private static DummyModel model;
Oui, c'était une remarque que je m'étais faite, ceci dit je sais pas si on aura besoin à un moment d'un modèle avec seulement des métadata, enfin techniquement vu que c'est type + metadata pourquoi pas, mais ça veut dire que ce sont des données non géo-référencées (ou alors sur lesquelles le géo-référencement est dans les attributs, pas pratique pour s'en servir de manière uniforme 🙃)
Par contre dans l'état, si tu la laisse abstraite et que tu as une implémentation ici, la classe reste `static` (pas le champ en dessous, mais la classe oui). C'est une question d'optimisation et de propreté du code (éviter les warnings du linter)

2024-08-23 14:27 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                }
Proposition de simplification:
```suggestion
                model.setMetadata("height", 20.0);
                if (height instanceof String s) {
                    try {
                        model.setMetadata("height", Double.valueOf(s));
                    } catch (NumberFormatException e) {}
                } else if (height instanceof Number n) {
                    model.setMetadata("height", n);
                }
```

2024-08-23 14:29 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                        model.setMetadata("height", Double.valueOf(heighString));
```suggestion
                if (height instanceof String heightString) {
                    try {
                        model.setMetadata("height", Double.valueOf(heightString));
```

2024-08-23 14:34 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                }
J'étais en train de modifer mon commentaire, je pense que dans ce cas on peut même se permettre:
```suggestion
                if (height instanceof String s) {
                    try {
                        model.setMetadata("height", Double.valueOf(s));
                    } catch (NumberFormatException e) {}
                } else if (height instanceof Number n) {
                    model.setMetadata("height", n);
                }
```

2024-08-23 14:36 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                }
Pas de valeur par defaut ?

2024-08-23 14:39 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +                    model.setMetadata("height", (height instanceof String) ? Float.valueOf(height.toString()) : 20.);
Oui effectivement, on doit pouvoir s'arrêter là. Mais tes essais @naulan-chrzaszcz vont te permettre de t'amuser sur la suite.

2024-08-23 14:43 UTC, pyrollo submitted a review, later dismissed

2024-08-23 15:04 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    class DummyModel extends Model {
```suggestion
    private static class DummyModel extends Model {
```
(voir mon commentaire sur la dernière discussion encore ouverte)

2024-08-26 09:07 UTC, indyteo submitted a review, later dismissed

2024-08-26 09:51 UTC, pyrollo requested changes
Ça me parrait bien, juste quelques remarques sur les tests.

2024-08-26 09:51 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    void testAddMetadata() {
```suggestion
    void testSetMetadata() {
```

2024-08-26 09:51 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    @DisplayName("Test if the \"hasMetadata\" function finds the metadata")
```suggestion
    @DisplayName("Test if the \"hasMetadata\" method finds the metadata")
```

2024-08-26 09:51 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    }
Ça devrait faire partie du test sur setMetadata non ?

2024-08-26 09:52 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +        assertEquals("dummy", (String) model.getMetadata("test"));
Ça c'est déjà testé donc inutile ici.

2024-08-26 11:47 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    @DisplayName("Test if the \"hasMetadata\" function finds the metadata")
Normalement, quand la fonction retourne une valeur, c'est pas une fonction ? (la phrase elle est bizarre mais j'pense que ta compris)
P.S: Et, quand elle retourne rien c'est une méthode ?

2024-08-26 12:20 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    @DisplayName("Test if the \"hasMetadata\" function finds the metadata")
Il semble que du moment que c'est attaché à un objet, on parle de méthode : 
https://stackoverflow.com/questions/155609/whats-the-difference-between-a-method-and-a-function

2024-08-26 12:29 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    @DisplayName("Test if the \"hasMetadata\" function finds the metadata")
Tu confonds la différence entre "fonction" (renvoie un résultat) et "procédure" (ne renvoie rien). Mais dans tous les cas, on ne fait pas vraiment cette différence à notre niveau.
Effectivement, dans certains langages orientés objets, on peut créer des fonctions (morceau de code "libre" pouvant être appelé à n'importe quel moment) et des méthodes (fonction rattachée à un objet). En Java, on ne peut pas faire de fonction libre, tout fonction est rattachée à une classe et devient donc une méthode. D'un certain point de vue, on peut considérer une méthode statique comme une fonction, mais ça n'apporte pas grand chose (c'est comme différencier fonction et procédure, pas grand intérêt...), d'autant plus que le langage lui-même appelle ça une méthode statique, donc techniquement tout est "méthode" en Java. Mais une méthode étant une fonction, je concluerais par : C'est pas faux.

2024-08-26 12:33 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    @DisplayName("Test if the \"hasMetadata\" function finds the metadata")
Okay, merci

2024-08-26 12:36 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    }
Oui, est-ce une bonne idée de split les tests en deux parties ?

2024-08-26 12:44 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    }
Ça me choque pas forcément de couper en deux tests vu que c'est 2 responsabilités / fonctionnalités de la méthode, mais ça pourrait aussi être testé en 1 seul, ça pourrait sans doute simplifier le test en l'occurence ici

2024-08-26 12:45 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    }
Ouaip, d'évité de réinsérer la donnée `"test"` ?

2024-08-26 12:46 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    }
@pyrollo qu'est-ce que tu en pense ? Le chef doit trancher

2024-08-26 12:47 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    private static DummyModel model;
J'ai pas lu ou bien cette conversation n'est pas résolu ? (J'vais relire)

2024-08-26 12:50 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    private static DummyModel model;
Ah oui, la conversation n'est pas résolu j'imagine a cause du débat sur l'`abstract` sur le Model.

2024-08-26 13:05 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    }
Sachant que les tests sont très simples (quelques lignes à peine), je pense qu'il est plus intéressant de les regrouper. C'était plus une remarque générique que je disais comme quoi quand une méthode a vraiment 2 responsabilités distinctes (déjà c'est peut-être un bon indicateur comme quoi il faut la couper en deux) on peut en faire 2 tests

2024-08-26 13:05 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/models/ModelTest.java
> +    }
Ca marche

2024-08-26 13:11 UTC, indyteo submitted a review, later dismissed

2024-08-26 13:37 UTC, zhak5388 requested changes
La dernière coquille que je vois : /

2024-08-26 13:37 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/Model.java
> +     * Creates or replace metadata with the given name.
*replaces

2024-08-26 13:38 UTC, pyrollo submitted a review, later dismissed

2024-08-26 13:40 UTC, zhak5388 approved these changes

2024-08-26 13:42 UTC, indyteo approved these changes

2024-08-26 14:09 UTC, pyrollo approved these changes

2024-08-26 14:14 UTC, merged