feat(voxelpattern): Add VoxelPattern interface and first implementation
ignfab/voxatile pull request #32
Opened 2024-08-13 12:46 UTC by zhak5388

### Issue

**JIRA ticket:** [MINALAC-52](https://ignfab.atlassian.net/browse/MINALAC-52)

This pull request also contains a commit from the [pull request](https://github.com/ignfab/minalac-generator/pull/31) that removes `OutOfWorldException`. The other pull request must be merged before this one can be merged. 

As discussed the basic implementation slightly differs from what was described in the Jira ticket. (Instead of an array of voxels, it will be voxels associated with a list of coordinates)

### Changes

Introduces the concept of pattern of voxels, which are voxels arranged in a specific geometrical configuration. (e.g. a pattern having the shape of box). Like voxels a pattern can be placed in the world.

#### Description

There are only two new additions : the `VoxelPattern` interface and its implementation `ListVoxelPattern`.

The `VoxelPattern` defines the method `place(int x, int y, int z)` for placing the pattern. (It also has a default alternate method: `place(WorldCoords3d coords)`)

As for the `ListVoxelPattern` class:
+ Patterns are defined by having a list of voxel-coordinate pairs where each voxel is associated with a list of coordinates (See [Showcase](#Showcase)). As such there can not be any duplicate voxels or duplicates coordinates
+ It stores these pairs in a map with where each voxel is used as key and the value is an integer array for the coordinates.
+ It can only be instantiated by providing a list of voxel-coordinate pairs. These pairs are encapsulated in a nested static class `ListVoxelPattern.Element`. Two static factory methods are provided to create the `Element` (of the `ListVoxelPattern.Element`).

I am a bit unsure about the choice of using a `HashMap` to store the voxel-coordinate pairs. I am wondering if there are other optimized choices. 

I would also appreciated if I could have feedback about the test for the `place()`. 

#### Showcase

```java
VoxelPattern plusPattern = new ListVoxelPattern(
    ListVoxelPattern.Element.create(
        stone,
        new int[]{0, 0, 0}
    ),
    //For readability, coordinates can be listed (Will be stored as an array)
    ListVoxelPattern.Element.create(
        grass,
        new WorldCoords3d(0, 1, 0),
        new WorldCoords3d(1, 0, 0),
        new WorldCoords3d(0, -1, 0),
        new WorldCoords3d(-1, 0, 0)
    )
);

plusPattern.place(0, 0, 0);
```
<img src="https://github.com/user-attachments/assets/4c193ba6-3323-443e-812d-57884aa368fd" width="250">

### Self-checks

- [x] The code has unit tests associated
- [x] The code has Javadoc Comments associated
- [x] Complex / Unexpected code is explained / justified with a small comment
- ~~Relevant documentation inside the `/docs` folder has been updated~~
- ~~All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)~~
- [x] Git history is clean (each commit accomplish a single task and describe it accordingly)
- [x] The texts have been proofread (documentation, error messages, logs, comments...)
- [x] [PR#31](https://github.com/ignfab/minalac-generator/pull/31) has been merged (Drop commit OutOfWorldException)

[MINALAC-52]: https://ignfab.atlassian.net/browse/MINALAC-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-13 17:39 UTC, indyteo commented
Pourquoi s'être éloigné du ticket d'origine et avoir fait ce choix d'implémentation ? Je ne comprends pas très bien

2024-08-14 08:27 UTC, zhak5388 commented
Ah, on dirait que l'on ne peut pas faire de réponses aux commentaires :/ Je te fais un ping (@indyteo ) 
Alors je me souviens pas exactement de la raison précise de pourquoi on avait décidé de faire comme première implémentation une "ListPattern" plutôt qu'une "ArrayPattern" (Le ticket d'origine ne semble pas avoir été mis à jour après avoir discuté de ça)
En tout cas, il me semble que c'était un mélange entre une déclaration du pattern plus souple et le fait que la pattern n'est plus "limitée" par la taille du tableau

2024-08-14 10:27 UTC, naulan-chrzaszcz commented
> Ah, on dirait que l'on ne peut pas faire de réponses aux commentaires :/ Je te fais un ping (@indyteo ) Alors je me souviens pas exactement de la raison précise de pourquoi on avait décidé de faire comme première implémentation une "ListPattern" plutôt qu'une "ArrayPattern" (Le ticket d'origine ne semble pas avoir été mis à jour après avoir discuté de ça) En tout cas, il me semble que c'était un mélange entre une déclaration du pattern plus souple et le fait que la pattern n'est plus "limitée" par la taille du tableau

Si c'est "quote reply" dans les "..." sur le message de @indyteo

2024-08-14 11:24 UTC, zhak5388 commented
@naulan-chrzaszcz Oui, merci, mais c'est pas vraiment une "réponse" pour moi (Pas d'option pour répondre juste en bas du commentaire; ça crée un nouveau commentaire)

2024-08-14 13:58 UTC, indyteo commented
Mais c'était une discussion avec @pyrollo ? Parce que cette implémentation n'est pas vraiment très optimisée (euphémisme), surtout par rapport à cette l'origine, personnellement je ne vois pas d'avantage (utile), mais par contre je vois bien plusieurs inconvénients 😅
@zhak5388

2024-08-14 14:09 UTC, zhak5388 commented
Oui, c'était bien une discussion avec Pierre-Yves 😅 
Après, j'ai sans doute mal compris l'implémentation `ListVoxelPattern`, du coup, je vais basculer cette PR en brouillon et je la reprendrai à son retour. Mais, sans forcément rentrer dans les détails, en deux mots, c'est quoi les principaux inconvénients ?
@indyteo

2024-08-14 14:29 UTC, indyteo commented
En terme de code, l'implémentation est volumineuse (il y a pas mal de code "pour rien", genre devoir vérifier que chaque coordonnée est unique), ensuite niveau mémoire ça consomme plus qu'un simple tableau pour des petits modèles (ce qui devrait être pas mal le cas), et moindre sujet mais les performances seront moins bonnes qu'avec un simple tableau (mais ça c'est négligeable si le reste est utile), sauf que le seul avantage que je vois c'est de pouvoir créer des modèles où certains voxels sont déconnectés et très loins, ou alors des gros modèles avec très peu de voxels, mais dans ces coups de temps-là, on pourra faire une autre implémentation quand ce besoin viendra (si il vient)
Le but de cette implémentation est d'être très très très simple et qui rempli le besoin le plus basique (enfin c'était ce dont on avait discuté quand on avait créé le ticket)

2024-08-14 15:20 UTC, zhak5388 commented
D'accord, je comprends un peu mieux, merci!

2024-08-19 08:09 UTC, pyrollo commented
> Oui, c'était bien une discussion avec Pierre-Yves 😅 Après, j'ai sans doute mal compris l'implémentation `ListVoxelPattern`, du coup, je vais basculer cette PR en brouillon et je la reprendrai à son retour. Mais, sans forcément rentrer dans les détails, en deux mots, c'est quoi les principaux inconvénients ? @indyteo

Je réponds avant d'avoir lu le code mais la discussion était au sujet du format de sérialisation plutôt que de l'implémentation.
Effectivement, implémenter avec cette structure risque d'être compliqué et lourd. De même qu'avoir le tableau dans le Yaml était compliqué et lourd. C'est l'avantage d'avoir découplé les classes "Param" des implémentations, on peut faire des choses très différentes.

Proposition (et ensuite je plonge dans le code): 
- Sérialisation comme tu l'as proposé  liste de [voxeltype -> liste de coords, et même plutôt liste de boxes])
- Implémentation au plus simple (probablement un tableau de voxeltypes)

Ce qui veut dire qu'il va faloir avoir à un moment quelque part une methode du genre `set(voxeltype, box)` qui va être appelée par le désérialiseur.

2024-08-19 08:16 UTC, pyrollo commented
> En terme de code, l'implémentation est volumineuse (il y a pas mal de code "pour rien", genre devoir vérifier que chaque coordonnée est unique), ensuite niveau mémoire ça consomme plus qu'un simple tableau pour des petits modèles (ce qui devrait être pas mal le cas), et moindre sujet mais les performances seront moins bonnes qu'avec un simple tableau (mais ça c'est négligeable si le reste est utile), sauf que le seul avantage que je vois c'est de pouvoir créer des modèles où certains voxels sont déconnectés et très loins, ou alors des gros modèles avec très peu de voxels, mais dans ces coups de temps-là, on pourra faire une autre implémentation quand ce besoin viendra (si il vient) Le but de cette implémentation est d'être très très très simple et qui rempli le besoin le plus basique (enfin c'était ce dont on avait discuté quand on avait créé le ticket)

Une autre implémentation inspirée de celle de Zen, mais plus simple et un peu plus performante, pourrait être une simple table de hash coords -> voxeltype. L'unicité est assurée, le dessin est très simple, et on s'évite de devoir connaitre la taile du tableau à l'avance (parce que ça, ça va être un problème avec le choix du format Yaml qui me semble pourtant bien meilleur que celui que j'avais imaginé à la base).

2024-08-19 08:24 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +        Set<WorldCoords3d> allCoords = new HashSet<>();
```suggestion
        // Temporary a "Set" type to ensure the uniqueness of the coordinates
```
Peut-être ? 😬

2024-08-19 08:29 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +        });
Pourquoi avoir call la fonction forEach ? 
C'est impossible de le faire de maniere "vanilla" ?

2024-08-19 08:29 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +        }
C'est une bonne pratique de faire ca ? (J'en ai aucune idée premier deg)
Les constructeurs peuvent faire l'affaire ?

2024-08-19 08:35 UTC, indyteo commented
> Une autre implémentation inspirée de celle de Zen, mais plus simple et un peu plus performante, pourrait être une simple table de hash coords -> voxeltype. L'unicité est assurée, le dessin est très simple, et on s'évite de devoir connaitre la taile du tableau à l'avance (parce que ça, ça va être un problème avec le choix du format Yaml qui me semble pourtant bien meilleur que celui que j'avais imaginé à la base).

Oui, après pour connaître la taille c'est pas non plus la mer à boire, il suffit d'appeler le constructeur de BBOX qui prend la liste de points en paramètres 😉 (et possiblement ajouter l'opérateur d'union de BBOX)

Mais oui en soit la `Map<WorldCoords3d, VoxelType>` est une implémentation simple et plus efficace que la proposition actuelle. En terme de consommation de mémoire, je dirais que ça devient avantageux par rapport à la matrix à partir du moment où une très grande partie de la BBOX est vide (il me semble que la `HashMap` consomme 3x plus de mémoire qu'un tableau (à nombre d'élément égaux), à peu près, + la clé qui doit être un objet, dans notre cas un `WorldCoords3d`)

Techniquement, le tableau/matrice de `VoxelType` à partir d'un index calculé selon la `WorldCoords3d`, c'est une implémentation optimisée dans certains contextes d'une map "coords -> voxel" 😄

2024-08-19 08:46 UTC, pyrollo requested changes
Y a moyen de beaucoup simplifier :)

2024-08-19 08:46 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +    private final Map<VoxelType, int[]> voxels;
Si tu inverses VoxelType et coordonnées (tu pouvais utiliser un WorldCoords3d je pense), tu t'évites de devoir vérifier l'unicité des coordonnées (ce qui, en soit, n'est nécessaire de toutes façons).

2024-08-19 08:46 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +                voxel.place(
Sans commentaire, c'est pas évident :D
Le mieux serait d'avoir un
```java
private final Map<WorldCoords3d, VoxelType> voxels;
```
et de faire un:
```java
 voxels.forEach((coords, voxel) -> { voxel.place(coords); });
```

2024-08-19 08:46 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +    /**
À mon avis, toute la suite ne concerne que la désérialisation du Yaml.

2024-08-19 08:46 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +    }
Le constructeur pourait se contenter de construire un objet vite et des méthodes `add` ou `set` permettraient de modifier le pattern. Par exemple:
```java
     public void set(WorldCoords3d coords, VoxelType type) {
          ...
     }

     public void set(WorldBBox3d box, VoxelType type) {
          ...
     }
```
Chaque méthode écrasant les données précédentes s'il y en a, sinon ça va être très difficile à utiliser pour 'sculpter' nos modèles.

2024-08-19 08:46 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +        // Temporary set to ensure the uniqueness of the coordinates
Quelle est l'utilité de s'assurer que les coordonnées sont uniques ?
Si l'utilisateur fait n'imp, et que tu peux le faire, pourquoi pas.
Avoir plusieurs fois les mêmes coordonnées ne pose que deux problèmes:
- Un possible problème de performances
- Un risque d'avoir un résultat aléatoire (mais là, ça semble être déterministe)

2024-08-19 08:46 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +        );
Un exemple de ce que cela pourrait donner avec constructeur vide + set:
```java
        VoxelPattern plusPattern = new ListVoxelPattern()
        plusPattern.set(new WorldCoords3d(0, 1, 0), grass);
        plusPattern.set(new WorldCoords3d(1, 0, 0), grass);
        plusPattern.set(new WorldCoords3d(0, -1, 0), grass);
        plusPattern.set(new WorldCoords3d(-1, 0, 0), grass);
        plusPattern.set(new WorldCoords3d(0, 0, 0), stone
);
```
Avec une version x, y, z :
```java
        VoxelPattern plusPattern = new ListVoxelPattern()
        plusPattern.set(0, 1, 0, grass);
        plusPattern.set(1, 0, 0, grass);
        plusPattern.set(0, -1, 0, grass);
        plusPattern.set(-1, 0, 0, grass);
        plusPattern.set(0, 0, 0, stone);
```

2024-08-19 08:46 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +        // Single voxel pattern to fill the void
Attention, tu construits un second test sur les données modifiées par le premier.
Ce n'est pas faux mais tu t'exposes au risque de devoir revoir ton second test si le premier venait à évoluer.

2024-08-19 08:46 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +        VoxelPattern emptyPattern = new ListVoxelPattern(
Idem ici, c'est risqué de ne pas repartir d'un jeu de donné préparé spécialement pour ton test.

2024-08-19 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +        public static Element create(VoxelType voxel, int[] coords) {
Ici tu exposes beaucoup ce que tu as en interne (cette liste de coordonnées à plat). Si jamais ton implémentation venait à changer tu serais bien embêté pour maintenir cette méthode.

2024-08-19 08:50 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +        public static Element create(VoxelType voxel, WorldCoords3d... coords) {
Pourquoi pas plutôt une collection de coordonnées ? Comme ça tu peux la passer d'appel en appel.

2024-08-23 12:42 UTC, zhak5388 reviewed
Un peu étrange mais je me fais un auto-review ! (Plus pratique pour pointer du code)
Je suis parti sur l’implémentation `Map<WorldCoords3d, VoxelType>` avec des `set()` et `remove()` pour scupter.
Les commentaires ci dessous c'est sur les parties dont je suis pas sur. Il manque des tests et javadoc. Je vais fermer pas mal des commentaires vu que le code a changé.

2024-08-23 12:42 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +package com.ignfab.minalac.generator.world;
Je me demandais, est ce c'est le bon package pour `VoxelPattern` ? Ou bien ça serait le package `generation`?

2024-08-23 12:42 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +    public void set(WorldCoords3d coords, VoxelType voxel) {
Ici, j'hésite un peu sur le nom, je me demande si il y a autre chose plus parlant. (Pour parler du fait que ça ajoute ou remplace)

2024-08-23 12:42 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +    public void remove(WorldCoords3d coords) {
Pour enlever les voxels, j'ai une légère préférence de de faire un : 
```java
pattern.remove(1, 2, 3) 
```
Plutôt que:
```java
pattern.set(1, 2, 3, null)
```

2024-08-23 12:45 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +        }
Je ferme vu que ça a changé!

2024-08-23 12:47 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +package com.ignfab.minalac.generator.world;
Moi ça me va, c'est le même package que `VoxelType`. Plus tard quand ça évoluera peut-être qu'un package dédié sera envisagé, pour l'instant je trouve ça bien ici

2024-08-23 12:47 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +        );
Du coup, c'est fait!

2024-08-23 12:48 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +        // Single voxel pattern to fill the void
J'avais pas pensé à l'évolution, j'ai fais 3 test séparés

2024-08-23 12:48 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +    public void set(WorldCoords3d coords, VoxelType voxel) {
`set` = définir, donc par définition (lol), "mettre la valeur à", si elle existe pas elle est ajoutée, sinon elle est remplacée. Ce nom me convient

2024-08-23 12:50 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +    public void remove(WorldCoords3d coords) {
Moi aussi, mais pour simplifier le code futur, `set(null)` doit fonctionner comme `remove()`

2024-08-23 13:00 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +package com.ignfab.minalac.generator.world;
Ok d'accord : )

2024-08-23 13:04 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +    public void set(WorldCoords3d coords, VoxelType voxel) {
Oui, c'est vrai, à force d'avoir des sets et gets, j'ai un peu "oublié" son sens originel. Du coup je n'hesite plus

2024-08-23 14:11 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +        });
```suggestion
        voxels.forEach((c, voxel) -> voxel.place(c.x() + x, c.y() + y, c.z() + z));
```

2024-08-23 14:11 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +            throw new IllegalArgumentException("Provided coordinates can not be null");
Concrètement c'est pas faux, mais on l'a fait nulle part parce que c'est une violation de contrat, en gros ta méthode dit "Je fonctionne avec des coordonnées non nulles. Si on me donne des coordonnées nulles, le résultat sera imprévu. Au mieux ça marche, au pire ça plante". Ne pas faire cette vérification optimise les appels par du code "valide", et ne change pas grand chose au code "invalide" (au lieu de pas marcher, il marchera mal)

(Valable aussi sur les mêmes checks plus bas sur `bbox`)

2024-08-23 14:11 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +            set(coords, voxel);
Tu pourrais légèrement optimiser (enfin en tout cas permettre une future optimisation, et ne rien changer au comportement actuel, si ce n'est gagner 3 nano-secondes 😄) en regardant si `voxel` est `null` avant de faire ta boucle, et appeler `remove(bbox)`. Plus tard, si une optimisation est faite au stockage (imaginons "bbox => voxel") ça pourra bénéficier de cette optimisation comme ça

2024-08-23 14:11 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/world/VoxelPattern.java
> +     * Coordinates are expressed using the system used in {@link com.ignfab.minalac.generator.utils.world3d.WorldCoords3d}.
```suggestion
     * Coordinates are expressed using the system used in {@link WorldCoords3d}.
```

2024-08-23 15:39 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +            throw new IllegalArgumentException("Provided coordinates can not be null");
Oui, je vois un peu la subtilité, il y a un certain équilibre à avoir

2024-08-23 15:43 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +            set(coords, voxel);
Le truc que je me demande c'est que si c'est pas null, je rentre dans la boucle et j'appelle `set()`, qui elle vérifie à chaque fois si voxel n'est pas null, du coup, est ce que ça vaut le coup de directement faire un `voxels.put(coords, voxel)` ?

2024-08-23 15:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +            set(coords, voxel);
Techniquement oui, mais selon la logique du code non. Ça change vraiment pas grand chose, et au moins si jamais un change la façon de stocker un voxel, il n'y a qu'un seul `set()` qui bouge (celui qui prend le voxel)

2024-08-23 16:01 UTC, indyteo reviewed
Pour moi c'est bon pour le code, je te laisse finaliser les tests et ensuite on pourra les review

2024-08-26 08:17 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +        plusPattern.set(-1, 0, 0, grass);
```suggestion
        plusPattern.set(0, 1, 1, grass);
        plusPattern.set(1, 0, 1, grass);
        plusPattern.set(0, -1, -1, grass);
        plusPattern.set(-1, 0, -1, grass);
```
Proposition pour tester Z aussi

2024-08-26 09:26 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +        // Pattern consisting of tree stacked layers: grass, dirt and stone. (top to bottom)
Tu as replanté une forêt, attention ! 🌳🌲🌴🎄

2024-08-26 09:28 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +        // Pattern consisting of tree stacked layers: grass, dirt and stone. (top to bottom)
(Moyen mnémotechnique que je viens d'imaginer : Les arbres (tree) n'aiment pas les H 🪓)

2024-08-26 09:29 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +        // Pattern consisting of tree stacked layers: grass, dirt and stone. (top to bottom)
:deciduous_tree: :deciduous_tree: :deciduous_tree:

2024-08-26 09:45 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +        plusPattern.set(-1, 0, 0, grass);
Ok, je modifie ça (j'ai ajouté des tests entre-temps)

2024-08-27 07:26 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +    public void testPlace() {
C'est plutôt un testAll du coup. Ça teste: set (voxel, null, bbox), remove (coords, bbox) et place.

C'est ok en l'état pour moi (c'est suffisant).

En revanche, en procédant de la sorte, si ton test échoue, c'est assez compliqué de savoir de quelle méthode vient le problème.

2024-08-27 07:27 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +
```suggestion

```

2024-08-27 07:56 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +    public void testPlace() {
En même temps ce problème vient de la classe elle-même, est-ce `set` qui n'enregistre pas ou `place` qui ne place pas sachant qu'on ne peut pas tester que `set` ai enregistré sans placer, ni `place` sans avoir défini de voxel... Peut-être avec des messages dans les tests ça peut aider un peu, mais ça sera difficilement mieux

2024-08-27 08:02 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +    public void testPlace() {
Oui, effectivement je suis passé à un seul gros test. Hmm est ce que tu penses que ça serait mieux déplacer certaines parties? Par exemple dans ce test faire que du set(voxel) et ajouter deux autres test avec set(null, bbox)/place() et remove(coords,bbox)/place()
**Edit:** Viens de voir ton commentaire Théo (alors que tu l''as posté avant haha)

2024-08-27 08:10 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +    public void testPlace() {
Comme je disais, ça me convient comme ça, je pense qu'il vaut mieux en rester là.

Pour avoir des tests plus précis, tu pouvais découper en tests plus simples (quite à finir par celui là). Par exemple, un test qui vérifie que set marche bien (en utilisant place), un autre qui vérifie que remove marche bien (en utilsiant set et place), mais sur des patterns très simple. Après tu pouvais répéter avec les BBox, etc.

L'avantage c'est que si le premier test merde, c'est que c'est set ou place qui sont problématiques mais pas les bbox ou remove. En revanche, si remove bbox merde, c'est probablement pas place, set ou remove coords qui ont été testés avant.

2024-08-27 08:12 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/world/ListVoxelPatternTest.java
> +    public void testPlace() {
Si un jour on a un bug, on revera les tests si nécessaire.

2024-08-27 08:12 UTC, pyrollo submitted a review, later dismissed

2024-08-27 08:26 UTC, indyteo reviewed
Juste un léger détail avant de merge, le nom `ListVoxelPattern` ne me convient pas. Soit quelque chose de basique (genre `SimpleVoxelPattern`), soit un peu plus lié à son implémentation (genre `MapVoxelPattern`, même si je trouve le nom pas fou fou)

2024-08-27 08:39 UTC, zhak5388 commented
@indyteo Pour le moment, je penche sur `SimpleVoxelPattern` (Map moins parce que j'ai l'impression que c'est plus le moyen utilisé pour faire une pattern de manière simple)

2024-08-27 08:39 UTC, pyrollo commented
> Juste un léger détail avant de merge, le nom `ListVoxelPattern` ne me convient pas. Soit quelque chose de basique (genre `SimpleVoxelPattern`), soit un peu plus lié à son implémentation (genre `MapVoxelPattern`, même si je trouve le nom pas fou fou)

Effectivement... maintenant avec `MapVoxelPattern` on risque la confusion.
Si on imagine qu'on ne va jamais développer un `ArrayVoxelPattern` mais plutôt des trucs randoms/generateurs, on peut effectivement aller vers `Simple` ou `Basic` (ou `Invariable` / `Solid` ? en regard de random).

2024-08-27 08:59 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +public class ListVoxelPattern implements VoxelPattern {
Juste pour ne pas merger sans avoir revu le nom.

2024-08-27 09:02 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/world/ListVoxelPattern.java
> +public class ListVoxelPattern implements VoxelPattern {
Yes, je viens de push avec `SimpleVoxelPattern` (Pour l'instant) Legerment modifie la description de classe pour le coup

2024-08-27 11:18 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/world/SimpleVoxelPattern.java
> + * {@code SimpleVoxelPattern} class is a {@link VoxelPattern} consisting of voxels and their associated coordinates.
```suggestion
 * A {@code SimpleVoxelPattern} is a {@link VoxelPattern} consisting of voxels at given coordinate offsets.
```

2024-08-27 11:25 UTC, indyteo approved these changes

2024-08-27 11:26 UTC, indyteo approved these changes

2024-08-27 11:32 UTC, merged