Add RendererParams deserialization
ignfab/voxatile pull request #38
Opened 2024-09-02 15:55 UTC by zhak5388

### Changes

Add the structure and deserialization of renderer parameters. That allows the creation of the adequate `Renderer`. 
#### Feature description

The main feature is the `RendererParams` abstract class which is meant for providing the structure to hold the parameters and create the adequate subclass `Renderer`. Specific renderer parameters will extend this class.

```yaml
renderers:  
  building:  
    type: vector  
    modelType: building  
    heightmapName: ground  
    inside: COBBLE  
    edge: STONE
```

The value `vector` of field `type` indicates the type of renderer. (In our case `VectorRendererParams`) The fields `modelType`, `heightMapName`, `inside` and `edge` are specific parameters.
#### Technical changes

+ Add `RendererParams` and `VectorRendererParams`
	+ -> The method in`VectorRendererParams` creates a `VectorRenderer`
	+ The attribute `type` of `RenderersParams` is used to determine the concrete class for deserialization.
+ Add `Renderer` interface and its abstract subclass `ModelRenderer`.
	+ `VectorRenderer` is now a `ModelRenderer` implementation
	+ Add a `ModelSelection` which is an iterable of `Model` matching a certain type. Used by `ModelRenderer`.
+ `RawParams` is now `GenerationParams` and has `validate()` method.
	+ `heigthmaps` is now a map instead of a list. This allow to remove the attribute `name` in yaml
+ `Generation` now contains `VoxelWorld` and stores for `Renderer` ans `Heightmap`
### How to add a new `Renderer`

Say we have created a `FooRenderer`. To enable the deserialization, this is what needs to be done:
1) Create a `FooRendererParams` class that extends `RendererParams` in the package `parameters.renderers`. 
2) Add the parameters needed for `FooRenderer`.
3) Implements `create(Generation generation)`. The `validate()` can be implemented if needs be.
4) Add an annotation `@JsonSubTypes.Type` in `RendererParams` to specify the concrete class that should be used for deserialization based on the `type` attribute. For exemple: `@JsonSubTypes.Type(value = FooRendererParams.class, name = "foo")`. There is always the possibility the specific  the concrete class by using `registerRenderer(Class, String)` of `ParamsParser`.

### Self-checks

- [x] The code has unit tests associated
- [x] The code has Javadoc Comments associated
- [x] Complex / Unexpected code is explained / justified with a small comment
- [x] Relevant documentation inside the `/docs` folder has been updated
- [x] All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)
- [x] Git history is clean (each commit accomplish a single task and describe it accordingly)
- [x] The texts have been proofread (documentation, error messages, logs, comments...)

2024-09-03 09:56 UTC, pyrollo requested changes

2024-09-03 09:56 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +    public ModelStore modelStore() {
Pour homogénéiser ?
```suggestion
    public ModelStore models() {
```

2024-09-03 09:56 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +            new Coordinate(world.limits().to2d().getMinX(), world.limits().to2d().getMinY())
```suggestion
            new Coordinate(world.limits().getMinX(), world.limits().getMinY()),
            new Coordinate(world.limits().getMaxX(), world.limits().getMinY()),
            new Coordinate(world.limits().getMaxX(), world.limits().getMaxY()),
            new Coordinate(world.limits().getMinX(), world.limits().getMaxY()),
            new Coordinate(world.limits().getMinX(), world.limits().getMinY())
```

2024-09-03 09:56 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/GenericStore.java
> +public class GenericStore<T> {
Pourquoi pas `Store` tout court ?

2024-09-03 09:56 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parsing/GenerationParams.java
> +    public static class HeightMapParams {
```suggestion
    public static class HeightmapParams {
```
Pour pas oublier plus tard

2024-09-03 09:56 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/generation/TestGeneration.java
> +            return new WorldBBox2d(-extendX / 2, -extendY / 2, extendX, extendY).to3d(0, 1);
```suggestion
            return new WorldBBox3d(-extendX / 2, -extendY / 2, 0, extendX, extendY, 1);
```

2024-09-03 09:56 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/generation/TestGeneration.java
> +        VoxelWorld world = new EmptyVoxelWorld(501, 501);
Tu as un `TestingVoxelWorld` qui peut² être² utilisé ici.

2024-09-03 09:56 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/generation/TestGenericStore.java
> +    public void testGetHeightMap() {
```suggestion
    public void testGet() {
```

2024-09-03 09:56 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/generation/TestGenericStore.java
> +        assertDoesNotThrow(() -> store.add("second", element));
```suggestion
```
Celui là ne sert pas à grand chose.
Tu peux peut être tester l'ajout d'un autre type d'objet ici.

2024-09-03 09:56 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/generation/TestGenericStore.java
> +        String element = "element";
Je mettrais en literal des valeurs plutôt que déclarer un String pour ça.

2024-09-03 09:56 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/generation/TestGenericStore.java
> +        assertEquals(element, store.get("first"));
```suggestion
        store.add("second", "othervalue");
        assertEquals(element, store.get("first"));
```
--> Comme ça on vérifie que le second add n'a pas écrasé la première valeur.

2024-09-03 09:56 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/generation/TestGenericStore.java
> +        assertThrows(IllegalArgumentException.class, () -> store.add("first", element), "Should not be able to add an element with an existing name");
```suggestion
        assertThrows(IllegalArgumentException.class, () -> store.add("first", "abcd"), "Should not be able to add an element with an existing name");
```
On peut imaginer que la classe pourrait accepter de ne rien changer (remettre la même valeur deux fois).

2024-09-03 09:56 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parsing/GenerationParamsTest.java
> +
Tant qu'à faire on peut faire les mêmes pour X et pour Y (un test 0 et un test négatif)

2024-09-03 09:56 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parsing/GenerationParamsTest.java
> +        params.area.extendX = 0;
```suggestion
        params.area.extendY = 0;
```
Pour coller au titre

2024-09-03 09:56 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parsing/RawParamsTest.java
>  public class RawParamsTest {
Ça devrait être:
```suggestion
public class GenerationParamsTest {
```

2024-09-03 09:56 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/renderers/VectorRendererTest.java
>                  ).render()
Ici on veut juste tester le rendu mais pas les mécanismes de sélection (qui seront testés dans `ModelSelection` ou `ModelRenderer`. On doit pouvoir se simplifier la vie comme ça:
```java
    private void render(Model model) {
        assertDoesNotThrow(
            () -> new VectorRenderer(
                    null,
                    heightMap,
                    world.getFactory().createVoxelType(SemanticType.COBBLE),
                    world.getFactory().createVoxelType(SemanticType.BRICK)
                ).render(model)
```

2024-09-03 09:56 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/ModelRenderer.java
> +            render(model);
```suggestion
        if (selection != null)
            for (Model model : selection)
                render(model);
```
Ça va permettre de ne pas passer de sélection au `ModelRenderer` (et de ne rien rendre dans ce cas). Cela va simplifier nos tests ensuite.

2024-09-03 09:56 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/renderers/VectorRendererTest.java
>          render();
Du coup:
```suggestion
        render(new TestingRasterizableModel(new TestingIterableArrayChunk2d(modelBbox, GeometryModel.INSIDE)));
```

2024-09-03 15:36 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/generation/TestGenericStore.java
> +        assertEquals(element, store.get("first"));
Je le fais avec un `get` sur `first` (Vu qu'il y a déjà un `store.add("first", "abcd")`)

2024-09-03 15:36 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/generation/TestGenericStore.java
> +        assertDoesNotThrow(() -> store.add("second", element));
Un autre type d'objet ? Avec un autre store?

2024-09-03 15:36 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/generation/TestGeneration.java
> +        VoxelWorld world = new EmptyVoxelWorld(501, 501);
Alors, oui il faudrait que je la modifie un peu (Elle prends une BBOX et pose les limites, et c'est generation qui set les limites)

2024-09-03 15:36 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +    public ModelStore modelStore() {
Yes

2024-09-04 07:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/ModelStore.java
> +        return (byType.get(type) == null) ? new LinkedList<>() : byType.get(type);
```suggestion
        return byType.containsKey(type) ? byType.get(type) : Collections.emptyList();
```

2024-09-10 16:23 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/generation/TestGeneration.java
> +        VoxelWorld world = new EmptyVoxelWorld(501, 501);
Je resolve (On avait discuté il me semble, `TestingVoxelWorld` car j'ai juste besoin de verifier la taille et comment Generation place la bbox)

2024-09-10 16:30 UTC, zhak5388 commented on pom.xml
> +        <jackson.version>2.17.2</jackson.version>
Permet de corriger un [bug](https://github.com/FasterXML/jackson-databind/issues/4441) sur annotation sur Map

2024-09-13 15:14 UTC, pyrollo reviewed
J'ai l'impression que la structure est suffisamment bonne pour que tu te lances dans les javadoc.

Je me demande si `HeightmapParams` ne devrait pas suivre la même interface que les autres (avec validation qui ne fait rien).

2024-09-13 15:14 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationParams.java
> +            this.defaultValue = parseDefaultValue(defaultValue);
Peut être plus lisible de tout mettre dans le constructeur (vu qu'il est presque vide) :
```suggestion
            this.defaultValue = switch (defaultValue) {
                case "minimal", "min" -> Integer.MIN_VALUE;
                case "maximal", "max" -> Integer.MAX_VALUE;
                ...
```

2024-09-13 15:14 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/Renderer.java
> +    void render();
Note pour le futur rebase:
Un nouveau paramètre de type `WorldBBox2d`/`3d` devrat être ajouter pour désigner la zone à rendre.

2024-09-13 15:14 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/ModelRenderer.java
> +    protected abstract void render(Model model);
Note pour le futur rebase:
Un nouveau paramètre de type `WorldBBox2d`/`3d` devrat être ajouter pour désigner la zone à rendre.

2024-09-13 15:14 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/generation/TestGenericStore.java
> +        store.add("first", "element");
```suggestion
        store.add("first", "bad");
        store.add("second", "good");
        store.add("third", "ugly");
```
Et je testerai sur le "second", histoire de vérifier que get renvoie bien celui que je veux.

2024-09-13 15:14 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/generation/TestGenericStore.java
> +        assertEquals("element", store.get("first"));
Pour vérifier que `get` donne toujours le même resultat ?

2024-09-13 15:14 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/ModelSelectionTest.java
> +        ArrayList<Character> retrievedElements = new ArrayList<>();
Vivement le rebase, on a de supers outils pour faire ces test maintenant!

2024-09-13 15:14 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +    private double[] conversionFromWGS84ToTargetCRS(CoordinateReferenceSystem targetCrs, double longitude, double latitude) {
Le paramètre `targetCrs` est inutile, c'est `this.crs`.

Pas surper fan de ce découpage.
Si tu fais une fonction, fais plutôt un truc qui met en place `voxelToCrs` et `crsToVoxel` ou bien mets tout dans le constructeur.

2024-09-13 15:14 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/Store.java
> +    public void add(String name, T object) throws IllegalArgumentException {
```suggestion
    public void add(String name, T object) {
```
Vu que c'est une RuntimeException, et qu'on fait déjà comme ça ailleurs.

2024-09-13 15:14 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/ModelStore.java
> +import java.util.*;
Ça ne passera jamais :)

2024-09-13 15:14 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationCreator.java
> +    public static Generation createGeneration(GenerationParams params) {
Je suppose que `create` est suffisamment explicite ici
```suggestion
    public static Generation create(GenerationParams params) {
```

2024-09-13 15:14 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/ParamsParser.java
> +    public Generation createGeneration() {
Est-ce que `parse` et `createGeneration` vont être utilisés séparément ? Si ce n'est pas le cas (pour le `ParamParser` en tout cas), ils peuvent peut être être fusionnés.

2024-09-13 15:14 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/ParamsParser.java
> +    public Generation createGeneration() {
Par souci d'homogénéité (même si le `create()` de la generation ne prend bien sûr pas de param), tu peux peut être ajouter une méthode `create()` à `GenerationParams` qui fait l'appel à `GenerationCreator`. C'est en tout cas comme ça que l'on fera pour les futures classes si on doit les séparer en deux.

2024-09-13 15:14 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationParams.java
> +        for (RendererParams params : renderers.values())
J'ajouterai au moins une séparation entre la validation des arguments correspondant aux attributs directs et celle des collections :
```suggestion
            throw new IllegalArgumentException("The provided format is not supported");

        for (RendererParams params : renderers.values())
```

2024-09-17 07:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
>      public Generation(
```suggestion
    @SuppressWarnings("ParameterNumber")
    public Generation(
```

2024-09-17 13:39 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/Store.java
> +    public void add(String name, T object) throws IllegalArgumentException {
Après ça m’empêche pas de le renseigner sur la javadoc ?

2024-09-17 13:51 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationParams.java
> +            this.defaultValue = parseDefaultValue(defaultValue);
Je suis tenté de mettre `HeightmapParams` en classe à part et ajouter le `validate()` mais je sais pas

2024-09-17 13:54 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/generation/TestGenericStore.java
> +        assertEquals("element", store.get("first"));
Ah mince, je m'en souviens plus exactement pourquoi, mais oui, ça semble redondant

2024-09-17 13:55 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +    private double[] conversionFromWGS84ToTargetCRS(CoordinateReferenceSystem targetCrs, double longitude, double latitude) {
Je mets dans le constructeur

2024-09-17 14:09 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/ParamsParser.java
> +    public Generation createGeneration() {
Oui, mais ça serait un peu étrange non? la méthode `create()` de `GenerationParams` ça sera ça:
```java
public Generation create() {
    return GenerationCreator.create(this);
}
```

2024-09-17 15:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/ParamsParser.java
> +    public Generation createGeneration() {
Comme discuté, ça serait donc plutôt : 
* `GenerationParams` a une méthode `create()` qui appelle `GenerationCreator`;
* `parse()` renvoie `GenerationParams` (ou fait le `create` et revoie une `Generation`, et peut être à renommer dans ce cas)
* Plus besoin de `createGeneration` ici.

2024-09-20 08:34 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationParams.java
> +            this.defaultValue = parseDefaultValue(defaultValue);
Tu peux si tu veux, ça sera plus homogène (et si on cherche où est ce foutu paramétrage heightmap, on trouvera plus vite)

2024-09-20 08:41 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/ModelSelectionTest.java
> +        assertEquals(1, Collections.frequency(retrievedElements, 'b'));
A y est, donc maintenant on a `IteratorTester` qui fait papa maman:
```suggestion
        assertBrowsesAllOnce(Arrays.asList('a', 'a', 'b'), iterator);
```
L'import correspondant:
```java
import static com.ignfab.minalac.generator.utils.iterator.IteratorTester.*;
```

2024-09-20 08:43 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/ModelSelectionTest.java
> +        assertFalse(emptySelection.iterator().hasNext());
Avec IteratorTester:
```suggestion
        assertEmpty(new ModelSelection(store, "special"));
```

2024-09-20 08:54 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/GenerationParamsTest.java
> +            GenerationParams.HeightmapParams.class));
Je cherche un moyen pour compacter un peu ton code (mais sans rien de très concluent):
```suggestion
        GenerationParams.HeightmapParams heightmapIntegerValue = assertDoesNotThrow(() -> mapper.readValue(
            """
            { "default" : 3 }
            """,
            GenerationParams.HeightmapParams.class));
```

```suggestion
        GenerationParams.HeightmapParams heightmapIntegerValue = assertDoesNotThrow(() -> mapper.readValue(
            "{ \"default\" : 3 }",
            GenerationParams.HeightmapParams.class));
```

2024-09-23 09:27 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/models/ModelSelectionTest.java
> +        assertEquals(1, Collections.frequency(retrievedElements, 'b'));
Ah, yes, ça fait plus compact!

2024-09-23 11:24 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/GenerationParamsTest.java
> +            GenerationParams.HeightmapParams.class));
Je pense que je prefere `{ "default" : 3 }`. Ceci dit j'ai viré/modifié ce test en créant la classe `HeightmapParams`: le constructeur ne renvoie plus une `ParseException` mais une `IllegalArgumentException`. Ce `IIllegalArgumentException` est catchée par `parse()` (Pour envoyer une `ParseException`)

2024-09-23 11:25 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationParams.java
> +            this.defaultValue = parseDefaultValue(defaultValue);
Du coup, j'ai fait quelques modifications (voir ce [commentaire](https://github.com/ignfab/minalac-generator/pull/38#discussion_r1771228627))

2024-09-23 12:19 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/ParamsParser.java
> +    public Generation createGeneration() {
Yes, je suis parti sur le fait que `parse()` renvoie un `GenerationParams`. Après on pourrait faire un "parseAndCreate" mais je vois comment faire des tests fin sur le parsing

2024-09-24 08:07 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/VectorRendererParams.java
> +    public void validate() throws IllegalArgumentException {
```suggestion
    @override
    public void validate() throws IllegalArgumentException {
```

2024-09-24 08:07 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        VoxelWorld world = generation.world();
Je me demande s'il faut encore garder cette variable. Parfois elle est utilisée, ailleurs c'est directement `generation.world()` qui est utilisé (au final, ce sera toujours la seconde solution qui sera utilisée).

2024-09-24 08:07 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        VoxelWorld world = generation.world();
Idem pour `groundHeightmap`, au final on utilisera toujours `generation.heightmaps().get("ground")` pour désigner ce heightmap.

2024-09-24 08:07 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/models/ModelSelectionTest.java
> +        private char content;
Ici `content` ne sert à rien et `assertBrowsesAllOnce` doit s'appuyer sur les références pour faire ses comparaisons.

Deux possibilités :
* Enlever tout ce qui concerne le `content` et avoir un test très simple qui s'appuie sur les refs;
* Ajouter une methode equals pour pouvoir tester avec des `new ModelImpl("...")` dans la liste des attendus.

2024-09-24 08:18 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/ModelSelection.java
> +    // public ModelSelection byClass(Class clazz);
```suggestion
```

2024-09-24 08:20 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationParams.java
> + * GenerationParams is a POJO representing the parameters used during the generation.
```suggestion
 * GenerationParams represents the parameters used during the generation.
```

2024-09-24 08:30 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationParams.java
> +
```suggestion

```

2024-09-24 08:41 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/VectorRendererParams.java
> +    public void validate() throws IllegalArgumentException {
Ça fera l'objet d'une future PR pour harmoniser tout ça.

2024-09-24 09:07 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/RendererParams.java
> +})
Pour éviter d'avoir deux méthodes d'enregistrement, je propose de virer cette annotation et de faire l'enregistrement dans le `main()` (en attendant de le faire ailleurs) en utilisant `ParamsParser.registerRenderer()`.

2024-09-24 09:07 UTC, pyrollo requested changes
Ajouter des tests pour `registerRenderer`

2024-09-24 09:10 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/ModelRenderer.java
> + * The abstract {@code ModelRenderer} class represents a type of {@link Renderer} that renders a specific type of models.
```suggestion
 * The abstract {@code ModelRenderer} class represents a type of {@link Renderer} that renders a selection of models.
```

2024-09-24 09:16 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/Renderer.java
> + * Implementation of this interface implements the logic for rendering specific content.
J'ai rien compris :D
Tentative de proposition:
```suggestion
 * A renderer capable of rendering something in an area
```

2024-09-24 09:38 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/GenerationParamsTest.java
> +        renderers.put("building", new VectorRendererParams(
Si ça ne pose pas de problème, c'est plus simple comme ça :
```suggestion
        params.heightmaps.put("altitude", new HeightmapParams("minimal"));
        params.heightmaps.put("ground", new HeightmapParams("0"));
        params.renderers.put("building", new VectorRendererParams(
```

2024-09-24 09:38 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/GenerationParamsTest.java
> +        params.renderers = renderers;
Et dans ce cas:
```suggestion
```

2024-09-24 09:39 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/GenerationParamsTest.java
> +        GenerationParams params = new GenerationParams(area, "minetest");
Il me semble que c'est fait dans setup ça;
```suggestion
```

2024-09-24 12:24 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/models/ModelSelectionTest.java
> +        private char content;
Finalement, j'ai viré content!

2024-09-24 12:30 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/GenerationParamsTest.java
> +        GenerationParams params = new GenerationParams(area, "minetest");
Ah, j'avais presque oublié le setUp!

2024-09-25 12:54 UTC, pyrollo submitted a review, later dismissed
Ça me semble bien comme ça même si j'ai fait quelques suggestions (optionelles donc).

2024-09-25 12:54 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/ParamsParserTest.java
> +        assertDoesNotThrow(() -> new ParamsParser().parse("heightmaps: {}\n" + MINIMAL_YAML));
En inversant les deux tu t'économises un \n:
```suggestion
        assertDoesNotThrow(() -> new ParamsParser().parse(MINIMAL_YAML + "heightmaps: {}"));
```

2024-09-25 12:54 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/TestingRendererParams.java
Tu peux mettre cette classe en `static class` de `ParamsParserTest`

2024-09-25 12:54 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/ParamsParserTest.java
Tu peux rassembler les tests pour avoir moins de méthodes, par exemple :

`testParseWithoutOptionalFields` (manque peut être un test avec des champs optionnels ?)

`testParseFormats`:
* `testParseJson`
* `testParseYaml`

`testParseMissingRequiredField`:
* `testParseMissingRequiredFieldArea`
* `testParseMissingRequiredFieldLatitude`
* `testParseMissingRequiredFieldLongitude`
* `testParseMissingRequiredFieldExtendX`
* `testParseMissingRequiredFieldExtendY`
* `testParseMissingRequiredFieldFormat`

`testParseHeightmaps`:
* `testParseFailedOnDuplicatedMapKey`
* `testParseOptionalFieldHeightmapEmpty`
* `testParseMissingRequiredFieldDefaultHeightmap`
* `testParseIllegalFieldDefaultHeightmap`

`testParseRenderers`:
* `testParseOptionalFieldRenderersEmpty`
* `testParseRendererMissingRequiredValueForField`
* `testParseRendererTypeFieldNotDeserialized`
* `testParseRendererWrongTypeFieldValue`
* `testRegisterRendererWithWrongSubClass`
* `testRegisterRenderer`

2024-09-25 12:54 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/generation/TestGeneration.java
> +        WorldBBox2d box = generation.world().limits().to2d();
```suggestion
        WorldBBox3d box = generation.world().limits();
```

2024-09-25 16:55 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/ParamsParserTest.java
Effectivement, je me suis fait la réflexion après que ça serait mieux de les ranger!

Du coup, des classes imbriquées? Je pense à quelque chose comme :

```java
class ParseFormatTests {
    @Test
    public void testParseYaml() { }
}

class ParseRequiredFieldTest {
    @Test
    public void testParseMissingAreaField() {}
}

// etc
```

2024-09-30 09:47 UTC, zhak5388 commented
Du coup, j'ai fait de légères modifications! 
+ Mettre à jour `docs` et `examples`
+ Restructurer `ParamsParserTest` avec des classes imbriquées + ajout d'un test pour optionnels

2024-09-30 13:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        parser.registerRenderer(VectorRendererParams.class, "vector");
Ça serait pas plus logique dans l'autre sens ?
```suggestion
        parser.registerRenderer("vector", VectorRendererParams.class);
```

2024-09-30 13:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/Store.java
> +            throw new IllegalArgumentException("Illegal name for the element, duplicate or null name : " + name);
```suggestion
            throw new IllegalArgumentException("Illegal name for the element, duplicate or null name: " + name);
```

2024-09-30 13:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/Store.java
> +     * Returns the associated element to the given name.
```suggestion
     * Returns the element associated to the given name.
```

2024-09-30 13:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/Store.java
> +     * @throws NoSuchElementException if there is not an element associated with the specified name
```suggestion
     * @throws NoSuchElementException if no element is associated to the specified name
```

2024-09-30 13:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/ModelSelection.java
> + *
```suggestion
```

2024-09-30 13:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationParams.java
> +     * This field is optional. (Default value : 1.0)
```suggestion
     * This field is optional. (Default value: 1.0)
```

2024-09-30 13:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationParams.java
> +     * This field is optional. (Default value : 1.0)
```suggestion
     * This field is optional. (Default value: 1.0)
```

2024-09-30 13:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationParams.java
> +            params.validate();
Pas de validation pour les heightmaps ?

2024-09-30 13:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/HeightmapParams.java
> +                    throw new ParseException("Invalid heightmap default field value : " + defaultValue, e);
```suggestion
                    throw new ParseException("Invalid heightmap default field value: " + defaultValue, e);
```

2024-09-30 13:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/ParamsParser.java
> +            throw new IllegalArgumentException("Can not register: " + clazz.getSimpleName() + "is not a subclass of " + RendererParams.class.getSimpleName());
```suggestion
    public <T extends RendererParams> void registerRenderer(Class<T> clazz, String name) {
```

2024-09-30 13:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/VectorRendererParams.java
> +            throw new IllegalArgumentException("The fields modelType and heightmap name cannot be empty");
Histoire d'avoir un message d'erreur qui indique directement à l'utilisateur le champ qui manque, au lieu de lui dire "ah il en manque un des deux, cherche" :
```suggestion
        if (modelType.isEmpty())
            throw new IllegalArgumentException("The field model type cannot be empty");
        if (heightmapName.isEmpty())
            throw new IllegalArgumentException("The field heightmap name cannot be empty");
```

2024-09-30 13:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/Renderer.java
> +
```suggestion
```

2024-09-30 13:22 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/GenerationParamsTest.java
> +        assertDoesNotThrow(() -> params.validate());
```suggestion
        assertDoesNotThrow(params::validate);
```
Même remarque sur tous les assert plus bas

2024-09-30 13:22 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/ParamsParserTest.java
> +public class ParamsParserTest {
Tu as des problèmes d'indentation dans tes multi-line strings dans tes classes imbriquées

2024-09-30 13:22 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/renderers/ModelRendererTest.java
> +public class ModelRendererTest {
Euh, je suis pas vraiment fan de l'idée de faire un string pour enregistrer les modèles... Tu ne peux pas faire plutôt une liste ? Voire "mieux", tu donnes à ton renderer de test la liste des modèles auquel il doit s'attendre, et il valide à chaque appel que c'est bon ?
Après au pire c'est juste un test mais je trouve ça vraiment bizarre cette solution avec un string

2024-09-30 13:22 UTC, indyteo commented on docs/usage/GenerationParameters.md
>  Available fields:
Pour la documentation de la structure, pour bien comprendre quand il y a une liste d'éléments ou une map string => élément, j'aime bien la solution adoptée par le Wiki de Minecraft de faire apparaître l'étape d'indentation correspondant à l'élément. Exemple (dans `CustomBossEvents`) :
https://minecraft.wiki/w/Java_Edition_level_format#level.dat_format

Indiquer le type est pas mal non plus. En gros :
```md
- `heightmaps`: heightmaps available for the generation
  - _`<name>`_: name of a heightmap
    - `default` (int or str): default value for all heightmap cells (integer or one of `minimal`, `min`, `maximal` or `max`)
- `renderers`: renderers used to generate the map
  - _`<name>`_: name of a renderer
    - `type` (str): type of the renderer
    - additional parameters specific to the given type
```
Rendu Markdown :

- `heightmaps`: heightmaps available for the generation
  - _`<name>`_: name of a heightmap
    - `default` (int or str): default value for all heightmap cells (integer or one of `minimal`, `min`, `maximal` or `max`)
- `renderers`: renderers used to generate the map
  - _`<name>`_: name of a renderer
    - `type` (str): type of the renderer
    - additional parameters specific to the given type

2024-09-30 15:17 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        parser.registerRenderer(VectorRendererParams.class, "vector");
Oui, pas faux! (J'avais gardé le même ordre que NamedType)

2024-09-30 15:18 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationParams.java
> +            params.validate();
Oui, je n'ai pas mis parce que `validate()` ne fait rien, mais à y repenser si ça vient à changer ça permet de le pas l'oublier, je vais l'ajouter du coup

2024-09-30 15:19 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/ParamsParserTest.java
> +public class ParamsParserTest {
Roger that (Décidement, j'ai toujours des soucis d'identation sur les tests)

2024-09-30 15:19 UTC, zhak5388 commented on docs/usage/GenerationParameters.md
>  Available fields:
C'est vrai que c'est pas mal!

2024-09-30 15:51 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/renderers/ModelRendererTest.java
> +public class ModelRendererTest {
J'ai fait quelques modification du coup : )

2024-09-30 16:14 UTC, indyteo commented on docs/usage/GenerationParameters.md
>  Available fields:
Du coup tu peux appliquer ce style sur les autres éléments (center, verticalScale...) et tant qu'à faire mettre extendsX et extendsY sur leur propre ligne histoire de lever toute ambiguïté, et expliciter longitude et latitude dans center aussi

2024-09-30 16:18 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/ParamsParser.java
> +     * @throws IllegalArgumentException when provided class is not a subclass of {@code RendererParams}
```suggestion
```

2024-09-30 16:19 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/VectorRendererParams.java
> +            throw new IllegalArgumentException("The fields modelType and heightmap name cannot be empty");*/
```suggestion
```

2024-09-30 16:29 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/renderers/ModelRendererTest.java
> +        assertEquals(0, new ModelRendererImpl(modelStore, "specialCharacter").modelsRendered.size());
C'est sûr que si tu appelles pas `.render()` tu risques pas d'avoir quoi que ça soit de render

2024-09-30 16:29 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/renderers/ModelRendererTest.java
> +        )));
C'est un détail mais si le test échoue à celle ligne, on ne sait pas si c'est parce qu'il manque le modèle 1 ou 2. Alors qu'en découpant, au moins c'est clair :
```suggestion
        assertTrue(renderer.modelsRendered.contains(new ModelImpl('1')));
        assertTrue(renderer.modelsRendered.contains(new ModelImpl('2')));
```

2024-09-30 16:29 UTC, indyteo commented on docs/usage/GenerationParameters.md
>  Available fields:
D'ailleurs il y a une erreur dans la doc, c'est `extendX` et `extendY` et non pas `extendsX` et `extendsY`

2024-10-01 09:19 UTC, zhak5388 commented on docs/usage/GenerationParameters.md
>  Available fields:
J'ai corrigé normalement. Rien à voir, mais je suis en train de me demander si c'est pas une bonne idée d'avoir une manière de marquer les champs optionnels et requis.

2024-10-01 09:25 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/renderers/ModelRendererTest.java
> +        assertEquals(0, new ModelRendererImpl(modelStore, "specialCharacter").modelsRendered.size());
Effectivement :sweat_smile:

2024-10-01 12:52 UTC, indyteo submitted a review, later dismissed

2024-10-01 12:53 UTC, indyteo commented on docs/usage/GenerationParameters.md
>  Available fields:
Oui, on pourra envisager une amélioration de la doc dans une future PR

2024-10-01 13:39 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/ParamsParserTest.java
Je pensais plutôt à des méthodes qui font plusieurs tests (comme on fait ailleurs), surtout quand les tests sont vraiment simples.

2024-10-01 13:47 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/ParamsParserTest.java
Pas sûr que l'ajout de classes imbriqué améliore le code des tests :'(

2024-10-01 14:36 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/ModelSelection.java
> +}
Une fonction statique ne serait-ce pas moins lourde ?

```java
public static Iterator<Model> modelSelection(ModelStore store, String type) {
    return store.getByType(type).iterator();
}
```

2024-10-01 14:51 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/renderers/VectorRenderer.java
> +        ShapesVoxelizer2d voxelizer = voxelizable.voxelize2d(bbox.to2d());
Dans mes renderers, j'ai beaucoup répété ce bout de code.
Il y a pas moyen de simplifier ce truc ?
Genre un `getVoxelizer` dans `ModelRenderer` ?

2024-10-01 15:21 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/VectorRenderer.java
> +        ShapesVoxelizer2d voxelizer = voxelizable.voxelize2d(bbox.to2d());
C'est drôle parce que ce qui va permettre de simplifier ça, c'est précisément ce que tu proposais de retirer dans ton commentaire précédent :laughing: 

En résumé (en réponse aux deux remarques à la fois du coup), le `ModelSelection` est un objet capable de renvoyer des modèles selon un critère. Pour l'instant, le seul critère est le type du modèle, et seule cette classe a été réalisée. Ensuite, d'autres filtres pourront venir, soit définis dans le YAML et donc inclus dans l'objet que le renderer recevra en paramètre, soit définis dans le renderer lui-même (une contrainte technique), et donc le renderer ajoutera ces filtres à l'objet reçu en paramètre.

Exemple concret :
```java
// ModelFilter / ModelSelection
interface ModelFilter extends Iterator<Model> {}
class ModelSelection implements ModelFilter { /* code actuel */ } // Récupère les modèles par type
class ModelFilterByClass implements ModelFilter { // Filtre selon la classe
    ModelFilter origin;
    Class<?> clazz;

    Iterator<Model> iterator() {
        return Iterators.filter(origin.iterator(), model -> model instanceof clazz); // ne compile pas mais tu as compris l'idée
    }
}

// Renderer
class MyRenderer {
    ModelFilter models;

    MyRenderer(ModelFilter models) {
        this.models = new ModelFilterByType(models, MyModel.class);
    }
}
```

2024-10-01 16:34 UTC, zhak5388 commented
Bon, j'ai (re)modifié la classe `ParamsParserTest` ! (En me calquant sur suggestion de Pierre-Yves), j'ai aussi ajouté quelques messages sur mes asserts lorsque l'erreur n'est pas évidente (Par exemple `Absence of the longitude field`)

2024-10-01 16:35 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/models/ModelSelection.java
> +}
Je t'avoue que j'arrive pas à voir ou ça simplifierait

2024-10-02 08:13 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/ModelSelection.java
> +}
Tu vois comment son utilisation du coup ?

2024-10-02 08:15 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/VectorRenderer.java
> +        ShapesVoxelizer2d voxelizer = voxelizable.voxelize2d(bbox.to2d());
Comme dit Théo, ce sera la `ModelSelection` (ou un truc autour) qui fera le job plus tard.

2024-10-02 08:25 UTC, indyteo submitted a review, later dismissed

2024-10-02 09:23 UTC, pyrollo submitted a review, later dismissed

2024-10-07 16:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
> +     * The name of the ground heightmap to use.
Ça ne représente pas forcément le sol
```suggestion
     * The name of the heightmap to use.
```

2024-10-08 06:53 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `heightmapName`: the name of the ground heightmap to use. It must exist.
Je pense qu'on peut garder seulement "heightmap", le fait que ce soit son nom ou id me parait sous-entendu.
```suggestion
- `heightmap`: the name of the ground heightmap to use. It must exist.
```

2024-10-08 06:54 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `heightmapName`: the name of the heightmap to use. It must exist.
Ici aussi je ne mettrais que "heightmap"
```suggestion
- `heightmap`: the name of the heightmap to use. It must exist.
```

2024-10-08 07:00 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        double secondCoordinate,
Pas super convaincu par cette notation : ce serait le seul endroit où l'on aurait un truc du genre (Geotools, JTS et probablement d'autres, font du X/Y). 
Peut être rester sur centerX/Y (on conserve ainsi l'idée de centre) mais mettre dans la description javadoc first/second ? De plus, comme ici on est censé être dans du projeté, on n'aura plus de lon/lat mais pratiquement toujours du x/y carto.

2024-10-08 08:34 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
> +     * The name of the ground heightmap to use.
Copir-coller un peu trop rapide! Il y a une réference de ground dans `HeightmapRenderer` que j'ai corrigé

2024-10-08 08:36 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        double secondCoordinate,
Du coup je suis parti sur ta suggestion!

2024-10-08 09:02 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/VectorRendererParams.java
> +    public String heightmapName;
```suggestion
    public String heightmap;
```

2024-10-08 09:02 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/VectorRendererParams.java
> +     * The name of the ground heightmap to use.
```suggestion
     * The name of the heightmap to use.
```

2024-10-08 09:04 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/VectorRendererParams.java
> +        this.heightmapName = heightmapName;
```suggestion
        this.heightmap = heightmap;
```

2024-10-08 13:18 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +import com.ignfab.minalac.generator.world.VoxelWorld;
```suggestion
import com.ignfab.minalac.generator.utils.world3d.WorldBBox3d;
import com.ignfab.minalac.generator.world.VoxelWorld;

```

2024-10-08 13:20 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        // crsToVoxel.translate(-center[0], -center[1]);
```suggestion
```

2024-10-08 13:20 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +        // voxelToCrs.translate(center[0], center[1]);
```suggestion
```

2024-10-08 13:31 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/ModelSelection.java
> +}
> Je t'avoue que j'arrive pas à voir ou ça simplifierait

C'est au lieu d'avoir un giga truc avec un objet, il y aurait juste une fonction statique.
Mais, j'ai l'impression que ça ne fait pas trop Java ce genre de code

Ca simplifie juste la lecture 🤔

2024-10-08 13:35 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/ModelSelection.java
> +}
> Tu vois comment son utilisation du coup ?

Je ne sais pas si j'ai bien compris, mais comme le code initial mais au lieu de faire `new ModelSelection(...)`, on `import static ....modelSelection;` la fonction pour le mettre en arg d'un Objet ?
Apres, je ne sais pas où la mettre dans le code

2024-10-08 13:37 UTC, pyrollo requested changes
Quelques modifs

2024-10-08 13:55 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/ModelSelection.java
> +}
Une fonction statique ne marche pas car on créé la sélection à un moment (la désérialisation) où il n'y a rien dans le modelStore. Si on fait ça, on va avoir un itérateur vide.

Dans ModelSelection, on embarque les critères de séléction qui seront utilisés plus tard, au moment du rendu, une fois que les modèles seront chargés.

2024-10-08 13:58 UTC, pyrollo submitted a review, later dismissed

2024-10-08 15:12 UTC, pyrollo approved these changes

2024-10-08 15:13 UTC, merged