Add ParamsParser utility classes
ignfab/voxatile pull request #4
Opened 2024-05-03 16:08 UTC by zhak5388

Quelques changements par rapport à la PR initial (je laisse l'ancien texte):
+ Il y a 3 classes `RawParams` (Le pojo), `ParamsParser` (Ancien `GenParamsDeserializer) et `ParseException`
+ C'est le constructeur de `ParamsParser` qui désérialise et vérifie les données. Elle fournit deux méthodes pour créer le `VoxelWorld` et `Generation`
+ Il y a un léger changement sur la structure des parametres : j'ai enlevé `directoryPath` (Vu que c'est la sortie, j'ai l'impression que ça n'a devrait être un paramètre à part. (Par exemple, le fait qu'il soit valide ou pas est liée à l'environnement) En revanche, je pense que ça peut être utile d'avoir le nom de carte en parametre qui servirait pour les metadonnes ou nom du dossier/zip contenant la carte).
+ La conversion des coordonées du centre de lon/lat vers targetCRS se fait temporairement dans `ParamsParser`

Test unitaires et javadoc à venir.

# Structure du yaml
```yaml
# champ optionnel (valeur par défaut 1)
verticalScale: 10.0
# champ optionnel (valeur par défaut 1)
horizontalScale: 1.0
# champs requis
area:
  center:
    latitude: 44.1519
    longitude: 1.7499
  extendX: 1000
  extendY: 1000
# champ optionnel (valeur par défaut 2154, mais amené à detecter CRS mieux adapté)
crs: EPSG:2154
# champ requis
format : minetest
```
# Lancement

```bash
export MINALAC_PARAMS='{"verticalScale":10.0,"horizontalScale":1.0,"area":{"center":{"latitude":44.1519,"longitude":1.7499},"extendX":1000,"extendY":1000},"crs":"EPSG:2154","format":"minetest"}'
```

```bash
mvn package && java -jar ./target/Generator.jar $HOME/.minetest/worlds/minalac
```

# Todo
- [ ] Tests unitaires
- [ ] JavaDoc
- [ ] Penser à vérifier nouvelles instructions de lancement dans`README.md`

# Ancienne description PR
Ajoute les classes nécessaires pour désérialiser les paramètres de génération depuis un `yaml` ou `json`.
+ Il existe des champs obligatoires et optionnels, voir [structure](#structure-du-yaml)
+ La fonction principale est `deserialize(String serialized)` de `GenParamsDeserializer` qui permet de renvoyer l'objet `GenParams` depuis un `String` au format `yaml` ou `json`.
+ Le non respect du format `json` ou `yaml` ou l'absence d'un champ requis entraîne une `StructureGenParamsException`.
+ La non validité des valeurs des champs entraine une `IllegalGenParamsException`.

J'ai modifié `SampleImplementation` pour que les coordonnées du centre soient converties (de EPSG:4326 au CRS fourni). Les paramètres sont maintenant passés via une variable d'environnement.

2024-05-24 10:00 UTC, indyteo requested changes
Globalement je trouve la syntaxe des POJOs (avec constructeur qui répète tous les champs avec les annotations en plus) très lourde, et je pense qu'il y a largement moyen d'alléger la chose.

Du point de vue des tests, pas mal de petites remarques sur des détails, convention ou syntaxe.

Ne pas hésiter à mettre des commentaires pour expliquer des détails techniques du code.

Ajouter un fichier qui documente un exemple de config, avec la signification des champs et les valeurs possibles. (Plus tard : Auto-génération à partir des POJOs avec des commentaires / annotations, voir inspiration exemple dans [indyteo/MinalacCore](https://github.com/indyteo/MinalacCore/blob/master/minalac-annotation-processor/src/main/java/com/ignfab/minalac/processing/ConfigurationValueProcessor.java)).

2024-05-24 10:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParams.java
> +public class GenParams {
À quoi sert cette classe, par rapport au POJO ?

2024-05-24 10:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParamsDeserializer.java
> +    public GenParams deserialize(String json) throws GenParamsDeserializationException {
`json` ? `YAMLFactory` ? Il faut revoir la cohérence globale pour éviter de s'emmêler les pinceaux soi-même

2024-05-24 10:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParamsPOJO.java
> +    public AreaPOJO area;
Je suis mitigé sur l'intérêt de l'imbrication d'objets qui regroupent des paramètres plutôt que de tout mettre à plat. Quand il y a de la redondance (plusieurs morceaux de la config avec le même schéma) oui bien sûr (par exemple ici `layers`) mais là je ne crois pas que ça soit le cas ?

2024-05-24 10:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/exceptions/GenParamsDeserializationException.java
> +    public GenParamsDeserializationException() {
Peut-être ajouter un message par défaut dans ce constructeur ou bien le supprimer pour obliger de spécifier un message.

2024-05-24 10:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/exceptions/GenParamsDeserializationException.java
> +public class GenParamsDeserializationException extends Exception {
Il pourrait être intéressant d'ajouter des constructeurs qui prennent aussi `Throwable cause` en paramètre pour le chaînage d'exception (exemple dans `GenParams` ligne 24, ne pas mettre `e.getMessage()` mais pouvoir passer `e` en entier)

Tu as un super-constructeur dans la classe `Exception` qui gère ça pour toi :
```java
public Exception(String message, Throwable cause)
```

2024-05-24 10:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/exceptions/IllegalGenParamsException.java
> +public class IllegalGenParamsException extends GenParamsDeserializationException {
Mêmes remarques que sur `GenParamsDeserializationException`

2024-05-24 10:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/exceptions/StructureGenParamsException.java
> +public class StructureGenParamsException extends GenParamsDeserializationException {
Mêmes remarques que sur `GenParamsDeserializationException`

2024-05-24 10:00 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParams.java
> +    private static GenParamsPOJO genParamsPOJO;
```suggestion
    private GenParamsPOJO genParamsPOJO;
```

2024-05-24 10:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParamsPOJO.java
> +                         @JsonProperty(value = "area") AreaPOJO area) {
Pourquoi ton constructeur initialise 2 champs de ta classe mais pas les autres ?

2024-05-24 10:00 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParams.java
> +        });
```suggestion
        GenParams genParams = assertDoesNotThrow(() -> new GenParams(genParamsPOJO));

        assertEquals("/home/john/.minetest/worlds/map/", genParams.getDestinationPath());
        assertEquals(3, genParams.getVerticalScale());
        assertEquals(4, genParams.getHorizontalScale());
        assertEquals(5.8, genParams.getCenterLat());
        assertEquals(2.4, genParams.getCenterLon());
        assertEquals(500, genParams.getExtendX());
        assertEquals(2500, genParams.getExtendY());
        assertEquals(epsg5643, genParams.getCrs());
```

C'est la création de l'objet qui ne doit pas faire d'erreur, pas les appels à `assertEquals` (et tes getters ne déclenchent pas d'exception)

2024-05-24 10:00 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParams.java
> +        assertDoesNotThrow(() -> {
Même remarque que tout à l'heure.

Et pourquoi ces tests sont dans `testIllegalCenterLat` ? Puisqu'ils testent des valeurs correctes au contraire, il faudrait séparer dans une autre méthode de test.

2024-05-24 10:00 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParams.java
> +    public void illegalCrs() {
Tester ici avec aussi des valeurs un peu moins absurdes (exemple : `EPSG:2154 ` avec un espace à la fin) qui pourraient être saisies par l'utilisateur et que le code devrait (ou pas ?) gérer.

2024-05-24 10:00 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +    private static GenParamsDeserializer deserializer;
```suggestion
    private GenParamsDeserializer deserializer;
```

2024-05-24 10:00 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +public class TestGenParamsDeserializer {
Beaucoup de remarques identiques par rapport à `GenParamsTest`

2024-05-24 10:00 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +                "}";
Utiliser un [Text Block](https://docs.oracle.com/en/java/javase/17/text-blocks/index.html) ici semble plus adapté

2024-05-24 10:00 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +    public void failureDeserializationAsJson() {
Un string vide ça fait quoi ?

2024-05-24 13:25 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParams.java
> +public class GenParams {
Alors, essentiellement je voyais le POJO comme étant une manière de valider la structure du json ou du yaml (Vérifier si les champs requis ont bien été fournis, si le type des champs est correct et si le json/ou yaml est mal structuré). GenParams est plutôt là pour vérifier si les champs fournis sont bien valides (latitude correcte, échelle positive), initialiser les champs optionnels à leurs valeurs par défaut (échelle à 1 par exemple) et faire d'éventuelle transformation (code epsg en CRS)
**Edit**: typo

2024-05-24 13:25 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParamsDeserializer.java
> +    public GenParams deserialize(String json) throws GenParamsDeserializationException {
Oui, j'ai pas encore trouvé de nom générique pour désigner json et yaml!

2024-05-24 13:26 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParamsPOJO.java
> +                         @JsonProperty(value = "area") AreaPOJO area) {
Essentiellement, c'est le seul moyen que j'ai trouvé pour forcer des champs requis lors d'une [désérialisation](https://github.com/FasterXML/jackson-databind/issues/858). J'utilise le constructeur pour ça avec l'annotation @JsonCreator. J'initialise pas les autres champs via le constructeur car il sont optionnels (et pour éviter d'alourdir l'écriture)

J'ai l'impression d'être passé au travers quelque chose, si il y a une autre manière de faire ça serait bien

2024-05-24 13:26 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParams.java
> +        });
Ah, alors le nom de la méthode est peut-être mal choisi mais je voulais aussi checker que ça a été instancié avec de bonnes valeurs

2024-05-24 13:32 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParamsDeserializer.java
> +    public GenParams deserialize(String json) throws GenParamsDeserializationException {
`serialized`

2024-05-24 14:57 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParamsPOJO.java
> +    public AreaPOJO area;
Ça peut être aussi un moyen de regrouper de la sémantique, comme ici avec area, plutôt que d'avoir les paramètres dans le même sac avec des trucs qui n'ont rien à voir.

2024-05-29 14:46 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParamsPOJO.java
> +    public AreaPOJO area;
Une autre raison, c'est pour éviter une écriture lourde sur le constructeur. (Rendre obligatoire des champs)

2024-05-29 14:47 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/exceptions/GenParamsDeserializationException.java
> +    public GenParamsDeserializationException() {
J'ai fait quelques modifications sur les exceptions, mais je ne suis pas si une bonne manière de faire.

2024-05-29 14:48 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/exceptions/GenParamsDeserializationException.java
> +public class GenParamsDeserializationException extends Exception {
`StructureGenParamsException` prend un `Throwable` maintenant et les deux autres que un message. L'idée c'est que `StructureGenParamsException` est juste une manière d'encapsuler des `JsonProcessingException` donc je voulais avoir le message par défaut. `IllegalGenParamsException` quant à elle est purement custom donc que message

2024-05-29 14:48 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/exceptions/IllegalGenParamsException.java
> +public class IllegalGenParamsException extends GenParamsDeserializationException {
Voir commentaires ci-dessus

2024-05-29 14:48 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/exceptions/StructureGenParamsException.java
> +public class StructureGenParamsException extends GenParamsDeserializationException {
Voir commentaires ci-dessus

2024-05-29 14:49 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParams.java
> +    public void illegalCrs() {
J'ai ajouté des cas de test, mais il y a un truc qui me gêne : c'est la function `CRS.decode()` qui est est chargée de faire la transformation. Donc c'est comme si je testais une méthode d'une librairie. 

Aussi `CRS.decode()` enlève les espaces avant et après le string.

2024-05-29 14:49 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +public class TestGenParamsDeserializer {
J'ai un tour normalement!

2024-05-29 14:50 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +    public void failureDeserializationAsJson() {
Alors, oui, c'était pour vérifier qu'il y a bien une erreur si le `serialized` n'est pas un `json`. J'ai ajouté deux autre cas: champ mal écrit et mauvais type.

2024-05-29 15:39 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParams.java
> +    public void illegalCrs() {
Si c'est la fonction de la librairie qui le fait déjà, c'est bon. Après, il faut documenter que ça utilise cette fonction, et comme ça quelqu'un qui veut les infos sur le format supporté etc, il saura où aller les chercher. Ceci dit, puisqu'on est dans les tests des paramètres de génération, utiliser des entrées réalistes me semble intéressant (à priori, personne va écrire dans la config `"crs": "toto"`, par contre faire une faute de frappe ou autre, ça donne une idée de la tolérence à l'erreur qu'on veut garantir. Si on s'en fiche, on garde effectivement la tolérence fournie par la méthode de la librairie appelée.

En résumé, si on veut garantir que notre méthode fait bien le nécessaire (genre trim les espaces), il vaut mieux le tester, même si c'est fait par la lib, comme ça si la lib change et ne le fait plus, les tests nous le montreront. Ceci dit, pas sûr qu'on veuille garantir ça, je pense qu'on peut très bien se contenter de dire "ça utilise telle lib, donc pour le format, allez voir chez eux"

2024-05-29 15:47 UTC, indyteo commented
Commentaire annexe sur la façon de passer les paramètres. Utiliser une variable d'environnement, pourquoi pas. Utiliser les arguments, pourquoi pas. On pourrait même aussi utiliser un fichier. Par contre, une combinaison de tout ça, là je suis perplexe. Quel est le raisonnement derrière le fait d'avoir une argument, qui contient le nom d'une variable d'environnement, qui contient la configuration ? On dirait un peu un jeu de piste, et en temps normal, j'aime bien les escape games, mais là je ne suis pas convaincu 😄

2024-05-29 22:57 UTC, indyteo requested changes

2024-05-29 22:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            String crsCode = "EPSG:" + CRS.lookupEpsgCode(crs, false);
Question technique géographique : On est sûr de n'avoir que du `EPSG` à gérer ?

2024-05-29 22:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +
`CoordsConverter` ne fait pas déjà ça plus ou moins ? Si ce n'est pas le cas, elle devrait le faire à mon avis

2024-05-29 22:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParams.java
> +public class GenParams {
POJO signifie Plain Old Java Object, c'est à dire un objet Java traditionnel. Ce qui est le cas de cette classe aussi, pour moi il n'y a pas usage d'avoir 2 classes différentes. Surtout quand la structure va prendre de l'ampleur (quand il va y avoir de plus en plus de paramètres et de configuration), ce qui va forcément arriver, on risque de regretter d'avoir tout en double.

Selon moi, la validation du schéma et des données peut être faite par le biais d'une méthode, qui sera appelée une fois que la désérialisation sera terminée, ou éventuellement, automatiquement au fur et à mesure que les données sont désérialisées par la librairie, si c'est possible.

2024-05-29 22:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParams.java
> +    }
Quitte à valider, autant vérifier que c'est pas déjà un fichier existant, et qu'on a la permission d'écrire à cet endroit

2024-05-29 22:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParams.java
> +                throw new IllegalGenParamsException("The field crs from center can not be decoded : " + e.getMessage());
La trace de l'exception `e` est perdue ici

2024-05-29 22:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParamsDeserializer.java
> +public class GenParamsDeserializer {
En réalité, cette classe n'a pas de raison de se limiter à la désérialisation de `GenParams`.

2024-05-29 22:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParamsPOJO.java
> +    public AreaPOJO area;
Pour moi, il peut y avoir des groupements sémantiques dans la structure sérialisée, peut-être sans s'embêter avec cette même structure dans le code (sachant qu'au final, tout est à plat dans `GenParams`... Mais ça c'est quelque chose qui va de pair avec ma remarque sur le doublon de classe entre `GenParams` et `GenParamsPOJO`).

Mais attention, je suis tout à fait pour utiliser des regroupements sémantiques quand c'est utile, par exemple regrouper `centerX` / `centerY` en `Coords2D`, ou aussi plus largement regrouper d'un côté les options relatives à l'input, et de l'autre celles à l'output (et même d'autres groupes si il y a d'autres options, et un groupe global si il y a des options globales (verbose, debug, ...), ou même sous-diviser ces groupes, comme par exemple input coupé en data_source / data_treatment, etc...)

2024-05-29 22:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParamsPOJO.java
> +    //(See setCrs() method of GenParams)
La JavaDoc supporte les références type `@see GenParams#setCrs()`

2024-05-29 22:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParamsPOJO.java
> +    //See https://github.com/FasterXML/jackson-dataformat-xml/issues/625
De même que les liens directs `@see https://github.com/FasterXML/jackson-dataformat-xml/issues/625 Explication de blablabla`

2024-05-29 22:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/exceptions/StructureGenParamsException.java
> +    }
Le but de la manœuvre n'est pas de faire remonter le message d'erreur, qui lui était déjà possible de passer sous forme de String à l'autre constructeur. On veut offrir la possibilité à l'utilisateur de notre Exception de spécifier la cause, et qu'elle soit enregistrée dedans, permettant d'analyser la stack-trace et mieux comprendre ce qui a causé l'erreur (l'enchaînement des appels de méthode qui ont mené à cette situation). Pour ça, qu'une seule solution : faire remonter le `Throwable cause` à travers toute la hiérarchie de constructeurs parents. Et c'est ce qu'il faut toujours faire, parce que perdre une stack-trace est dangereux pour l'analyse du problème.

2024-05-29 22:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/exceptions/GenParamsDeserializationException.java
> +public class GenParamsDeserializationException extends Exception {
Les exceptions sont conçues pour être chaînées, et ce mécanisme est crucial lors de l'analyse d'une stack-trace. Le fait que ça soit une exception custom n'exclu en rien le fait qu'elle puisse être causée par une autre exception. Et si c'est le cas, il est très important de conserver cette cause, car bien souvent, si l'utilisateur veut résoudre le problème et éviter de recevoir l'exception custom, il doit résoudre la cause plutôt.
C'est le cas dans `GenParams` ligne 98, où la stack-trace de la cause `e` est actuellement perdue :
```diff
 try {
     this.crs = CRS.decode(epsgCode);
 } catch (FactoryException e) {
-    throw new IllegalGenParamsException("The field crs from center can not be decoded : " + e.getMessage());
+    throw new IllegalGenParamsException("The field crs from center can not be decoded", e);
 }
```

# Exemple détaillé et raisonnement derrière l'importance de ce choix

Imagine un code complet qui importe des données depuis plusieurs sources (HTTP, fichier local, base de données, ...) puis les traite. Une fonction de supervision (disons `importDataAndApplyTreatment`) reçoit en paramètre une source de données, et un traitement à effectuer. Cette fonction importe les données depuis la source, puis applique le traitement dessus. Elle gère notamment les `DataImportException` qui viennent de la source de données.

En parallèle, le code est fait pour exécuter une suite d'opération quelconque, en orchestrant le travail (parallélisation, chronométrage, statistique de consommation mémoire, ...). Ce code défini donc "une opération" comme une fonction, qui peut `throw` une `OperationFailedException`, pour signifier que ça ne s'est pas passé comme prévu.

Pour pouvoir être intégrée à la pipeline (pouvant réaliser bien d'autres tâches), notre fonction `importDataAndApplyTreatment` est donc considérée comme une opération quelconque, et elle va `throw new OperationFailedException()` si elle reçoit une `DataImportException`.

Imaginons que cette exception custom `OperationFailedException` n'ai pas la possibilité de renseigner une cause. Lorsque l'utilisateur reçoit une `OperationFailedException` lui disant, au mieux, si le développeur a au moins chaîné les messages :
> OperationFailedException: Opération échouée : Erreur à l'import des données : Impossible de charger les meta-données : Lecture du fichier impossible : Le fichier dataset/metadata/special.txt n'existe pas
> Stack-trace:
> - MyCustomOperation.importDataAndApplyTreatment()
> - Pipeline.executeOperation()
> - Main.runPipeline()

Et au pire (si le message d'origine n'est pas conservé) "Opération échouée" fin.
L'utilisateur sera bien embêté pour retracer l'historique du problème, et comprendre comment le code en est arrivé à chercher ce fichier étrange.

Maintenant, imaginons que l'exception custom `OperationFailedException` permette de spécifier la cause. Lorsque l'utilisateur aura l'erreur, il verra plutôt :
<details>
<summary>Voir la stack-trace détaillée</summary>

> OperationFailedException: Opération échouée
> Stack-trace:
> - MyCustomOperation.importDataAndApplyTreatment(), line 29
> - Pipeline.executeOperation(), line 43
> - Main.runPipeline(), line 10
>
> Cause:
> > DatabaseDataImportException: Erreur à l'import des données
> > Stack-trace:
> > - DatabaseDataSource.importData(), line 17
> > - MyCustomOperation.importDataAndApplyTreatment(), line 29
> > - ...
> >
> > Cause:
> > > DataLoadException: Impossible de charger les meta-données
> > > Stack-trace:
> > > - MetadataLoader.loadMetadataFromFile(), line 6
> > > - DatabaseDataSource.readSpecialMetadataFile(), line 40
> > > - DatabaseDataSource.importData(), line 17
> > > - ...
> > >
> > > Cause:
> > > > FileReadException: Lecture du fichier impossible
> > > > Stack-trace:
> > > > - FileReader.&lt;init&gt;(), line 3
> > > > - MetadataLoader.loadMetadataFromFile(), line 6
> > > > - ...
> > > >
> > > > Cause:
> > > > > FileNotFoundException: Le fichier dataset/metadata/special.txt n'existe pas
> > > > > Stack-trace:
> > > > > - File.checkIfFileExist(), line 30
> > > > > - FileReader.&lt;init&gt;(), line 3
> > > > > - ...
</details>

Avec tout ça, on a absolument tout le détail des exceptions qui ont causé successivement les erreurs, bon l'exemple est exagéré et simplifié, mais ça reste réaliste. On peut y voir tous les appels, et par conséquent, si on explore le code dans `DatabaseDataSource` autour de la ligne 17, on y voit :
```java
if (config.isSpecial() && !metadataLoaded) {
    readSpecialMetadataFile();
    metadataLoaded = true;
}
```
Et on comprend que la faute vient de notre config dans laquelle on a renseigné `special = true` par erreur. Pas évident à pister si on n'avait pas le détail pour remonter jusqu'au bout de code en question 😄

Ça nous permet aussi d'avoir les types des exceptions, et au cas où ça ne serait pas visible du premier coup avec les messages, mieux voir ce qu'il s'est passé (comme quoi c'est une `DatabaseDataImportException`, et que c'est bien sur l'import de depuis une base de données et non des fichiers comme on pourrait le croire par le message).

*Toute ressemblance entre mon exemple et MinalacGenerator est une pure coïncidence... Ou pas !*

2024-05-29 22:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/exceptions/GenParamsDeserializationException.java
> +        super("Failed to deserialize the parameters : " + message);
Ce genre de texte rajouté en préfixe est assez bien inutile en fait (car une `GenParamsDeserializationException` est forcément un échec à la désérialisation des paramètres)

2024-05-29 22:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParams.java
> +    public void successInstantiationAndRightValues() {
Mon commentaire précédent au sujet de cette méthode tiens toujours. Relis-le pour bien comprendre la différence avec ce que tu as toi, et si besoin demande-moi une explication plus détaillée.

On dit "successful" d'ailleurs ici, pas "success"

2024-05-29 22:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParams.java
> +        assertDoesNotThrow(() -> {
Pareil partout, la méthode `assertDoesNotThrow` n'est pas utilisée correctement, elle s'utilise comme le `assertThrows`. Pour le nom, peut-être que "valid" plutôt que "legal" serait plus adapté, mais c'est une plus une question de préférence je pense.

2024-05-29 22:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParams.java
> +public class TestGenParams {
Les conventions de nommage ne sont toujours pas respectées ici. On peut décider de se faire nos propres conventions, mais dans ce cas il faut les documenter, et les respecter partout.

Rappel pour Java avec JUnit :
- Classe : `<NomDeLaClasseConcernée>Test` (`GenParamsTest`)
- Méthodes : `test<NomDeLaMéthodeConcernéeOuExplicationDuTest>` (Ici c'est toujours le constructeur qui est testé, donc on choisi des noms explicatifs plutôt : `testValidDirectoryPath`, `testIllegalVerticalScale`, `testUnknownCrs`, ...)

2024-05-29 22:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +public class TestGenParamsDeserializer {
Plusieurs points qui n'ont pas été corrigé dans l'autre classe de test sont toujours présents ici aussi (logique, mais c'est juste pour pas oublier de rapporter les correctifs ici également 😉)

2024-05-29 22:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +                }""";
L'identation dans ce JSON est étrange (la première accolade est indentée d'un niveau de trop)

2024-05-29 22:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +                ---
Ces tirets ne devraient pas être requis, ils sont uniquement lorsque plusieurs documents YAML sont présents dans un même fichier, je me trompe ? Tout ça pour dire, dans un usage réaliste, on met jamais ça.

2024-05-29 22:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +    public void failureDeserializationAsJson() {
Alors oui, c'est très bien pour les autres cas, mais le string vide ? Il cause bien une erreur ? Parce que ça me semble une situation réaliste, le fait qu'on oublie de remplir le fichier de config, mais on l'a créé par exemple, qu'est-ce qu'il se passerait ? Il faut s'assurer qu'il y a bien une exception, et pas un autre comportement bizarre (genre ça ignore et tout est initialisé par défaut, bon je te rassure c'est pas le cas, ça doit bien faire une erreur à mon avis, mais juste ajouter un cas de test pour s'en assurer !)

2024-05-29 23:07 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/exceptions/GenParamsDeserializationException.java
> +    public GenParamsDeserializationException() {
Je t'ai fait une explication détaillée sur les exceptions et l'importance de les enchaîner proprement, on continue la conversation dans l'autre commentaire si nécessaire, je ferme celui-ci et les autres qui parlent des exceptions, à part celui avec la grande explication

2024-05-29 23:12 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParamsPOJO.java
> +                         @JsonProperty(value = "area") AreaPOJO area) {
Aussi surprenant que ça puisse paraître, ça semble être le cas, et c'est un problème connu de la lib : https://github.com/FasterXML/jackson-databind/issues/230

Ça me fait pencher vers la solution de la validation custom de nos objets (de toute façon, on doit bien le faire pour s'assurer que les valeurs des champs sont valides, alors on peut en même temps s'assurer que les champs requis sont présents, et initialiser ceux qu'il manque à des valeurs par défaut en même temps)

2024-05-29 23:13 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParams.java
> +        });
Comme je l'ai dit dans l'autre discussion (je sais pas pourquoi tout à l'heure je pouvais pas répondre ici, bref), ce commentaire est toujours d'actualité. Essaye de comprendre pourquoi, la différence dans le code et la sémantique, et si besoin je te ferais une explication plus détaillée

2024-05-30 08:37 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        Point convertedPoint = (Point) JTS.transform(point, mathTransform);
Verifier si ce n'est pas plus simple avec : https://docs.geotools.org/latest/javadocs/org/geotools/api/referencing/operation/MathTransform.html#transform(org.geotools.api.geometry.Position,org.geotools.api.geometry.Position)

2024-05-30 08:37 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParams.java
> +    public void illegalCrs() {
Je plussoie pour le commentaire et la référence à la lib.
En revanche, pour les tests "toto" me convient parfaitement. Il ne s'agit pas d'imaginer ce qu'un utilisateur va faire mais simplement vérifier que l'information d'erreur est bien transmise. En plus on est presque sûr qu'il n'y aura jamais de CRS nommé "toto".

2024-05-30 09:07 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParams.java
> +public class GenParams {
Ce doit être un problème de nomenclature. POJO a été choisi par défaut. Peut être que RawParam ou un truc du genre serait plus clair : On a un ensemble de structures qui ne représentent que la structure json/yaml, et dont sont issus des objets plus internes (il est probable que GenParams disparaisse pour devenir Generation).

2024-05-30 10:34 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParams.java
> +    public void illegalCrs() {
Oui, si on dit "le décodage du CRS est assuré par la lib" effectivement je suis d'accord que n'importe quel string invalide juste pour s'assurer que l'erreur de la lib est bien traitée, c'est suffisant. La question était plutôt si on voulait garantir la qualité du décodage de notre fonction (et ainsi imposer des contraintes sous la forme de tests qui passent parce que la lib se comporte ainsi, mais qui ne passeraient plus si la lib changeait). Et encore une fois, sur ce sujet, je suis partage l'avis que c'est pas nécessaire, c'était plutôt par principe que je l'évoquais.

2024-05-30 15:23 UTC, pyrollo requested changes

2024-05-30 15:23 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParams.java
> +        }
```suggestion
            this.horizontalScale = (horizontalScale == null)?1:horizontalScale;

            if (this.horizontalScale <= 0)
                    throw new IllegalGenParamsException("The field horizontalScale must be greater than 0");

        }
```

2024-05-30 15:23 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParams.java
> +        setCrs(genParamsPOJO.crs);
Ces méthodes ne servent qu'ici, j'aurais fait un gros constructeur qui valide tout plutôt que d'éclater en plein de méthodes de quelques lignes.

2024-05-30 15:23 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParams.java
> +                throw new IllegalGenParamsException("The field crs from center can not be decoded : " + e.getMessage());
Ici tu peux te simplifier la vie en oubliant l'idée de faire une exception particulière pour l'EPSG-2154. Au besoin, on pourrait avoir une vérification ailleurs pour la base de données (avec un autrre  CRS.decode peut être, rien que pour ça).

Le code pourrait se simplifier en :
```suggestion
            if (epsgCode == null || epsgCode.isEmpty()) {
                //TODO : If not provided its default value should be calculated by finding the appropriated projected CRS for the provided center point.
                // At the moment the default value is EPSG:2154 (France)
                epsgCode ="EPSG:2154";
            }
            try {
                this.crs = CRS.decode(epsgCode);
            } catch (FactoryException e) {
                throw new IllegalGenParamsException("Target CRS could not be decoded : " + e.getMessage());
```

2024-05-30 15:23 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParams.java
> +        if (epsgCode == null || epsgCode.isEmpty()) {
Ça arrive que le CRS soit vide et pas null ?

2024-05-30 15:23 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +    public void failureDeserializationAsJson() {
Des champs étant obligatoires, si Jackson désérialize sans erreur une valeur vide, le problème n'est pas chez nous mais dans la lib. Donc en termes de tests unitaires c'est la lib qu'on testerai, pas notre code.
En revanche, cela aurait du sens dans des tests d'intégration.

2024-05-30 15:23 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +                    "wrongDirectoryPath": "/home/john/.minetest/worlds/map/",
Ici on teste plutôt ce qu'il se passe s'il manque un champ.
Cela peut être intéressant de verifier que les champs requis sont bien en obligatoire mais cela va ête un peu lourd, il faut faire un test distinct par champs requis (EDIT: j'avais pas vu mais c'est déjà fait).

2024-05-30 15:23 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +        String wrongType = """
Si le test ne fonctionnait pas ici, le bug serait du côté de la lib qui ne fait pas son job. Donc ce n'est pas un test unitaire concernant notre code. Cela aurait sa place côte tests d'intégrations.

2024-05-30 15:23 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +    public void missingRequiredFieldDirectoryPath() {
C'est déjà testé par misspelledField.

2024-05-30 15:23 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +    public void optionalFieldVerticalScaleInitializedWhenMissing() {
Tous les optional...InitializedWhenMissing peuvent être rassemblés en un seul test qui check tous les default.

2024-05-30 17:42 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +    public void failureDeserializationAsJson() {
Je vois ça justement comme le cas de test : "désérialisation quand il manque les champs requis => erreur" (qui est différent de "désérialisation impossible car mauvaise syntaxe).
Alors oui je suis d'accord que c'est la même erreur qui est attendue dans les cas de test individuels des champs requis, mais à mon sens ces cas-là valident que le champ est bel et bien requis.
En gros, selon moi, ici on teste que l'erreur renvoyée est bonne, et dans les tests suivants on test que l'absence d'un champ requis renvoie une erreur (et comme le seul test qu'on fait sur l'erreur renvoyée ici, c'est sa présence (et son type), forcément ça paraît redondant...). Bref, dans l'état (parce qu'il y a les suivants et qu'on n'a rien de plus à tester que le type et la présence de l'erreur), on peut le retirer, mais sa présence est justifiée tout autant je trouve

2024-05-30 17:52 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +        String wrongType = """
Ou bien du côté de notre code qui demande un string et pas un double 😉
Ça dépend d'où on veut placer le cursor sur l'exigence de nos tests, mais si on veut tester à 100% notre schéma, il faut s'assurer qu'il y a les bons champs, qu'ils sont bien requis ou optionels, et qu'ils ont les bons types, et éventuellement la bonne valeur par défaut si ils sont optionnels (et je suis d'accord que c'est lourd, et qu'on peut se contenter de valider la présence du champ)

2024-05-30 17:56 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +    public void optionalFieldVerticalScaleInitializedWhenMissing() {
La seule situation qui pourrait nécessiter un cas de test dédié serait des optionels dont la valeur par défaut dépend d'autres champs, éventuellement eux aussi optionnels (exemple : crs qui dépend des coords de center)

2024-05-30 17:59 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
>          String jsonAsString = """
Pour tous les JSON, en général le format c'est :
```json
{
  "key": "value"
}
```
Avec 2 espaces pour l'indentation, et un espace après les `:` et les `,`

2024-05-31 09:38 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParams.java
> +        if (epsgCode == null || epsgCode.isEmpty()) {
Si tu écris dans ta config `"crs": ""`, oui

2024-05-31 09:40 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsdeserializer/TestGenParamsDeserializer.java
> +                    "wrongDirectoryPath": "/home/john/.minetest/worlds/map/",
En revanche, ce que test aussi ce cas indirectement (et qui pourrait avoir son cas de test dédié), c'est le fait qu'un champ supplémentaire non prévu cause (ou non) une erreur

2024-05-31 13:12 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/GenParams.java
> +        if (epsgCode == null || epsgCode.isEmpty()) {
Dans le cas ou le CRS est vide, pour moi ça devrait lever une `IllegalGenParamsException` et non recevoir la valeur par défaut, du coup je corrigerai ça

2024-06-13 16:32 UTC, zhak5388 reviewed
Commentaire à moi-même pour ne pas oublier la `JavaDoc` lorsque structure sera suffisamment stable pour commencer (+ misc du todo) **Edit**: Bon je pensais que je pouvais m'auto-review pour bloquer un merge mais non on dirait (ou alors l'option est cachée haha)

2024-06-14 12:34 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/paramsdeserializer/exceptions/GenParamsDeserializationException.java
> +public class GenParamsDeserializationException extends Exception {
Un peu en retard, mais merci beaucoup pour l'explication!

2024-06-14 13:27 UTC, pyrollo requested changes
Quelques remarques

2024-06-14 13:27 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +     * @param verticalScale   Vertical size of voxel in CRS units
Partout ailleurs on a mis un seul espace après @param. Je ne sais pas s'il faut qu'on passe à cette présentation.

2024-06-14 13:27 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsparser/ParamsParser.java
> +        try {
Si c'est juste pour catcher l'exception  produite par CRS.decode, mieux vaut mettre le try juste à côté.

2024-06-14 13:27 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsparser/ParamsParser.java
> +            MathTransform mathTransform = CRS.findMathTransform(DefaultGeographicCRS.WGS84, targetCrs);
Ici je suis moins sûr de moi, mais j'aurais fait deux blocs d'exception toujours pour n'encadrer que le strict nécessaire.

2024-06-14 13:27 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsparser/RawParams.java
> +@SuppressWarnings("checkstyle:VisibilityModifier")
Il faudrait commenter pour indiquer pourquoi cette suppression.

2024-06-14 13:27 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsparser/RawParams.java
> +    public String format = "minecraft";
Je pense que tu peux le laisser en obligatoire, c'est pas aberrant d'obliger à indiquer le format.

2024-06-14 13:27 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsparser/TestParamsParser.java
> +            """;
Cette variable n'est plus utilisée.

2024-06-14 13:27 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsparser/TestParamsParser.java
> +        assertThrows(ParseException.class, () -> new ParamsParser(jsonAsString));
Tu peux aussi écrire tes tests comme ça, sans variable intermédiaire:
```suggestion
        assertThrows(ParseException.class, () -> new ParamsParser("""
            {
              "verticalScale": 3,
              "horizontalScale": 4,
              "crs": "EPSG:5643"
            }
            """));
```

2024-06-14 13:27 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsparser/TestParamsParser.java
Tu peux ajouter un test quand tout se passe bien pour vérifier.

2024-06-14 13:52 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +import static java.lang.System.getenv;
En général on évite les imports statiques, bon pour `System.exit` ça peut passer, mais c'est pas la partique la plus courante en Java, pour `System.getenv` ça me dérange un peu plus, bon après ça va que la classe `System` est assez bien connue en général, mais je pense que ça n'apporte rien par rapport à un import standard

2024-06-14 13:52 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        String serialized = getenv("PARAMS");
Je serais plutôt d'avis à utiliser un nom un peu plus complet, du genre `MINALAC_PARAMS` ou `MINALAC_CONFIG`

2024-06-14 13:52 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            System.out.println("PARAMS was not set");
(Détail) préciser que c'est une variable d'environnement dont on parle
```suggestion
            System.out.println("PARAMS environment variable was not set");
```

2024-06-14 13:52 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            System.out.println("They must be one argument : directoryPath");
```suggestion
            System.out.println("There must be one CLI argument: directoryPath");
```

2024-06-14 13:52 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        ParamsParser parser = new ParamsParser(serialized);
Il y a un problème dans le nommage quelque part. Si c'est un parser, il doit avoir une méthode pour parse. Là, ça ressemble plus à une factory qui crée des Generation à partir d'un unique modèle de paramètres. Je pense que ce que tu veux faire est plutôt quelque chose comme :
```java
ParamsParser parser = new ParamsParser(/* optional parsing options, like supported formats, error policy (fail fast, best effort, ...), default values... */);
RawParams params = parser.parse(serialized);

Generation generation = new Generation(params);
VoxelWorld world = new VoxelWorld(params);
// or
Generation generation = Generation.createFromRawParams(params);
VoxelWorld world = VoxelWorld.createFromRawParams(params);
// or
Generation generation = rawParams.createGeneration();
VoxelWorld world = rawParams.createVoxelWorld();
```

2024-06-14 13:52 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        CRS.cleanupThreadLocals();
Ça peut être supprimé depuis le temps, c'est un relicat de quand le code était exécuté avec Maven sans l'option `-Dexec.cleanupDaemonThreads=false`

2024-06-14 13:52 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsparser/ParamsParser.java
> +        } catch (FactoryException e) {
Il n'y a que la dernière ligne du `try` qui peut réellement throw un `FactoryException`. Il vaut mieux limiter le bloc à la zone à risque

2024-06-14 13:52 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsparser/ParamsParser.java
> +                throw new ParseException("The provided format is not supported");
J'aurais tendance à faire toutes ces validations dans une méthode dans la classe `RawParams` plutôt. Ça me semble plus intéressant de rassembler les champs et leurs contraintes au même endroit

2024-06-14 13:52 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsparser/RawParams.java
> + * See <a href="https://github.com/FasterXML/jackson-dataformat-xml/issues/625">this issue</a> for more information about required fields during deserialization.
```suggestion
 * @see <a href="https://github.com/FasterXML/jackson-dataformat-xml/issues/625">GitHub issue about required fields during deserialization</a>
```

2024-06-14 13:52 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsparser/RawParams.java
> +    }
```suggestion
    @ConstructorProperties({ "center", "extendX", "extendY" })
    Area(Center center, int extendX, int extendY) {
        this.center = center;
        this.extendX = extendX;
        this.extendY = extendY;
    }
```
Ça s'applique aux autres, et j'ai pas testé mais j'ai trouvé ça dans des issues GitHub en cherchant autre chose

2024-06-14 13:52 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/utils/paramsparser/TestParamsParser.java
> +            """;
C'est quoi ça ?

2024-06-14 13:54 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +     * @param verticalScale   Vertical size of voxel in CRS units
Je pense qu'en règle général on n'a pas besoin d'aligner (c'est un peu lourd et ça n'apporte pas grand chose quand il n'y a que très peu de paramètres), mais on peut le faire quand il y a beaucoup de paramètres, ça peut apporter un peu de lisibilité (et je vois pas de raison particulière de se l'interdire quand ça apporte vraiment quelque chose)

2024-06-14 13:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsparser/ParamsParser.java
> +            MathTransform mathTransform = CRS.findMathTransform(DefaultGeographicCRS.WGS84, targetCrs);
Ça ne me choque pas ici parce qu'il n'y a que 3 lignes et c'est la même unité de travail qui peut échouer (transformer les coordonnées). En revanche, il faut une meilleure gestion de l'erreur que `throw new RuntimeException(e);`, mais ça pourra sans doute être amélioré plus tard

2024-06-14 14:17 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/paramsparser/RawParams.java
> +    }
Oh, c'est super ça!

2024-06-14 14:26 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/paramsparser/ParamsParser.java
> +            MathTransform mathTransform = CRS.findMathTransform(DefaultGeographicCRS.WGS84, targetCrs);
Ici, je me dis que s'il y a pas de `MathTransform` possible forcément il n'y pas de conversion possible (dans l'usage que l'on a je pense)

2024-06-14 14:44 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/utils/paramsparser/TestParamsParser.java
> +            """;
Un espèce de template que je n'ai pas viré :sweat_smile:  (Aussi parce que j'ai pas entièrement fini les tests)

2024-06-14 14:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsparser/ParamsParser.java
> +            MathTransform mathTransform = CRS.findMathTransform(DefaultGeographicCRS.WGS84, targetCrs);
De toute façon vu que c'est du temporaire je ne pense pas que ça soit un problème

2024-06-14 15:56 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        ParamsParser parser = new ParamsParser(serialized);
Oui, le nom est pas parfait. Idéalement j'aimerais que "`ParamsParser`" produise `Generation` et `VoxelWorld`.
```java
ParamsParser p = new ...

Generation generation = p.createGeneration();
```
Et que `RawParams` n'est pas d'autre intelligence autre que la structure et validation des données.

2024-06-14 15:57 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        ParamsParser parser = new ParamsParser(serialized);
Hmm, `ParamsFactory`?
```java
ParamsFactory paramsFactory = new ParamsFactory(serialized);
Generation generation = paramsFactory.createGeneration();
```

2024-06-14 16:01 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +     * @param verticalScale   Vertical size of voxel in CRS units
J'avais utilisé l'alignement dans certaines classes (WritableChunk je pense), j'avais pas réalisé que l'on avait fait un choix explicite. Les deux me vont personnellement.

2024-06-14 16:04 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/utils/paramsparser/TestParamsParser.java
Oui, j'ai d'autres tests à ajouter

2024-06-14 17:21 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        ParamsParser parser = new ParamsParser(serialized);
Non, `ParamsFactory` construirait des `Params`. Pourquoi la logique ne devrait pas être dans `RawParams` ? (C'est une vraie question, dans quel scénario ça pourrait nous embêter ?)

De mon point de vue, je vais proposer la solution que j'ai en tête (dont pas mal d'éléments sont déjà là, mais j'utilise des noms qui me semblent plus appropriés) :
```java
ConfigParser parser = new ConfigParser();
Config config = parser.parseFromString(serialized); // Throws ParsingException
config.validate(); // Throws InvalidConfigException
ObjectCreator.createGeneration(config);
ObjectCreator.createVoxelWorld(config);
```
Globalement `Config` = `RawParams`, `ConfigParser` = `ParamsParser`. J'utilise des méthodes statiques parce qu'on n'a pas vraiment besoin d'instance de `ObjectCreator`, elle n'existe que pour compartimenter le code par responsabilité, mais ne stocke aucune donnée et peut donc être selon moi un simple outil. La création d'un `ConfigParser` (plutôt qu'une méthode statique) est également discutable, mais elle peut rester car on pourrait être amené à utiliser plusieurs fois notre parser (pas dans l'immédiat certes, mais plus tard)

2024-06-18 08:30 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        ParamsParser parser = new ParamsParser(serialized);
Pour ajouter mon grain de sable, je ne suis pas sûr que remplacer "param" par "config" soit le plus adapté. Il s'agit vraiement de paramètres (de la génération) et pas d'une config. Dans la config, j'imagine plutôt les trucs liés à l'environnement d'exécution (chemin de sauvegarde, chemin des évetuelles données locales, etc.). Autrement dit, une config stable pour le générateur et des paramètres différents à chaque génération.

2024-06-18 08:33 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        ParamsParser parser = new ParamsParser(serialized);
J'aime bien l'idée de la classe "ObjectCreator", RawParams reste bête (sont rôle est juste de faciliter l'accès à la structure du json) et ObjectCreator (peut être faut il un meilleur nom ? Mais je vois pas), s'occupe de faire les choses intelligentes.

2024-06-18 08:37 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        ParamsParser parser = new ParamsParser(serialized);
En revanche, le `config.validate()` me parait être un nid à emmerde : ça va être dûr de valider sans dupliquer trop de code des `createXXX()` ou sans trop divisier un code qui pourrait être unifié.
Donc pour reprendre le code de Théo avec mes remarque, j'imagine plutôt ça:
```java
ParamsParser parser = new ParamsParser();
Params params = parser.parseFromString(serialized); // Throws ParsingException
ObjectCreator.createGeneration(params)
ObjectCreator.createVoxelWorld(params);
```

2024-06-18 08:38 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        String serialized = getenv("PARAMS");
Je ne suis pas d'accord, ce n'est pas une config, ça peut être trompeur.

2024-06-18 08:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +        String serialized = getenv("PARAMS");
Au final, il y aura plusieurs moyens de récupérer les paramètres de la génération :
* Par une variable d'environnement (qui pourrait s'appeler `GENERATION_PARAMS`);
* Via un fichier (`-f generation_params.yaml`);
* Via l'entrée standard (peut être pratique pour la dockerisation ?);
* Autre chose ?

2024-06-18 08:47 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/paramsparser/ParamsParser.java
> +                throw new ParseException("The provided format is not supported");
Ça va dépendre des champs. Une partie peut rester proche de RawParam, mais une autre, si elle doit migrer, devrait plutôt migrer vers la création de la génératon. Ici par exemple:
* extendX/extendY > 0 -> effectivement, c'est très raw;
* lon/lat -> entre les deux (est-ce une règle de format ou une logique métier?)
* format -> ça doit aller côté génération car côté json/raw on ne connait pas forcément ce qui doit être fait en fonction de ça (je trouve que ça ressemble à CRS, on ne sait pas a priori quelles sont les valeurs).

2024-06-21 09:31 UTC, closed without merging