Implement rotation
ignfab/voxatile pull request #49
Opened 2024-10-09 07:08 UTC by pyrollo

### Changes

Add ability to rotate generated map around center.

#### Feature description

New parameter `angle` added in generation parameter. It determines the map rotation (in degrees) of the area around the center.

#### Technical changes

Rotation is simply performed by adding a rotation transformation to coordinates converters.

#### Showcase

### Reason

This was a feature in previous version.

### Self-checks

- [x] The code has unit tests associated
- [x] The code has Javadoc Comments associated
- ~~Complex / Unexpected code is explained / justified with a small comment~~
- [x] Relevant documentation inside the `/docs` folder has been updated
- [x] All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)
- [x] Git history is clean (each commit accomplish a single task and describe it accordingly)
- ~~The texts have been proofread (documentation, error messages, logs, comments...)~~

2024-10-09 23:42 UTC, indyteo reviewed
Est-ce qu'il serait possible de faire des tests unitaires sur la rotation ? Enfin oui c'est possible, mais est-ce que ça vaut le coup ? Probablement pour la non-régression, puisqu'en l'état on voit que ça fonctionne, mais pour éviter de casser quelque chose plus tard j'imagine...

Sinon le code est ok (c'est tellement trivial de toute façon)

2024-10-10 15:28 UTC, pyrollo commented
> Est-ce qu'il serait possible de faire des tests unitaires sur la rotation ? Enfin oui c'est possible, mais est-ce que ça vaut le coup ? Probablement pour la non-régression, puisqu'en l'état on voit que ça fonctionne, mais pour éviter de casser quelque chose plus tard j'imagine...

Je me suis posé la question et puis je me suis dit que les tests unitaires étaient déjà faits dans les converters. Du coup je ne sais pas trop.

2024-10-10 15:48 UTC, indyteo commented
Oui, mais tous les tests de converter ont une rotation de 0, il faut juste valider qu'elle est bien prise en compte dans le converter renvoyé par la génération justement ?

2025-02-06 16:23 UTC, esgn requested changes

2025-02-06 16:23 UTC, esgn commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationParams.java
> +        public int angle = 0;
Should we check angle is between -360 and +360 ?

2025-02-06 16:23 UTC, esgn commented on docs/usage/GenerationParameters.md
> +  - `angle` : Clockwise rotation angle around area center (in degrees, optional, default 0)
angle type is not documented. Do we want 0.5 degree ?

2025-02-06 16:23 UTC, esgn commented on examples/minecraft.yaml
>    extendY: 1000
```suggestion
  extentX: 1000
  extentY: 1000
```

2025-02-06 16:29 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +  - `angle` : Clockwise rotation angle around area center (in degrees, optional, default 0)
1 degree is precise enough for anyone.

2025-02-06 16:30 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationParams.java
> +        public int angle = 0;
Mais ce que l'on ne voit pas c'est qu'en mettant 400° la carte fait effectivement un tour + 40°!

En fait je pense que ça n'apporte rien de limiter (voire ça peut être em... pour certains calculs en amont). D'ailleurs ça serait -180/+180 ? ou 0/360 ?

2025-02-06 16:34 UTC, esgn commented on src/main/java/com/ignfab/minalac/generator/parameters/GenerationParams.java
> +        public int angle = 0;
pas reveillé effectivement. Bref ok ne bloquons rien.

2025-02-06 17:09 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +  - `angle` : Clockwise rotation angle around area center (in degrees, optional, default 0)
However I think there is absolutely no difference in the code between handling int or double angles, so I see no reason to disallow it?
Allowing double angle do not require more code, neither any change in existing code, and it also do not prevent using int inside config, so, only pros?

2025-02-07 10:14 UTC, indyteo approved these changes

2025-02-07 10:28 UTC, esgn approved these changes
Pas le temps de retester en local. Parait ok suite aux échanges.

2025-02-07 10:31 UTC, merged