Deserialization du post-processeur "copy" depuis les sources
ignfab/voxatile pull request #57
Opened 2024-10-28 15:47 UTC by naulan-chrzaszcz

### Type of modification

Types:
- Documentation
  - Javadoc Comments
  - Markdown Files
  - Code Comments
- Code
  - processors
    - post
  - parameters
    - processors
      - post
- Tests

### Issue

MINALAC-79

### Changes

La possibilité de désérialiser une liste de post-processeurs depuis les sous elements de `sources` grâce au champ `postProcessors`.
Prise en charge du post-processeur "copy".

#### Feature description

Modification de l'objet `DataSourceParams` pour permettre la prise en charge des `PostProcessor` dans le fichier YAML.

Création de 2 nouvelles classes dans un nouveau dossier au sein du projet, portant le nom de `processors/post` : 
- `MetadataCopyPostProcessorParams.java` : permet de désérialiser un post-processeur "copy".
- `PostProcessorParams.java` : class parent des params des post-processeurs.

Ajout d'un param "copy" dans le fichier `SimpleImplementation`

#### Showcase

```yaml
# ...
sources:
  # ...
  bati:
    # ...
    postProcessors:
      - type: copy
        metadata: hauteur
        to: height
# ...
```

### Reason

Les Post-Processeurs, disparus du fichier `SampleImplementation` où mes renderers #24 en avaient besoin (mais peuvent faire sans). J'ai donc ajouter le support des post-processeurs dans le fichier YAML.

### TODOs

- [x] Ecrire les JavaDocs
- [x] Améliorer l'écriture du code
- [x] Régler les problèmes de code style
- [x] Supprimer les `sout` restants (s'il y'en a)
- [x] Supprimer le fichier `.vscode`
- [x] Améliorer le nom des params dans l'`yaml`
- ~~Tester de mettre PostProcessorParams en interface~~
- [x] Ajouter les champs manquants dans les classes de paramètres créées.
- [x] Mettre des valeurs par défaut aux champs non obligatoire
- [x] Mettre à jour le `/docs`
- [x] Mettre à jour le fichier `minecraft.yaml`
- [x] Le paramètre `failurePolicy` de `MetadataParsePostProcessorParams` non géré
- [x] Faire les tests unitaire des params

### Self-checks

- [x] The code has unit tests associated
- [x] The code has Javadoc Comments associated
- ~~Complex / Unexpected code is explained / justified with a small comment~~
- [x] Relevant documentation inside the `/docs` folder has been updated
- [x] All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)
- [x] Git history is clean (each commit accomplish a single task and describe it accordingly)
- [x] The texts have been proofread (documentation, error messages, logs, comments...)

2024-10-31 10:29 UTC, indyteo requested changes

2024-10-31 10:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/DataSourceParams.java
> +     * Additional processing data steps (optional).
```suggestion
     * Additional data-processing steps (optional).
```

2024-10-31 10:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/DataSourceParams.java
> +    public List<PostProcessorParams> postProcessors;
Si le fait que la valeur puisse être `null` te gêne plus tard, met par défaut une liste vide à la place

2024-10-31 10:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/DataSourceParams.java
> +            : new PostProcessor<?, ?>[0];
Là par exemple si tu as mis une liste vide par défaut, ça facilite pas mal ton code :
```suggestion
        PostProcessor<?, ?>[] postProcessorsArray = new PostProcessor<?, ?>[postProcessors.size()];
        for (int i = 0; i < postProcessors.size(); i++)
            postProcessorsArray[i] = postProcessors.get(i).create();
```
Et je pense que tu aurais intérêt à remplacer ce tableau par une liste (faire le changement dans `DataSource`)

2024-10-31 10:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +    public final Number value;
La valeur par défaut n'est pas seulement un nombre.

Mais effectivement tu risques de te heurter à la question de "comment je désérialise un truc dont je connais pas le type ?", et peut-être que la réponse est simplement de demander le type pour pouvoir le désérialiser... Mais ça reste à expérimenter

Une autre option serait sans doute de ne pas désérialiser (autrement dit, laisser en string), et d'appliquer un parsing comme le `MetadataParsePostProcessor`, mais ça complique aussi (et peut-être inutilement) le code et/ou la config

Utiliser un désérialiseur custom qui prend en compte le type demandé me parait le plus simple au premier abord

2024-10-31 10:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +public class MetadataParsePostProcessorParams<T> extends PostProcessorParams {
Cette classe c'était le piège, parce qu'elle est bien plus compliquée, ça demande un travail supplémentaire pour fournir la fonction de parsing correspondante. Et il va falloir quelque chose de beaucoup plus souple que ça :/

Ceci dit, je propose de l'écarter pour l'instant, retirer la désérialisation de ce post-processeur de cette PR, et du coup en corrélation, mettre la valeur par défaut du `MetadataDefaultPostProcessorParams` en string, du coup pour l'instant rien n'est parsé, donc tu feras le `Integer.parseInt(...)` dans le `BuildingRenderer` à la main, et une future PR introduira ce post-processeur avec le mécanisme qui va bien (et améliorera celui qui met une valeur par défaut par la même occasion)

2024-10-31 10:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataDefaultPostProcessor.java
> +    private final String metadataName;
```suggestion
    private final String name;
```
(Gardons les noms simples, on est dans une classe qui parle de metadata, donc c'est implicite si on dit juste "name" qu'on parle du nom d'une métadonnée)

2024-10-31 10:29 UTC, indyteo commented on examples/default.yaml
> +        to: Integer
(Je sais bien que je t'ai dit de retirer le parsing pour l'instant, donc ça résoud temporairement cette remarque, mais je veux juste que tu réfléchisses à cette question)

Qu'est-ce que tu penses de l'ordre dans lequel tu as mis ces 3 post-processeurs ?
Est-ce qu'il peut y avoir un problème potentiel ?
Pouvait-on faire mieux ?

2024-10-31 10:29 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +        - Additional parameters specific to the given [type](#post-processor-parameters)
Il y a un niveau d'indentation en trop (même problème sur `provider` et `processor` d'ailleurs)

En revanche, c'est un hasard mais dans le cas des `postProcessors`, il faut justement mettre ce niveau d'indentation (donc il n'est pas vraiment en trop), sauf qu'il faut mettre l'étape intermédiaire qui fait apparaître ce niveau :
```suggestion
    - `postProcessors` (optional list): Definitions of post processors to use
      - _List item_:
        - `type`: Type of post processor
        - Additional parameters specific to the given [type](#post-processor-parameters)
```

Ce qui donne :
- `sources`: Sources providing models to render
  - _`<name>`_: Unique name of the source
    - ...
    - `postProcessors` (optional list): Definitions of post processors to use
      - _List item_:
        - `type`: Type of post processor
        - Additional parameters specific to the given [type](#post-processor-parameters)

2024-10-31 10:29 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +## Post Processor Parameters
Par uniformité avec le reste des titres
```suggestion
## Post processor parameters
```

2024-10-31 10:29 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +### Metadata Copy parameters
Pareil, pour uniformiser, seulement la 1ère lettre en majuscule, et on n'a pas répété à chaque fois "parameters" à la fin
```suggestion
### Metadata copy
```

2024-10-31 10:29 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +- `doNotOverwriteExistingTo`: Whether to abort if copy would overwrite existing metadata.
Toujours de l'uniformisation par rapport au reste de la doc
```suggestion
**Extra parameters**:
- `from` (required): Original name of the metadata to copy
- `to` (required): Destination name to store the copied metadata
- `abortIfFromIsAbsent` (optional): Whether to abort if metadata is absent
- `doNotOverwriteExistingTo` (optional): Whether to abort if copy would overwrite existing metadata
```

2024-10-31 10:29 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +Example:
J'ai pas l'impression qu'un exemple individuel sur chaque post-processeur apporte grand chose, si ce n'est allourdir considérablement la doc...

Je pencherais plutôt pour des exemples complets, documentés (avec des commentaires explicatifs dans le YAML), qu'on pourrait référencer depuis la doc (mais ça pourra être fait plus tard, juste je pense il vaut mieux retirer les exemples ici)

2024-11-04 09:34 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +public class MetadataParsePostProcessorParams<T> extends PostProcessorParams {
Dommage que je doit laisser tomber cette classe, car, c'était plutôt "amusant" de faire du générique.
Qu'est-ce qu'il manque ? Le parsing vers un objet qu'on a crée dans le projet ?

Par exemple:
_Une metadonnée dans les sources._
```
{
    # ...
    "dummy": {
        "attr1": 8,
        "attr2": "Something"
    }
    # ...
}
```
Vers un objet ?

2024-11-04 09:40 UTC, naulan-chrzaszcz commented on examples/default.yaml
> +        to: Integer
L'ordre est important dans mon yaml.
Mais, j'avais réfléchi à un système de priorité grâce à une variable dans chaque PostProcessor qu'on crée.
```java
public class MetadataCopyPostProcessorParams extends PostProcessorParams {
    public int priority = 0;
}
```
`0` serai la priorité maximal.
(J'ai l'impression que c'est légèrement bricoler mon système)

Et `DataSources` sera en charge de trier la liste des post processors selon les priorités de chacun.

2024-11-04 09:41 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +    public final Number value;
Yes.
J'ai vu ce post processor uniquement pour mes rendereurs, j'ai oublié d'avoir une vue plus globale.

2024-11-04 09:45 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +public class MetadataParsePostProcessorParams<T> extends PostProcessorParams {
C'est pas un abandon, juste extraire cette classe dans une autre PR pour pouvoir plus facilement merger celle-ci et continuer à travailler sur l'autre (sinon ça va bloquer/ralentir inutilement toute la feature concernant la désérialisation des post-processeurs à cause d'un seul post-processeur)

Concrètemement, la gestion du type / de la fonction de parsing est entièrement à refaire. Je te propose d'emmener cette classe sur une autre PR (en la retirant d'ici), tu peux baser la PR sur cette branche, et ensuite je ferais une review dessus

2024-11-04 10:26 UTC, indyteo commented on examples/default.yaml
> +        to: Integer
L'ordre est important, nous sommes d'accord là dessus.

Je ne suis pas sûr de comprendre l'objectif de ton système de priorité (enfin si j'ai compris, mais je veux que tu l'expliques pour te rendre compte du problème potentiel)

En revanche, avec tes 3 post-processeurs dans l'ordre dans lequel tu les as mis, qu'est-ce qu'il se passe si j'ai une donnée avec un attribut `hauteur` ayant pour valeur `"toto"` ? Comment est-ce que tu peux régler ce problème ?

2024-11-04 10:39 UTC, naulan-chrzaszcz commented on examples/default.yaml
> +        to: Integer
J'avais enlevé (edit: plutôt je l'ai skip) le post-processor qui (je crois) géré si les données étaient bien des Integer (ou autres types).
Mais pour répondre (si j'ai bien compris), si on verifies pas les types des données dans l'attribut `hauteur`, il y aura des erreurs au niveau des autres post-processor à propos des `cast`.
Du coup, faut que je crée aussi un post processor pour verifier ce genre de cas.

2024-11-04 10:44 UTC, pyrollo commented on examples/default.yaml
> +        to: height
J'imaginais quelque chose de plus compact et un peu différent, pour simplifier l'écriture des postProcessors:

```suggestion
    postProcessors:
      - copyMetadata: { from: hauteur, to: height }
      - copyMetadata: { from: aa, to: bb }
      - defaultMetadata: { field: aa, value: 0 }
```
Suffirait de faire une liste de clés / valeurs dont la clé est le type. Ça évite une répétition deu "type:" à chaque fois.

Ensuite, je pense que les opérations sur les metadata font être les plus courante, donc je propose qu'on sous-entende metadata. Donc `copyMetadata` ou `defaultMetadata` deviennent `copy` et `default`. Si besoi, `from` peut devenir metadata` si c'est plus clair. Ce qui donnerai:
```
    postProcessors:
      - copy: { metadata: hauteur, to: height }
      - copy: { metadata: aa, to: bb }
      - default: { metadata: aa, value: 0 }
```

2024-11-04 10:49 UTC, indyteo commented on examples/default.yaml
> +        to: Integer
En t'appuyant sur les options de configuration disponibles dans le `MetadataParsePostProcessor`, est-ce que tu vois une autre solution, sans ajouter un autre post-processeur ?

2024-11-04 10:54 UTC, naulan-chrzaszcz commented on examples/default.yaml
> +        to: Integer
La supprimer grâce a l'attribut `failurePolicy` ?
Par défaut, le post-processor qui parse applique `REMOVE_METADATA` quand ca fail.

2024-11-04 10:55 UTC, naulan-chrzaszcz commented on examples/default.yaml
> +        to: Integer
Ah okay.
Je vois ce que tu veux dire.

2024-11-04 10:55 UTC, naulan-chrzaszcz commented on examples/default.yaml
> +        to: Integer
Faudrait parse avant de mettre une valeur par default
(edit: Excuse moi, j'ai pris un peu de temps)

2024-11-04 10:56 UTC, indyteo commented on examples/default.yaml
> +        to: height
Je ne suis pas contre permettre une syntaxe plus concise (je suis même pour, en fait), mais ça demande un système différent de l'existant pour le gérer (alors que le code qui se base sur `type: ...` existe déjà, via `PolymorphicParams`)

Personnellement, je pense que permettre une syntaxe plus concise serait un travail à faire plus tard (et il y a d'autres situations où on pourrait compacter notre syntaxe actuelle, comme on avait discuté avec les processeurs par défaut, etc.), histoire de pouvoir profiter de la fonctionnalité au plus vite (et améliorer ensuite).

De même pour les clés des types où on pourrait sans mal avoir un système d'alias pour les plus utilisés (comme ceux des metadata par exemple)

2024-11-04 10:59 UTC, indyteo commented on examples/default.yaml
> +        to: Integer
Voilà, gagné. Dans le cas présent, ton modèle se retrouvait à la fin sans attribut `height` (puisque supprimé car échec de parsing). En inversant les 2 derniers post-processeurs, le problème était résolu :)

Tu pourras le rectifier dans l'autre PR du coup ^^

2024-11-04 12:15 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/DataSource.java
> +            uncheckedPostProcessors.add((PostProcessor<Model, ?>) postProcessor);
Plutôt que de remonter le @SuppressWarnings("unchecked") sur toute la méthode, tu peux faire ça:
```suggestion
            @SuppressWarnings("unchecked")
            PostProcessor<Model, ?> uncheckedPostProcessor = (PostProcessor<Model, ?>) postProcessor;
            uncheckedPostProcessors.add(uncheckedPostProcessor);
```

2024-11-04 13:53 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/DataSourceParams.java
> +            .collect(Collectors.toList());
Un `Stream` sera toujours moins performant qu'une boucle. Bon là on s'en fiche vu la taille, c'est négligeable, mais je voulais juste soulever le point pour que tu sois au courant.
```suggestion
        List<PostProcessor<?, ?>> postProcessors = this.postProcessors.stream()
            .map(PostProcessorParams::create)
            .toList();
```

2024-11-05 09:16 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/DataSourceParams.java
> +            .collect(Collectors.toList());
J'ai déjà essayé cette méthode d’écriture mais j'ai eu ce genre d'erreur provenant de mon IDE : 
```
Type mismatch: cannot convert from List<PostProcessor<capture#5-of ?,capture#6-of ?>> to List<PostProcessor<?,?>>
```
J'ai pas chercher plus loin et j'ai essayé une autre manière d’écrire le `toList()`

2024-11-05 09:36 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/DataSourceParams.java
> +            .collect(Collectors.toList());
C'est parce que le `.toList()` utilise une signature légèrement différente effectivement, mais tu peux t'en sortir en changeant le type de `postProcessors` en `List<? extends PostProcessor<?, ?>>` (et du coup même chose sur le paramètre du constructeur de `DataSource`, ça ne change rien d'autre, ça veut juste dire que ta liste peut être une liste de sous-type de `PostProcessor<?, ?>`)

2024-11-05 09:44 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/DataSourceParams.java
> +            .collect(Collectors.toList());
Par contre, je ne savais pas que les streams étaient moins performants qu'une boucle. A l'IUT, ils nous ont forcés avec l'utilisation des streams de partout quand on le pouvait.

2024-11-05 10:04 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/DataSourceParams.java
> +            .collect(Collectors.toList());
Il y a d'autres avantages que les performances, et dans beaucoup de situations comme j'ai dit ici on s'en fiche parce que c'est négligeable, c'était juste pour être au courant. En regardant vite fait sur Internet j'ai cet article (lu en diagonale ça a l'air un peu léger mais ça fait un overview comparatif) : https://www.baeldung.com/java-streams-vs-loops

Et en l'occurrence, si leur but au BUT :upside_down_face: c'était de vous faire découvrir les `Stream`s, c'est logique de vous "forcer" à les utiliser ^^ Ça ne veut pas dire qu'il faut les utiliser partout une fois que vous les avez appris x)

2024-11-05 10:13 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataDefaultPostProcessor.java
> +    private final String metadataName;
Modifier sur la PR #62

2024-11-05 10:13 UTC, naulan-chrzaszcz commented on examples/default.yaml
> +        to: Integer
Modifier sur la PR #62

2024-11-06 10:05 UTC, pyrollo requested changes

2024-11-06 10:05 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `from` (required): Original name of the metadata to copy
```suggestion
- `from` (required): Name of the metadata to copy
```

Et pour harmoniser avec les autres PP, mettre "data", "meta", ou "field" à la place de "from"

2024-11-06 10:05 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `doNotOverwriteExistingTo` (optional): Whether to abort if copy would overwrite existing metadata
Heu... onVaTacherDEviterLesNomsDeChampsARalongeCarCaNAidePasALaLecture.
```suggestion
- `keepExisting` (optional): Whether to abort if copy would overwrite existing metadata
```
L'explication aussi peut se simplifier.
-> + Si "Optional", faut indiquer ce qu'il se passe quand on ne le met pas.

2024-11-06 10:05 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `abortIfFromIsAbsent` (optional): Whether to abort if metadata is absent
abort what ?

2024-11-06 10:05 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +**Type**: copyMetadata
Je propose de ne pas mettre "Metadata" partout.
```suggestion
**Type**: copy
```

2024-11-06 12:55 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +- `abortIfFromIsAbsent` (optional): Whether to abort if metadata is absent
J'ai ecrit a la place : `When set, the copy operation is aborted if the metadata is missing`

2024-11-06 12:56 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +    public final Number value;
Fichier mis à jour sur la PR #62

2024-11-07 14:05 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `abortIfFromIsAbsent` (optional): Whether to abort if metadata is absent
Je sais que @indyteo ne voulait pas inverser le booléen, mais ça me parait infiniment plus clair de mettre `overwrite` et `erase` avec default False.

D'ailleurs, il manque toujours le comportement par défaut puisque ces champs sont optionels.

2024-11-07 14:20 UTC, pyrollo requested changes
Des remarques sur la documentation

2024-11-07 14:20 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `keepExisting` (optional): Whether to abort if copy would overwrite existing metadata
Champs optionels -> manque l'indication de ce qu'il se passe si absent (le lecteur ne peut deviner).

2024-11-07 14:20 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +      - _List item_:
On a une liste ici ?

2024-11-07 14:20 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +      - _List item_:
Ici aussi ?

2024-11-07 14:20 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +A post-processor is responsible for altering models so they can comply with renderers requirements.
```suggestion
A post-processor alters models so they can comply with renderers requirements.
```
Eviter les "responsable de", "permet de" qui ne veulent pas dire grand chose.

2024-11-07 14:20 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +Post-processor copying a metadata into another, effectively adding a new one with a new name and the same value.
```suggestion
A post-processor copying a metadata into another, effectively adding a new one with a new name and the same value.
```
J'enlèverais même la suite (copier c'est effectivement créer une seconde instance avec la même valeur, c'est la définition du mot):
```suggestion
A post-processor copying a metadata into another.
```

2024-11-07 14:20 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `keepExisting` (optional): Whether to abort if copy would overwrite existing metadata
```suggestion
- `keepExisting` (optional): Do not overwrite existing metadata
```

2024-11-07 15:33 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +- `abortIfFromIsAbsent` (optional): Whether to abort if metadata is absent
À la base, je voulais conserver les booléens dans le sens dans lequel ils étaient utilisés (mais dans le code, au niveau du post-processeur). Il se trouve que Naulan ayant recopié mot pour mot les paramètres "orientés code", je suis d'accord que ça n'est pas très "orienté utilisateur" du coup (mais je n'ai rien fait dans ce sens, quand on en avait discuté c'était exclusivement à propos du code).

Je suis d'accord qu'il est intéressant de trouver de meilleurs noms, et si possible je favoriserait une valeur par défaut "false" (comme un flag, absent/défaut = false, et on l'ajoute pour mettre à true), mais si ça entâche trop la compréhension pour l'utilisateur, je ne suis pas du tout contre l'inverser dans les params. Dans ce cas la classe de params fait l'interprétation de la valeur "orientée utilisateur" et la transforme en valeur "orientée code" (par exemple l'inverser si nécessaire).

En revanche je ne vois pas le rapport entre le fait d'échouer si on essaye de copier du vide et "overwrite" ou "erase" ?

EDIT : En relisant le code j'ai compris, c'est pas un échec mais un "ignorement", ce qui supprime ou non la destination déjà existante si la source ne l'était plus, d'où "erase" (mais ça me paraît un peu vague comme mot, il faudrait préciser à mon sens)

2024-11-07 15:41 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/DataSource.java
> +        List<PostProcessor<Model, ?>> uncheckedPostProcessors = new ArrayList<>();
Tu peux mettre directement la liste au bon endroit, après par uniformité du code on peut décider de laisser dans des variables temporaires ici et faire les assignations définitives en dessous comme c'est le cas actuellement, c'est toi qui voit.
```suggestion
        this.postProcessors = new ArrayList<>();
```

2024-11-07 15:47 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
> +        assertDoesNotThrow(() -> params.create());
```suggestion
        assertDoesNotThrow(params::create);
```
Je ne sais pas vous, mais moi je trouve ce test assez stupide... Je dis pas ça contre toi Naulan pas de panique, c'est plutôt notre envie de faire des tests unitaires sur ce genre de chose (les classes de params) que je critique. Je n'ai pas l'impression que ça apporte quoi que ça soit d'utile en fait...
On test une factory là

2024-11-08 06:44 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `abortIfFromIsAbsent` (optional): Whether to abort if metadata is absent
Pour l'instant la doc ne parle pas d'échec mais d'"abort" (donc pas forcément avec erreur). Sans erreur, ne rien faire si la destination existe, est l'équivalent de l'inverse d'"overwrite". En revanche, si l'"abort" génère une erreur, mieux vaut utiliser "fail" qui est plus clair.

EDIT: Je viens de voir ton edit, le problème est donc quelque part dans le terme "abort" :)

2024-11-08 06:54 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
> +        assertDoesNotThrow(() -> params.create());
Je suis partagé. Effectivement tu as raison sur le peu d'intérêt du test en lui même mais il a au moins le mérite de couvrir cette partie là et de s'assurer qu'on y fera pas de bêtises plus tard.

Tout seul dans son fichier c'est effectivement un peu idiot. Mais s'il y avait d'autres tests, je trouverais que cela ne mange pas de pain. 

Or, ici, ce ne serait pas mal de tester ce qu'il se passe si on met des `null` dans les paramètres obligatoires et vérifier que cela se comporte comme prévu (encore faut il avoir prévu quelque chose :) ).

2024-11-08 06:56 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/DataSource.java
> +        List<PostProcessor<Model, ?>> uncheckedPostProcessors = new ArrayList<>();
Je suis pour ! (la liste temporaire n'apporte pas grand chose)

2024-11-08 09:34 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
> +        assertDoesNotThrow(() -> params.create());
J'ai un doute, quand un paramètre obligatoire est `null` (absent ou explicitement `null` dans le YAML), est-ce que Jackson appelle quand même notre constructeur avec cette valeur `null`, ou bien il génère l'erreur lui-même ? Dans le cas de la 1ère option OK pour le tester (mais il faut du coup le gérer dans le code), en revanche si c'est la 2ème option, tester un comportement qui ne se produira pas en utilisation nominale (puisqu'on n'instancie pas des classes de params à la main), je vois pas l'intérêt

2024-11-12 14:06 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `keepExisting` (optional, `yes`/`no`): Do not overwrite existing metadata. By default, any existing metadata in the target field will be overwritten.
Ça marche comme ça, mais tu pouvais simplement dire:
```suggestion
- `keepExisting` (optional, `yes`/`no`, default `no`): Do not overwrite existing metadata.
```

Ou, pour être plus précis:
```suggestion
- `keepExisting` (optional, default `no`): `no` to overwrite existing data, `yes` to keep existing metadata.
```

2024-11-12 14:11 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `abortIfMetadataIsAbsent` (optional, `yes`/`no`): When set, the copy operation is aborted if the metadata is missing. By default, the copy proceeds even if the metadata is absent.
Ici aussi, proposition alternative:
```suggestion
- `abortIfMetadataIsAbsent` (optional, default `no`): `yes` to abort copy operation if the metadata is missing, `no` to ...
```
(j'avoue que je n'ai pas compris ce qu'il se passait si on met `no` et que la metadonnées est absente. Ça copie quoi ?)

2024-11-13 10:37 UTC, naulan-chrzaszcz commented on examples/default.yaml
> +        to: height
Ticket créé dans Jira ( MINALAC-82 )

2024-11-13 10:48 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/DataSource.java
> +            @SuppressWarnings("unchecked")
Changement à rollback (le commentaire porte bien exclusivement sur la présence de l'annotation)

2024-11-13 10:48 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/DataSource.java
> +            postProcessors.add(uncheckPostProcessor);
Attention, tu viens d'introduire un méchant bug

2024-11-13 12:17 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/generation/DataSource.java
> +            postProcessors.add(uncheckPostProcessor);
Oh l'erreur de débutant :skull:

2024-11-13 12:34 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
> +        assertDoesNotThrow(() -> params.create());
Dans la version actuel, le post-processeur "fonctionne" même avec des champs à `null` (il renomme `null` en `null` ou `null` en quelque chose et inversement).
J'pense que c'est interresant de mettre la fonction `validate` pour ne pas accepter les valeurs `null` ?

2024-11-13 12:34 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/generation/DataSource.java
> +            postProcessors.add(uncheckPostProcessor);
Normalement, c'est corrigé.

2024-11-13 12:35 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +- `abortIfMetadataIsAbsent` (optional, `yes`/`no`): When set, the copy operation is aborted if the metadata is missing. By default, the copy proceeds even if the metadata is absent.
Je ne sais pas si mon ajout est suffisant pour resolve cette conversation.

2024-11-13 12:59 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/DataSource.java
> +            PostProcessor<Model, ?> uncheckPostProcessor = (PostProcessor<Model, ?>) postProcessor;
Y-a-t-il une raison pour avoir dupliqué le code ?
(je regarde vite fait d'un oeil entre deux chapitres de ma formation)

2024-11-13 13:05 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/generation/DataSource.java
> +            PostProcessor<Model, ?> uncheckPostProcessor = (PostProcessor<Model, ?>) postProcessor;
Pas vraiment, c'est résolu

2024-11-13 13:12 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
> +        assertDoesNotThrow(() -> params.create());
Donc malgré la présence du constructeur, Jackson accepte que la valeur soit absente (et il met `null` par défaut) ?

2024-11-13 13:19 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
> +        assertDoesNotThrow(() -> params.create());
Oui, il accepte avec aucune valeur (`metadata: ` et `to: `).
Les valeurs sont bien `null` (confirmé avec un sout dans copy params lors du create)

2024-11-13 13:33 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
> +        assertDoesNotThrow(() -> params.create());
Donc dans ce cas il faut effectivement écrire une méthode pour la validation, et des tests associés. Cependant, il n'y a pas une façon intégrée à la librairie ? Quelque chose du style `@JsonRequired` à mettre sur le champ et qui provoquerait une erreur si il est absent ou `null` ? (Peut-être que non, mais ça me surprend car ça parait être un besoin assez élémentaire)

2024-11-13 13:45 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
> +        assertDoesNotThrow(() -> params.create());
`@JsonSetter(nulls = Nulls.FAIL)` ?
Ça fonctionne avec cette annotation (j'ai une exception levée).

2024-11-13 14:01 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
> +        assertDoesNotThrow(() -> params.create());
Par contre, cela ne fonctionne pas pour un `String` vide.

Edit : Après quelques recherches, je n'ai pas trouvé de solution native. Il y a des `@NotBlank` qui traînent sur StackOverflow ou des deserializers personnalisés, mais pas de vrai truc concret. 
Là, je suis parti pour écrire la fonction `validate` juste pour vérifier si les champs sont vide ou contient uniquement des espaces blancs.

2024-11-13 14:35 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `abortIfMetadataIsAbsent` (optional, `yes`/`no`): When set, the copy operation is aborted if the metadata is missing. By default, the copy proceeds even if the metadata is absent.
C'est toujours un peu compliqué mais c'est un peu plus compréhensible.

2024-11-13 14:39 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
> +        assertDoesNotThrow(() -> params.create());
Ok après tout on pourrait imaginer que le validate vérifie d'autres contraintes si il y en avait (exemple : si on voulait blacklister un nom de métadonnée pour un usage "réservé"... bon on ne fera pas ça, mais ça montre que de toute façon on fini sur une méthode custom)

2024-11-13 14:39 UTC, pyrollo commented
Deux remarques à résoudre avant de valider:

Il faudrait faire un seul commit. Si le découpage en commit a du sens, il n'est pas strictement nécessaire et ne me semble pas parfaitement fait (le premier commit met à jour la doc alors qu'on ne peut pas utiliser le post-processeur). Donc le mieux est d'en faire un seul.

Il faut vérifier ces points avant de pouvoir fusionner:
- [ ] All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)
- [ ] The texts have been proofread (documentation, error messages, logs, comments...)

2024-11-13 14:47 UTC, naulan-chrzaszcz commented
> Deux remarques à résoudre avant de valider:
> 
> Il faudrait faire un seul commit. Si le découpage en commit a du sens, il n'est pas strictement nécessaire et ne me semble pas parfaitement fait (le premier commit met à jour la doc alors qu'on ne peut pas utiliser le post-processeur). Donc le mieux est d'en faire un seul.
> 
> Il faut vérifier ces points avant de pouvoir fusionner:
> 
>     * [ ]  All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)
> 
>     * [ ]  The texts have been proofread (documentation, error messages, logs, comments...)

C'est normal que j'ai modifier la documentation sur mon premier commit car les modifications apporté permet de supporter les post-processeurs (j'ai mis une base dans la documentation pour les ajouts futur, comme pour le commit suivant).
Et avoir une base qui ne bouge pas pour #62

2024-11-13 14:56 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
> +        assertThrows(IllegalArgumentException.class, () -> new MetadataCopyPostProcessorParams("", "").validate());
```suggestion
        assertDoesNotThrow(new MetadataCopyPostProcessorParams("toto", "tata")::validate);
        assertThrows(IllegalArgumentException.class, new MetadataCopyPostProcessorParams("toto", "")::validate);
        assertThrows(IllegalArgumentException.class, new MetadataCopyPostProcessorParams("", "tata")::validate);
        assertThrows(IllegalArgumentException.class, new MetadataCopyPostProcessorParams("", "")::validate);
```

2024-11-13 15:21 UTC, pyrollo commented
> C'est normal que j'ai modifier la documentation sur mon premier commit car les modifications apporté permet de supporter les post-processeurs (j'ai mis une base dans la documentation pour les ajouts futur, comme pour le commit suivant). Et avoir une base qui ne bouge pas pour #62

Ok, je n'avais pas vu dans le bon ordre. Reste les deux points à vérifier.

2024-11-13 16:13 UTC, indyteo commented
Comme je suis gentil, j'ai relu les textes et c'est bon pour moi. Le correcteur orthographique de l'IDE n'a rien trouvé non plus

2024-11-14 14:20 UTC, pyrollo requested changes
Je ne capte pas trop l'intérêt du changement pour lequel tu demande la revue (je n'ai vu que l'ajout d'un "else" inutile).

Il reste toujours les conversations non résolues (en particulier sur les tests) et les deux points non cochés. Tu peux t'occuper de ça avant de demander une nouvelle revue ?

2024-11-14 14:20 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
> +        else if (to.isBlank())
```suggestion
        if (to.isBlank())
```

2024-11-14 15:49 UTC, naulan-chrzaszcz commented
> Je ne capte pas trop l'intérêt du changement pour lequel tu demande la revue (je n'ai vu que l'ajout d'un "else" inutile).
> 
> Il reste toujours les conversations non résolues (en particulier sur les tests) et les deux points non cochés. Tu peux t'occuper de ça avant de demander une nouvelle revue ?

Normalement c'est ok

2024-11-14 15:55 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
> +    }
Avec `@JsonSetter(nulls = Nulls.FAIL)`, c'est toujours nécessaire d'avoir ce constructeur ? Au final, à quoi il sert puisque je croyais (et d'après son commentaire aussi) que son but était de vérifier que les paramètres obligatoires étaient présents, sauf que désormais l'annotation le fait toute seule, non ? Donc on peut simplifier en l'enlevant ?

2024-11-15 08:02 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
> +    }
A tester, peut être que l'annotation indique qu'on ne peut mettre null dans la valeur si le champ est présent mais sans obliger à mettre le champ. @zhak5388 a probablement déjà exploré ça.

2024-11-15 08:04 UTC, pyrollo commented
> Normalement c'est ok

Je ne suis pas sûr que cela soit correct :
- ~~All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)~~

Indice : Dans l'onglet "Changed Files" on voit des modifs sur les exemples, on peut légitimement se demander si tu as bien vérifié que ça fonctionne toujours.

2024-11-15 08:46 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
> +    }
ça a l'air d'être ça. La doc indique une vérification seulement sur la valeur.

Ici une discussion sur les champs requis : https://stackoverflow.com/questions/13756540/jackson-required-property

2024-11-15 08:47 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
> +        assertThrows(IllegalArgumentException.class, new MetadataCopyPostProcessorParams("", "")::validate);
Ce test là me semble être un cas particulier du précédent. Autrement dit, il réussi à tout les coups si le précédent réussit.

2024-11-15 09:52 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
> +    }
Ah j'ai compris, oula oui c'est vraiment mal fait... Ça donne envie d'écrire un petit bout de code avec une annotation pour générer automatiquement ce constructeur, sauf que c'est pas aussi simple qu'une macro Rust malheureusement :(

2024-11-15 09:55 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
> +    }
J'avais testé hier, et l'erreur est bien plus clair avec l'annotation `ConstructorProperties`.
Il nous dit qu'il manque un champs, alors que sans l'annotation c'est : "je ne peux pas construire l'objet"

2024-11-15 11:05 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
> +    }
C'est indiqué "par design" quelque part. L'idée est probablement de dire que le job de Jackson est de faire correspondre une structure fichier à une structure mémoire mais sans la valider. Ça doit être une histoire comme ça.

2024-11-15 13:57 UTC, naulan-chrzaszcz commented
> > Normalement c'est ok
> 
> Je ne suis pas sûr que cela soit correct :
> 
>     * ~All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)~
> 
> 
> Indice : Dans l'onglet "Changed Files" on voit des modifs sur les exemples, on peut légitimement se demander si tu as bien vérifié que ça fonctionne toujours.

Je beug pour savoir comment bien remplir ce markdown

2024-11-15 14:34 UTC, pyrollo commented
> Je beug pour savoir comment bien remplir ce markdown

Ce n'est pas si compliqué que ça: à chaque point tu doit te poser la question de si tu es concerné ou pas. Et si tu l'es, tu dois faire l'action et cocher la case ensuite. Au final, ta PR n'est ok que s'il ne reste rien à cocher.

Ici par exemple:
- [ ] All examples in docs/usage/Examples.md work the same (or have been adapted if subject to changes in this PR)

Cela signifie "je dois tester que les exemples fonctionnent toujours et ont bien été mis à jour". Si tu penses ne pas être concerné tu barres. Sinon tu vérifies et tu coches seulement si tu as vérifié.

2024-11-20 08:09 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
> + * Represents the parameters used for {@link MetadataCopyPostProcessor} creation.
RIen d'obligatoire, mais "Represents" n'apporte rien ici.
La version suivante, expurgée des mots qui n'apportent pas grand chose, me semble tout aussi compréhensible:
```suggestion
 * Parameters for {@link MetadataCopyPostProcessor}.
```

2024-11-20 08:09 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
> +     * The original name of the metadata to copy (required).
```suggestion
     * Name of the metadata to copy (required).
```

2024-11-20 08:10 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
> +     * The destination name to store the copied metadata (required).
```suggestion
     * Name of copied metadata (required).
```

2024-11-20 09:15 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
> +     * Whether to abort if copy would overwrite existing metadata (optional).
```suggestion
     * Whether to keep existing metadata or not (optional).
```

2024-11-20 12:20 UTC, indyteo reviewed
Plus une remarque qu'autre chose : Sinon si c'est bon, ça me convient

2024-11-20 12:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/DataSourceParams.java
> +    public void validate() throws IllegalArgumentException {
Les providers et processors params n'ont pas de validation ?

2024-11-20 12:45 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/DataSourceParams.java
> +    public void validate() throws IllegalArgumentException {
Ouaip, aucune fonction de validation ecrite.

2024-11-20 13:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/DataSourceParams.java
> +    public void validate() throws IllegalArgumentException {
Aucune n'a été codée mais j'ai vérifié, il y en a bien une (puisqu'ils héritent de `PolymorphicParams`) ! Donc je serais d'avis de l'appeler ici, histoire qu'on ne se fasse pas avoir en pensant qu'elle est appelée alors que non le jour où on en implémente une sur l'un des providers / processors

2024-11-20 14:54 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/DataSourceParams.java
> +    public void validate() throws IllegalArgumentException {
Done

2024-11-20 15:10 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/PostProcessorParams.java
> + * Represents the parameters of a type of {@link PostProcessor}.
```suggestion
 * Parameters for {@link PostProcessor}.
```

2024-11-20 16:42 UTC, pyrollo submitted a review, later dismissed

2024-11-20 17:25 UTC, indyteo requested changes

2024-11-20 17:25 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
Il ne faut pas déclarer les champs comme `final`

2024-11-21 08:31 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
Je me demandais du coup comment faire apparaitre ça dans les tests sans faire du tests de jackson.

2024-11-21 08:32 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
Je me réponds à moi même:
Peut être faire apparaitre les champs optionels dans un example.yaml suffit à vérifier que ça marche.

2024-11-21 09:58 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
Je confirme que le `final` flingue la désérialisation, j'avais pas testé correctement...

2024-11-21 09:58 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
J'ai écrit un test supplémentaire pour vérifier si la désérialisation se fait correctement.
Edit : Bon, malheuresement ca test un peu `jackson` mais tant pis

2024-11-21 10:35 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
Oui mais du coup, là on voit bien que ce n'est pas inutile de tester ça.

2024-11-21 10:40 UTC, pyrollo commented
Ça me parrait bon comme ça.

Pas tout à fait sûr de l'effet du final sur les champs obligatoires, je ne sais pas si cela peut arriver qu'une désérialisation tente de les modifier a posteriori ou si, au contraire, c'est bien comme ça.

A voir avec @indyteo

2024-11-21 11:05 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
Okay, je supprime donc l'ajout inutile ?

2024-11-21 16:05 UTC, indyteo commented
En théorie ça devrait pas changer grand chose puisque Jackson va utiliser le constructeur, et ne devrait pas les modifier ensuite, mais je pense que ça n'a aucune valeur ajoutée de les déclarer en `final`. Je suis plutôt d'avis de ne déclarer aucun champ final dans les classes de params, pour la simplicité et la claretée du code (ces champs ne sont pas fondamentalement différents des autres, juste qu'ils n'ont aucune valeur par défaut, et sont ainsi obligatoires)

2024-11-21 17:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
Les tests ? Je disais justement qu'ils ne sont pas inutiles. Donc à garder (on voit bien que ça sert)

2024-11-21 17:41 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
Peut être même qu'on peut généraliser ce genre de tests qui permettent de vérifier que la doc ne dit pas de conneries: Un test avec juste les champs obligatoires, un autre avec tous les champs possibles.

2024-11-21 20:07 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
> Les tests ? Je disais justement qu'ils ne sont pas inutiles. Donc à garder (on voit bien que ça sert)

Je crois que tu l'as perdu avec ton "pas inutile" 😄

2024-11-21 20:38 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
🥴

2024-11-27 17:04 UTC, pyrollo submitted a review, later dismissed

2024-11-27 17:06 UTC, pyrollo commented
La PR me semble assez mure pour fusionner. @indyteo ne manque plus que ton approval :)

2024-11-27 20:05 UTC, indyteo reviewed
Dernier correctif

Je viens de tilter aussi, on s'embête à mettre `@SuppressWarnings("checkstyle:VisibilityModifier")` sur toutes les classes de params, mais on pourrait juste désactiver le check sur le package... 🙃 Je fais une PR

De manière similaire, juste à réfléchir comme ça pour la suite, on a pas moyen de dire à Jackson "par défaut `@JsonSetter(nulls = Nulls.FAIL)`, et autre chose si spécifié explicitement" ?

2024-11-27 20:05 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
> +        });
Sinon tu assert tes asserts
```suggestion
        MetadataCopyPostProcessorParams params = assertDoesNotThrow(() -> mapper.readValue(requiredFields, MetadataCopyPostProcessorParams.class));
        assertEquals("hauteur", params.metadata);
        assertEquals("height", params.to);
        assertFalse(params.abortIfMetadataIsAbsent);
        assertFalse(params.keepExisting);
```

2024-11-27 20:05 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
> +        });
```suggestion
        MetadataCopyPostProcessorParams params = assertDoesNotThrow(() -> mapper.readValue(requiredAndOptionalFields, MetadataCopyPostProcessorParams.class));
        assertEquals("toto", params.metadata);
        assertEquals("tata", params.to);
        assertTrue(params.abortIfMetadataIsAbsent);
        assertTrue(params.keepExisting);
```

2024-11-28 08:24 UTC, pyrollo commented
> Je viens de tilter aussi, on s'embête à mettre `@SuppressWarnings("checkstyle:VisibilityModifier")` sur toutes les classes de params, mais on pourrait juste désactiver le check sur le package... 🙃 Je fais une PR

Le problème c'est que l'on n'a pas que des classes de param dans le package si tu mets ça au niveau "param".

> De manière similaire, juste à réfléchir comme ça pour la suite, on a pas moyen de dire à Jackson "par défaut `@JsonSetter(nulls = Nulls.FAIL)`, et autre chose si spécifié explicitement" ?

C'est là que pouvoir mettre ça au niveau package serait adapté mais je n'ai pas vu si c'était possible.

2024-11-29 10:13 UTC, indyteo approved these changes

2024-11-29 10:14 UTC, merged