feat(input): Add GeoPackage and Shapefile data providers
ignfab/voxatile pull request #59
Opened 2024-10-28 23:15 UTC by indyteo

### Type of modification

- Code
  - Inputs
- Documentation
  - Javadoc Comments
  - Markdown Files

### Changes

Add two new data providers: GeoPackage & Shapefile

#### Feature description

This PR adds two data providers based on GeoTools. They both rely on the `DataStore` class, and the `GeoToolsDataStoreProvider` is an abstract class created to reduce code duplication.

The `GeoPackageDataProvider` reads features `typeName` from a `.gpkg` file.

The `ShapefileDataProvider` reads features from a `.shp` file and its supporting files.

They are both fully compatible with `GeoToolsVectorProcessor` and can be interchanged with `WFS1_1_GML3_1_DataProvider`.

#### Technical changes

`gt-geopkg` are GeoPackage bindings for GeoTools.
`gt-shapefile` are Shapefime bindings for GeoTools.

### Reason

Having GeoPackage files may help with integration testing, and some data sources are only available as GeoPackage or Shapefile download.

### Self-checks

- ~~The code has unit tests associated~~
- [x] The code has Javadoc Comments associated
- ~~Complex / Unexpected code is explained / justified with a small comment~~
- [x] Relevant documentation inside the `/docs` folder has been updated
- [x] All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)
- [x] Git history is clean (each commit accomplish a single task and describe it accordingly)
- [x] The texts have been proofread (documentation, error messages, logs, comments...)

2024-12-02 09:19 UTC, pyrollo requested changes
"Juste" une grosse question sur l'utilité du paramètre CRS qu ne me semble pas utilisé au bout du compte.

2024-12-02 09:19 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +                targetEnvelope = envelope.transform(targetCRS, true);
Je suis perplexe avec cette partie, j'ai l'impression qu'il y a des simplifications faisables.

En fait, on n'utilise ni le CRS de la génération (par défaut), ni celui donné en paramètre, mais toujours celui du fichier (logique).

Donc, on pourrait tout simplement virer le CRS des paramètres, et passer Generation à ce provider afin qu'il puisse directement appeler getEnvelopeForCRS avec son CRS.

Si cela pose des problèmes structurels, a minima n'utiliser que celui de la génération et ne pas permettre d'en spécifier un dans les paramètres.

2024-12-02 10:11 UTC, pyrollo commented
Je me demandais aussi quels tests unitaires pourraient être fait mais ce qui me semble "unit testable" est très trivial.

2024-12-02 12:16 UTC, indyteo commented
Hmm concernant les tests unitaires, j'y ai réfléchit rapidement aussi mais je n'ai rien trouvé de simple et je me suis dit qu'on en discuterait dans la PR justement ^^

2024-12-02 12:24 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +                targetEnvelope = envelope.transform(targetCRS, true);
Je suis d'accord que je n'ai pas beaucoup creusé ça, j'ai principalement récupéré ce morceau de code depuis les exemples de GeoTools et je me suis contenté de l'adapter pour qu'il fonctionne dans notre code. Mais de ce que je me souviens, tu as le CRS de la source, nous on a le CRS souhaité pour les données, et il y a le CRS de la génération, dans lequel sont exprimées les coordonnées de la zone d'intérêt (l'enveloppe). Du coup de mémoire je converti l'enveloppe dans les coordonnées de la source, mais je ne sais plus trop pourquoi j'ai fait ça, car effectivement on peut considérer que c'est une erreur si on demande la couche dans un CRS différent de celui dans lequel elle est encodée ?

2024-12-02 16:00 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +                targetEnvelope = envelope.transform(targetCRS, true);
Il doit y avoir certaines couches qui laissent le choix du CRS (en tout cas en WxS ça semble possible même si probablement limité aux capabilities). Ici cela semble exclus puisque les données sont dans un CRS donc autant utiliser celui là directement (en tout cas, ne pas proposer un paramètre pour ça).
Je n'ai pas creusé sur le bien ou pas bien de passer la génération au provider.

2024-12-02 16:03 UTC, pyrollo commented
Pour les tests, peut être faire le minimum, tester comme d'hab que les instanciations se font sans problème, dès fois que quelqu'un vienne casser qq chose. Ce serait d'autant plus utile que c'est un truc qu'on utilisera pas beacoup côté IGNfab, donc qu'on risque de ne pas remarquer si on le casse [TODO: remettre cette phrase en français]

2024-12-02 17:10 UTC, indyteo commented
Je m'étais dit justement que ça pouvait servir pour faire des tests d'intégration, tester une pipeline complète sans risquer de se manger les aléas de la Géoplateforme 🙃

2024-12-20 11:23 UTC, indyteo commented
J'ai ajouté quelques tests unitaires selon ce qui avait été fait sur les autres tests de params.

Il reste la question du CRS en paramètre, j'ai testé rapidement et j'ai l'impression que je peux bel et bien demander les données dans le CRS que je veux, c'est probablement GeoTools qui fait la reprojection en interne. Donc je me dis qu'on peut laisser le paramètre "au cas où", et si un jour on se motive à creuser le sujet des CRS et la manière de "plus proprement" les gérer, on pourra revenir dessus...

2025-02-12 21:02 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +                targetEnvelope = envelope.transform(targetCRS, true);
Après relecture approfondie du code, il me manquait une ligne pour appliquer la reprojection demandée aux données. Du coup, là tout est bon, et on peut lire un Geopackage / Shapefile stocké dans un CRS et obtenir les données dans un autre CRS.
Donc la question devient désormais : est-ce qu'on doit pouvoir choisir ce CRS de sortie des données de la couche, ou alors il faut impérativement que ce soit le CRS de la génération ? Je ne me souviens plus

2025-02-13 09:28 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +                targetEnvelope = envelope.transform(targetCRS, true);
Pas facile de se replonger là dedans mais c'est bon :) En partant à rebours c'est plus simple.

Le `processor` prend le `provider.crs()` pour effectuer la reprojection des géométries vers le CRS cible.

Le `provider` ne doit donc pas reprojeter puisque le `processor` le fait (sinon on risque une double reprojection). En revanche, il doit donner le CRS des données (via `crs()`). 

Pour ce qui est de l'envelope, il faut effectivement la reprojeter depuis le CRS cible vers celui des données pour effectuer une sélection correcte. Mais il y a pour ça un truc dans `generation`, je vais creuser.

Dans le paramétrage du provider, on a parfois un CRS quand on peut demander à la source un CRS donné. Dans le cas des fichiers, le CRS est cencé être indiqué par le fichier donc, on ne devrait pas l'avoir dans le paramétrage (sauf à faire un truc du genre forcer le CRS malgré l'indication du fichier, si celle-ci est erronée).


**Donc :**

Dans `provide`, il ne faut pas faire le `query.setCoordinateSystemReproject(wantedCRS)` et dans `crs()` il faut donner le CRS des données et pas le CRS demandé.

Je vais mettre ça sous forme de remarque dans le code.

2025-02-13 09:47 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +                targetEnvelope = envelope.transform(targetCRS, true);
### Envelope
Pour l'envelope, l'idéal est d'utiliser `generation.getEnvelopeForCRS(crs)`, ce qui nécessite de connaitre le CRS des données et qui reprojete directement la zone de génération depuis le CRS cible vers le CRS donné. La double reprojection de l'envelope fait grandir intuilement la zone (reprojection -> bbox -> reprojection -> bbox).

Les autres processors tirent leur CRS du paramétrage alors ici, il vient des données. Ils crééent leur envelope dans `...Params.create()` mais dans notre cas, on ne connait pas encore le CRS.

Deux solutions: 
- Reprojeter l'envelope comme tu le fais (mais ça agrandit la zone pour rien)
- Passer l'objet `generation` ou au moins la méthode `generation.getEnvelopeForCRS` au constructeur de ton provider dans la méthode `create` du paramétrage.

Une autre solution, plus propre mais plus couteuse, serait d'avoir un objet `Area` dans `Generation` qui gèrerait ces aspects géographique, qui arait la méthode `getEnvelopeForCRS` et que l'on pourrait passer plusôt que `generaion`.

2025-02-13 09:52 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +                targetEnvelope = envelope.transform(targetCRS, true);
Oui je me disais bien que j'oubliais quelque chose, mais c'est effectivement le processor qui fait le projection directement, en effet. Je vais adapter en laissant la possibilité d'override le CRS dans les paramètres car visiblement il est possible d'avoir un Geopackage ou un Shapefile avec un CRS invalide / manquant

2025-02-13 09:58 UTC, pyrollo reviewed
Voilà, j'ai mis ce que je pense qu'il faut modifier pour cette histoire de CRS (j'espère ne pas me tromper mais je ne crois pas).
Ça fait malheureusement pas mal de changement.

2025-02-13 09:58 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +    public GeoToolsDataStoreProvider(ReferencedEnvelope envelope) {
Donc ici, il faudrait récupérer `generation::getEnvelopeForCRS` plutôt que l'envelope pour pouvoir la créer plus tard.

2025-02-13 09:58 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +        return envelope.getCoordinateReferenceSystem();
Ici il faudrait aller lire le CRS dans les données.

2025-02-13 09:58 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +            Filter filter = ff.bbox(ff.property(geometryPropertyName), envelopeInCurrentCRS);
Ici il suffirait d'utiliser `generation::getEnvelopeForCRS(this.crs())` pour avoir la bonne envelope.

2025-02-13 09:58 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +                query.setCoordinateSystemReproject(wantedCRS);
Et là, pas de reprojection car c'est le processeur qui va la faire.

2025-02-13 09:58 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/providers/GeoPackageProviderParams.java
> +    public String crs;
Ici il ne devrait pas y avoir de CRS sauf si l'on veut permettre au paramétreur d'importer un fichier en forcant un autre CRS (genre celui du ficher est faux).

2025-02-13 09:58 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/providers/GeoPackageProviderParams.java
> +
Du coup tout ça devrait sauter.

2025-02-13 09:58 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/providers/ShapefileProviderParams.java
> +    public String crs;
Idem ici, on ne devrait pas avoir de CRS.

2025-02-13 10:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +                targetEnvelope = envelope.transform(targetCRS, true);
Par contre il y a un léger problème c'est que c'est le `DataSourcParams` qui prend le CRS du provider pour créer le processor, avant même que les données aient été lues. Donc le CRS des données n'est pas connu à ce moment-là

2025-02-13 10:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +        return envelope.getCoordinateReferenceSystem();
J'ai pas envie de lire les données à ce moment-là, car c'est appelé dans les params et je pense qu'il faut éviter de manipuler les données avant de commencer réellement la génération, sinon on casse un peu le cycle de vie du générateur à mes yeux. Du coup on arrive sur ma remarque ici : https://github.com/ignfab/minalac-generator/pull/59#discussion_r1954193731

2025-02-13 13:55 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +        return envelope.getCoordinateReferenceSystem();
J'ai push une version qui fonctionne en lisant les données pour trouver le CRS au moment de lire les params, mais je pense qu'il faut trouver une autre façon de faire

2025-02-13 15:31 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +        return envelope.getCoordinateReferenceSystem();
Je suis d'accord, il vaut mieux ne pas lire les données dans les params, c'est pour ça qu'on doit pouvoir s'en sortir en passant `generation` plutôt que `envelope`.
J'hésite à proposer une modif avec un objet `Area` pour faire ça bien (je ne pourrais que la semaine pro)

2025-02-13 15:33 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +                targetEnvelope = envelope.transform(targetCRS, true);
Ah ! J'avais pas vu ça. Peut être faut il qu'on revoit ça car cela ne parait pas abérant d'avoir un CRS connu qu'à partir des données.

2025-02-13 15:35 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +        return envelope.getCoordinateReferenceSystem();
Ça ne résoudra pas la question. Le problème n'est pas de passer la génération, le problème est qu'il faudrait revoir le fait que le `GeoToolsVectorProcessor` demande son `CoordsConverter` à la création (donc il faudrait avoir le CRS pour ça, sauf si on modifie le code pour délayer la création du converter)

2025-02-13 15:38 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/inputs/GeoToolsDataStoreProvider.java
> +                targetEnvelope = envelope.transform(targetCRS, true);
Je jetterait un œil ce week-end sur ce sujet alors (le fait de ne potentiellement pas connaître le CRS de la couche avant la lecture des données)

2025-02-20 08:08 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `crsOverride` (optional, default none): CRS to use when reading data. By default, the CRS is read from the GeoPackage itself. You should only use this parameter if the CRS is invalid or missing fro
```suggestion
- `crsOverride` (optional, default none): CRS to use when reading data. By default, the CRS is read from the GeoPackage itself. You should only use this parameter if the CRS is invalid or missing from the file. This **DOES NOT** reproject data!
```

2025-02-20 08:38 UTC, pyrollo reviewed
Juste relevé quelques bricoles.

L'idée de passer le CRS dans les Results est impeccable, c'est plus évident comme ça !

2025-02-20 08:38 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `crsOverride` (optional, default none): CRS to use when reading data. By default, the CRS is read from the Shapefile itself. You should only use this parameter if the CRS is invalid or missing from
idem ici
```suggestion
- `crsOverride` (optional, default none): CRS to use when reading data. By default, the CRS is read from the Shapefile itself. You should only use this parameter if the CRS is invalid or missing from the file. This **DOES NOT** reproject data!
```

2025-02-20 08:38 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/providers/ShapefileProviderParams.java
> +    public String filePath;
On n'a pas toujous mis l'annotation (et je crois que je la mets parfois en trop) mais ici elle change une NullPointerException en exception Jackson si le champs est vide (peut être un jour on parviendra à afficher le contexte de l'erreur dans le fichier de paramétrage) :
```suggestion
    @JsonSetter(nulls = Nulls.FAIL)
    public String filePath;
```

2025-02-20 08:38 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/providers/GeoPackageProviderParams.java
> +    public String typeName;
```suggestion
    @JsonSetter(nulls = Nulls.FAIL)
    public String typeName;
```

2025-02-20 08:38 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/providers/GeoPackageProviderParams.java
> +    public String filePath;
```suggestion
    @JsonSetter(nulls = Nulls.FAIL)
    public String filePath;
```

2025-02-20 10:19 UTC, pyrollo approved these changes
Yeah! Let's go!

2025-02-20 10:24 UTC, merged