Add `ReadableHeightmap` and update of `GroundRenderer` in order to render water
ignfab/voxatile pull request #60
Opened 2024-10-30 17:27 UTC by zhak5388

### Changes

Adds read only heightmaps and new renderers that can be used to render water.

*Edits on PR Description*: 
+ 2025-03-14: Removed notes about missing doc for `HeightmapParams`
+ 2025-02-28: Custom ReadableHeightmap is now deserialized using deduction (and not typeinfo) + Note on heightmap documentation
+ 2025-02-27: Changed all PR Description

#### Changes for `Heightmap`

There is a new interface `ReadableHeightmap`. On this PR implementations of this interface are used to have dynamically calculated heightmap which are:
- `ConstantHeightmap`: It always returns the same value.
- `LocalMinimumHeightmap`: It returns the local minimum of another heightmap around a specified range 
- `CappedManhattanHeightmap`:  It returns a capped manhattan distance of another heightmap
- `FunctionHeightmap`: Takes a heightmap, applies a function and returns the result. 
- `BiFunctionHeightmap`: Takes two heightmapsapplies a function and returns the result. This allows the creation of two readable heightmap parameters: a sum heightmap and product heightmap. 

`Heightmap` is the only class that is both writable and readable.

`ReadableHeightmap` is deserialized in tree ways:  it will be deserialized as a `ConstantHeightmap` if it is a number, or by using the name of a declared heightmap on the `heightmaps` field, or by using deduction mechanism.

```yaml
# Constant ReadableHeightmap
heightmap: 1
# Using the name
heightmap: ground
# Type
heightmap:
  localMin:
    base: ground  
    range: 9
```

#### Changes for `Renderers`

Changes on existing renderers:
+ `GroundRenderer` becomes `HeightmapRenderer`. This updated renderer can place placeable between a minimum and maximum heightmaps.
+ `HeightmapRenderer` becomes `MatrixToHeightmapRenderer` for clarity.

`CopyHeightmapsRenderer` is a new renderer that copies a heightmap to another at all coordinates within the model's shape.

Note that `MatrixToHeightmapRenderer` and `CopyHeightmapsRenderer` do not place anything in the world; they performs operations instead. For that reason, they should not be named renderers. However, they are kept as renderers on this PR, as it would imply a certain revamp which is not the goal of this PR. (Originally this PR was made to render water).

### Reason 
The aims of this PR is to be able to render water. On this version, unlike on version 1, the depth of the water is progressive.
#### Water Rendering
1) Water presence is stored in a heightmap from WFS source.
2) There is an inconsistency  between the data representing ground elevation (coming WMS) and data representing water presence (derived from WFS) resulting in a offset. Because of that `ground` heightmap is flattened on the region where there is water.
3) This water presence `heightmap` is then transformed into a water heightmap using a depth function based on a manhattan distance between water point and nearest ground point.
4) Water voxels are then placed between the `ground` and `waterHeight` heightmaps. 
#### Showcase
At (44.4523, 6.3935)
![Capture d’écran du 2025-02-27 14-06-54](https://github.com/user-attachments/assets/0250a836-0ca1-42a9-b991-aa12e1ec101a)
At (44.4523, 6.3935) Depth smoothing
![Capture d’écran du 2025-02-27 13-44-10](https://github.com/user-attachments/assets/435f45f1-58de-4591-a011-0570fd1bcf0a)
At (48.841, 2.421)
![Capture d’écran du 2025-02-27 14-08-45](https://github.com/user-attachments/assets/63ae1dda-a455-41f4-98f8-38412ccd1eea)

### Self-checks

- [x] The code has unit tests associated
- [x] The code has Javadoc Comments associated
- [x] Complex / Unexpected code is explained / justified with a small comment
- [x] Relevant documentation inside the `/docs` folder has been updated
- [x] All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)
- [x] Git history is clean (each commit accomplish a single task and describe it accordingly)
- [x] The texts have been proofread (documentation, error messages, logs, comments...)

2024-10-31 10:40 UTC, indyteo commented
Avant de laisser des remarques sur le code, j'aimerais juste que tu expliques quelques éléments :
1. Pourquoi vouloir appliquer un filtre sur la Heightmap ?
2. Quel impact sur les performances (temps, mémoire) cela peut avoir ? (Notamment ton implémentation, est-ce que tu penses qu'il y a mieux ou pas ?)
3. Pourquoi la synchronisation (jusqu'aux opérations de lecture) ?
4. L'image que tu montres contient de l'eau alors que la configuration que tu as inclus génère du verre, c'est normal ?

2024-11-04 11:05 UTC, zhak5388 commented
@indyteo  Alors, du coup ! 
> Pourquoi vouloir appliquer un filtre sur la Heightmap ?

C'était pour faire en sorte que la profondeur de l'eau soit progressive en fonction de sa distance au sol. J'ai appliqué un filtre moyenneur, mais je pense qu'il y a d'autres filtres qui correspondraient mieux.

> Quel impact sur les performances (temps, mémoire) cela peut avoir ?

C'est deux à trois plus de mémoire, je rajoute une heightmap qui est temporairement cloné lorsque le filtre est appliqué.

En terme de temps, il y a pas mal d'opérations qui s'ajoutent: voxelizer -> écriture dans une heightmap -> filtre sur la totalité de la heightmap -> parcours de la totalité de la heightmap -> placement du voxel.

> Pourquoi la synchronisation?

C'était principalement pour empêcher de lire des profondeurs qui ne sont pas définitive (c'est à dire avant d'avoir appliqué le filtre). Mais à y repenser, ça semble pas nécessaire, les dépendances des renderers permettent de gérer ça.

> L'image que tu montres contient de l'eau alors que la configuration que tu as inclus génère du verre, c'est normal ?

Oui et non! J'ai oublié de retirer le verre de la configuration (C'était pour tester, plus facile de voir le rendu)


Du coup, en écrivant, ça me fait penser que c'est un peu overkill tout ça..

2024-11-04 11:38 UTC, indyteo commented
Je vois, merci pour les précisions.

1. Oui c'est intéressant d'avoir le concept d'opérations sur les heightmaps (filtre...), et l'opération spécifique appliquée n'a pas beaucoup d'importance (enfin bien sûr ça altère le rendu, mais comme tu l'as dit, c'est indépendant, interchangeable, optionnel). Sauf que dans ton implémentation non, c'est hard-codé ! Peut-être une 1ère piste d'amélioration ici.
2. En effet, comme tu le vois l'impact mémoire est réel (bon, ok, c'est pas grand chose sur une petite zone, mais sur du 5km² par exemple, 5k x 5k x 4 octets = 100 Mo). Le temps de calcul est aussi impacté, mais bien moindre (et négligeable / inévitable selon moi). Est-ce que tu as une idée qui pourrait améliorer les performances mémoire ?
3. Je suis d'accord, la synchronisation n'est pas nécessaire à mes yeux car on s'assure de l'ordre d'exécution souhaité à travers les dépendences des opérations.
4. Je m'en suis douté, mais comme ça tu peux rectifier ^^

Je ne pense pas que tout ça soit "overkill", au contraire il doit s'agir d'une base solide pouvant être exploitée par d'autres briques du générateur (par exemple, appliquer un filtre pour "smooth" le terrain, appliquer un offset...)

2024-11-04 14:42 UTC, zhak5388 commented
Merci pour le retour : )

> Sauf que dans ton implémentation non, c'est hard-codé ! 

Oui, j'y avais pas pensé haha J'imagine que ça pourrait être quelque chose dans le paramétrage : utiliser le `WaterRenderer` avec telle heightmap en y pré-appliquant une opération (par exemple tel filtre) ou bien un renderer dédié pour les opérations (mais il faudrait qu'il passe après tous les renderers qui alimentent la heightmap).

Pour ce qui est des performances mémoires, j'ai pas vraiment d'idée. La seule chose qui me vienne en tête, c'est que pour un filtre avec un noyau de taille 3x3, quand on calcule la valeur à (x+2, y+2), la valeur calculée à (x, y) peut être écrite dans la heightmap. Du coup, plutôt qu'une copie complète je pourrais commencer à me limiter à une utilisation mémoire de deux "bandes" de la heighmap pour stocker les anciennes valeurs

2024-11-04 16:31 UTC, indyteo commented
Je vais faire 2 réponses différentes, je ne sais pas encore laquelle est la meilleure, les deux ont des avantages et des inconvénients.

***

Dans l'état actuel, le plus simple et souple serait d'avoir un renderer dédié à l'application du filtre. La chaîne de travail du générateur (concernant les cours d'eau) deviendrait alors :
1. Import des données vecteur relatives aux cours d'eau (`WFSDataProvider`)
2. Rasterisation des surfaces (voxelisation 2d) dans une Heightmap avec profondeur fixe (`WaterDepthRenderer`)
3. (Optionel) Application d'un filtre sur la Heightmap de profondeur (`HeightmapFilterRenderer`)
4. Rendu en jeu en creusant le lit des cours d'eau et en plaçant l'eau dedans (`WaterRenderer`)

L'orchestration des tâches s'assure que le filtre n'est appliqué qu'une fois que toutes les surfaces ont été rasterisées, et que le rendu n'est fait qu'après que le filtre ai été appliqué.

Concernant les performances, à part effectivement rentrer dans des optimisations complexes (et pas rentables à mon sens) comme tu as pu réfléchir, tu ne peux pas vraiment te débarrasser du double tableau. Cependant, tu peux (en modifiant un peu le code actuel) gagner du temps (et un peu de mémoire sur ton implémentation). Actuellement, tu fais :
1. Création d'une nouvelle `Heightmap` (agrandie) => Allocation
2. Recopie des valeurs de l'ancienne dans la nouvelle `Heightmap` => Lecture/Écriture
3. Calcul de chaque valeur depuis les données de la nouvelle `Heightmap` vers l'ancienne => Lectures/Écriture

Déjà, tu peux éviter l'agrandissement en faisant juste un test si la donnée existe ou pas et en prenant 0 sinon (sur une zone de 5km² tu évites de stocker 80 ko de zéros). Ensuite, tu peux éviter l'étape de recopie en subtilisant les données depuis l'ancienne `Heightmap`, puisque toutes ses valeurs vont être recalculées :
1. Création d'une nouvelle `Heightmap` à partir des données existantes (nécessite de changer le code actuel) => Pas d'allocation (tableau déjà existant) ni de lecture/écriture (données déjà présentes dans le tableau)
2. Remplacement des données de l'ancienne `Heightmap` par un tableau vide => Allocation
3. _Étape 3. inchangée_

Au final tu as économisé une étape de recopie complète puisque ton étape 3 fait déjà une écriture complète des données.

C'est pas la plus grosse optimisation, mais ça reste relativement simple à faire pour un petit gain.

***

Ok alors maintenant tu oublies tout ce que je viens de dire, et voici une autre proposition de solution qui répond à ce besoin et à d'autres aussi.

Tu utilises actuellement 2 renderers, un qui rasterise les surfaces aquatiques dans une `Heightmap`, représentant ainsi la "profondeur de l'eau" en tout point de ton terrain (avec 0 = pas d'eau), et le second qui effectue le rendu en voxel correspondant (on oublie le filtre pour l'instant).

Effectivement, avec ce traitement brut, les bordures des zones aquatiques sont raides, puisqu'on passe d'une profondeur de 0 (pas d'eau) à une profondeur fixe du fond de la surface (par défaut 5). L'utilisation d'une convolution avec un filtre gaussien (ou une moyenne dans un premier temps, c'est (presque) pareil) permet bel et bien d'améliorer drastiquement le rendu en adoussissant les bordures. Problème : *Stocker le résultat* d'une convolution demande d'allouer un nouveau tableau.

Mais, est-ce réellement un problème, tout compte fait ? Veut-on réellement *stocker* le résultat de la convolution ? Eh bien la réponse est non : Nous avons seulement besoin de le calculer au moment de l'utiliser ! Donc le `WaterRenderer` peut calculer dynamiquement la "profondeur après convolution" à chaque fois qu'il va s'en servir pour le rendu. Après tout, il n'utilise qu'une seule fois chaque valeur, donc il y a le même nombre de calculs, et on évite une allocation coûteuse.

Ok mais, est-ce qu'on ne viendrait pas de faire un truc pas très bien, là ? Eh si, on vient d'*hard-coder* le mécanisme de convolution dans le `WaterRenderer`, alors comment on fait si on voulait pas faire de convolution, ou alors on voulait faire autre chose, ou même si on voulait l'utiliser ailleurs ?

Machine arrière, on retire le code de convolution du `WaterRenderer`. Mais où est-ce qu'on peut le mettre alors ? Pour trouver la réponse à cette question, observons plus en détail ce code, et en particulier ses entrées et sorties. Outre les hyper-paramètres, pouvant dépendre de la demande de génération (kernel, padding...), la convolution travaille sur une `Heightmap`, et fourni une (nouvelle) valeur pour chaque point de cette `Heightmap`.

Mais d'ailleurs, une `Heightmap`, c'est quoi ? C'est un ensemble de valeurs sur une zone définie qu'on peut définir (set) et lire (get). Mais la `Heightmap` utilisée par le `WaterRenderer`, est-ce qu'il a vraiment besoin de ces deux fonctionnalités ? Non, il ne demande qu'à pouvoir lire des données, il n'a pas besoin d'en définir. Et pourquoi je précise ça, moi ? Parce qu'au final, rien n'empêche d'extraire depuis la classe `Heightmap` une interface permettant la lecture, et ainsi remplacer le champ `Heightmap` dans le `WaterRenderer` par cette `ReadableHeightmap`. Ça fonctionnerait pareil.

Et revenons à notre résultat de convolution. On a dit que c'était quelque chose qui, à partir d'une `(Readable)Heightmap` (et quelques hyper-paramètres) en entrée, nous donnait une valeur pour chaque point. Autrement dit, c'est un objet depuis lequel on peut lire des valeurs... C'est-à-dire une `ReadableHeightmap` ! Et là c'est gagné, puisqu'il ne reste plus qu'à créer notre objet `ConvolutedHeightmap` à partir des paramètres d'entrée et et la `ReadableHeightmap` de base, et la filer à notre `WaterRenderer` au même titre qu'on lui passerait n'importe quelle `ReadableHeightmap`.

Avec cette solution, on a réussi notre abstraction (à un détail de désérialisation près, mais c'est seulement un défi de programmation et non plus de conception), et on n'a pas de problème de performances.

***

Bon, là comme ça difficile de se décider. La 2ème solution parait peut-être un peu plus attrayante sur le plan des performances, mais il y a quelque chose d'important à noter avec cette solution, c'est que tous les calculs sont faits à la volée. Donc ça fonctionne bien si tu n'utilises qu'une seule fois les résultats, comme c'est le cas ici, mais si on voulait appliquer le même concept disons au sol (avec un filtre bilatéral par exemple pour réduire le bruit dans les données d'élévation), on se retrouverait à recalculer souvant les valeurs (et le filtre bilatéral est une opération "lourde"), et peut-être que le coût d'une allocation supplémentaire serait bénéfique pour économiser le temps de recalcul multiple.

En pratique, il n'est pas impossible qu'on finisse avec les 2 options, pouvoir appliquer des modifications à une `Heightmap`, ou alors utiliser des calculs à la volée, selon le cas d'usage. Pour l'instant, la 1ère solution est la plus simple à implémenter puisqu'elle ne change pas grand chose, et tu peux décider de faire ou non l'optimisation que j'ai mentionné.

Pour la suite, si la 2nde option t'a donné envie / des idées, tu peux expérimenter sur une branche à côté ça ne sera pas inutile selon moi.

2024-11-05 07:58 UTC, pyrollo commented
De bonnes idées ici, et le fait qu'on puisse avoir besoin d'un filtre heightmap aussi sur le MNT justifie l'effort d'amélioration.

La solution que propose Théo (celle de l'interface ReadableHeigthMap) me parait bonne.

> Avec cette solution, on a réussi notre abstraction (à un détail de désérialisation près, mais c'est seulement un défi de programmation et non plus de conception), et on n'a pas de problème de performances.

Pour la désérialisation, il faut qu'on se mette à s'abstraire des classes internes. Je veux dire, on peut avoir une classe "à tout faire", et plusieurs classes Params qui l'utilisent de différentes façons plus simples.

Un exemple dans une autre PR est le post-processeur Parse, qui prend en paramètre des closures. Le paramétrage n'est pas obligatoirement aussi souple et on pourrait faire des paramètres bien plus simples qui traitent différents cas avec la même classe interne.

> Bon, là comme ça difficile de se décider. La 2ème solution parait peut-être un peu plus attrayante sur le plan des performances, mais il y a quelque chose d'important à noter avec cette solution, c'est que tous les calculs sont faits à la volée. Donc ça fonctionne bien si tu n'utilises qu'une seule fois les résultats, comme c'est le cas ici, mais si on voulait appliquer le même concept disons au sol (avec un filtre bilatéral par exemple pour réduire le bruit dans les données d'élévation), on se retrouverait à recalculer souvant les valeurs (et le filtre bilatéral est une opération "lourde"), et peut-être que le coût d'une allocation supplémentaire serait bénéfique pour économiser le temps de recalcul multiple.

Dans ce cas, une méthode de la classe HeightMap actuelle (ou une sorte de constructeur copy) pourrait lancer le calcul sur toutes les cellules pour le stocker. Un truc qui marche sur toutes les classes implémentant ReadableHeightMap.


Avec Zen, on a discutté hier, sur les filtres pour faire le fond de l'eau.

La convolution pause un problème : Elle "regarde" au delà des bords. Deux plans d'eau proches influencent leur profondeur.

Un autre filtre pourait être tout simplement un truc qui donne la distance au plus proche bord. Le problème, c'est de trouver un algo optimisé. L'avantage, c'est qu'une simple fonction permet de sculpter le profil du plan d'eau.

(mais ça s'inscrit tout à fait dans ce qui a été dit plus haut, c'est juste un autre filtre)

2024-11-06 17:03 UTC, zhak5388 commented
J'ai commencé à intégrer une `ReadableHeightmap` et `ConvolutedHeightmap` (C'est du brouillon). J'ai dans l'idée de faire en sorte que  `ConvolutedHeightmap`  soit assez flexible pour le noyau passé en paramètre (A voir si c'est rentable)
Concernant l'algorithme qui calcule la distance de Manhattan (On en avait discuté avec Pierre-Yves), j'imagine qu'il y aura deux versions une à volé et une autre la totalité qui pourrait être optimisée.
Bon, c'est du brouillon tout ça, je reprends ça la semaine prochaine!

2024-11-14 15:47 UTC, indyteo commented
En expérimentant sur un autre sujet, j'ai eu besoin d'un renderer qui construisait une sorte de "masque" dans une `Heightmap`, à partir de modèles `ShapeVoxelizable2d`. En somme, le résultat consistait en une `Heightmap` dont les valeurs étaient `0` partout, et `1` là où il y avait des modèles. J'allais le coder, puisque j'ai tilté que j'avais déjà vu ce mécanisme quelque part : Ici (le [`WaterHeightmapRenderer`](https://github.com/ignfab/minalac-generator/blob/zhak/water-renderer/src/main/java/com/ignfab/minalac/generator/renderers/WaterHeightmapRenderer.java)).

Seulement voilà, au niveau du nommage, il est un peu trop spécifique, et à tord, puisqu'il ne fait absolument rien de spécifique à l'eau. Tout ce qu'il fait, c'est prendre une valeur constante, et la placer dans une `Heightmap`, aux endroits où des modèles `ShapeVoxelizable2d` se situent. Du coup je te propose de renommer ton renderer, et adapter sa documentation pour mieux respecter ce côté générique.

Ça fait vraiment réfléchir "un pas en arrière" par rapport à notre vision du code, quand on fait quelque chose, on a généralement un cas d'usage concret, appliqué à notre problème, mais au final notre solution est souvent plus large, et il faut réussir (parfois après avoir terminé) à généraliser nos nommages avec un peu plus de recul.

Cette remarque n'est pas uniquement pour toi @zhak5388, mais plutôt pour nous tous, car au final le `GroundRenderer` est aussi dans une situation similaire, il s'appelle "ground" mais en réalité il ne fait que placer des voxels d'après une `Heightmap`, c'est tout (pas nécessairement le sol, je l'utilise avec des données LiDAR sur les toits des bâtiments par exemple)

2024-11-18 15:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/CappedManhattanHeightmap.java
> +            return k + k;
C'est plus simple, pour les distances de manhattan, de calculer en losange :

```suggestion
        for (int i = 0; i < k; i++) {
            if (isTargetValue(x - k + i, y - i)
                || isTargetValue(x + k - i, y + i)
                || isTargetValue(x - i, y - k + i)
                || isTargetValue(x + i, y + k - i))
            return k;
        }
```
Comme le résultat est toujours -1 ou k, ça peut être un booleen = "y a t-il quelque chose à distance k ?"


Le carré c'était plutôt pour l'autre distance, celle qui fait 1 en diagonale.

2024-11-18 15:24 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/CappedManhattanHeightmap.java
> +            return k + k;
(a vérifier pour les formules, j'ai fait ça vite fait)

2024-11-18 15:26 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/CappedManhattanHeightmap.java
> +    }
ça vaudrait le coup de coder ça dans la heightmap directement, une version de `get`, un `getNoEx` ou bien un `getEx` et `get` devient dans exception.

2024-11-18 15:34 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/WaterRendererParams.java
> +    public Integer nonWaterValue = 0;
J'ai l'impression que le ShapeToHeightmapRenderer ne laisse pas le choix que d'utiliser 0. Cela fait sens, on peut se dire 0, c'est là où il n'y a rien.

Mais dans ce cas, cela n'a pas trop d'intérêt de pouvoir choisir dans le Yaml cette valeur qu'on ne pourra jamais changer (encore une fois, pour moi, ça fait sens que ce soit toujours 0).

Donc je virerai purement et simplement ce champ car je pense qu'on en aura jamais besoin.

2024-11-18 15:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/CappedManhattanHeightmap.java
> +            if (distance > 0 && distance <= maximumDistance)
```suggestion
            if (distance > 0 && distance <= maximumDistance)
```
Avec le calcul en carré, c'est dommage, tu parcours éventuellement des tas de cellules, pour ignorer le résultat ensuite avec ce if maximumDistance.

2024-11-18 16:54 UTC, indyteo reviewed
1ère passe de review

2024-11-18 16:54 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/CappedManhattanHeightmap.java
> +    }
Sans l'exception, ça aurait aussi pu être codé avec un simple test d'inclusion

2024-11-18 16:54 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/WaterRenderer.java
> +        this.waterHeightmap = new CappedManhattanHeightmap(waterHeightmap, maximumDepth, nonWaterValue);
En laissant la création de cette `Heightmap` hardcodée, on perd toute la flexibilité qui était intéressante avec un tel système

2024-11-18 16:54 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/ShapeToHeightmapRenderer.java
> +    }
Le fait d'imposer aux modèles d'être `ShapesVoxelizable2d` n'apporte rien, il suffit qu'ils soient `Voxelizable2d`. En revanche tu peux imaginer permettre d'écrire une valeur différente pour les bordures, mais ça tu peux t'en sortir sans l'imposer...

2024-11-18 16:54 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/WaterRendererParams.java
> +    public Integer nonWaterValue = 0;
Si, ça correspond à la valeur par défaut que tu auras mis dans ta `Heightmap`

2024-11-18 16:54 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/WaterRendererParams.java
> +    public Integer maximumDepth;
```suggestion
    public int maximumDepth;
```
Non ?

2024-11-18 16:54 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/WaterRenderer.java
> +                air.place(c.x(), c.y(), groundHeightmap.get(c));
C'est plutôt une sorte de "hack" qu'on fera au niveau de la configuration je pense, mais je le note ici pour vous le partager et éventuellement ça peut valloir le coup de l'indiquer dans la documentation :
Au lieu de placer de l'air ici, si on place un voxel invisible, ça évite que l'eau coule partout si il y a des dénivelés

2024-11-19 07:37 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/WaterRendererParams.java
> +    public Integer nonWaterValue = 0;
Dans ce cas on peut utiliser la valeur par défaut de la HeightMap à condition qu'elle soit capable de nous la renvoyer (ce qui ne serait pas bête non plus).

2024-11-19 07:39 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/CappedManhattanHeightmap.java
> +    }
Effectivement, mon idée de faire des getNoEx ne fonctionne pas si l'on veut ignorer ce qui n'est pas dans la heightmap (on peut imaginer qu'il renverrait la valeur par défaut ce qui induirait la distance en erreur).

2024-11-19 10:09 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/renderers/WaterRenderer.java
> +        this.waterHeightmap = new CappedManhattanHeightmap(waterHeightmap, maximumDepth, nonWaterValue);
Du coup, si je comprends bien, le constructeur du WaterRenderer prendrait en paramètres deux `ReadableHeightmap` (groud et water) et les `VoxelType` (pour l'instant)
Par contre au niveau du paramétrage, j'aurai quelque chose comme:
```yaml
renderers:
  water:
    after:
      - renderer:waterDepth
      - renderer:ground
    type: water
    groundHeightmap: ground
    # Soit le nom, soit cette forme là
    waterHeightmap:
      base: water
      maximumDepth: 5
      nonWaterValue: 0
```

2024-11-19 10:32 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/WaterRenderer.java
> +        this.waterHeightmap = new CappedManhattanHeightmap(waterHeightmap, maximumDepth, nonWaterValue);
Oui selon moi, sauf qu'il va sans doute te falloir préciser le type quelque part, puisqu'il ne pourra pas le deviner (le but est justement de pouvoir passer un autre type de `ReadableHeightmap` si on veut).

Du coup, tu vas sans doute avoir une désérialisation de `ReadableHeightmapParams`, avec un désérialiseur custom (similaire à celui des voxels dans #54), pour gérer le cas "string" comme `generation.heightmaps().get("string")`, et le reste de façon traditionnelle.

Point bonus si tu arrives à permettre la récursivité (que `base` puisse aussi être une `ReadableHeightmap` custom) :slightly_smiling_face:

2024-11-19 10:41 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/WaterRenderer.java
> +                air.place(c.x(), c.y(), groundHeightmap.get(c));
Côté Minetest, il faut créer ce voxel invisible. Du coup, une autre solution équivalente en terme de modif est de dupliquer le voxel eau pour en faire un indentique mais qui ne coule pas.

2024-11-19 15:11 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/renderers/ShapeToHeightmapRenderer.java
> +    }
Il y a quelque chose qui m'échappe, j'arrive à voir comment je peux connaitre les bordures du modele en question sans que ça soit un `ShapeVoxelizer2d`

2024-11-19 15:26 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/CappedManhattanHeightmap.java
> +            return k + k;
Yes, j'étais trop dans l'ancienne version, j'ai corrigé du coup!

2024-11-19 16:04 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/WaterRendererParams.java
> +    public Integer nonWaterValue = 0;
J'ai un peu du mal à voir ou est ce que l'on passerait la valeur par défault de la `Heightmap`. Si `CappedManhattanHeightmap` prend une `ReadableHeightmap` il faudrait une méthode au niveau de l'interface qui permette de renvoyer la valeur par défault, non? (Pareil, si on adopte une structure pour le `WaterRendeder` comme [ici](https://github.com/ignfab/minalac-generator/pull/60#discussion_r1848043824))

2024-11-19 16:11 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/WaterRendererParams.java
> +    public Integer maximumDepth;
Oui, effectivement comme c'est un champ requis je peux me passer de l'objet : )

2024-11-19 16:32 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/CappedManhattanHeightmap.java
> +    }
Pourquoi c'est mieux de vérifier que la heightmap contienne le point (+ égalité) que de faire un try catch? J'avoue que la raison m'échappe

2024-11-19 18:27 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/ShapeToHeightmapRenderer.java
> +    }
Tu as plusieurs solutions : Soit tu fais un renderer séparé, et selon si le paramètre `edgeValue` est présent ou pas, tu choisis ta classe qui va bien, soit tu fais juste un test ici avec un `if` / `else`

2024-11-19 18:30 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/WaterRendererParams.java
> +    public Integer nonWaterValue = 0;
Oui c'est ça, il faut que la `ReadableHeightmap` puisse fournir sa valeur par défaut. Et éventuellement dans l'interface, si ça simplifie (mais pas sûr), la valeur par défaut par défaut peut être 0, mais je pense que les `ReadableHeightmap` seront (presque) toujours directement une `Heightmap`, soit calculée à partir d'une autre `ReadableHeightmap`, et on retombera sur une `Heightmap` classique à la fin

2024-11-19 18:48 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/CappedManhattanHeightmap.java
> +    }
Il y a plusieurs raisons, déjà premièrement on ne catch jamais une `Exception` comme ça, ensuite sur la lisibilité c'est quand même plus simple à lire avec un if, on comprend mieux ce qui se passe, après sémantiquement, les _exceptions_ sont en principe pour les cas _exceptionnels_, c'est à dire quand quelque hors de notre contrôle se passe mal, donc si on peut éviter nous-même que ça se passe mal, c'est mieux, et enfin il y a un impact non négligeable sur les performances à la création d'une exception (récupération de la stack-trace), alors surtout quand c'est pour l'ignorer ensuite, c'est d'autant plus optimisé de vérifier avant avec un if

2024-11-25 08:16 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/WaterRenderer.java
> +        this.waterHeightmap = new CappedManhattanHeightmap(waterHeightmap, maximumDepth, nonWaterValue);
Déclarer ces heightmaps dans la section `heightmaps` devrait simplifier la désérialisation (en tout cas, il faut se poser la question entre les déclarer dans le renderer comme proposé ou dans `heightmaps`).

Je ne suis pas sûr que ce soit une bonne chose de se lancer là dedans dans cette PR. Cela va l'alourdir et la ralentir or on est encore au niveau POC pour l'eau, on n'est pas sûr que cela donne ce que l'on veut.

Je serais d'avis de faire un truc pas peaufiné mais qui permet d'avancer et de vérifier que c'est bien ce que l'on veut, pour faire une PR plus tard pour ce mécanisme (qui n'est pas prioritaire à mes yeux).

2024-11-25 08:19 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/ShapeToHeightmapRenderer.java
> +    }
Je crois qu'on n'a pas besoin des bordures pour l'instant. Tu devrais pouvoir avoir un renderer très simple qui prend n'importe quel voxelizable et le plaquer dans la heightmap.

Idéalement, si l'on voulait les bordures, il faudrait putôt une interface qui indique que la classe est capable de fournir des informations sur les bordures.

2024-11-25 08:28 UTC, pyrollo commented on examples/default_water.yaml
> +    nonWaterValue: 0
Je note pour en discutter:

Vu que `waterHeigthmap` est censé être la profondeur d'eau, il me parait évident que `0` représente les endroits sans eau.

2024-11-25 08:29 UTC, pyrollo commented on examples/default_water.yaml
> +    newHeight: 1
Suis pas convaincu par le "new" mais pas non plus décidé sur quoi mettre à la place.
Propositions: `height`, `setHeight`, `insideHeight`

2024-11-25 08:37 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/CappedManhattanHeightmap.java
> +    }
Eventuelllement, tu peux compacter ton code (la fonction n'est appelée qu'à un seul endroit et ne simplifie pas la lecture):

```suggestion
    @Override
    public int get(int x, int y) {
        if (heightmap.get(x, y) == targetValue)
            return 0;
        for (int distance = 1; distance < maximumDistance; distance++)
            for (int i = 0; i < distance; i++)
                if (isTargetValue(x + i, y + distance - i)
                    || isTargetValue(x - i + distance, y - i)
                    || isTargetValue(x - i, y - distance + i)
                    || isTargetValue(x - distance + i, y + i))
                    return distance;
        return maximumDistance;
    }

    @Override
    public WorldBBox2d bbox() {
        return heightmap.bbox();
    }
```

2024-11-25 08:43 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/WaterRenderer.java
> +    private final CappedManhattanHeightmap waterHeightmap;
```suggestion
    private final ReadableHeightmap waterHeightmap;
```

2024-11-25 08:44 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/WaterRenderer.java
> +        this.waterHeightmap = new CappedManhattanHeightmap(waterHeightmap, maximumDepth, nonWaterValue);
En revanche, si on ajourne la désérialization, mettre un gros commentaire ici pour expliquer.

2024-11-25 08:45 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/ShapeToHeightmapRenderer.java
> +    }
C'est exactement ce qu'on a oui 😄

2024-11-25 08:47 UTC, indyteo commented on examples/default_water.yaml
> +    newHeight: 1
Je mettrais bien simplement `value` perso

2024-11-25 09:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/WaterRenderer.java
> +        this.waterHeightmap = new CappedManhattanHeightmap(waterHeightmap, maximumDepth, nonWaterValue);
Au début c'était ce que je me disais aussi, sauf que les `Heightmap`s déclarée en haut sont "read/write", hors là il ne s'agit que de `ReadableHeightmap`s... Et puis c'est pas très compliqué à faire (même pas compliqué du tout, c'est quasi identique à ce qui est fait pour les voxel)

2024-11-25 09:45 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/CappedManhattanHeightmap.java
> +    }
C'est noté, merci pour l'explication : )

2024-11-25 13:07 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/WaterRenderer.java
> +        this.waterHeightmap = new CappedManhattanHeightmap(waterHeightmap, maximumDepth, nonWaterValue);
Pas trop compliqué mais copieux quand même. J'ai demandé à Zen de fignoler le rendu et ensuite on peut voir la désérialisation des heightmaps. Cela peut se faire dans une autre PR car je sens que ça va faire beaucoup de modif. Dans celle-ci, il y aura juste une ou deux lignes à supprimer pour que ça s'adapte.

Pour la désérialisation, on aurait un désérialiseur pour ReadableHeightmap et un autre pour WritableHeightmap (qui serait readable). On pourrait virer le store de génération (qui ne servira plus à rien) pour le mettre dans params.

Ainsi, à la fin de la désérialisation, on a toutes les heightmaps connectées à d'autres objets (voire certaines connectés à la map pour la minimap).

Tout ça pour dire qu'il y a un peu de travail juste pour ce qui, à la base, n'est qu'un calcul de distance (il faudra évidement le faire, mais ça peut être fait ailleurs).

2024-12-17 17:37 UTC, zhak5388 commented
J'ai fais des notes à moi-même pour reprendre la PR plus facilement. Je vais les mettre ici : )

Nouvelles classes:
+ `Heightmap`: (+Paramètres associées)
	+ Interfaces `ReadableHeightmap` et `WritableHeightmap`
	+ `CappedManhattanHeightmap`, `FunctionHeightmap` et `LocalMinimumHeightmap`
	+ Pour la désérialisation en plus: `TypeReadableHeightmapParams`, `StoredHeightmapParams`
+ `Renderer`: (+Paramètres associées)
	+ `ShapeToHeightmapRenderer`, `CopyHeightmapRenderer`et `WaterRenderer`

Actuellement déroulé rendu de l'eau:
+ 1) Création d'une heightmap qui sert à contenir la profondeur de l'eau. (`ShapeToHeightmapRenderer`) (En réalité il s'agit plus d'une heightmap de présence)
+ 2) Correction du MNT de ground avec `CopyHeightmapRenderer` et `LocalMinimumHeightmap`. Il y a un décalage entre les données du MNT et celui issues des données WFS, le résultat permettant d'avoir un rendu plus propre est corriger le MNT en remplaçant ses valeurs par des minimums locaux là ou il y a les zones d'eau.
+ 3) `WaterRender` place des voxels à "l'intersection" des heightmap `ground` et `water` "calculée". Afin d'avoir une profondeur de l'eau progressive  `CappedManhattanHeightmap` et `FunctionHeightmap` sont utilisées. L'idée est d'avoir une profondeur en fonction d'une distance. (La fonction utilisée dans les paramètres est peut-être à peaufiner)

*Note sur le point 2):*

Actuellement le filtrage est fait de cette manière.

```yaml
updateMnt:
  type: copy  
  from:  
    type: localMin  
    base: ground  
    range: 9  
  to: ground  
  filter:  
    heightmap: water  
    condition: GREATER_DEFAULT
```
La partie `filter` est pas super claire, comme discuté avec @pyrollo  on pourrait modifier  `ShapeToHeightmapRenderer` pour que ça prenne une `Heightmap` à la place d'un simple `int` quitte à faire la voxelisation deux fois.
```yaml
Surface:
  modelType: water
  heightmap: ground
  copyFrom:
    type: localMin
    base: ground
```

Autres:
+ Il y a des TODOs/Notes et commentaires sur le code.
+ J'ai enlevé la javadoc que j'avais faite dans le cas ou elle serait dépréciée mais il y a certainement des résidus. 
+ Passable à ReadableHeightmapParams n'est pas fait sur les Renderers existants.
+ Merge `default_water.yaml` -> `default.yaml`

2024-12-18 08:52 UTC, pyrollo requested changes
J'ai mis des commentaires en fonction de ce qu'on s'était dit hier.

2024-12-18 08:52 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +### ShapeToHeightmapRenderer
Je suppose qu'on va avoir un `LinearToHeigthmapRenderer` pour les rivières.
```suggestion
### PolygonToHeightmapRenderer
```
ou
```suggestion
### SurfaceToHeightmapRenderer
```

2024-12-18 08:52 UTC, pyrollo commented on examples/default_water.yaml
> +    newHeight: 1
Après discussion avec Zen, on pourrait partir dans une autre direction en fusionnant `shapeToHeightmap` et `copy` pour faire un `copyHeightmap` (ou `copyHeightmapUnderModel` ?) qui prendrait:
- une heightmap source
- une heightmap cible
- une modelSelection

Son action serait de copier la source dans la destination partout où l'on est sous la surface du modèle.

Le même rendrerer (plutôt générique) peut servir à : 
- Creuser les zones d'eau (à condition de créer une Heightmap 'constant' pour donner la valeur que l'on veut mettre, ou bien un raccourci pour l'indiquer directement)
- Lisser les surfaces d'eau en copiant une heightmap "localMin" partout où il y a de l'eau.

Pour éviter que la modification de la cible entraine des effets de bords sur la source, le renderer devrait:
- cloner la cible
- travailler sur le clone
- remplacer la cible par le clone à la fin

Le remplacement final peut se faire par copie ou par buffer swap. Le swap est mieux en terme de performances CPU mais en fait cela nous importe peu (question mémoire les deux solutions reviennent au même).

2024-12-18 08:52 UTC, pyrollo commented on examples/default_water.yaml
> +    type: water
Ce renderer peut devenir un "placeBetweenHeightmaps".

Il place des trucs partout entre deux heigtmap (une supérieure et une inférieure).

Il n'aurait plus que les paramètres suivant (les noms sont seulement des suggestion):
- `upperHeightmap`
- `lowerHeightmap`
- `place`

(Si l'on fait bien le travail sur le mnt en lissant la surface de l'eau, on n'a plus besoin de placer de voxels d'air)

2024-12-18 08:52 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/Heightmap.java
> +    public Heightmap copy() {
Ce serait bien plus intéressant d'avoir un : 
```
    public copy(ReadableHeightmap from) {
```
Celui-ci, en plus de faire de même que ta proposition, permettrait d'"aplatir" une heightmap calculée.

(faudrait que cela ne copie que là où il y a intersection).

2024-12-18 08:52 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/Heightmap.java
> +                copy.set(x, y, values[index(x, y)]);
Vu que les deux heigthmaps ont la même bbox tu pouvais simplifier avec un seul indice pour parcourir tout le tableau. Voir mieux, en appelant `.clone()` dessus pour le copier "bêtement".

On va avoir besoin de rendre cette classe `Cloneable` pour tes renderers.

2024-12-18 08:52 UTC, pyrollo commented on examples/default_water.yaml
> +    type: water
Pour cela il faudra une addition/soustraction de heightmap pour avoir "altitude - profondeur" comme heightmap inférieure.

2024-12-18 08:53 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +### ShapeToHeightmapRenderer
C'est une vieille remarque qui trainait mais peut être à prendre en compte.

2025-01-20 14:56 UTC, pyrollo commented on examples/default_water.yaml
> +    type: water
Discussion avec Zen :

Ce renderer peut être fusionné avec le `HeigthMapRenederer`.

Ce nouveau `HeigthMapRenederer` prendrait 3 paramètres:
- Le placeable;
- Une ReadableHeightmap `minimum`
- Une ReadableHeightmap `maximum`

Il placerait le placeable partout où : `minimum(x, y) <= z <= maximum(x, y)`

Là où `maximum(x, y) < minimum(x, y)`, rien de serait placé.

Et pour le *ground renderer*, il suffit de l'utiliser avec la même heightmap comme minimum et comme maximum.

Le paramétrage peut prende 2 formes:
```yaml
type: heightmap
place: ...
minimum: ...
maximum: ...
```
ou bien:
```yaml
type: heightmap
place: ...
at: ...
```
Pour une seule heightmap.

2025-02-27 13:35 UTC, zhak5388 commented
Un truc auquel je viens de penser, je me dis que ça serait bien que je change le paramétrage pour addition et soustraction. (`AdditionHeightmapParams` et `SubtractionHeightmapParams` )Au lieu de faire:
```yaml
type: subtraction  
first:  
  type: addition  
  first: ground  
  second: 1  
second: water
```

D'avoir quelque chose comme:
```yaml
type: sum
heightmaps:
  - ground
  - 1
  - neg: water
```

Aussi il y a le fait de ne pas avoir deux types de paramètres pour `HeightmapRenderer`. Au lieu de: 
```yaml
# Type 1
type: atHeightmap  
at: ground  
place: default:stone
# Type 2
type: betweenHeightmaps
minimum: water  
maximum: ground
place: default:water_source
```

D'avoir:
```yaml
# Type 1
type: heightmapRenderer 
at: ground  
place: default:stone
# Type 2
type: heightmapRenderer
minimum: water  
maximum: ground
place: default:water_source
```

2025-02-27 14:35 UTC, pyrollo commented
Dans ce cas, pourquoi ne pas faire un truc comme les filters:
```yaml
sum:
  - ground
  - 1
  - negate: water
```
Et donc enlever le type pour ne faire que de la déduction ?
C'est moins extensible mais, si on suppore qu'il ne va pas y avoir infiniment de heightmaps calculés, c'est bien plus lisible.

2025-02-27 15:08 UTC, indyteo commented
Juste une remarque, en parlant de nombres, je ne sais pas ce qui est le mieux entre `negate` et `opposite`.
Indépendemment, au moins pour la partie code, cette opération n'est pas nécessaire : seule la multiplication l'est (en plus de l'addition qui existe déjà).
```
a - b = a + b * (-1)
```

Et je ne suis pas contre remplacer `addition` / `multiplication` (opérations binaires) par `sum` / `product` (opérations n-aires), mais je ne sais pas si ça sera très utile. Juste vérifier que ça ne vient pas complexifier le code (à coder, mais aussi à l'exécution) inutilement. Sinon si ça s'intègre bien et qu'on y trouve des usages, ça me convient très bien

2025-02-28 11:44 UTC, indyteo commented on parameters/map.sqlite
Attention tu as commit une map générée

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/BiFunctionHeightmap.java
> +    private final BiFunction<Integer, Integer, Integer> biFunction;
```suggestion
    private final IntBinaryOperator biFunction;
```

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/BiFunctionHeightmap.java
> +     */
Pour moi ce commentaire est inutile car il me semble que la doc de base de la méthode stipule qu'elle doit être appelée uniquement avec des coordonnées appartenant à sa BBOX. Et justement, la BBOX de cette heightmap, c'est l'intersection des BBOX des deux autres
```suggestion
```

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/ConstantHeightmap.java
> +        return this.value;
```suggestion
        return value;
```

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/FunctionHeightmap.java
> +    private final Function<Integer, Integer> function;
```suggestion
    private final IntUnaryOperator function;
```

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/Heightmap.java
> +    }
Ici, plutôt que d'invalider l'autre heightmap, tu pourrais juste lui donner tes valeurs actuelles, comme le suggère le nom de la méthode ("swap" = échanger) :
```suggestion
    public void swap(Heightmap other) {
        if (!other.bbox.equals(bbox))
            throw new IllegalArgumentException("Bounding boxes are not equals");
        int[] values = this.values;
        this.values = other.values;
        other.values = values;
    }
```

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/LocalMinimumHeightmap.java
> +                    localMin = base.get(i, j);
C'est un peu plus lisible comme quoi on fait un "min", et surtout on évite de lire (donc potentiellement calculer) 2x la valeur dans la heightmap de base
```suggestion
                if (base.bbox().contains(i, j))
                    localMin = Math.min(localMin, base.get(i, j));
```

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/ParamsParser.java
> +        module.addDeserializer(ReadableHeightmapParams.class, new ReadableHeightmapParams.Deserializer());
Sur les autres classes il me semble qu'on passe plutôt par une annotation style `@JsonDeserialize(using = ReadableHeightmapParams.Deserializer.class)` sur la classe `ReadableHeightmapParams`. C'est possible ici aussi ou pas ?

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/LocalMinimumHeightmap.java
> +    private final ReadableHeightmap base;
Comme c'est pas la seule classe qui implémente `ReadableHeightmap` et qui fait une opération à partir d'une `Heightmap` de base (on en a 3 actuellement : `Function`, `LocalMin` et `CappedManhattan`), ça peut valloir le coup de faire une petite classe abstraite qui a le champ `base` et qui propose l'implémentation `bbox()` par défaut en déléguant à `base.bbox()` (ça évite de le coder 3x). Pour le nom je sais pas trop, je dirais quelque chose du style `ReadableHeightmapBase`, mais n'hésite pas à proposer si tu trouve une meilleure idée

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/AdditionHeightmapParams.java
> +            (f, s) -> f + s
```suggestion
            Integer::sum
```

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/CappedManhattanHeightmapParams.java
> +    public Integer maximumDistance = 10;
Je ne pense pas qu'il y ai besoin d'un `Integer`, puisqu'on lui donne une valeur par défaut `10`, et avec l'annotation pour Jackson, je pense qu'un `int` suffit (à tester)

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ConstantHeightmapParams.java
> +    public Integer value;
```suggestion
    public int value;
```

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/FunctionListHeightmapParams.java
> +    @JsonSetter(nulls = Nulls.SKIP, contentNulls = Nulls.FAIL)
```suggestion
    @JsonSetter(nulls = Nulls.FAIL, contentNulls = Nulls.FAIL)
```

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/FunctionListHeightmapParams.java
> +    public Integer defaultValue = 0;
Même chose ici, `int` suffit à priori

2025-02-28 11:44 UTC, indyteo commented on examples/default.yaml
> +      defaultValue: 0
Concrètement, avant d'aller lire le code du `FunctionHeightmapParams`, je n'avais pas la moindre idée de ce que ce truc faisait. En fait, même après avoir lu le code, je sais ce qu'il fait maintenant, mais je n'ai toujours pas la moindre idée d'à quoi il sert (quel besoin il rempli, pourquoi c'était utile / nécessaire de faire ça ?)

À partir de ces remarques j'en tire 2 conclusions :
1. Ce paramètre n'est pas clair
    - Pourquoi "function" alors qu'il fait plutôt un "mapping" de valeurs ?
    - Pourquoi cette notation sous forme de tableau qui "dissimule" les valeurs d'origine derrière les indices (et donc on doit compter nous-même pour comprendre) ?
    - Pourquoi avoir un `defaultValue` alors qu'on pourrait simplement prendre la valeur de la heightmap d'origine si on ne nous demande pas de la remapper ? (Je comprends l'intérêt potentiel ici, mais ça ne me semble pas utile ici)
2. Nos YAML de paramètres devraient être commentés avec des explications sur "pourquoi" on fait les choses comme ça

PS : La "preuve" que c'était pas clair, si tu regardes tes tests unitaires, tu as dû te mettre des commentaires de partout pour y comprendre toi-même quelque chose 😉 

Concernant ce paramétrage de heightmap précisément, j'ai en tête quelque chose de beaucoup plus simple (mais pour lequel tu aurais besoin des `IntegerInterval`s de #77, et éventuellement une version "améliorée") :
```yaml
type: remap # On peut trouver un autre nom
base: ...
values: # On peut trouver un autre nom
  0: 0
  1: 1
  2: 8
  3: 10
  4..6: 11
  7..12: 12
  ..: 0 # On peut trouver un autre nom, mais voir explication plus bas
```

Concrètement, le principe serait le suivant : On a un ensemble d'intervalles (ouverts*) auxquels on associe une nouvelle valeur. À l'exécution, on les parcours dans l'ordre dans lequel ils sont déclarés, jusqu'à en trouver un dans lequel notre valeur se trouve, et dans ce cas on s'arrête et on renvoie la valeur associée. De la sorte, on peut avoir facilement un mapping de valeurs particulières, puis d'intervalles plus larges, jusqu'à potentiellement une valeur par défaut, et si il n'y en a pas (et que notre valeur ne match aucun intervalle défini), on renvoie la valeur brute, non modifiée, depuis la heightmap d'origine.

*Ici, les intervalles peuvent être ouverts, c'est à dire `..n` équivalent à `]-inf; n]` (`x <= n`), `n..` à `[n; +inf[` (`x >= n`) ou même `..` (`]-inf; +inf[`, ℤ) qui permettrait de donner la valeur par défaut sans avoir à coder quelque chose de spécial. Pour ne pas avoir à trop changer le code, on peut utiliser `Integer.MIN_VALUE` et `Integer.MAX_VALUE` comme -inf / +inf respectivement. Par contre, ces valeurs ne sont pas légales dans l'utilisation "box" par #77, donc il faudrait ajouter une méthode `IntegerInterval#isFinite()` qui pourrait être appelée pour s'assurer que l'intervalle est fini si nécessaire

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/LocalMinimumHeightmapParams.java
> +    public LocalMinimumHeightmapParams(ReadableHeightmapParams base, Integer range) {
```suggestion
    public LocalMinimumHeightmapParams(ReadableHeightmapParams base, int range) {
```

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ReadableHeightmapParams.java
> +     * Deserialization is done in tree ways:
🌳

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/StoredHeightmapParams.java
> +    }
```suggestion
    }

```

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/StoredHeightmapParams.java
> +    public String name;
```suggestion
    @JsonSetter(nulls = Nulls.FAIL)
    public String name;
```

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
> +        */
Ancien code
```suggestion
```

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
>          );
```suggestion
        ReadableHeightmap at = this.at.create(generation);
        return new HeightmapRenderer(
            at,
            until == null ? at : until.create(generation),
            place.create(generation.world())
        );
```

2025-02-28 11:44 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/CopyHeightmapsRenderer.java
> +public class CopyHeightmapsRenderer extends ModelRenderer<ShapesVoxelizable2d> {
Pourquoi `CopyHeightmaps` avec un `s` ?

2025-02-28 11:44 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/generation/heighmaps/LocalMinimumHeightmapTest.java
> +        );
Niveau code style, c'est plus logique de fermer sur la même ligne les parenthèses qui ont été ouvertes sur la même ligne, et d'aligner les fermetures avec les ouvertures :
```suggestion
            -1
        ));
```

2025-02-28 11:44 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/ReadableHeightmapParamsDeserializerTest.java
> +        assertEquals(700, ((ConstantHeightmapParams) params).value);
```suggestion
        ConstantHeightmapParams chp = assertInstanceOf(ConstantHeightmapParams.class, params);
        assertEquals(700, chp.value);
```

2025-02-28 15:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/ParamsParser.java
> +        module.addDeserializer(ReadableHeightmapParams.class, new ReadableHeightmapParams.Deserializer());
J'avais oublié qu'il y avait ça à voir (on en avait discuté avec Zen et ça me parait louche aussi).

Alors, Théo a raison, ça devrait être plutôt l'attribut que le `addDeserializer` mais !

...mais ça ne marche qu'avec `addDeserializer` actuellement sinon ça tombe dans une boucle infinie.

Mais c'est un bug !

Ton `ReadableHeightmapParams.Deserializer` utilise un autre `ObjectMapper` pour désérializer `CustomReadableHeightmapParams`. En mettant l'annotation, cet autre `ObjectMapper` va utiliser `ReadableHeightmapParams.Deserializer` pour faire cette désérialisation car `CustomReadableHeightmapParams` descend de `ReadableHeightmapParams` et là, c'est le drame: la boucle infinie.

Pour éviter ça, il suffit d'ajouter un `@JsonDeserialize()` à `CustomReadableHeightmapParams` pour revenir à la désérialisation standard et là ça marche.

Donc, comme dit Théo :
1 - supprimer `module.addDeserializer(ReadableHeightmapParams...`
2 - ajouter `@JsonDeserialize(using = ReadableHeightmapParams.Deserializer.class)` sur `ReadableHeightmapParams`
mais aussi:
3 - ajouter `@JsonDeserialize()` à `CustomReadableHeightmapParams`.

2025-02-28 15:56 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/ParamsParser.java
> +        module.addDeserializer(ReadableHeightmapParams.class, new ReadableHeightmapParams.Deserializer());
Note :
Pour le `OutputFormat`, le problème était de pouvoir donner un paramètre runtime au désérialiseur, ce qui ne pouvait se faire via l'annotation.
Note 2 :
Ceci implique, mais on s'en fout un peu, que seul l'`ObjectMapper` de `ParamParser` est capable de déséraliser les formats.

2025-02-28 16:01 UTC, pyrollo commented on examples/default.yaml
> +      defaultValue: 0
C'est marant, je me suis posé la même question concernant l'"ouverture" sur les bbox. Dans certains cas, il aurait été pratique d'avoir des bbox infinies (pour des motifs infinis dans certaines directions mais pas d'autres par exemple) mais malheusement j'ai eu peur que ça complique beaucoup trop tout le reste du code.
Pour les intervalles, on peut très bien avoir les deux variantes (pour les bbox aussi finalement).

2025-02-28 16:03 UTC, pyrollo commented on examples/default_.yaml
Faudra fusionner ou virer ce fichier avant de merger.

2025-02-28 16:07 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/BiFunctionHeightmap.java
> +     */
Hmm, elle hérite de `ReadableHeightmap` et il me semble pas avoir fait mention de ça. (C'est juste que `Heightmap` disait qu'il pouvait y avoir `IndexOutOfBoundsException`), bon je vais voir

2025-02-28 16:13 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/Heightmap.java
> +    }
J'utilise cette méthode pour un espèce "buffer" dans `render()` de `CopyHeightmapsRenderer`, j'avais dans l'idée d'un consommable, mais oui, le nom est mal choisi ^^

2025-02-28 16:17 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/AdditionHeightmapParams.java
> +            (f, s) -> f + s
La nouvelle classe c'est `SumHeightmapParams`, j'ai fait la modif là bas

2025-02-28 16:20 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ReadableHeightmapParams.java
> +     * Deserialization is done in tree ways:
🌳

2025-02-28 16:21 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/BiFunctionHeightmap.java
> +     */
Dans ce cas ça me semble pertinent à ajouter au niveau de la `ReadableHeightmap`. Et tu peux formuler ça de manière à ce que ça ne soit pas *obligatoire* pour les implémentation de `throw` cette exception, mais *possible*. Inspire-toi de ce qui est fait dans Java de base, exemple ici : https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Collection.html#remove(java.lang.Object) la méthode dit qu'elle peut optionnellement `throw` une `NullPointerException`, si l'implémentation ne supporte pas la valeur `null`. Mais c'est pas obligatoire. Tu peux faire quelque chose de plus ou moins similaire ici, en disant que la méthode `throw` une `IndexOutOfBoundsException` si les coordonnées sont en dehors de sa BBOX et qu'elle ne peut pas fournir de valeur

2025-02-28 16:22 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
> +        */
Ca a été remis entre temps. (Soit at, soit minimum/maximum)

2025-02-28 16:24 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/Heightmap.java
> +    }
En pratique, le fait d'échanger les valeurs et de remettre `this.values` dans `other.values` plutôt que de mettre `null` dans `other.values` ne change strictement rien aux performances, mais permet de ne pas laisser une `Heightmap` (`other`) dans un état invalide, en récupérant le contenu de `this.values` qui serait perdu sinon (et au pire si la heightmap `other` n'est plus utilisée après, eh bien le contenu des `values` sera libéré quand même, donc vraiment aucun impact mémoire

2025-02-28 16:28 UTC, zhak5388 commented on examples/default_.yaml
Oui, fichier temporaire!

2025-02-28 16:31 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ListHeightmapParams.java
> +        );
```suggestion
        ReadableHeightmap heightmap = iterator.next().create(generation);
```
Et tu baisse le minimum à 1 item dans la liste (sum (a) = a, product(a) = a, ça sert pas à grand chose mais le code est plus simple).

2025-02-28 16:33 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ListHeightmapParams.java
> +        if (list.size() < 2)
Avec la modif suggérée dans create, tu peux faire ça
```suggestion
        if (list.isEmpty())
```

2025-02-28 16:35 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ListHeightmapParams.java
> +            params.validate();
Tu dois pouvoir faire ça:
```suggestion
        list.forEach(ReadableHeightmapParams::validate);
```

2025-02-28 16:36 UTC, zhak5388 commented
Rien à voir, mais je compte resolve toutes les conversations de 2024 (Je pense pas qu'elle soit à jour)

2025-02-28 16:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ListHeightmapParams.java
> +public abstract class ListHeightmapParams extends CustomReadableHeightmapParams {
Avec les suggestions, ListHeightmapParams devient vraiment petite, à voir si c'est utile de factoriser le peu qui reste plutôt que de l'avoir dans les deux sous classes.

2025-02-28 16:51 UTC, zhak5388 commented on examples/default.yaml
> +      defaultValue: 0
J'aime bien ta syntaxe (Sur papier, j'avais un truc comme j'associe cet ensemble de nombre à ce nombre) !

Comme j'avais la distance d'un point au bord, l'étape suivante c'était d'avoir une profondeur d'eau en fonction de sa distance au bord. (A 1 voxel du bord je suis à une profondeur de 1, à deux voxels du bord, une profondeur de 8, etc..)
Initialement, j'avais fait un parametrage du style `a*x^p + b`, mais c'était pas lisible, d'ou cette autre syntaxe.

2025-03-10 10:49 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ListHeightmapParams.java
> +public abstract class ListHeightmapParams extends CustomReadableHeightmapParams {
Ce qui me gênait au début c'était le create similaire entre le deux; mais au final comme il n'y a que deux usages, j'ai supprimé `ListHeightmapParams`

2025-03-12 14:56 UTC, naulan-chrzaszcz reviewed
Je crois que ce n'est pas encore fini, j'ai regardé vite fait ce que tu as fait.

2025-03-12 14:56 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/FunctionListHeightmapParams.java
> +                return functionList.values.get(x - functionList.startInput);
```suggestion
            return functionList.values.get(x - functionList.startInput);
```

2025-03-12 14:56 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/FunctionListHeightmapParams.java
> +        return new FunctionHeightmap(functionList.base.create(generation), (x) -> {
```suggestion
        return new FunctionHeightmap(functionList.base.create(generation), x -> {
```

2025-03-12 14:56 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/FunctionListHeightmapParams.java
> +        public Integer defaultValue = 0;
```suggestion
        public int defaultValue = 0;
```

2025-03-12 14:56 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/FunctionListHeightmapParams.java
> +        public Integer startInput = 0;
```suggestion
        public int startInput = 0;
```

2025-03-12 14:56 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/LocalMinimumHeightmapParams.java
> +        localMin.base.validate();
```suggestion
        localMin.getBase().validate();
```
Il faudrait un getter pour obtenir le contenu de la variable `base`.

2025-03-12 14:56 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ReadableHeightmapParams.java
> +            throw new InputCoercionException(jsonParser, "ReadableHeightmap should be either an integer, a string or an object", node.asToken(), ReadableHeightmapParams.class);
```suggestion
            ObjectCodec codec = jsonParser.getCodec();
            JsonNode node = codec.readTree(jsonParser);
            return switch (node.getNodeType()) {
                case JsonNodeType.NUMBER -> new ConstantHeightmapParams(node.asInt());
                case JsonNodeType.STRING -> new StoredHeightmapParams(node.asText());
                case JsonNodeType.OBJECT -> codec.treeToValue(node, CustomReadableHeightmapParams.class);
                default -> throw new InputCoercionException(
                    jsonParser, 
                    "ReadableHeightmap should be either an integer, a string, or an object", 
                    node.asToken(), 
                    ReadableHeightmapParams.class
                );
            };
```
`com.fasterxml.jackson.databind.node.JsonNodeType`

2025-03-12 17:20 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/FunctionListHeightmapParams.java
> +                return functionList.values.get(x - functionList.startInput);
Je clos, elle n'existe plus cette classe : )

2025-03-12 17:22 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/LocalMinimumHeightmapParams.java
> +        localMin.base.validate();
Pourtant le membre `base` est public, non?

2025-03-13 12:27 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/LocalMinimumHeightmapParams.java
> +        localMin.base.validate();
Ouais mais c'est la règle de l'encapsulation :
The meaning of Encapsulation, is to make sure that "sensitive" data is hidden from users. To achieve this, you must:
- declare class variables/attributes as private
- provide public get and set methods to access and update the value of a private variable

https://www.w3schools.com/java/java_encapsulation.asp

2025-03-13 13:30 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/LocalMinimumHeightmapParams.java
> +        localMin.base.validate();
Sur le papier je suis entièrement d'accord avec le principe d'encapsulation (je le rappelais même ce matin à mes étudiants), mais ici on est dans une situation particulière : Jackson a besoin* que les attributs soient publics pour y accéder et leur donner la bonne valeur. Du coup, puisqu'ils sont publics, et qu'il s'agit d'une classe interne, ajouter un accesseur n'apporterait pas grand chose...

Ceci dit, il faut réfléchir à *pourquoi* on est dans cette situation (hormis Jackson) :
On se retrouve avec une classe `LocalMinimumHeightmapParams` qui au lieu de contenir ces champs comme d'habitude, contient une classe interne (ici `LocalMinParams`) qui contient ces champs. Pourquoi ? Quelle est la justification de ce choix ? N'y avait-il pas moyen de faire simple, comme dans le reste du code ?

*On pourrait le mettre privé et ajouter une annotation pour Jackson, puis configurer l'instance du parser pour qu'il aille lire les champs privés. Mais c'est beaucoup d'effort pour pas grand chose !

2025-03-14 15:02 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/Heightmap.java
> +    public Heightmap copy() {
Je n'avais pas pris en compte la modification, du coup, est ce que c'est mieux d'avoir un `copy()` et un `copy(ReadableHeightmap from)`, ou juste celui avec from? (Je me sert un peu du copy pour avoir un "clone")

2025-03-14 15:03 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/LocalMinimumHeightmap.java
> +    private final ReadableHeightmap base;
J'ai ajouté la classe abstraite, pour le nom je pense qu'on peut faire mieux, mais pas d'idée pour le moment!

2025-03-14 15:03 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
>          );
Vu que c’est soit `at` ou soit `minimum`, `maximum` , ça me semble moins utile

2025-03-14 15:03 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/generation/heighmaps/LocalMinimumHeightmapTest.java
> +        );
J'avoue que j'ai du mal à quand il y a retour à la ligne :sweat_smile:

2025-03-14 15:04 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/LocalMinimumHeightmapParams.java
> +        localMin.base.validate();
Alors, ici le choix d'avoir une classe interne `LocalMinParams` vient plutôt que je trouvais qu'il était plus lisible d'avoir un paramétrage de ce type 
```
localMin:  
  base: ground  
  range: 9
```

Plutôt que:
```
heightmap:
  type: localMin
  base: ground
  range: 9
```

Après j'aurai pu ne pas faire ça et avoir quelque chose comme 

```
heightmap:
  base: ground
  range: 9
```
Ca marcherait en déduction, seulement les paramètres ne permettent pas d'avoir une d'idée de ce que ça fait à mon avis. La première notation a l'avantage de tout de suite qualifier ce que ça fait (Minimum local).

2025-03-14 15:06 UTC, zhak5388 commented
Par rapport à [cette](https://github.com/ignfab/minalac-generator/pull/60#discussion_r1975216347) discussion, la nouvelle syntaxe a été mise!
```yaml
base:  
  manhattan:  
    base: water  
    maximumDistance: 12  
    targetValue: 0  
values:  
  -.INF..-1: 0  
  0: 0  
  1: 1  
  2: 8  
  3..3: 10  
  4..6: 11  
  7..12: 12  
  13..+.INF: 0
```

Pour les valeurs pour infinis, j'ai pris des derivations que j'ai vu sur [yaml.org](https://yaml.org/spec/1.2.2/#1032-tag-resolution): `-.inf`, `-.Inf`, `-.INF`, `+.inf`, `+.Inf` et `+.INF`. 

Les intervalles doivent former un ensemble continu.

2025-03-14 15:31 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/LocalMinimumHeightmapParams.java
> +        localMin.base.validate();
Sauf que ton exemple est inexact si j'ai bien compris la situation.

En réalité, tu transformes :
```yaml
heightmap:
  type: localMin
  base: ground
  range: 9
```
En :
```yaml
heightmap:
  localMin:
    base: ground
    range: 9
```

Ce qui ajoute un niveau d'indentation parfaitement inutile et superflu à mes yeux (il n'y aura jamais 2 clés au niveau de `heightmap:`). C'est pas vraiment plus court à écrire en YAML, et en plus ça complexifie pas mal le code des params. Je vote pour une solution "KISS" avec `type`, comme tout le reste de notre code (en plus ça fait un seul mécanisme pour l'utilisateur je trouve ça plus simple à comprendre pour lui).

2025-03-14 15:58 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/LocalMinimumHeightmapParams.java
> +        localMin.base.validate();
Oui, effectivement, ça ajoute un niveau d'indentation. Initialement, les paramètres des `ReadableHeightmap` étaient en mode `type`. (Je sais plus si il y avait une autre raison de passer à la deduction, mais oui l'indentation est génante) Du cop, tu serais pour passer en mode type, y compris pour `sum` et `product`? Du coup, ça donnerait quelque chose comme?
```yaml
heightmap:
  type: sum
  heightmaps:
    -  ground
    -  1
    -  type: product
       heightmaps: [ -1, water ]
```

2025-03-14 16:35 UTC, indyteo commented
Je n'ai que survolé le code gérant le "remap" mais je l'ai immédiatement trouvé beaucoup trop compliqué.

Je pense que tu as essayé de faire des vérifications qui me semblent absolument pas nécessaires, et même au contraire un peu limitantes. Quasiment tout le code du générateur suit la philosophie : "je fais bêtement ce qu'on me demande de faire, même si ça paraît stupide, sauf si je ne peux matériellement pas le faire".

Typiquement, tu dis :

> Les intervalles doivent former un ensemble continu.

Mais pourquoi ? Qu'est-ce qui t'oblige à imposer ça ?

Sur le même principe, pourquoi on voudrait interdire le recouvrement ?

Voici un exemple pour illustrer :
Imaginons qu'on travaille avec une heightmap contenant des valeurs de classification (représentant l'occupation du sol par exemple : [OCS GE](https://geoservices.ign.fr/ocsge)).
On veut, dans un traitement spécifique, ne considérer que quelques classes (disons 3, 7, 8 et 14) sur les 21 disponibles. On veut donc une heightmap à 0 partout sauf sur ces classes, à 1.
Dans ton exemple actuel, il faut donc écrire :
```yaml
type: remap
base: ...
values:
  0..2: 0
  3: 1
  4..6: 0
  7..8: 1
  9..13: 0
  14: 1
  15..21: 0
```

Mais franchement, c'est lourd à écrire. Alors qu'on pourrait tout simplement faire :
```yaml
type: remap
base: ...
values:
  3: 1
  7..8: 1
  14: 1
  0..21: 0
```

<details>
<summary>(Bonus)</summary>

> On pourrait même rêver d'une syntaxe :
> 
> ```yaml
> type: remap
> base: ...
> values:
>   3,7..8,14: 1
>   0..21: 0
> ```
> 
> Mais ça demanderait d'avoir une notion de "multi-interval", qu'on n'a pas dans notre code actuel.

</details>

Et ça, on a tout le nécessaire dans notre code pour le faire.

Autre exemple :
Même situation, sauf qu'on veut maintenant conserver toutes les classes, sauf qu'il y a 3 classes qui représentent la végétation (haute, basse, moyenne) et on veut les gérer de manière uniforme.
Admettons que ce sont les classes 5, 6 et 7 et qu'on veut toutes les considérer comme 7, sauf toucher au reste.

Ça devrait être aussi simple que ça au niveau du paramétrage :
```yaml
type: remap
base: ...
values:
  5..7: 7
```

Sauf qu'actuellement, en dehors des valeurs données (ici `5..7`), on obtiendra une exception. C'est dommage, on avait en réalité une valeur à notre disposition qu'on pouvait utiliser, au lieu de produire une erreur : La valeur d'origine de `base`.
Et si on voulait toutefois garder la possibilité de faire une erreur sur certaines valeurs (mais je pense pas que ça soit ni intéressant, ni utile : à quoi ça servirait ?), on pourrait avoir une valeur spéciale (`null` ?) représentant ce cas, et ainsi pouvoir écrire quelque chose du style `-.inf..+.inf: error` à la fin du remap pour garder ce comportement.

---

En bref, selon moi tu peux grandement simplifier ton implémentation, avec comme bénéfice de permettre + de choses.

Quelques indices si besoin :
- L'idée est de garder les intervalles dans l'ordre dans lequel ils sont écrits dans le YAML, donc tu auras sans doute recours à une `LinkedHashMap<IntegerIntervalParams, Integer>`
- Tu *peux* vouloir faire une erreur de validation si un intervalle est **complètement** recouvert par ses prédécesseurs, et donc inaccessible, mais dans un premier temps ça ne me semble pas fondamentalement nécessaire (au pire, il y a une valeur de la config de l'utilisateur qui n'est jamais utilisée, et peut-être que l'utilisateur n'obtiendra pas le résultat qu'il voulait parce qu'il s'est trompé dans sa config, mais toi ton code est capable de répondre à la demande (stupide) de l'utilisateur)
- Tu introduis la possibilité de lire depuis la config des `IntegerInterval` "infinis" (utilisant `Integer.MIN_VALUE` et `Integer.MAX_VALUE`), il faudrait que tu ajoutes une méthode pour vérifier si l'intervalle est fini ou pas, et l'appeler à l'endroit où était utilisé les intervalles avant, sinon ta PR modifie par effet de bord la validité de ces autres features (notamment `BoxPlaceableStructureParams` qui va faire une boucle quasi infinie dans ce cas).

---

PS : Cette logique de "on prend le 1er intervalle qui match notre valeur" pourrait aussi s'appliquer à l'envers comme par exemple on fait avec les placeables où "tout ce qui match écrase ce qui avait été défini avant", mais ça me paraît beaucoup plus simple à coder dans le sens que je t'ai proposé

2025-03-17 13:30 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/LocalMinimumHeightmap.java
> +    private final ReadableHeightmap base;
Vu que ces heightmaps sont des opérateurs, peut être s'inspirer d'un nom du genre FunctionHeightmap ou HeightmapFunction (puis HeightmapBiFunction si deux HM) ?

2025-03-17 13:35 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/LocalMinimumHeightmapParams.java
> +        localMin.base.validate();
Faut voir en global car effectivement, pour sum, product (et des truc genre negate, et autre), la syntaxe qu'on a pour les filtres de modèle (sans type) me parait plus agréable.

2025-03-17 13:37 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/LocalMinimumHeightmapParams.java
> +        localMin.base.validate();
Et du coup, tu peux simplifier en :
```
localMin: ground
range: 9
```
C'est la clé `localMin` qui fera le discriminant pour la déduction.

C'est pareil que pour sum et product, sauf que dans leur cas il n'y a qu'une clé qui contient une liste de hm.

2025-03-17 13:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/LocalMinimumHeightmapParams.java
> +        localMin.base.validate();
> Je vote pour une solution "KISS" avec `type`, comme tout le reste de notre code (en plus ça fait un seul mécanisme pour l'utilisateur je trouve ça plus simple à comprendre pour lui).

C'est déjà trop tard, on a quelques endroits qui n'utilisent plus `type` (dont le côté simple n'est vrai que côté code, côté yaml on a trouvé mieux à certains endroits). C'est surtôt côté "calculs" qu'il est, à mon avis, intéressant d'alléger la notation (model selection, déjà fait, peut être plus tard les post-processeurs).

2025-03-17 13:48 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/utils/IntegerInterval.java
> +    public boolean isImmediatelyFollowedBy(IntegerInterval other) {
Ça ressemble à une fonction que ne sert et de ne servira jamais qu'une fois ça :)

2025-03-17 13:56 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/LocalMinimumHeightmapParams.java
> +        localMin.base.validate();
En applatissant les paramètres de l'opération au même niveau que la clé ok ça me va, mais ça n'est pas comme ça que ça a été fait pour l'instant.
Côté calculs il faudrait surtout un mini langage pour pouvoir écrire des choses comme `localMin(ground, 9) + 1 - water` mais ça demande un peu plus de travail :smile:

2025-03-17 14:06 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/MultipleIntervalFunction.java
> +    }
Je trouve la proposition de Théo intéressante (on ne touche pas la heightmap si on ne trouve pas d'intervalle) donc ce code devrait sauter mais juste pour dire, tu pouvais le faire beaucoup plus simple avec un early return (pas de variable condition) et sans le predicate (on veut toujours vérifier la même condition, pas besoin de la rendre variable).

2025-03-17 15:59 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/LocalMinimumHeightmapParams.java
> +        localMin.base.validate();
En revanche, ça je ne suis pas pour car ce n'est plus du Yaml et je préfèrerais rester dans ce format (sauf quelques exceptions rares qui simplifient beaucoup la vie (pour l'iinstant on n'a que les intervales)).
On peut toujours écrire en ligne et en Yaml: `sum [{ localMin: ground, range: 9 }, 1, { negate: water }]`
C'est moins beau mais c'est pas très loin.

2025-03-18 10:10 UTC, zhak5388 commented
Merci pour vos retours.
Concernant le paramétrage des heightmaps, je vais partir sur le fait d'utiliser la clé comme discrimiant et avoir les autres paramètres au même niveau: 
```yaml
heightmap:
  localMin:
    sum: [1, ground]
  range: 7
```

Pour la "remap" heightmap, je vais partir sur la logique la valeur retournée est celle du premier intervalle contenant la valeur d'entrée. Si aucun intervalle ne contient la valeur, la valeur de retour est celle de la heightmap de base.
Concernant les intervalles infinis, je ne pense pas les implémenter car ça ne semble pas être utile pour cette PR. Ca pourrait être utile pour définir une valeur de retour par défaut différente que celle de la heightmap de base mais je ne sais si c'est forcement utile.

2025-03-18 15:22 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/LocalMinimumHeightmap.java
> +    private final ReadableHeightmap base;
Il y a déjà `FunctionHeightmap` qui applique une fonction à une heightmap. Cette classe est étendue par `FunctionHeightmap`, `LocalMinimumHeightmap` et `CappedManhattanHeightmap`. Les deux dernières ne sont pas vraiment des fonctions, du coup j'ai nommé cette classe abstraite `UnaryOperatorHeightmap`

2025-03-18 15:25 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/IntegerInterval.java
> +    public boolean isImmediatelyFollowedBy(IntegerInterval other) {
Oui, j'avais initialement deux vérification (une pour la continuité et l'autre pour l'overlap). Je vérifiais ces deux conditions separement en la passant au `verify()`. Je me suis rendu compte après que continuité => Pas d'overlap. 
Du coup c'est un résidu (Mais oui ne sert qu'une fois)
Bon, maintenant ça a disparu

2025-03-18 15:41 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParams.java
> +    }
J'ai hésité à la mettre dans une classe à part, mais vu qu'elle est relativement simple, j'ai choisi de la laisser dans la classe de paramètres

2025-03-18 16:31 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParams.java
> +    }
Honnêtement je trouve même que tu t'es compliqué la vie pour pas grande chose en declarant explicitement cette classe. Tu aurais pu garder un simple lambda, elle n'est utilisée qu'une seule fois et son implémentation est relativement triviale.

2025-03-18 17:12 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParams.java
> +    }
Oui c'est vrai!

2025-03-19 12:40 UTC, pyrollo reviewed
Des commentaires déjà

2025-03-19 12:40 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +Fields:
```suggestion
```

2025-03-19 12:40 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +This renderer places voxels using one or two heightmaps.
```suggestion
This renderer places [placeable](Placeables.md) on one heightmap (`at`) or between two (`minimum` and `maximum`).
```

2025-03-19 12:40 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +#### Using one heightmap
Je pense que j'aurais d'abort énoncé tous les paramètres et donné deux exemples (comme dans le VectorRenderer) pour éviter les répétition des autres paramètres.

2025-03-19 12:40 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `place`: [Placeable](#placeables) to place at each heightmap voxel.
```suggestion
- `place`: [Placeable](Placeables.md) to place at each heightmap voxel.
```

2025-03-19 12:40 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `place`: [Placeable](#placeables) to place at each heightmap voxel.
```suggestion
- `place`: [Placeable](Placeables.md) to place at each heightmap voxel.
```

2025-03-19 12:40 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +
Peut être ajouter une intro du genre:
```
Heightmaps can be one of those declared in `heightmaps` section (designated by their name) or a computed one as follows.
```

(ici on ne sait pas qu'on peut utiliser des heightmaps de base)

2025-03-19 12:40 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +### Constant Heightmaps
```suggestion
### Constant heightmaps
```

2025-03-19 12:40 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +### Local Minimum Heightmap Parameters
```suggestion
### Local minimum heightmaps
```
Tu as des majuscules sur beaucoup de titres. Jusqu'à présent je crois qu'on a réservé les majuscules aux sigles (WMS/"Web Map Service" par exemple).

Faut voir si on met "heightmap", "heightmaps" ou rien pour ces titres là (déjà je pense que parameters est en trop, on est dans le paramétrage jusqu'au cou).

2025-03-19 12:40 UTC, pyrollo commented on examples/places/ign.yaml
> +    longitude: 2.421
Je garderai l'IGN à la même adresse quitte à ajouer un autre fichier de location.

2025-03-19 12:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/BiFunctionHeightmap.java
> +        if (first.bbox().intersection(second.bbox()).isEmpty())
Ici il y a un binz : Tu calcule la bbox dynamiquement à chaque demande mais tu ne vérifie qu'elle n'est pas vide qu'au constructeur.

S'il n'y avait pas le tuilage je t'aurais dit : calcule et stocke la bbox ici.

Avec le tuilage les bbox vont cesser d'être constantes.

Je propose donc de supprimer ce test qui ne sert pas à grand chose et qui, avec le tuilage ne servira plus à rien.

2025-03-19 12:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/BiFunctionHeightmap.java
> +public class BiFunctionHeightmap implements ReadableHeightmap {
Y a deux choses dans cette classe:
- une heightmap calculée à partir de 2 heightmaps
- une heightmap calculée avec un calcul simple paramétrable

Je me demande si on ne devrait pas plutôt avoir une classe abstraite plus générique `BinaryOperatorHeightmap` et une `SimpleBinatyOperatorHeightmap` qui prendrait une `BiFunction` (et la `FunctionHeightmap` serait une `SimpleUnaryOperatorHeightmap`).
A voir, ça prendrait plus de sens si on avait d'autres opérateurs binaires "non simples".

2025-03-19 12:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/ConstantHeightmap.java
> +    public ConstantHeightmap(int value, WorldBBox2d bbox) {
Je me demande si l'on peut faire sans bbox car elle n'apporte pas grand chose.
On pourrait avoir une constant BBoxMax et la renvoyer mais il y a un risque que quelque part, quelqu'un itère dessus (même si cela de doit pas arriver, on a maintenant d'autres bbox sur lesquelles itérer).

2025-03-19 12:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/FunctionHeightmap.java
> +public class FunctionHeightmap extends UnaryOperatorHeightmap {
Si trop de classes, celle-ci peut devenir une sous classe de UnaryOperatorHeightmap (par exemple UnaryOperatorHeightmap.Simple)

2025-03-19 12:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/SumHeightmapParams.java
Les deux fichiers Sum et Product ne difèrent en réalité que d'une ligne, y a de la refacto à faire dans une classe abstraite (je dois avoir le même problème dans filter je me dis).

2025-03-19 12:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/StoredHeightmapParams.java
> +        if (name.isEmpty())
Si "Name cannot be empty or blank" alors:
```suggestion
        if (name.isBlank())
```

2025-03-19 12:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ConstantHeightmapParams.java
> +    @ConstructorProperties("value")
Pour la déduction:
```suggestion
    @ConstructorProperties("constant")
```

2025-03-19 12:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ConstantHeightmapParams.java
> +public class ConstantHeightmapParams implements ReadableHeightmapParams {
Elle pourrait extend CustomReadableHeightmap pour pouvoir utiliser la sytanxe `constant:`

2025-03-19 12:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/CustomReadableHeightmapParams.java
> + * Base class for all {@code ReadableHeightmap} that are typed.
Peut être à reformuler depuis qu'il n'y a plus le `type`.

2025-03-19 13:47 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +
En fait il manque une section pour expliquer le choix "stored heightmap" je pense

2025-03-19 15:45 UTC, zhak5388 commented on docs/usage/GenerationParameters.md
> +
Et je vais faire mettre la documentation de renderer et heightmaps dans des fichiers à part comme on en avait discuté

2025-03-19 15:47 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/SumHeightmapParams.java
J'ai fait le changement du coup (Les test unitaires pas completement)

2025-03-20 10:28 UTC, zhak5388 commented on docs/usage/GenerationParameters.md
> +### Local Minimum Heightmap Parameters
Ca marche, j'ai mis au singulier (vu que ça semble comme ça ailleurs)

2025-03-20 10:29 UTC, zhak5388 commented on docs/usage/GenerationParameters.md
> +#### Using one heightmap
MaJ, j'ai pris la structure de vector

2025-03-20 11:22 UTC, indyteo commented
Une petite remarque également pour essayer d'y voir plus clair sur cette grosse PR, peut-être qu'il serait intéressant de découper les modifications en plusieurs commits (actuellement il n'y a qu'un seul commit avec 71 fichiers modifiés et plusieurs features concernées, c'est un peu beaucoup)

2025-03-20 12:30 UTC, zhak5388 commented
> Une petite remarque également pour essayer d'y voir plus clair sur cette grosse PR, peut-être qu'il serait intéressant de découper les modifications en plusieurs commits (actuellement il n'y a qu'un seul commit avec 71 fichiers modifiés et plusieurs features concernées, c'est un peu beaucoup)

Oui, ça me paraissait laborieux avec les différents rebase, ça marche, hmm je pense faire deux commits dans ce cas:
+ Le premier introduisant les readable heightmaps (Classe de base, paramètres associés et documentation)
+ Le second apportant les modications aux renderers (Base, parametres et docs) + Modification yaml et SampleImplementation

2025-03-24 18:34 UTC, indyteo reviewed
Review sur le 1er commit

2025-03-24 18:34 UTC, indyteo commented on docs/usage/Heightmaps.md
> +  heightmap: 5
Euh, `matrixToHeightmap` ne demande pas une heightmap writable à tout hasard, pour y écrire les données ? Je pense que tu ferais mieux de prendre un exemple plus simple ici 😄

2025-03-24 18:34 UTC, indyteo commented on docs/usage/Heightmaps.md
> +On the example below, wherever the ground is equal to 0, the new heightmap will be equal to 21, and when the ground is -1, the new heightmap will be 34. Whenever the ground is 4, the new heightmap wi
Soit tu as changé ton exemple en cours de route, soit il manque un morceau dans cette phrase :
```suggestion
On the example below, wherever the ground is equal to 0, the new heightmap will be 21, and when the ground is between -1 and 2 (inclusive), the new heightmap will be 34. Other values will be untouched, meaning for example whenever the ground is 4, the new heightmap will remain 4 (no match, so the original value is used).
```

2025-03-24 18:34 UTC, indyteo commented on docs/usage/Heightmaps.md
> +  - - 5
Euh, c'est bizarre ta notation ici. Tu voulais dire `-5` ? Je serais d'avis de prendre un exemple simple pour commencer, avec un nombre positif histoire de ne pas (trop) embrouiller le lecteur 😄

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/BinaryOperatorHeightmap.java
> + * Abstract for all readable heightmaps that are the result of an operation on two other {@code ReadableHeightmap}.
```suggestion
 * Abstract class for all readable heightmaps that are the result of an operation on two other {@code ReadableHeightmap}.
```

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/CappedManhattanHeightmap.java
> +        return base.bbox().contains(x, y) && base.get(x, y) == targetValue;
```suggestion
        return bbox().contains(x, y) && base.get(x, y) == targetValue;
```

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/CappedManhattanHeightmap.java
> +        if (base.get(x, y) == targetValue)
```suggestion
        if (isTargetValue(x, y))
```

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/ConstantHeightmap.java
> +    public ConstantHeightmap(int value, WorldBBox2d bbox) {
Sur le papier je suis d'accord, mais voilà effectivement il y a le risque de la boucle infinie, sachant que je ne vois pas (encore ?) de point où avoir cette bbox pourrait gêner. Après, si on voulait faire les choses bien, il faudrait distinguer le côté "fini" / "infini" pour ne permettre que l'itération sur les bbox finies, et typer correctement pour que l'intersection avec une bbox finie donne bien un résultat itérable... Bref beaucoup d'efforts si on veut faire les choses proprement.
Selon moi on touche rien, c'est largement acceptable en l'état

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/Heightmap.java
> +        this.bbox = new WorldBBox2d(bbox.min(), bbox.size());
Nos bbox sont immutables, non ? Si c'est bien le cas comme il me semble, inutile d'en faire une copie 😉

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/Heightmap.java
> +     * The other heightmap will be invalidated.
```suggestion
     * The other heightmap will get the current values of this heightmap.
```

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/LocalMinimumHeightmap.java
> +                if (base.bbox().contains(i, j))
```suggestion
                if (bbox().contains(i, j))
```

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/SimpleBinaryOperatorHeightmap.java
> +    private final ReadableHeightmap second;
Euh, mais tu as pas déjà ces champs dans la classe `BinaryOperatorHeightmap` ?

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/UnaryOperatorHeightmap.java
> + * Abstract for all readable heightmaps that are the result of an operation on another {@code ReadableHeightmap}.
```suggestion
 * Abstract class for all readable heightmaps that are the result of an operation on another {@code ReadableHeightmap}.
```

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/CappedManhattanHeightmapParams.java
> +            targetValue);
```suggestion
            targetValue
        );
```

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/CustomReadableHeightmapParams.java
> +@JsonDeserialize()
```suggestion
@JsonDeserialize
```

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/CustomReadableHeightmapParams.java
> +public abstract class CustomReadableHeightmapParams implements ReadableHeightmapParams {
Je ne suis pas sûr de comprendre la distinction à faire entre `CustomReadableHeightmapParams` et `ReadableHeightmapParams`

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/OperandHeightmapParams.java
> +    private final IntBinaryOperator operand;
```suggestion
    private final IntBinaryOperator operator;
```

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/OperandHeightmapParams.java
> +    public List<ReadableHeightmapParams> heightmaps;
C'est nécessaire qu'il soit `public` ?

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ReadableHeightmapParams.java
> +                case NUMBER -> new ConstantHeightmapParams(node.asInt());
J'imagine que `NUMBER` couvre aussi les nombres décimaux. Qu'est-ce qu'il se passe quand on fait `.asInt()` si on a mit `0.7` dans la config ?

2025-03-24 18:34 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParams.java
> +        nulls = Nulls.SKIP,
Est-ce que ça a vraiment du sens de mettre un `remap` sans aucun `mapping` ?

2025-03-24 18:34 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/generation/heighmaps/SimpleBinaryOperatorHeightmapTest.java
> +        ReadableHeightmap map = new SimpleBinaryOperatorHeightmap(first, second, (x, y) -> x + y);
```suggestion
        ReadableHeightmap map = new SimpleBinaryOperatorHeightmap(first, second, Integer::sum);
```

2025-03-24 18:34 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/TestingTypedReadableHeightmapParams.java
> +    }
```suggestion
    }

```

2025-03-25 07:36 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/ConstantHeightmap.java
> +    public ConstantHeightmap(int value, WorldBBox2d bbox) {
Le problème va venir lors du tuilage. Les heightmaps calculées pourraient avoir une BBox dynamique dépendant des opérandes mais la heightmap constant n'en a pas. Le plus simple serait donc d'avoir une bbox constante (infinie, non itérable, ou aux capacités max, itérable mais faut pas).

Pour l'instant, pour le tuilage, on part sur un "reset" entre chaque tuile : reset des schedules, du model store et des heightmaps (leurs objets restent mais changent de bbox).

2025-03-25 15:58 UTC, zhak5388 commented on docs/usage/Heightmaps.md
> +  heightmap: 5
Oui, ça ne marcherait même pas haha!

2025-03-25 16:02 UTC, zhak5388 commented on docs/usage/Heightmaps.md
> +On the example below, wherever the ground is equal to 0, the new heightmap will be equal to 21, and when the ground is -1, the new heightmap will be 34. Whenever the ground is 4, the new heightmap wi
Je pense que là ça vient plutôt de ma formulation (J'avais aussi changé d'exemple en cours de route)

2025-03-25 16:05 UTC, zhak5388 commented on docs/usage/Heightmaps.md
> +  - - 5
Merci! Un double ajout du tiret

2025-03-25 16:19 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/Heightmap.java
> +        this.bbox = new WorldBBox2d(bbox.min(), bbox.size());
Ah oui, c'est le cas, mais je me demande, c'est pas étrange d'avoir deux "manières" d'initialiser les attributs? (Dans le sens pas homogène, une par référence et l'autre par copie)

2025-03-25 16:22 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/Heightmap.java
> +     * The other heightmap will be invalidated.
Merci (Ca me fait penser que je devrais me refaire une relecture)

2025-03-25 16:23 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/Heightmap.java
> +        this.bbox = new WorldBBox2d(bbox.min(), bbox.size());
Maintenant que j'y pense, c'est pas si étrange que ça

2025-03-25 16:25 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/SimpleBinaryOperatorHeightmap.java
> +    private final ReadableHeightmap second;
Oui, oublié de nettoyer

2025-03-25 16:38 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ReadableHeightmapParams.java
> +                case NUMBER -> new ConstantHeightmapParams(node.asInt());
Oui, ça le convertit, je vais mettre l'ancienne version, je préfère avoir une erreur

2025-03-25 16:40 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/OperandHeightmapParams.java
> +    public List<ReadableHeightmapParams> heightmaps;
Nope!

2025-03-25 16:52 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/CustomReadableHeightmapParams.java
> +public abstract class CustomReadableHeightmapParams implements ReadableHeightmapParams {
Je vérifierai ça, il me semble qu'il y avait une raison mais elle me semble caduc maintenant

2025-03-27 07:49 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/ConstantHeightmap.java
> +    public ConstantHeightmap(int value, WorldBBox2d bbox) {
@zhak5388 tu peux résoudre cette conversation et j'ajoute cette question sur la bbox des Constant Heightmap à un ticket jira pour ne pas oublier (MINALAC-124).

2025-03-27 09:52 UTC, pyrollo reviewed
Quelques remarques, je n'ai pas revu les tests

2025-03-27 09:52 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/Heightmap.java
> +        this.values = Arrays.copyOf(values, values.length);
Faudrait une vérification que la taille du tableau correspond bien à la bbox pour s'éviter des problèmes.

2025-03-27 09:52 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/Heightmap.java
> +            throw new IllegalArgumentException("Bounding boxes are not equals");
```suggestion
            throw new IllegalArgumentException("Bounding boxes are not equal");
```

2025-03-27 09:52 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/ReadableHeightmap.java
> +     * @throws IndexOutOfBoundsException if position is outside the heightmap and doesn't provide default value (optional).
Pas sûr de saisir le `(optional)`. Si c'est pour dire que l'exception n'arrive pas tout le temps, c'est évident donc inutile.

2025-03-27 09:52 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/OperandHeightmapParams.java
> +public abstract class OperandHeightmapParams extends CustomReadableHeightmapParams {
Le nom est un peu zarbi. Peut être `MutlipleOperandsHeightmapParams` ou `MultiOperandsHeightmapParams` serait plus clair ? Dans tous les cas il manque un `s` à `Operand` (là je vois "Paramètre de Heightmap à (un) opérande").

2025-03-27 09:52 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/OperandHeightmapParams.java
> +    private final List<ReadableHeightmapParams> heightmaps;
Ici si tu veux, tu peux prendre la terminologie "operands" / "operator"

2025-03-27 09:52 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ReadableHeightmapParams.java
> +    ReadableHeightmap create(Generation generation);
Ici on pourait se contenter du Heightmap store, sauf à cause de la ConstantHeightmap qui a besoin de la bbox du monde (pour ne pas vraiment s'en servir :'( )

2025-03-27 15:28 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/heightmaps/ReadableHeightmap.java
> +     * @throws IndexOutOfBoundsException if position is outside the heightmap and doesn't provide default value (optional).
Hmm ici c'était plutôt pour dire que les implémentations n'ont pas l'obligation de lever cette exception (Par rapport à cette [discussion](https://github.com/ignfab/minalac-generator/pull/60#discussion_r1975114313))

2025-03-27 15:56 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/ReadableHeightmapParams.java
> +    ReadableHeightmap create(Generation generation);
Todo avec numéro ticket ajouté : )

2025-03-27 16:10 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/CustomReadableHeightmapParams.java
> +public abstract class CustomReadableHeightmapParams implements ReadableHeightmapParams {
Ah, du coup la différence c'est qu'une `CustomReadableHeightmapParams` ne peut pas être de la forme nom ou entier. `ReadableHeightmapParams`peut-être une custom, nom ou entier.

2025-03-28 11:55 UTC, indyteo reviewed
Review du 2ème commit

2025-03-28 11:55 UTC, indyteo commented on docs/usage/Renderers.md
> +# Renderer
```suggestion
# Renderers
```
(en plus le fichier aussi est au pluriel)

2025-03-28 11:55 UTC, indyteo commented on docs/usage/Renderers.md
> +## Operation on world
Ça me parait plus naturel en mode "_(titre)_ Renderers... _(sous-titre)_ **Agissant** sur le monde"
```suggestion
## Operating on world
```
Après bon ça marche dans les deux sens, donc tu prends ce que tu préfères :)

(Attention il faut mettre à jour le ToC et le 2ème sous-titre aussi si tu modifies)

2025-03-28 11:55 UTC, indyteo commented on docs/usage/Renderers.md
> +**NOTE**: `at` cannot be used with `minimum` or `maximum` (`minimum` and `maximum` may and must be used together).
```suggestion
**NOTE**: `at` cannot be used with `minimum` or `maximum` (when `at` is absent, `minimum` and `maximum` must be used together).
```

2025-03-28 11:55 UTC, indyteo commented on docs/usage/Renderers.md
> +- `models`: [Selection of models](GenerationParameters.md#model-selections) to use as a filter
```suggestion
- `models`: [Selection of models](GenerationParameters.md#model-selections) to use as a filter (required, models must be voxelizable in 2d)
```

2025-03-28 11:55 UTC, indyteo commented on docs/usage/Renderers.md
> +- `to`: the name of the heightmap to use. It must exist.
Il y a du copié/collé raté dans l'air

2025-03-28 11:55 UTC, indyteo commented on examples/processes/full.yaml
> +        1: 1
Techniquement pas nécessaire du coup (mais on peut éventuellement vouloir les garder pour la clareté, pourquoi pas)

2025-03-28 11:55 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/CopyHeightmapRendererParams.java
> +     * The type of models to render (required).
```suggestion
     * Models to use as a filter (required).
```

2025-03-28 11:55 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/CopyHeightmapRendererParams.java
> +     * @param models type of models to render
```suggestion
     * @param models models to use as a filter
```

2025-03-28 11:55 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/CopyHeightmapRendererParams.java
> +     * @param from the copied heightmap
```suggestion
     * @param from the copied heightmap
     * @param to the name of the heightmap receiving the values
```

2025-03-28 11:55 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/CopyHeightmapRendererParams.java
> +    public String to;
Je me demande si tu pourrais pas mettre `StoredHeightmapParams` à ces endroits (ce qui me semblerait plus clair, et permettrait de réutiliser le mécanisme de validation codé dans cette classe). Et si nécessaire de faire une classe dédiée pour Jackson (pour lui attacher un désérialiseur), tu peux faire un `WritableHeightmapParams`.

D'ailleurs, si jamais un jour on veut valider qu'une "Stored Heightmap" est belle et bien "stored" (= déclarée dans les paramètres de génération), ça permettrait de n'avoir qu'une seule méthode `.validate()` à modifier !

Et si jamais un jour, pourquoi pas, on a une notion de `WritableHeightmap` qui émerge (et que ce ne sont plus seulement les `Heightmap` stockées qui sont écrivables), l'adaptation du reste du code deviendra alors triviale.

2025-03-28 11:55 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
> +            && (at == null || minimum != null || maximum != null))
Cette condition m'a retourné le cerveau. Ça fonctionne, mais j'espère qu'on n'aura jamais besoin de la relire 😄

2025-03-28 11:55 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
> +                at.create(generation),
Pas utile / nécessaire de créer 2x la `ReadableHeightmap` à mon sens (imagine si on implémente un système de "cache" sur les opérations effectuées sur les heightmaps, pour ne pas avoir à recalculer plusieurs fois la même valeur par exemple, bah là ça ne pourrait pas être utilisé...)

De plus, on pourrait imaginer vouloir optimiser le code du `HeightmapRenderer` pour tester `if (minimum == maximum)` ne pas faire de boucler (et donc ne pas lire (= calculer) 2x la même valeur), mais dans ton cas ça ne fonctionnerait pas

2025-03-28 11:55 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
> +                place.create(generation.world()));
```suggestion
                place.create(generation.world())
            );
```

2025-03-28 11:55 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/CopyHeightmapRenderer.java
> +     * @param from the giving heightmap
```suggestion
     * @param from the giving heightmap
     * @param to the receiving heightmap
```

2025-03-28 11:55 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/HeightmapRenderer.java
> +        for (WorldCoords2d c : minimum.bbox().intersection(maximum.bbox()).intersection(bbox))
Ça ne change rien mais c'est un peu plus lisible je trouve et ça reste uniforme avec ce que tu as fais dans `CopyHeightmapRenderer` qui était très bien :
```suggestion
        for (WorldCoords2d c : bbox.intersection(minimum.bbox()).intersection(maximum.bbox()))
```

2025-03-28 11:55 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/HeightmapRenderer.java
> +    public void render(WorldBBox3d bbox) {
Avec les calculs de heightmaps qui ne sont plus forcément triviaux, ça pourrait valoir le coup de faire un cas particulier ici `if (minimum == maximum)` pour ne pas faire 2x `.get(c)` si il s'agit de la même heightmap

2025-03-28 11:55 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/MatrixToHeightmapRenderer.java
> +     * Creates a new HeightmapRenderer.
```suggestion
     * Creates a new {@code MatrixToHeightmapRenderer}.
```

2025-03-28 11:55 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/MatrixToHeightmapRenderer.java
> +    protected void render(FloatMatrixModel model, WorldBBox3d bbox) {
La bbox de génération est ignorée ici

2025-03-28 11:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/CustomReadableHeightmapParams.java
> +public abstract class CustomReadableHeightmapParams implements ReadableHeightmapParams {
D'accord mais à quoi ça sert du coup ? Est-ce qu'on aura besoin un jour de demander une `ReadableHeightmap` qui ne soit pas exprimée sous la forme d'un nom ou d'un entier ?

2025-03-28 14:45 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
> +                at.create(generation),
C'est marant, cela me dit quelque chose, j'ai dû voir la même chose ailleurs ou zapper de commenter ça, car oui, faut pas faire 2x le create sur le même objet sauf si on veut vraiment qu'ils aient deux destins (si jamais on a des heightmaps générant de l'aléatoire ? Mais c'est pas d'actualité).

2025-03-28 14:47 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
> +                at.create(generation),
Et si tu sors deux variables minimum et maximum que tu "create" en fonction des paramètres, tu factorises le reste du code (le return).

2025-03-28 16:29 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
> +                at.create(generation),
> si jamais on a des heightmaps générant de l'aléatoire ?

C'est drôle parce que je me suis fait la même remarque initialement, et au moment où j'allais le préciser je me suis dis : Bah on fait même pas, car avec nos seeds pour avoir des résultats déterministes, je pense que l'hypothétique objet `RandomHeightmap` ne stockerait rien lui-même, et donc en avoir 1 ou 2 ne changerait rien 😄

2025-03-31 12:52 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/renderers/MatrixToHeightmapRenderer.java
> +    protected void render(FloatMatrixModel model, WorldBBox3d bbox) {
Corrigé : )

2025-03-31 12:54 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/renderers/HeightmapRenderer.java
> +    public void render(WorldBBox3d bbox) {
J'ai ajouté la condition, mais pour le coup il faut passer la même reference si on veut l'optimisation. Ca me fait penser, je vais ajouter un constructeur pour "assurer" ça

2025-03-31 12:57 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
> +                at.create(generation),
Oui, je sais pas pourquoi, comme j'étais dans une classe de paramètres, j'ai fait un raccourci dans ma tête en considérant le `create` comme un accesseur mdr

2025-03-31 13:02 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
> +            && (at == null || minimum != null || maximum != null))
Oui, j'avais fait la condition de la validité, puis j'ai fait sa négation avec de morgan haha

2025-03-31 13:03 UTC, zhak5388 commented on examples/processes/full.yaml
> +        1: 1
Oui, ce n'est plus necessaire mais un poil plus lisible je trouve

2025-04-01 09:15 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/CopyHeightmapRendererParams.java
> +    public String to;
Je viens de push la modification en passant les passant à `StoredHeightmapParams`, le `create()`de `StoredHeightmapParams` renvoie une `Heightmap` au lieu d'une `ReadableHeightmap`

2025-04-02 11:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/CustomReadableHeightmapParams.java
> +public abstract class CustomReadableHeightmapParams implements ReadableHeightmapParams {
Du coup tu peux fermer et on dans discute dans #92 si tu veux

2025-04-02 13:32 UTC, pyrollo requested changes

2025-04-02 13:32 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/MatrixToHeightmapRendererParams.java
> +        heightmap.validate();
```suggestion
```

2025-04-02 13:32 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/utils/IntegerIntervalParams.java
> +        public static FallbackParams stringToFallbackParams(String string) {
Ça pouvait être un constructeur, ça a la même signature et le même rôle.

2025-04-02 13:32 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/HeightmapRenderer.java
> +    public HeightmapRenderer(ReadableHeightmap heightmap, Placeable placeable) {
Ici je n'aurais gardé qu'un seul constructeur avec les 2 hm et fait ce qu'il faut plutôt côté param.

2025-04-02 13:32 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParams.java
> +            );
Je voyais plutôt un truc comme ça:
```suggestion
       ReadableHeightmap from;
       ReadableHeightmap to;
       if (at != null) {
            from = at.create(generation);
            to = from;
       } else {
            from = minimum.create(generation);
            to = maximum.create(generation);
       }
       return new HeightmapRenderer(from, to, place.create(generation.seed(), generation.world()));
```

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParamsTest.java
> +        assertNull(paramsWithAtMax.minimum);
Je pense que c'est inutile étant donné que cela ne valide pas, on ne devrait pas s'en servir.

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParamsTest.java
> +        assertNull(paramsWithAtMin.maximum);
Idem ici

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/ReadableHeightmapParamsDeserializerTest.java
> +        assertEquals("optional", thp.optionalField);
Je me demande pourquoi ne pas l'avoir laissé null par défaut et tester AssertNull plutôt ?
Et puis pourquoi tester ce champ, si Jackson marche, ça va marcher.

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/ReadableHeightmapParamsDeserializerTest.java
> +        assertInstanceOf(ConstantHeightmapParams.class, thp.otherHeightmapParams);
Ici je ne vois pas non plus l'intérêt de tester une heightmap imbriquée plutôt que de tester simplement "3" comme heightmap.

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParamsTest.java
> +    }
Ça vaudrait le coup de tester avec une clé qui n'est pas un intervalle et vérifier que ça échoue bien.

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParamsTest.java
> +        ));
Ici j'ai l'impression que tu testes Jacskon (ces deux propriétés sont dans le ConstructorProperties, ça semble ok de pas tester ça).

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParamsTest.java
> +        invalidMap.put(IntegerIntervalParams.FallbackParams.Deserializer.stringToFallbackParams("7..5"), 8);
```suggestion
        invalidMap.put(new IntegerIntervalParams(2, 5), 7);
        invalidMap.put(new IntegerIntervalParams(7, 5), 8);
```

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParamsTest.java
> +        validMap.put(IntegerIntervalParams.FallbackParams.Deserializer.stringToFallbackParams("2..5"), 7);
```suggestion
        validMap.put(new IntegerIntervalParams(2, 5), 7);
```

2025-04-02 13:32 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParams.java
> +    public LinkedHashMap<IntegerIntervalParams, Integer> mapping;
Cela vaudrait le coup d'exliquer en commentaire le choix LinkedHashMap plutôt que Map pour garder l'ordre.

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/placeables/voxels/TestingVoxelTypeParams.java
J'aurais gardé la version "chaine vide = invalide" plutôt que d'ajouter un flag.

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/TestingTypedReadableHeightmapParams.java
> +            throw new IllegalArgumentException("This TestingTypedReadableHeightmapParams is flagged as invalid");
```suggestion
            throw new IllegalArgumentException();
```

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/TestingTypedReadableHeightmapParams.java
> +    @JsonSetter(nulls = Nulls.SKIP)
A voir si l'annotation est nécessaire

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/CopyHeightmapRendererParamsTest.java
> +                """,
```suggestion
                """
                    type: copyHeightmap
                    from: water
                    to: ground
                """,
```

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/CopyHeightmapRendererParamsTest.java
> +                    """,
```suggestion
                """,
```

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/CopyHeightmapRendererParamsTest.java
> +                    """,
```suggestion
                """,
```

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParamsTest.java
> +            place: somethingInvisible
```suggestion
                type: heightmapRenderer
                at: ground
                place: somethingInvisible
```

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParamsTest.java
> +            place: somethingInvisible
```suggestion
                type: heightmapRenderer
                minimum: water
                maximum: ground
                place: somethingInvisible
```

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/MatrixToHeightmapRendererParamsTest.java
> +            type: matrixToHeightmap
Pas sûr pour les indentations des yaml, faudrait que ce soit homogène et homogène à ce que l'on a déjà (si possible).

2025-04-02 13:32 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/VectorRendererParamsTest.java
> +        params.borders = new TestingVoxelTypeParams("notValid", false);
Ici vaudrait mieux garder l'ancienne méthode, plus concise.

2025-04-02 13:34 UTC, pyrollo commented on docs/usage/GenerationParameters.md
Ici, il faudrait ajouter des liens du genre `[renderer](Renderers.md)` sur un certain nombre de mots `renderer` et pareil avec `[heightmap](Heightmaps.md)`.

EDIT: les heightmap y a déja plusieurs lien.

2025-04-02 13:41 UTC, pyrollo requested changes

2025-04-02 13:41 UTC, pyrollo commented on docs/usage/GenerationParameters.md
>    - _`<name>`_: Unique name of the renderer
Par exemple:
```suggestion
  - _`<name>`_: Unique name of the [renderer](Renderers.md)
```

2025-04-02 13:41 UTC, pyrollo commented on docs/usage/Renderers.md
> +- `heightmap`: Name of the ground heightmap (required, updated according to leveling)
```suggestion
- `heightmap`: Ground [heightmap](Heightmaps.md), should be a stored heightmap, will be updated according to leveling (required)
```

2025-04-02 13:41 UTC, pyrollo commented on docs/usage/Renderers.md
> +- `heightmap`: Name of the heightmap to use (required)
```suggestion
- `heightmap`: [Heightmap](Heightmaps.md) to use (required)
```

2025-04-02 13:41 UTC, pyrollo commented on docs/usage/Renderers.md
> +- `to`: Name of the heightmap to use. It must exist.
```suggestion
- `from`: [Heightmap](Heightmaps.md) from which copy values (required).
- `to`: [Heightmap](Heightmaps.md) to which copy values, should be a stored heightmap (required,  will be updated).
```

2025-04-02 14:04 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParams.java
> +    public LinkedHashMap<IntegerIntervalParams, Integer> mapping;
Après concrètement je crois que Jackson utilise naturellement l'implémentation `LinkedHashMap` quand on demande `Map`. Mais oui, ici l'intérêt est d'expliciter notre demande pour le forcer à utiliser l'implémentation qu'on veut, donc je suis d'accord avec l'idée de l'expliciter en commentaire aussi

2025-04-02 14:04 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/utils/IntegerIntervalParams.java
> +        public static FallbackParams stringToFallbackParams(String string) {
`super()` c'est pas super

2025-04-02 14:12 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/placeables/voxels/TestingVoxelTypeParams.java
Bof, j'aime bien le côté explicite avec le flag, perso

2025-04-02 14:15 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/utils/IntegerIntervalParams.java
> +        public static FallbackParams stringToFallbackParams(String string) {
Java 22 est `super` cependant mais on est en 21

2025-04-02 14:19 UTC, indyteo commented on docs/usage/Renderers.md
> +- `heightmap`: Name of the ground heightmap (required, updated according to leveling)
Du coup :
```suggestion
- `heightmap`: Ground [heightmap](Heightmaps.md#stored-heightmap), should be a stored heightmap, will be updated according to leveling (required)
```
ou :
```suggestion
- `heightmap`: Ground [heightmap](Heightmaps.md), should be a [stored heightmap](Heightmaps.md#stored-heightmap), will be updated according to leveling (required)
```

2025-04-02 14:30 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParamsTest.java
> +        assertNull(paramsWithAtMax.minimum);
Tu parles du `assertNull`?

2025-04-02 14:39 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/ReadableHeightmapParamsDeserializerTest.java
> +        assertInstanceOf(ConstantHeightmapParams.class, thp.otherHeightmapParams);
Je vais virer ce test unitaire, on est plus dans dans du typé mais de la deduction

2025-04-02 15:00 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/placeables/voxels/TestingVoxelTypeParams.java
J'ai commencé à changer de syntaxe. Personnellement, je trouve ça moins évident, je préfère un constructeur ou je met explicitement un `false`

2025-04-02 15:00 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/TestingTypedReadableHeightmapParams.java
> +    @JsonSetter(nulls = Nulls.SKIP)
Pas necessaire, je l'ai enlevé

2025-04-02 15:01 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/placeables/voxels/TestingVoxelTypeParams.java
C'est quand même bien plus lourd

2025-04-02 15:03 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/ReadableHeightmapParamsDeserializerTest.java
> +        assertEquals("optional", thp.optionalField);
J'ai enlevé ce test vu que déduction

2025-04-02 15:10 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParamsTest.java
> +        ));
J'ai viré, mais c'était plutôt pour s'assurer que dans la classe de paramètres ces deux champs sont requis, genre je voulais m'assurer qu'on les passe pas en optionnel ou autre (et pas tester que jackson s'assure que c'est requis)

2025-04-02 15:13 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParamsTest.java
> +        invalidMap.put(IntegerIntervalParams.FallbackParams.Deserializer.stringToFallbackParams("7..5"), 8);
`IntegerIntervalParams` est abstraite mais je vais mettre `FallbackParams` à la place

2025-04-02 15:19 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/utils/IntegerIntervalParams.java
> +        public static FallbackParams stringToFallbackParams(String string) {
On est en 17 ici

2025-04-02 15:22 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/placeables/voxels/TestingVoxelTypeParams.java
Pas tant que ça, et puis c'est pour les tests unitaires, pour moi c'est plus important qu'on comprenne ce qu'ils font quand on les lis

2025-04-02 15:53 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/utils/IntegerIntervalParams.java
> +        public static FallbackParams stringToFallbackParams(String string) {
Et je viens de tilter mais non c'est pas le rôle du constructeur selon moi de faire la désérialisation. Sauf si tu parles d'un constructeur d'une classe de params, dans quel cas pourquoi pas, mais je trouve que c'est bien là où c'est codé actuellement

2025-04-02 16:19 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/placeables/voxels/TestingVoxelTypeParams.java
@indyteo @pyrollo On a pensé à une syntaxe (Elle est dans `HeightmapRendererParamsTest`), un aperçu:
```java
HeightmapRendererParams paramsWithAt = new HeightmapRendererParams(TestingPlaceableParams.VALID);
paramsWithAt.minimum = TestingHeightmapParams.VALID;
paramsWithAt.maximum = TestingHeightmapParams.INVALID;
```
Qu'est ce que tu en penses? (Je pense l'introduire pour mes tests)

2025-04-02 19:48 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/placeables/voxels/TestingVoxelTypeParams.java
C'était globalement ce que je voulais proposer, mais tu as été plus rapide que moi 😄

Et je me disais même pourquoi pas avoir une classe un peu globale aux tests genre `Testing` qui regrouperait ces différentes constantes, et une classe imbriquée `Invalid` pour les versions invalides (ce qui donnerait `Testing.HEIGHTMAP` et `Testing.Invalid.HEIGHTMAP`, ça me paraît assez explicite et comme ça c'est facile de trouver les faux objets dont on peut avoir besoin dans des tests parfois ?)

2025-04-03 06:28 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParamsTest.java
> +        ));
Oki ! J'ai vu ailleurs qu'on le faisait.

2025-04-03 06:31 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/placeables/voxels/TestingVoxelTypeParams.java
L'idée de `Testing` est plaisante, en revanche, je pense que l'instanciation des constantes doit rester dans la classe concernée (elle dépend beaucoup de l'implémentation, flag, valeur de variable, voire sous-classe spécifique). Du coup `Testing` serait une collection de raccourcis avec un risque de retrouver les deux noms (classe concernée, ou `Testing`) au long des tests (c'est peut être pas un problème).

En tout cas, pour cette PR on va se contenter des constantes et il devrait y avoir une autre PR pour généraliser cette façon de faire. On pourra voir à cette occasion.

2025-04-03 06:35 UTC, pyrollo commented on docs/usage/Renderers.md
> +- `heightmap`: Name of the ground heightmap (required, updated according to leveling)
J'aime bien la v2 car, si on fait bien les choses, Heightmaps.md devrait contenir en début de page une définition de ce qu'est une heightmap (on a tendance à oublier de définir nos concepts dans notre doc).

2025-04-03 09:16 UTC, zhak5388 commented on docs/usage/Renderers.md
> +- `heightmap`: Name of the ground heightmap (required, updated according to leveling)
J'ai ajouté une petite section pour définir les champs de hauteur (heightmap)

2025-04-03 09:17 UTC, zhak5388 commented on docs/usage/GenerationParameters.md
Je pense que ça devrait être bon

2025-04-03 14:26 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/VectorRendererParamsTest.java
> +        params.borders = new TestingVoxelTypeParams("notValid", false);
J'ai remplacé par `VALID`/`INVALID` (hors de ma PR, mais j'ai du modifié ce fichier pour cette PR)

2025-04-03 14:35 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/CopyHeightmapRendererParamsTest.java
> +                """,
Yes, j'avais pas vu, j'ai corrigé pour que ça soit uniforme

2025-04-03 14:36 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/MatrixToHeightmapRendererParamsTest.java
> +            type: matrixToHeightmap
Bon on est pas hyper homogène j'ai l'impression haha, j'ai fait un truc homogène dans mes classes

2025-04-03 15:00 UTC, indyteo commented on suppressions.xml
> +    <suppress checks="StaticVariableName" files=".*[\\/]src[\\/]test[\\/].*[\\/]Testing.*\.java"/>
Pourquoi avoir désactivé cette règle ? Je pense que tu as mal lu sa description, car elle t'indiquait le problème dans ton code :
> Checks that `static`, **non-`final`** variable names conform to a specified pattern. 

https://checkstyle.org/checks/naming/staticvariablename.html#StaticVariableName

2025-04-03 15:15 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/utils/IntegerIntervalParams.java
> +        public static FallbackParams stringToFallbackParams(String string) {
Je vais le laisser tel quel finalement (et oui on est en 17, 21 c'est la version installée sur ma machine)

2025-04-03 15:15 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/parameters/heightmaps/CustomReadableHeightmapParams.java
> +public abstract class CustomReadableHeightmapParams implements ReadableHeightmapParams {
Ok, ça marche!

2025-04-03 16:02 UTC, zhak5388 commented on suppressions.xml
> +    <suppress checks="StaticVariableName" files=".*[\\/]src[\\/]test[\\/].*[\\/]Testing.*\.java"/>
Merci! (Oui, j'ai lu un peu trop rapidement et je m'étais dit "c'est quand même bizarre.. c'est quand même courant de mettre en lettres capitales" mdr)

2025-04-04 13:19 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/ProductHeightmapTest.java
> +
```suggestion
```
Sauf si je me trompe, c'est le même test que le suivant.

2025-04-04 13:47 UTC, pyrollo requested changes
Rien de fondamental mais quelques petites corrections avant de merge

2025-04-04 13:47 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParamsTest.java
> +        RemapHeightmapParams paramsBaseInvalid = new RemapHeightmapParams(invalidBase, validMap);
Ça ne me parait pas nécessaire de créer une variable intermédiaire:
```suggestion
        LinkedHashMap<IntegerIntervalParams, Integer> validMap = new LinkedHashMap<>();
        validMap.put(new IntegerIntervalParams.FallbackParams(2, 5), 7);

        RemapHeightmapParams paramsBaseInvalid = new RemapHeightmapParams(TestingHeightmapParams.INVALID, validMap);
```

2025-04-04 13:47 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParamsTest.java
> +        RemapHeightmapParams paramsMapInvalid = new RemapHeightmapParams(validBase, invalidMap);
Ici non plus:
```suggestion
        LinkedHashMap<IntegerIntervalParams, Integer> invalidMap = new LinkedHashMap<>();
        invalidMap.put(new IntegerIntervalParams.FallbackParams(2, 5), 7);
        invalidMap.put(new IntegerIntervalParams.FallbackParams(7, 5), 8);

        RemapHeightmapParams paramsMapInvalid = new RemapHeightmapParams(TestingHeightmapParams.VALID, invalidMap);
```

2025-04-04 13:47 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/SumHeightmapParamsTest.java
> +    public void testValidate() {
J'ai un petit doute sur ce test. En fait il fait exactement la même chose et teste la même fonction que dans Product. Pas sûr qu'il faille le garder. Peut être mettre un commentaire dans les deux tests (Product et Sum) pour indiquer qu'ils utilisent le même test ? Ou bien le mettre dans un fichier `MultiOperandHeightmapParamsTest` ? Ou (peut être encore mieux) mettre les trois tests dans ce même fichier, qui correspond au fichier testé ?

2025-04-04 13:47 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/HeightmapRendererParamsTest.java
> +    }
Tu as peut être aussi les cas `minimum` tout seul et `maximum` tout seul qui doivent Throw.
(ici ou peut être dans `MinMax`)

2025-04-04 13:47 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/MatrixToHeightmapRendererParamsTest.java
> +            new StoredHeightmapParams("hi")
Du coup ici tu peux utiliser `TestingHeightmapParams.VALID` et après `TestingHeightmapParams.INVALID`.

2025-04-04 13:49 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/ProductHeightmapTest.java
> +
Oui, en effet!

2025-04-04 13:56 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/SumHeightmapParamsTest.java
> +    public void testValidate() {
Au début j'étais tenter de faire un `MultiOperandsHeightmapParamsTest` avec `testValidate()`, `testDeserializeSum()` et `testDeserializeProduct()`, puis je me suis dit `MultiOperandsHeightmapParams` est abstraite, autant faire les tests sur les concretes quitte à ce que ça soit redondant

2025-04-04 13:57 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/renderers/MatrixToHeightmapRendererParamsTest.java
> +            new StoredHeightmapParams("hi")
Un stored qui a échappé au CTRL + F

2025-04-04 14:06 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/RemapHeightmapParamsTest.java
> +        RemapHeightmapParams paramsMapInvalid = new RemapHeightmapParams(validBase, invalidMap);
Oui, nettoyage pas complet!

2025-04-04 14:34 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/parameters/heightmaps/SumHeightmapParamsTest.java
> +    public void testValidate() {
J'ai fait un `MultiOperandsHeightmapParamsTest` avec les 3 tests

2025-04-04 14:43 UTC, pyrollo approved these changes

2025-04-04 14:58 UTC, merged