Deserialization des post-processeurs "parse" et "default"
ignfab/voxatile pull request #62
Opened 2024-11-04 10:08 UTC by naulan-chrzaszcz

### Type of modification

Types:
- Documentation
  - Javadoc Comments
  - Markdown Files
  - Code Comments
- Code
  - processors
    - post
  - parameters
    - processors
      - post
- ~~Tests~~ (TODO)

### Issue

MINALAC-80
MINALAC-78

### Changes

Ajout des classes `MetadataDefaultPostProcessorParams` et `MetadataParsePostProcessorParams`.

#### Feature description

Création de 2 nouvelles classes :
- MetadataDefaultPostProcessorParams.java
- MetadataParsePostProcessorParams.java

Ajout de la classe MetadataDefaultPostProcessorParams pour permettre de set une valeurs par défaut dans la metadonnée du model lorsque la valeur de la metadonnée est null

Enregistrement des params dans le fichier SimpleImplementation

#### Showcase

```yaml
sources:
  # ...
  bati:
    modelType: building
    provider:
      type: wfs
      url: https://data.geopf.fr/wfs/wfs
      features: BDTOPO_V3:batiment
    processor:
      type: geoToolsVector
    postProcessors:
      - type: copy
        metadata: hauteur
        to: height
      - type: parse
        metadata: height
        as: integer
      - type: default
        metadata: height
        value: 20
        as: integer
```

### Reason

Les PostProcessors, disparus du fichier SampleImplementation où mes renderers #24 en avaient besoin, je dois mettre à jour le fonctionnement des PostProcessors pour ensuite mettre à jour ma PR #24 afin qu'elle puisse refonctionner.

### TODOs

- [x] Faire le test que MetadataDefaultPostProcessorParams

### Self-checks

- [x] The code has unit tests associated
- [x] The code has Javadoc Comments associated
- [x] Complex / Unexpected code is explained / justified with a small comment
- [x] Relevant documentation inside the `/docs` folder has been updated
- [x] All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)
- [x] Git history is clean (each commit accomplish a single task and describe it accordingly)
- [x] The texts have been proofread (documentation, error messages, logs, comments...)

2024-11-06 09:54 UTC, pyrollo reviewed
Quelques commentaires.

2024-11-06 09:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +    public final Class<T> to;
Ce serait surement plus simple de le garder en String et d'ajouter une validation (avec une méthode `validate()`) comme dans les autres paramètres.

2024-11-06 09:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +            if (to == Double.class) {
Avec le "to" en String, tu pouvais simplement faire un `switch`.

2024-11-06 09:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +                case "Boolean" -> (Class<?>) Boolean.class;
```suggestion
                case "integer" -> (Class<?>) Integer.class;
                case "decimal" -> (Class<?>) Double.class;
                case "text" -> (Class<?>) String.class;
                case "boolean" -> (Class<?>) Boolean.class;
```
(Les termes doivent être en camelCase)

2024-11-06 09:54 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `failurePolicy`: what to do in case of failure (e.g. exception in `parser`)
Faut expliquer la valeur à mettre.

2024-11-06 09:54 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `failWhenParserReturnNull`: whether `null` return value from `parser` is a failure.
Faut être plus clair. "parser" et "null" ne dira rien à un utilisateur qui ne connait pas notre code.
Le nom est sans doute à revoir aussi.

2024-11-06 09:54 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +**Extra parameters**:
Si les paramètres sont optionels, il faut indiquer la valeur par défaut.

2024-11-06 09:54 UTC, pyrollo commented on examples/default.yaml
> +        value: 20
Suggestion de nommage
```suggestion
      - type: copy
        meta: hauteur
        to: height
      - type: parse
        meta: height
        as: integer
      - type: default
        meta: height
        value: 20
```

2024-11-06 09:54 UTC, pyrollo commented on examples/minecraft.yaml
> +        value: 20
Comme discutté, on va avoir besoin de typer la valeur:
```suggestion
      - type: default
        name: height
        value: 20
        as: integer
```

2024-11-06 10:44 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +            if (to == Double.class) {
Ouaip, c'était sur quoi je travaillé ce matin.
Je viens de push 🚀

2024-11-06 10:45 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +    public final Class<T> to;
Idem, j'étais en train de méditer sur mon deserializer car c'était pas uniforme

2024-11-06 10:46 UTC, naulan-chrzaszcz commented on examples/default.yaml
> +        value: 20
J'étais parti sur `metadata` au lieu de `meta`

2024-11-06 10:51 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +    public final Class<T> to;
J'pense que je dois faire la même chose avec `ParsingFailurePolicyDeserializer`

2024-11-07 13:59 UTC, pyrollo requested changes

2024-11-07 13:59 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +        List<String> validAsValue = List.of("integer", "decimal", "text", "boolean");
Il y a duplication avec le switch ici. Cela pose deux problèmes:
- Si on veut ajouter/modifier une valeur, faut le faire aux deux endroits.
- Il y a un risque de bug car rien n'assure que les deux listes sont les mêmes.

--> Mettre la liste dans une collection (et trouver une solution intelligente pour ça :) )

... imagine que tu en aies besoin aussi dans un autre postprocesseur (ça peut arriver très très vite ;) )

2024-11-07 13:59 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +                return ParsingFailurePolicy.valueOf(parser.getText().toUpperCase());
Pas sûr que ce soit la bonne façon de faire. A voir quand tu auras documenté ça.

2024-11-07 13:59 UTC, pyrollo commented on examples/default.yaml
> +        value: 20
Oui ça devrait aller aussi même si c'est un peu long (ça peut être `field`, `data`... je pense qu'on en discutera plus tard quand on aura quelques fichiers de conf).

2024-11-07 13:59 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `doNotOverwriteExistingTo` (optional): Whether to abort if copy would overwrite existing metadata
```suggestion
- `keepExisting` (optional): Whether to abort if copy would overwrite existing metadata
```

2024-11-07 13:59 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `from` (required): Original name of the metadata to copy
```suggestion
- `metadata` (required): Name of the metadata to copy
```

2024-11-07 13:59 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +**Type**: copyMetadata
```suggestion
**Type**: copy
```

2024-11-07 13:59 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `to` (required): Destination name to store the copied metadata
```suggestion
- `to` (required): Name of destination metadata
```

2024-11-07 13:59 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `abortIfFromIsAbsent` (optional): Whether to abort if metadata is absent
abort what ?

2024-11-07 13:59 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `failWhenMissingMetadata`: whether the absence of metadata is a failure.
Peut être mieux en plus court:
```suggestion
- `failIfMissing`: whether the absence of metadata is a failure.
```

2024-11-07 13:59 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `name`: the name of the metadata.
```suggestion
- `metadata`: the name of the metadata.
```

2024-11-07 13:59 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +
`as` + Liste des types

2024-11-07 14:31 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +                return ParsingFailurePolicy.valueOf(parser.getText().toUpperCase());
C'était l'ancienne méthode, j'ai tout mis dans la fonction `validate`.

2024-11-08 12:40 UTC, indyteo commented on docs/usage/GenerationParameters.md
Il faut uniformiser la doc avec les mêmes remarques qui ont été faites sur la 1ère PR

2024-11-08 12:40 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +            default -> new Object(); // Unexpected case: this should be unreachable
Si c'est un cas impossible, mieux vaut faire une erreur à mon sens (montrer que c'est bel et bien impossible) :
```java
throw new IllegalStateException();
```
(IllegalState parce qu'on est dans un état dans lequel on ne devrait pas être, avec une valeur de `as` qui ne correspond pas à ce qu'on devrait avoir si on avait passé la validation)

2024-11-08 12:40 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +    public String failurePolicy = "remove";
Je ne suis pas forcément convaincu que ça soit la meilleure valeur par défaut.

Quel comportement, en tant qu'utilisateur qui ne connait pas le fonctionnement, tu t'attendrais à avoir (sans spécifier cette option), lorsqu'une erreur se produit au moment de parser ta donnée ?

2024-11-08 12:40 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +public class MetadataParsePostProcessorParams<T> extends PostProcessorParams {
Ton `T` vient te polluer inutilement, tu devrais le faire disparaître d'ici

2024-11-08 12:40 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataDefaultPostProcessor.java
> +    public Model process(Model model) throws GenerationFailedException, IgnorableException {
```suggestion
    public Model process(Model model) {
```
Lorsque des exceptions ne peuvent pas se produire dans ta méthode, ça n'a pas grande utilité de les indiquer (sinon tu vas te retrouver à vouloir les tester alors qu'elles sont impossibles)

2024-11-12 07:49 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +  - error
C'est un peu le minimum syndical. Imagine que tu te retrouvres devant cette doc sans connaitre le générateur. Est-ce suffisant pour toi ?

2024-11-13 15:36 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +        List<String> validAsValue = List.of("integer", "decimal", "text", "boolean");
Okay, pour les types -> j'ai crée une `enum` portant le nom `SupportedTypePostProcessor`

2024-11-13 16:00 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +        List<String> validAsValue = List.of("integer", "decimal", "text", "boolean");
Pas sûr qu'une enum suffise pour factoriser.

2024-11-18 16:10 UTC, naulan-chrzaszcz commented
Je dois refaire au propre mes commits car il y a eu un petit problème sur ma machine lors des ajouts des nouveaux fichiers

2024-11-18 16:12 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +            default -> new Object(); // Unexpected case: this should be unreachable
Le code a changé de structure

2024-11-18 16:13 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +        List<String> validAsValue = List.of("integer", "decimal", "text", "boolean");
Nouvelle solution poussé
Edit: merci pour l'aide

2024-11-19 15:36 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataDefaultPostProcessor.java
> +    public Model process(Model model) throws GenerationFailedException, IgnorableException {
Je ne sais même plus pourquoi j'ai ecrit ca

2024-11-19 15:56 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +    public String failurePolicy = "remove";
Qu'on ignore le model ?

2024-11-19 15:57 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +  - error
J'ai ajouté le comportement de chaque valeur

2024-11-19 16:00 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +- `to` (required): Destination name to store the copied metadata
Fait sur la PR #57

2024-11-19 16:00 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +- `doNotOverwriteExistingTo` (optional): Whether to abort if copy would overwrite existing metadata
Fait sur la PR #57

2024-11-19 18:23 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +    public String failurePolicy = "remove";
Personnellement je dirais plutôt une erreur. Lorsqu'une erreur se produit, pour moi par défaut, il faut qu'il y ai une erreur. Ensuite on peut spécifier l'option pour dire d'ignorer cette erreur, ou alors de supprimer la métadonnée, ou le modèle... Bref choisir notre politique de gestion de l'erreur. Mais éviter une silent failure par défaut

2024-11-20 15:38 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +  - `error`: A fatal error occurs, and the process stops immediately.
Si j'ai bien compris:
```suggestion
- `failurePolicy` (optional, text): What to do if data parsing fails:
  - `skip`: The model is skipped.
  - `remove`: The metadata is removed.
  - `ignore`: Failure is ignored, nothing is done.
  - `error`: An error occurs, and the generation stops (default).
```
Je ne suis pas sûr de la conséquence (la génération s'arrête?) pour le dernier.

2024-11-20 15:39 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `failWhenParserReturnNull` (optional, boolean): whether `null` return value from `parser` is a failure.
```suggestion
- `failIfMissing` (optional, boolean): whether the absence of metadata is a failure.
- `failWhenParserReturnNull` (optional, boolean): whether `null` return value from `parser` is a failure.
```
Manque la valeur par défaut.

2024-11-20 15:41 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +  - `text`: The value will be treated as plain text (a string).
Peut être plus simple (c'est déjà indiqué au dessus qu'il va y avoir convertion):
```suggestion
  - `integer` (a whole number)
  - `decimal` (a number with decimals)
  - `boolean` (true/false or yes/no)
  - `text` (a string)
```

2024-11-20 15:42 UTC, pyrollo commented on examples/default.yaml
> +        to: integer
Pas sûr mais ça parait plus homogène avec `default`:
```suggestion
        as: integer
```

2024-11-21 10:23 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +  - `error`: A fatal error occurs, and the process stops immediately.
D'apres le code, oui : 
```java
// ...
        /**
         * Throws an {@link GenerationFailedException} causing a fatal error.
         */
        ERROR
// ...
```

2024-11-21 10:27 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
@pyrollo, tu veux que j'ecrit `Fields:` a la place de `**extra parameters**` ?

2024-11-21 10:33 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +- `failWhenParserReturnNull`: whether `null` return value from `parser` is a failure.
En réalité, je me suis fait aider par ChatGPT pour cette version du texte que je viens de poussé (je suis pas bon en anglais)

2024-11-21 10:43 UTC, pyrollo commented on docs/usage/GenerationParameters.md
Je pense que @indyteo parle de ta PR.

Par rapport à la mienne, elle n'est pas encore fusionnée donc elle ne compte pas. En revanche, possible qu'un jour on se fasse une passe sur la doc. Il va de toutes façons falloir découper GenerationParameters.md en plusieurs fichiers (au moins un pour les renderers, un autre pour les sources et les processeurs)

2024-11-21 10:45 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `failurePolicy` (optional, text): What to do if an error occurs (e.g., during data parsing):
```suggestion
- `failurePolicy` (optional, text): What to do if parsing fails:
```
Ne pas parler d'"error" ici vu que ce n'est qu'un echec pour l'instant et qu'on le transforme eventuellement en erreur plus bas.

2024-11-21 10:45 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
(Oui, c'était une question a part)

2024-11-21 10:47 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
Normalement, la documentation est uniformiser. Je peux resolve cette remarque ?
~~Manque un truc dans la documentation du default parameters~~

2024-11-21 10:56 UTC, naulan-chrzaszcz commented
Il manque un test unitaire pour le post processeur `default`

2024-11-21 11:06 UTC, pyrollo requested changes
Quelques remarques déjà, avant que tu ne re-re-re-re-pousses

2024-11-21 11:06 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `failWhenParserReturnNull` (optional, default `no`): specifies whether the `parser` should be considered as failed when it returns an invalid or empty result.
"ParserReturnNull" n'est vraiment pas user friendly.
```suggestion
- `failIfNotParsable` (optional, default `no`): fails if not able to parse.
```

C'est un peu tard, mais je me dis qu'on aurait pu faire un truc vachement mieux:

- `ifMissing` : `skip` | `remove` | `ignore` | `error`
- `ifNotParsable`: `skip` | `remove` | `ignore` | `error`

ça nécéssiterai une petite modif du postprocesseur.

2024-11-21 11:06 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/FailurePolicyParser.java
> +        return PARSERS.get(key.toLowerCase());
```suggestion
        return PARSERS.get(key);
```

2024-11-21 11:06 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +        return PARSERS.get(key.toLowerCase());
```suggestion
        return PARSERS.get(key);
```

2024-11-21 11:06 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +            throw new IllegalArgumentException("Invalid value for 'as': " + as + ". Expected one of " + ValueParser.avalaible());
Si tu mettais ça dans une méthode `validate(string)` de ValueParser, tu pouvais t'économiser la méthode `available()`

2024-11-21 11:06 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/FailurePolicyParser.java
> +package com.ignfab.minalac.generator.parameters.processors.post.parsers;
Je me demande si cette `FailurePolicyParser` n'est pas plus générique que ça.
Elle n'est pas spécifique au parser mais pourrait être réutilisée par d'autres post-processeurs. Je la mettrais bien un cran plus haut.

2024-11-21 11:06 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/FailurePolicyParser.java
> +    }
En remplaçant ça par un `validate` tu t'économises la méthode `available`

2024-11-21 11:06 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +    }
En remplaçant ça par un `validate` tu t'économises la méthode `available`

2024-11-21 11:06 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +        }
Duplication avec getParser

2024-11-21 11:06 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +        }
Duplication avec getType

2024-11-21 12:20 UTC, naulan-chrzaszcz commented
> Quelques remarques déjà, avant que tu ne re-re-re-re-pousses

L'historique du repository avec mes forces push doit être jolie a voir 🤪

2024-11-21 12:22 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +- `failWhenParserReturnNull` (optional, default `no`): specifies whether the `parser` should be considered as failed when it returns an invalid or empty result.
Le changement est rapide a faire, je vais ecrire plutot `ifMissing` et `ifNotParsable`

2024-11-21 12:23 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +            throw new IllegalArgumentException("Invalid value for 'as': " + as + ". Expected one of " + ValueParser.avalaible());
Okay
Est-ce que la fonction `available` est à garder au final ?

2024-11-21 12:26 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/FailurePolicyParser.java
> +        return PARSERS.get(key.toLowerCase());
Ce n'est pas bien de faire ce truc ?

2024-11-21 13:03 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +- `failWhenParserReturnNull` (optional, default `no`): specifies whether the `parser` should be considered as failed when it returns an invalid or empty result.
Je regarde le code, et j'me dit que ce changement va supprimer un champ (le failurePolicy)

2024-11-21 13:05 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `failWhenParserReturnNull` (optional, default `no`): specifies whether the `parser` should be considered as failed when it returns an invalid or empty result.
Oui, c'est le but

2024-11-21 13:06 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +            throw new IllegalArgumentException("Invalid value for 'as': " + as + ". Expected one of " + ValueParser.avalaible());
", tu pouvais t'économiser la méthode available()" =  tu peux t'en passer

2024-11-21 13:08 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/FailurePolicyParser.java
> +        return PARSERS.get(key.toLowerCase());
Ben non. La doc dit "skip", pas "sKiP". En plus si tu veux faire du camelCase, tu es eu.

2024-11-21 14:35 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +        }
J'ai ecrit une fonction validate()

2024-11-21 17:00 UTC, indyteo reviewed
1ère partie du review, je continue après

2024-11-21 17:00 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +- `as` (required, text): the type of parsed value :
```suggestion
- `as` (required, text): the type of parsed value:
```

2024-11-21 17:00 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +- `IfMissing` (optional, default `no`): What to do if have an absence of metadata :
```suggestion
- `IfMissing` (optional, default `no`): What to do when metadata is absent:
```
La valeur par défaut n'est pas bonne

2024-11-21 17:00 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +- `IfNotParsable` (optional, default `no`): What to do if data parsing fails :
```suggestion
- `IfNotParsable` (optional, default `no`): What to do if data parsing fails:
```
Même problème que la valeur par défaut

2024-11-21 17:00 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +  - `error`: An error occurs, and the generation stops (default).
(Peut-être que cette remarque pourra être traitée plus tard)
Ça vaudrait le coup de mutualiser (et étoffer) la documentation de ces valeurs

2024-11-21 17:00 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +**Required parameters**
```suggestion
**Extra parameters**
```

2024-11-21 17:00 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +- `as` (requires, text): the type to which the value should be converted :
```suggestion
- `as` (requires, text): the type to which the value should be converted:
```

2024-11-21 17:00 UTC, indyteo commented on examples/default.yaml
> +        ifMissing: ignore
Selon moi, dans notre cas si la valeur n'est pas parsable, on devrait fallback sur la valeur par défaut

2024-11-21 17:00 UTC, indyteo commented on examples/default.yaml
> +        value: 20
Des bâtiments de 20m ça me paraît beaucoup quand même pour une valeur par défaut. Si on n'a pas d'info, en plus, c'est sans doute que le bâtiment n'était pas très important, alors le faire aussi haut, ressortir du paysage, me semble peu opportun. 5 à 7 mètres me paraît plus raisonnable (ça ne veut pas dire que je te demande de faire une valeur random, mais d'en décider une toi-même pour l'instant, et ensuite réfléchir juste à imaginer à quoi pourrait ressembler le mécanisme si on voulait une valeur random à la place)

2024-11-21 17:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
Peut-être que ça a déjà été étudié, mais il n'était pas possible de déléguer le travail à Jackson ici ? Probablement par le biais d'un désérialiseur custom + un mapping string => class

Après je comprends que ça ai été mutualisé avec le mécanisme de parsing, mais c'était une remarque qui m'est venue, alors je me demandais si vous y aviez réfléchi ou pas

L'intérêt que j'y vois c'est pouvoir appliquer une valeur par défaut "structurée", alors que là ça fail si on met autre chose qu'un string-like

2024-11-21 17:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +        @SuppressWarnings({ "unchecked", "rawtypes" })
Pourquoi ?

2024-11-21 17:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/FailurePolicyParser.java
> +package com.ignfab.minalac.generator.parameters.processors.post.parsers;
Oui pour l'enum, et franchement la classe de parsing de l'enum c'est pas un poil too much ? Ca fait "beaucoup" de code pour rien je trouve (je comprends l'idée, mais est-ce que ça vaudrait pas le coup d'une petite simplification ici quand même ?)

2024-11-21 17:00 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +    private static final Map<String, Parser> PARSERS = Map.of(
Bah non du coup, là tu n'as toujours pas rendu ton code flexible. Presque, tu as tout fait pour, tu as pavé le chemin, envoyé les invitations, décoré la porte d'entrée, préparé l'apéro, mais tu as mis des barbelés sur la grille et tu as fermé la porte à double tour...

2024-11-21 17:37 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +    private static final Map<String, Parser> PARSERS = Map.of(
Là je ne trouve pas ça trop grave.

Déjà on a un truc à un seul endroit, et facile à étendre si on veut.

Il sera toujours temps d'améliorer ça au besoin (je sens que ça va mettre du temps à venir, sauf si tu vois déjà qq chose).

2024-11-21 19:28 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +    private static final Map<String, Parser> PARSERS = Map.of(
C'est pas une question de temps, c'est jusqu'il manque 2 détails (et je dis bien "détails" vraiment) pour que ça soit le cas avec son code actuel :
- Utiliser un type de map non immutable
- Exposer une méthode pour y ajouter un élément

Et c'est tout. Alors je trouve ça très dommage de ne pas le faire...

2024-11-21 20:05 UTC, indyteo reviewed
Il y a encore du travail

2024-11-21 20:05 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/FailurePolicyParser.java
> +        "skip", ParsingFailurePolicy.SKIP_MODEL,
La différence entre "skip" et "remove" est difficile à comprendre en voyant simplement ces valeurs. C'était pour ça que j'avais précisé `SKIP_MODEL` et `REMOVE_METADATA` dans l'enum, pour comprendre que dans un cas c'est la métadonnée qui est éliminée, et dans l'autre c'est le modèle entier. Ça rajoute quelques caractères mais je trouve que ça en vaut la peine pour la compréhension de la config

2024-11-21 20:05 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +    private final Function<String, ? extends T> parser;
Je ne suis pas d'accord, la valeur d'origine n'a pas à être forcée en un string. Après si les fonctions de parsing par défaut décident de travailler avec un string, c'est leur problème, mais ça n'a pas à être imposé ici.

2024-11-21 20:05 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +    private final ParsingFailurePolicy ifWhenParserReturnNull;
Il y a un problème avec les noms

2024-11-21 20:05 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +                throw new Exception("Parsing function returned null");
Il y a un problème ici à mélanger inconditionnellement les erreurs de parsing et la valeur de retour `null`. Une fonction peut échouer, ou retourner `null` sans échouer, ou parfois retourner `null` pour signifier un échec. Ces 3 situations sont distinctes et doivent pouvoir être gérées, là on ne peut plus différencier la 1 et la 2.

2024-11-21 20:05 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +            switch (ifWhenParserReturnNull) {
Il s'agit ici surtout du cas où il y a eu une erreur de parsing... Le cas `null` ne devrait pas être mélangé inconditionnellement

2024-11-21 20:05 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorTest.java
> +        assertThrows(IllegalArgumentException.class, new MetadataDefaultPostProcessorParams("toto", "5", "unknow")::validate);
```suggestion
        assertThrows(IllegalArgumentException.class, new MetadataDefaultPostProcessorParams("toto", "5", "unknown")::validate);
```

2024-11-21 20:05 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorTest.java
> +        assertDoesNotThrow(new MetadataDefaultPostProcessorParams("toto", "yes", "boolean")::validate);
Au demeurant ça ne me choquerait pas de considérer que ce test devrait échouer. `yes` n'est pas une valeur que Java comprend comme un `boolean`. Enfin si pardon, ça veut dire `false` 😉 Considérer que la validation échoue ne me semblerait pas inadapté.

2024-11-21 20:05 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        """;
Juste une remarque pour que tu saches : Tous tes strings ici sont indentés de 4 espaces (causé par la position des guillemets fermants)

2024-11-21 20:05 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        assertDoesNotThrow(() -> new MetadataParsePostProcessorParams("toto", "integer").validate());
```suggestion
        assertDoesNotThrow(new MetadataParsePostProcessorParams("toto", "integer")::validate);
```

2024-11-21 20:40 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        """;
J'ai vu, j'me suis dit avec une indentation de 4 espaces dans cette chaines de char... C'était plus jolie 😅
Ca causer pas d'erreur particulier, donc j'ai laissé

2024-11-22 09:47 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
🔃 Ma première version de mon param pour les champs où il y avait le type `FailurePolicy` était un désérialiseur custom pour faire le mapping String => Class 🔃.
Je ne me rappelle plus pourquoi j'ai dû enlever le désérialiseur custom que j'avais écrit, mais ce qui était sûr, c'est après une remarque de @pyrollo .

2024-11-22 09:52 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
(Ce n'est pas vraiment le premier commit, c'est quelques commits plus tard.)
Le code que j'avais écrit :
```java
/**
 * Deserializes the JSON string representation of a type into a ParsingFailurePolicy enum.
 */
private static final class ParsingFailurePolicyDeserializer extends JsonDeserializer<ParsingFailurePolicy> {
    @Override
    public ParsingFailurePolicy deserialize(JsonParser parser, DeserializationContext context)
            throws IOException, JacksonException {
        try {
            return ParsingFailurePolicy.valueOf(parser.getText().toUpperCase());
        } catch (IllegalArgumentException e) {
            return ParsingFailurePolicy.REMOVE_METADATA;
        }
    }
}
```

2024-11-22 10:02 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +        @SuppressWarnings({ "unchecked", "rawtypes" })
J'ai écrit un commentaire qui explique pourquoi j'ai dû utiliser l'annotation `@SuppressWarnings`.

2024-11-22 10:02 UTC, naulan-chrzaszcz commented on examples/default.yaml
> +        value: 20
J'ai pris `5` comme valeur par défaut.

2024-11-22 10:03 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +    private final ParsingFailurePolicy ifWhenParserReturnNull;
Cette version est mieux ?

2024-11-22 12:17 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
Je ne parle pas de ça (il n'y a pas de failure policy ici)

2024-11-22 12:22 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +        @SuppressWarnings({ "unchecked", "rawtypes" })
Pour avoir le droit de supprimer un warning, tu dois être en mesure d'expliquer exactement pourquoi il survenait, et ainsi pourquoi on peut sereinement l'ignorer.

Je t'écoute ^^

2024-11-22 12:56 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +        @SuppressWarnings({ "unchecked", "rawtypes" })
~~yes.~~
Je ne peux pas expliquer complètement avec mes propres mots pourquoi j'ai supprimé les warnings, mais j'en comprends l'idée générale.
Je dois approfondir mes connaissances sur les types génériques pour pouvoir expliquer clairement pourquoi j'ai supprimé le warning rawtypes dans mon code.
Pour finaliser la PR, j'ai généré un commentaire à l'aide de l'assistant...

2024-11-25 13:22 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorTest.java
> +        assertDoesNotThrow(new MetadataDefaultPostProcessorParams("toto", "yes", "boolean")::validate);
Pour se rendre compte du problème, il faudrait les tests d'échec.

Ici la validation n'est pas vraiment testée,  il manque tous les cas d'erreur("toto" -> "boolean", "titi" -> "decimal" par exemple).

2024-11-25 13:27 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +    private static final Map<String, Parser> PARSERS = Map.of(
Bah justement, c'est prêt pour quand on en a besoin :p

2025-01-06 11:00 UTC, pyrollo requested changes
Quelques nouveaux commentaires. Y a pas mal de commentaires en attente déjà.

2025-01-06 11:00 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +**Type**: parse
On ne l'avait pas fait dans la précédente PR (tant pis) mais comme `parse` est du 'code', il vaut mieux le mettre en code:
```suggestion
**Type**: `parse`
```

2025-01-06 11:00 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `metadata` (required, text): the name of the metadata to parse.
Pour moi, le type ici n'est pas très utile car évident. A voir s'il faut le garder (ça alourdi mais c'est plus précis) ou pas.
```suggestion
- `metadata` (required): the name of the metadata to parse.
```

2025-01-06 11:00 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +  - `text` (a string)
Pareil, ici je ne suis pas sûr que décrire les types soient pertinents (c'est assez évident à comprendre). Suggestion:
```suggestion
- `as` (required): the type of parsed value: `integer`, `decimal`, `boolean`, `text`
```

2025-01-06 11:00 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `IfMissing` (optional, default `no`): What to do when metadata is absent:
`no` n'est pas décrit dans les options ?

2025-01-06 11:00 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +- `IfNotParsable` (optional, default `no`): What to do if data parsing fails:
`no` n'est pas décrit dans les options ?

2025-01-06 11:00 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +**Type**: default
```suggestion
**Type**: `default`
```

2025-01-06 11:00 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +  - `text` (a string)
Les mêmes remarques que plus haut, je propose:
```suggestion
- `metadata` (required): the name of the metadata.
- `value` (required): the default value to use if the metadata is not present.
- `as` (requires): the type to which the value should be converted:  `integer`, `decimal`, `boolean`, `text`
```

2025-01-06 11:00 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/FailurePolicyParser.java
> +    private static final Map<String, ParsingFailurePolicy> PARSERS = Map.of(
Pourquoi cette variable s'appelle `PARSERS` ?

2025-01-06 11:00 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/FailurePolicyParser.java
> +package com.ignfab.minalac.generator.parameters.processors.post.parsers;
J'ai l'impression que cette classe ne fait que faire la correspondance entre un string et l'énum. Si c'est le cas c'est effectivement too much (un simple `@JsonProperty` fait le job).

2025-01-06 11:00 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParams.java
> +@SuppressWarnings("checkstyle:VisibilityModifier")
```suggestion
```
C'est géré par https://github.com/ignfab/minalac-generator/blob/main/suppressions.xml maintenant.

2025-01-06 11:00 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +@SuppressWarnings("checkstyle:VisibilityModifier")
```suggestion
```
Géré par https://github.com/ignfab/minalac-generator/blob/main/suppressions.xml

2025-01-06 11:00 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +@SuppressWarnings("checkstyle:VisibilityModifier")
```suggestion
```
Géré par https://github.com/ignfab/minalac-generator/blob/main/suppressions.xml

2025-01-06 11:00 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
Ce fichier n'est pas censé être modifié par cette PR (et la modif n'est pas super).

2025-01-06 11:00 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        });
Vu que tu testes `validate` et pas `readValue` j'aurais plutôt écrit un truc du genre:

```suggestion
        MetadataParsePostProcessorParams params = mapper.readValue(removeFailurePolicyYaml, MetadataParsePostProcessorParams.class);
        assertDoesNotThrow(params::validate);
```

(pareil pour les autres tests)

2025-01-06 11:00 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        });
Ces deux tests ne testent pas grand chose.

Le test précédent a montré qu'avec une valeur valide de `ifMissing` et `ifNotParsable` on a bien une validation. Là tu refait la même (ici on teste la validation de MetadataParsePostProcessorParams, pas de FailurePolicy)

2025-01-06 11:00 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        });
Ici non plus tu ne testes rien de nouveau (ligne 50, on a déjà un test qui vérifie le cas où tout est valide).
En revanche, il manque un test pour vérifier qu'avec un type invalide, tu as bien un échec de validation.
(encore une fois, penses à ce que tu testes : la validation de MetadataParsePostProcessorParams, donc il faut vérifier que chaque validation (ou invalidation) remonte bien, mais pas tester les autres validations, c'est déjà censé être fait ailleurs).

2025-01-06 11:00 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +                throw new Exception("Parsing function returned null");
Il manquerait une troisième "failurePolicy" pour aller dans le sens de la modif:
```
private final ParsingFailurePolicy ifParserFails;
```

Après, je ne sais pas si ça a du sens de traiter ici le "Null". Après tout, si le parser fait correctement son travail et qu'il retourne null, c'est que la valeur est véritablement "null". À nous de traiter ce cas dans un autre postproc non ?

2025-01-06 13:33 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataCopyPostProcessorParamsTest.java
J'ai mal rebasé

2025-01-06 14:15 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        });
J'ai fait une version differente, il y avait beaucoup de repetition :
```java
/**
 * This method simplifies code repetition for test cases significantly.
 *
 * @param yaml the YAML input to be validated
 * @throws JsonProcessingException if an error occurs during JSON processing
 */
private void validate(String yaml) throws JsonProcessingException {
    MetadataParsePostProcessorParams params = mapper.readValue(yaml, MetadataParsePostProcessorParams.class);
    assertDoesNotThrow(params::validate);
}
```

Et j'appel ensuite ma fonction a chaque `String` :
```java
// Test case for 'remove' failure policy (when missing or not parsable)
validate("""
type: parse
metadata: toto
as: integer
ifMissing: remove
ifNotParsable: remove
""");
```

2025-01-06 14:18 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        });
Je voulais mettre un `try/catch` sur la variable `params` et call la fonction `fail` quand ca fait une erreur, mais je pense que mettre un `throws` sur la fonction`validate` doit faire la même chose.

2025-01-06 14:29 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        });
J'ai crée cette fonction pour tester le FailurePolicy dans MetadataParsePostProcessorParams (C'est pour ca que j'ai nommé la fonction de test : `testValidateFailurePolicy`)

2025-01-06 14:30 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        });
C'est mieux de faire un cas juste et un cas mauvais ? Pas besoin de tester tout le FailurePolicy ?

2025-01-06 14:31 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        });
Je pense que la modification apporté ne va pas servir a grand chose vu qu'il y a des tests en extra qui ne servent a rien.
Je vais encore modifier.

2025-01-06 15:31 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        });
Oui, ce genre de factorisation dans les tests n'est pas forcément bienvenue car elle les ne les rend pas toujours plus lisibles (les tests doivent rester plutôt simples et simplistes)

2025-01-06 15:38 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        });
On est dans des tests **unitaires** :) Ça veut dire que tu testes une chose à la fois (une fonction en général). Donc soit tu es dans le test de FailurePolicy, soit tu es dans le test d'autre chose mais tu ne peux être dans les deux.

Ensuite, "un cas juste et un cas mauvais", ce n'est pas forcément suffisant.

L'idée est plutôt, si entre deux cas de tests, la seule différence se produit ailleurs que dans ta fonction, alors ton cas est inutile.

Si, en revanche, tes cas de tests ne couvrent pas toutes les possibilitées qu'offre ta fonction, alors il en manque.

Imagine une fonction qui prend deux paramètres et qui ne fait qu'appeler la validation de chacun d'eux. Ce sont tous les deux des "yes"/"no".  Combien de tests faut il faire ?

2025-01-06 15:45 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        );
Ici on teste plutôt `ValueParser` que `MetadataParsePostProcessorParams`

2025-01-06 15:46 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
Manque les tests pour ce fichier. C'est dommage car la classe n'est pas complètement triviale, ça serait bien de vérifier que le parsing est fait correctement.

2025-01-07 16:57 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +    private static final Map<String, Parser> PARSERS = Map.of(
Bon, manifestement, y avait 25x le temps de le faire :D

2025-01-09 08:17 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +        @SuppressWarnings({ "unchecked", "rawtypes" }) // Type safety is guaranteed by PostProcessor<Model, Model>, and raw type usage simplifies instantiation.
Pour éviter ça, une solution simple est de changer `Class<T>` en `Class<? extends T>` dans `MetadataParsePostProcessor`.

2025-01-09 09:04 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +        @SuppressWarnings({ "unchecked", "rawtypes" })
Une solution a été apportée par @pyrollo pour la suppression des warnings.

2025-01-09 09:06 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +        @SuppressWarnings({ "unchecked", "rawtypes" }) // Type safety is guaranteed by PostProcessor<Model, Model>, and raw type usage simplifies instantiation.
C'est fait 👍🏻

2025-01-09 15:05 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
Je pense que je peux resolve cette remarque.
Elle sera faite dans une autre PR (MINALAC-95)

2025-01-09 15:10 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
Le code a changé, je pense que la remarque n'est plus à jour 🤔 
@indyteo, je résous ou est-ce encore d'actualité ?

2025-01-09 15:22 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +    private static final Map<String, Parser> PARSERS = Map.of(
> C'est pas une question de temps, c'est jusqu'il manque 2 détails (et je dis bien "détails" vraiment) pour que ça soit le cas avec son code actuel :
> 
>     * Utiliser un type de map non immutable
> 
>     * Exposer une méthode pour y ajouter un élément
> 
> 
> Et c'est tout. Alors je trouve ça très dommage de ne pas le faire...

Je pense avoir fait ce que tu as proposé @indyteo, j'espère qu'il ne manque rien ?

2025-01-09 16:35 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +        validate(key);
Je sens que `validate` va gêner l'ajout d'un nouveau parser.

2025-01-09 16:40 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +        validate(key);
Ah oui, effectivement 😅
Je corrige demain

2025-01-09 19:49 UTC, indyteo reviewed
Je n'ai pas review les tests ici non plus

2025-01-09 19:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/FailurePolicyParams.java
Pourquoi être passé par une autre énumération et pas directement la bonne ?

2025-01-09 19:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
Bah, ma question "est-ce que vous y avez réfléchi" n'ayant pas de réponse, la remarque n'est pas résolue, à moins que vous y ayez réfléchi mais oublié d'en partager le résultat de cette réflexion 😅

2025-01-09 19:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +        return postProcessor;
```suggestion
        return new MetadataParsePostProcessor<>(
            metadata,
            ValueParser.getType(this.as),
            ValueParser.getParser(this.as),
            ifMissing.create(),
            ifNotParsable.create()
        );
```

2025-01-09 19:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +    private record Parser(Class<?> type, Function<Object, ?> parser) {}
Pour t'assurer que les parsers enregistrés correspondent au type qu'ils renseignent, tu peux ajouter un type générique :
```suggestion
    private record Parser<T>(Class<T> type, Function<Object, ? extends T> parser) {}
```

2025-01-09 19:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +    );
```suggestion
    private static final Map<String, Parser> PARSERS = new HashMap<>();

    static {
        addParser("integer", Integer.class, obj -> Integer.valueOf(obj.toString()));
        addParser("decimal", Double.class, obj -> Double.valueOf(obj.toString()));
        addParser("text", String.class, Object::toString);
        addParser("boolean", Boolean.class, obj -> Boolean.valueOf(obj.toString()));
    }
```

2025-01-09 19:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +     * Checks if there are any blatantly invalid key.
```suggestion
     * Checks if a parser has been registered for this key.
```

2025-01-09 19:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +     */
```suggestion
     * @throws IllegalArgumentException if no parser is found for the key
     */
```

2025-01-09 19:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +    public static void addParser(String key, Class<?> type, Function<Object, ?> parser) {
```suggestion
    public static <T> void addParser(String key, Class<T> type, Function<Object, ? extends T> parser) {
```

2025-01-09 19:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +    private final Class<? extends T> type;
Attention avec ça, parce que là tu autorises la création d'un post-processeur invalide / incohérent.
Avec ta modif, ce code compile :
```java
new MetadataParsePostProcessor<>(
    "toto",
    Integer.class,
    obj -> "string",
    ...
);
```
Puisque `T = Object`, `Integer.class = Class<Integer>` (`Integer extends Object`), `obj -> "string" = Function<Object, String>` (`String extends Object`)

Donc il faut garder `Class<T>` ici pour conserver la vérification à la compilation

2025-01-09 19:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +        if (type.isAssignableFrom(value.getClass()))
```suggestion
        if (type.isInstance(value))
```
(T'as pas touché à cette partie je sais mais je viens de voir que je m'étais compliqué la vie, donc autant simplifier ici tant qu'à faire)

2025-01-09 19:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +            T parsed = parser.apply(value.toString());
```suggestion
            T parsed = parser.apply(value);
```

2025-01-09 19:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +                throw new Exception("Parsing function returned null");
> Après tout, si le parser fait correctement son travail et qu'il retourne null, c'est que la valeur est véritablement "null".

Je suis 100% d'accord avec cette phrase, mais le problème est qu'on n'est pas capable de gérer cette valeur dans les métadonnées actuelles. Notre système considère que `null` = absent.

Selon moi, on devrait modifier ce comportement car il n'apporte pas tant de simplification / facilité que ça, pour autoriser une métadonnée `null` (et ensuite adapter ce post-processeur en conséquence pour gérer cette valeur "normalement").

2025-01-09 19:49 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +            }
Ici il s'agit d'un cas d'échec du parser, pas qu'il a renvoyé `null` (enfin puisque tu fais juste un bête `throw` quand c'est `null` actuellement c'est un cas particulier d'échec, mais puisque ce comportement est à changer, cette politique de traitement d'échec est à renommer)

2025-01-09 19:49 UTC, indyteo commented on examples/default.yaml
> +        as: integer
(Même remarque sur `minecraft.yaml`)

Qu'est-ce que tu penses de ta config actuelle ? Est-ce que tu es sûr de toi ? (La réponse est peut-être "oui", mais je voudrais que tu vérifies)

Notamment, qu'est-ce qu'il devrait se passer dans les situations suivantes (la manière dont tu VEUX le gérer, pas la manière dont la config actuelle le gère si différent) :
- Un bâtiment a une métadonnée `height = 10`
- Un bâtiment n'a pas de métadonnée `height`
- Un bâtiment a une métadonnée `height = "10"`
- Un bâtiment a une métadonnée `height = "toto"`

Maintenant que tu as répondu à ces questions, est-ce que la config actuelle produit bien l'effet désiré dans chaque situation ? Si oui, tant mieux, sinon, comment tu peux l'améliorer ?

2025-01-09 19:49 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +### Metadata parser
```suggestion
### Metadata parse
```
(Pour rester cohérent en terme de nommage)

2025-01-09 19:49 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +  - `error`: An error occurs, and the generation stops.
Le format utilisé pour donner les valeurs possibles donne l'impression qu'il faut écrire :
```yaml
ifMissing:
  skip: ???
  remove: ???
  ignore: ???
  error: ???
```

Il faudrait trouver une autre façon de lister les 4 valeurs possibles sans que ça soit écrit de la même manière que des attributs imbriqués.

D'ailleurs, dans le cas du `ifMissing`, la politique `remove_metadata` n'a pas d'intérêt, puisque la métadonnée était déjà absente justement, du coup techniquement elle a le même comportement que `ignore`. Bien entendu, dans le code cette valeur est présente parce que ça simplifie pas mal de réutiliser la même `enum`, mais est-ce que ça ne vaudrait pas le coup d'adapter un peu la doc pour masquer cette valeur, ou bien la regrouper avec `ignore` en disant qu'elle n'a aucun effet particulier par conséquent.

Au passage :
```suggestion
  - `skip_model`: The model is skipped.
  - `remove_metadata`: The metadata is removed.
  - `ignore`: Failure is ignored, nothing is done.
  - `error`: An error occurs, and the generation stops.
```
(Même chose en dessous)

2025-01-09 19:49 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +- `IfMissing` (optional, default `error`): What to do when metadata is absent:
```suggestion
- `ifMissing` (optional, default `error`): What to do when metadata is absent:
```

2025-01-09 19:49 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +- `IfNotParsable` (optional, default `error`): What to do if data parsing fails:
```suggestion
- `ifNotParsable` (optional, default `error`): What to do if data parsing fails:
```

2025-01-10 08:39 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/FailurePolicyParams.java
Il s'agissait déviter d'avoir du paramétrage ailleurs que dans params. Ça se discutte mais je pense que c'est peut être mieux de ne pas avoir les noms yaml dans le reste du code.

--> Ça mérite un commentaire s'il y a question.

2025-01-10 08:43 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +    private final Class<? extends T> type;
Du coup, comment évite-t-on l'usage du raw type (ce qui semble à banir) à l'instanciation du processor dans les params ?

2025-01-10 08:45 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +    );
Y a-t-il une raison particulière pour laquelle on doit l'écrire comme ça ?

2025-01-10 09:27 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +    );
C'est plus standard : tu n'as qu'une seule façon d'ajouter des parsers au lieu de deux. Si on fait des modifs sur "addParser", tu n'as pas à modifier aussi ton static pour coller à ces modifs.

2025-01-10 09:34 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +                throw new Exception("Parsing function returned null");
En revanche, les parsers que nous avons pour l'instant ne devraient jamais générer de null (mais faire des exceptions plutôt) donc "pour l'instant", on ne vas pas être confronté au problème. Mais je suis d'accord sur le fait qu'il faudrait autoriser les valleurs null, justement parce qu'on ne va pas avoir de problème avec.
(ça veut dire aussi qu'il faut que j'ajoute un fitlre "metadatanull" dans ma PR).

2025-01-10 09:44 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +  - `error`: An error occurs, and the generation stops.
Juste remarque sur le case de la proposition, ce serait plutôt en camelCase donc :
```suggestion
  - `skipModel`: The model is skipped.
  - `removeMetadata`: The metadata is removed.
  - `ignore`: Failure is ignored, nothing is done.
  - `error`: An error occurs, and the generation stops.
```
Pour la présentation, je me gratte la tête pour trouver :D

2025-01-10 09:48 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +  - `error`: An error occurs, and the generation stops.
C'était pas vraiment une "proposition" mais plutôt une "correction" par rapport à ce qu'il avait mit dans son code. On peut changer, mais il faut qu'il aille aussi corriger le code alors 😉 Au demeurant je suis d'accord qu'on utilise du camelCase partout, donc c'est plus cohérent qu'il aille corriger aussi son code

2025-01-10 09:50 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +    private final Class<? extends T> type;
Je vais regarder, mais il doit y avoir une astuce, je jette un œil

2025-01-10 09:59 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +  - `error`: An error occurs, and the generation stops.
## Première idée
Une première idée (en fait deux propositions en une):
- On ne met dans l'explication du champ que les valeurs possible (avantage : pas de répéption, inconvéniant : pas clair si on a plein de paramètres avec plusieurs listes);
- Utiliser un autre signe que ":" pour les valeurs (ici j'ai mis "="). Pas super convaincu mais c'est peut être une piste.

On pourrait utiliser un tableau à la place de la liste aussi mais c'est surement lourd.

### Rendu
**Extra parameters**:
- `metadata` (required): the name of the metadata to parse.
- `as` (required): the type of parsed value: `integer`, `decimal`, `boolean`, `text`.
- `IfMissing` (optional, default `error`): What to do when metadata is absent: `skipModel`, `ignore` ot `error` (see bellow).
- `IfNotParsable` (optional, default `error`): What to do if data parsing fails: `skipModel`, `removeMetadata`, `ignore` or `error` (see bellow).

Value meanings for `IfMissing` and `IfNotParsable`:
- `skipModel` = The model is skipped and won't be rendered.
- `removeMetadata` = The metadata is removed.
- `ignore`= Failure is ignored, nothing is done.
- `error` = An error occurs, and the generation stops.

## Autre idée

L'italique (et autre décorations) marche pour le code. Inconvéniant: ça fait revoir pas mal la doc.

### Rendu

- `metadata` (required): the name of the metadata to parse.
- `as` (required): the type of parsed value: `integer`, `decimal`, `boolean`, `text`.
- `IfMissing` (optional, default *`error`*): What to do when metadata is absent: *`skipModel`*, *`ignore`* ot *`error`* (see bellow).
- `IfNotParsable` (optional, default *`error`*): What to do if data parsing fails: *`skipModel`*, *`removeMetadata`*, *`ignore`* or *`error`* (see bellow).

Value meanings for `IfMissing` and `IfNotParsable`:
- *`skipModel`* : The model is skipped and won't be rendered.
- *`removeMetadata`* : The metadata is removed.
- *`ignore`* : Failure is ignored, nothing is done.
- *`error`* : An error occurs, and the generation stops.

2025-01-10 10:56 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +    private final Class<? extends T> type;
Je suis arrivé à un résultat fonctionnel : https://github.com/ignfab/minalac-generator/commit/ec19f5b572a9240d31b3e9abd5258ac061ddcaf2

À noter :
- Ignorez le reformatage des imports, j'ai pas fait gaffe
- J'ai appliqué quelques-unes de mes remarques notamment l'ajout du type générique dans `Parser`, c'est nécessaire
- La fonction `ValueParser.get` utilise un `unchecked`, j'ai étrangement pas pu faire autrement. Ceci dit, c'est beaucoup moins grave que `rawtypes`, puisque ce dernier signifie "on veut l'ancien comportement, déprécié et dangereux", alors qu'`unchecked` dit juste au compilateur "t'inquiète, je sais ce que je fais, fait-moi confiance"

Pour les explications + détaillées :

On défini le type générique sur le `Parser`, qu'on rend `public` par la même occasion. Ça signifie que le `Class<T>` et `Function<Object, ? extends T>` font bien référence au même type, capturé dans la "variable" `T`. On expose la classe car on va vouloir en quelque sorte accéder à ce `T` en plus des deux champs.
Pas d'impact particulier sur la méthode pour enregistrer les parsers, si ce n'est qu'on y a ajouté le type générique, capturé automatiquement par Java d'après les paramètres d'appel.
On ajoute une méthode pour récupérer le parser associé à une clé. Probablement que ça devrait remplacer les 2 autres, mais je suis pas allé plus loin. L'intérêt est comme j'ai dit de pouvoir renvoyer à la fois le type, et à la fois le parser, en informant qu'ils ont le même type. Et là c'est un peu bizarre, je ne suis moi-même pas encore 100% sûr pourquoi c'est nécessaire, mais je propose un type générique au lieu de `Parser<?>`, parce que sinon visiblement Java perd l'info comme quoi les deux composantes font bien référence au même type... Pas 100% satisfaisant mais fonctionnel et ça reste juste un micro-contournement d'une incompréhension du compilateur, et puisque les types génériques sont effacés après la compilation, ça n'a pas vraiment d'impact (si on utilise bien `Object` ou bien un sous-type correspondant réellement au parser enregistré pour cette clé).
Pour finir, on récupère le parser et on utilise `Object` nous car on n'a pas la moindre idée de ce que c'est réellement, et on s'en fiche à ce stade-là.

2025-01-10 11:08 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +  - `error`: An error occurs, and the generation stops.
L'idée du tableau est franchement pas mauvaise selon moi ! Rendu :

**Extra parameters**:
- `metadata` (required): the name of the metadata to parse.
- `as` (required): the type of parsed value: `integer`, `decimal`, `boolean`, `text`.
- `ifMissing` (optional, default `error`): What to do when metadata is absent. See failure policies below.
- `ifNotParsable` (optional, default `error`): What to do if data parsing fails. See failure policies below.

Failure policy | Explanation
:---|:---
`skipModel` | The model is skipped.
`removeMetadata` | The metadata is removed.
`ignore` | Failure is ignored, nothing is done.
`error` | An error occurs, and the generation stops.

2025-01-10 11:30 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +  - `error`: An error occurs, and the generation stops.
On est d'accord que la conversation a divagué et que vos suggestions sera fait lorsqu'on travaillera sur le ticket MINALAC-95 ? (Dans une autre PR)
Ou, ce problème est uniquement dans ma PR ?

2025-01-10 11:44 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +  - `error`: An error occurs, and the generation stops.
Il y a 2 sujets évoqués :
1. Ta documentation ne correspond pas à ton code (doc : `skip` / code : `skip_model`) et il se trouve que ton code ne correspond pas non plus au style général des paramètres (`skipModel`). Donc ça c'est impératif à faire ici.
2. Le style que tu as utilisé ici induit en erreur à la lecture. Ça peut être traité ailleurs, si on ne se décide pas maintenant, mais ça ne fera que grossir cet autre ticket, alors que si on est décidé dès maintenant sur le style à adopter pour cette situation, ça me paraît judicieux de le faire ici pour s'éviter du travail en plus, plus tard. En l'occurrence, j'aime bien personnellement la proposition de @pyrollo avec un tableau. Je ne trouve pas ça spécialement lourd, au contraire très lisible. À voir vos avis sur la question :)

2025-01-10 14:17 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +  - `error`: An error occurs, and the generation stops.
A voir le rendu, je suis finalement très convaincu par le tableau !

Donc résumé : 
* champs + juste valeurs + "see bellow"
* tableau des valeurs avec nom/type de valeur + "Explanation"

2025-01-10 14:26 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
On n'y avait pas réfléchi.

Ça me fait penser à ta question sur ma PR : https://github.com/ignfab/minalac-generator/pull/69/files#r1908641320

Peut être peut on utilsier "Object" et laisser faire Jackson (avec un "as" spécial) ou "JSONNode" et mettre la logique dans le Parser.

Je propose d'en rester là sur ce sujet pour cette PR qui fait déjà bien le job (et qui traine ...) avec cette version et de garder la question (intéressante) sous le coude.

2025-01-10 14:28 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParser.java
> +public final class ValueParser {
```suggestion
public final class ValueParsers {
```
Je comprends `ValueParser` comme la classe qui va analyser la valeur.
(ou `ValueParserFactory` ou  `...store` ou qq chose qui indique plus clairement ce que c'est)

2025-01-10 14:49 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +                throw new Exception("Parsing function returned null");
Ce qu'on va faire, c'est faire comme si les métadonnées des modèles géraient correctement le null. Si ce n'est pas le cas on fait un ticket et une PR sur ce sujet qui sort de la PR (que je veux merger au plus vite :) )

2025-01-10 14:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +    private final ParsingFailurePolicy ifWhenParserReturnNull;
c'était mieux ensuite mais y a encore un rename à faire (-> ifParserFailed)

2025-01-12 09:25 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +  - `error`: An error occurs, and the generation stops.
Je me demande, et je ne sais pas si on en avait parlé, @pyrollo : pour `ifMissingMetadata`, est-ce qu'on pourrait mettre `ignore` par défaut ?

2025-01-12 09:43 UTC, naulan-chrzaszcz commented on examples/default.yaml
> +        as: integer
Je pense avoir résolu le problème

2025-01-12 09:54 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/FailurePolicyParams.java
```java
/**
 * Parameters for {@link ParsingFailurePolicy}.
 * 
 * Avoid scattering configuration-specific names 
 * for {@link ParsingFailurePolicy} across the codebase.
 */
public enum FailurePolicyParams {
    // ...
}
```
Le commentaire rajouté sur la JavaDoc de l'enum est correct ?

2025-01-12 12:38 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/FailurePolicyParams.java
Avoid**s**

2025-01-12 12:52 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +  - `error`: An error occurs, and the generation stops.
Mon avis sur la question :
Quel est l'objectif concret de ce post-processeur ? Dans quel but l'utilisateur va-t-il le plus souvent s'en servir ?

Si la réponse est "Pour s'assurer que tous les modèles aient une métadonnée du bon type (grâce à une opération de conversion)", la valeur par défaut `error` semble correcte.
Si la réponse est "Pour s'assurer qu'il n'y a aucune métadonnée d'un autre type (en convertissant les métadonnées qu'il trouve)", la valeur par défaut `ignore` paraît plus adaptée.

Je sais que j'ai répondu à la question par une autre question, mais pour moi c'est vraiment ce questionnement sur le point de vue utilisateur qu'il faut avoir pour se demander si nos paramètres sont adaptés ou pas

2025-01-12 12:59 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +`skipModel` | The model is skipped.
En relisant je me rend compte que "skip" n'est pas très évocateur pour l'utilisateur, et au contraire ça laisse penser que ce post-processeur saute ce modèle et passe au suivant, en le laissant intact, alors que c'est `ignore` ça... Le mot naturel pour "se débarrasser" d'un modèle (car c'est vraiment ça qui se passe, on le jette à la poubelle) c'est "discard".
```suggestion
`discardModel` | The model is discarded.
```
Je pense qu'il est bénéfique de le changer dans la doc et les params (`discardModel`) mais même dans l'enum orientée code (`DISCARD_MODEL`)

2025-01-12 13:03 UTC, indyteo commented on examples/default.yaml
> +        as: integer
Tu es sûr de ton `ifNotParsable` ? Qu'est-ce qu'il se passe dans la situation suivante ?
> Un bâtiment a une métadonnée height = "toto"

2025-01-13 08:24 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +  - `error`: An error occurs, and the generation stops.
A priori j'aurais tendance à dire "error", ce qui force à être explicite sur ce que l'on veut faire s'il y a un problème (en gros: si tu dis pas ce que tu veux faire, je fais grêve).
En revanche, en cas de mauvais paramétrage sur une source qui est presque toujours bonne, ça va nous pêter à la tête au moment où on ne s'y attend pas.
Autre voie, à la Rust : rendre le champ obligatoire.

Je penche tout de même pour "error".

2025-01-13 08:32 UTC, naulan-chrzaszcz commented on examples/default.yaml
> +        as: integer
Oui, il y a un problème. La metadonnée n'est pas supprimé

2025-01-13 13:19 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +`skipModel` | The model is skipped.
> mais même dans l'enum orientée code (`DISCARD_MODEL`)

On est d'accord que tu parles uniquement de l'enum `FailurePolicyParams` ? (Je ne réplique pas la modification sur `ParsingFailurePolicy` ?)

2025-01-13 13:42 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +`skipModel` | The model is skipped.
Si

2025-01-13 13:59 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParserTest.java
> +        assertEquals(false, result);
Est-ce logique de ne pas faire d'erreur là dessus ?

"toto" as integer et "toto" as decimal vont faire des erreurs mais pas "toto" as boolean ?

Et quid de True, TRUE et autre ? ça peut vite mener à des erreurs de configuration s'ils sont acceptés mais conmpris comme faux.

2025-01-13 14:07 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParserTest.java
> +        assertEquals(false, result);
D'autant plus pour l'utilisateur un tout petit peu avancé en YAML qui sait qu'il peut utiliser `yes` pour les booléens (c'est les [spécifications YAML](https://yaml.org/type/bool.html) qui disent ça), et qui ne comprendra pas pourquoi `"yes" as boolean => false` dans cette situation

2025-01-13 14:15 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorTest.java
> +        assertDoesNotThrow(new MetadataDefaultPostProcessorParams("toto", "yes", "boolean")::validate);
@pyrollo @naulan-chrzaszcz la conversation tout en bas vient d'ici en fait. On doit pouvoir fermer l'une des deux conversation (celle-ci je pense)

2025-01-13 14:16 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        });
@naulan-chrzaszcz il te reste cette remarque et celle d'en dessous aussi (je te ping parce qu'elles sont pas visibles par défaut il faut déplier donc peut-être que tu ne les as pas vu)

2025-01-13 14:19 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParserTest.java
> +        assertEquals(false, result);
Ceci dit, il semblerait que ce sont les anciennes specs YAML, et que les nouvelles interdisent ces valeurs, pour revenir aux bases : `true` / `false` (https://yaml.org/spec/1.2.2/#10212-boolean)... Amusant

En tout cas, entre ce que les specs disent et ce que Jackson fait, on n'a pas trop le choix que de s'en tenir à Jackson, donc si il autorise ces valeurs, il faut à mon sens soit les autoriser nous-même, soit les interdire avec une erreur pour le signaler à l'utilisateur qui se tromperait, au lieu de les dissimuler sous une valeur par défaut (`false`)

2025-01-13 14:51 UTC, pyrollo requested changes
Quelques remarques déjà.
Des trucs importants, du pinaillage, des simplifications.

Je regarde les tests maintenant.

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +    public final String metadata;
```suggestion
    @JsonSetter(nulls = Nulls.FAIL)
    public final String metadata;
```

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +    public final String value;
```suggestion
    @JsonSetter(nulls = Nulls.FAIL)
    public final String value;
```

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +    public final String as;
```suggestion
    @JsonSetter(nulls = Nulls.FAIL)
    public final String as;
```

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +        ValueParsers.validate(as);
```suggestion
        if (metadata.isBlank())
            throw new IllegalArgumentException("The 'metadata' field cannot be empty or contain only whitespace.");
        ValueParsers.validate(as);
```

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParams.java
> +
```suggestion
```
(redondant, c'est à `ValueParsers.validate()` de tester ça).

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> + * Utility class for parsing values into specific types based on a key.
Ce n'est pas tout à fait ça. Cette classe ne "parse" pas. Elle gère juste une collection.

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +     * Maps predefined keys to their corresponding parsers.
Ici, les clés ne sont pas prédéfinies (la méthode permet justement d'en ajouter qui ne sont pas prédéfinies).

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +    static {
Ici en revanche ce sont les parser prédéfinis.

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +     * Private constructor to prevent instances.
```suggestion
     * Private constructor to prevent instantiation.
```
(c'est du pinaillage)

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +     * Adds a new parser to the map.
```suggestion
     * Adds a new parser.
```
(vu de l'extérieur, on ne sais pas que c'est une "map" dedans... et on s'en tape :) )

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +    }
Ailleurs on a plutôt fait ça pour bien indiquer où est le *unchecked* (pas sûr qu'il faille le faire ici aussi, à toi de voir):

```suggestion
    public static <T> Parser<T> get(String key) {
        validate(key);
        @SuppressWarnings("unchecked")
        Parser<T> parser = (Parser<T>) PARSERS.get(key);
        return parser;
    }
```

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +    }
Cette méthode n'est plus utilisée.

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +}
Tu peux te débarasser de celle-ci en remplaçant son appel dans `MetadataDefaultPostProcessorParams`.

2025-01-13 14:51 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorTest.java
> +        assertDoesNotThrow(new MetadataDefaultPostProcessorParams("toto", "yes", "boolean")::validate);
Plus de conv ça met la pression sur @naulan-chrzaszcz  :p

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorParams.java
> +        return new MetadataDefaultPostProcessor(metadata, ValueParsers.getParser(as).apply(value));
```suggestion
        return new MetadataDefaultPostProcessor(metadata, ValueParsers.get(as).parser().apply(value));
```
et tu peux virer `getParser` de `ValueParsers`.

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
>       * Creates a new post-processor parsing {@code name} as a {@code type}.
```suggestion
     * Creates a new post-processor parsing metadata {@code name} as a {@code type}.
```

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +     * @param ifMissingMetadata parsing function to use when the metadata is absent
C'est pas une `function to use` mais un comportement à avoir plutôt ("policy to apply" / "what to do" / "behavior to have" /...)

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +     * @param ifParserFails parsing function to use when the {@code parser} return error
Idem ici

2025-01-13 14:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
>                  }
```suggestion
                case IGNORE, REMOVE_METADATA -> return model;
```
Pas testé mais vu qu'en dessous, tu fais ça, je mettrais bien ça pareil.

2025-01-13 15:03 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        assertThrows(IllegalArgumentException.class, new MetadataParsePostProcessorParams("dummy", "")::validate);
Tu peux ajouter un cas qui marche:
```java
assertDoesNotThrow(new MetadataParsePostProcessorParams("dummy", "integer")::validate);
```

2025-01-13 15:09 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorTest.java
> +        assertDoesNotThrow(params::create);
Tu peux tester un cas où la valeur n'est pas parsable. Ça vérifiera que`MetadataDefaultPostProcessorParams` remonte bien l'exception depuis le parser.

2025-01-13 15:11 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
>                  }
Non, Java ne voudra pas (j'ai pas exactement la justification mais je sais que ça ne compile pas)

2025-01-13 15:13 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
>                  }
Explication : https://stackoverflow.com/questions/71751296/why-cant-return-be-expressed-in-one-line-when-using-a-switch-expression

2025-01-13 15:14 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorTest.java
> +        assertDoesNotThrow(new MetadataDefaultPostProcessorParams("toto", "yes", "boolean")::validate);
En fait ici, on a pas autant de tests à faire. Il faut juste tester que l'exception remonte bien depuis `ValueParsers` donc un test où il y a exception et un test où il n'y en a pas. Le reste est redondant (testé dans `ValueParsers`)

2025-01-13 15:16 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorTest.java
> +        assertDoesNotThrow(new MetadataDefaultPostProcessorParams("toto", "yes", "boolean")::validate);
Enfin, suite à ma remarque sur `MetadataDefaultPostProcessorParams` il va aussi falloir vérifier le cas où le nom de la métadonné est vide.

2025-01-13 15:18 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorTest.java
> +        assertDoesNotThrow(new MetadataDefaultPostProcessorParams("toto", "yes", "boolean")::validate);
Pour faire simple: trois sorties possible donc 3 tests (if -> exception, validate() -> exception, ou OK):
```java
    public void validate() throws IllegalArgumentException {
        if (metadata.isBlank())
            throw new IllegalArgumentException("The 'metadata' field cannot be empty or contain only whitespace.");
        ValueParsers.validate(as);
    }
```

2025-01-14 13:42 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParserTest.java
> +        assertEquals(false, result);
Vu avec Naulan, on ne garde que `true` / `false` et on fait erreur sur le reste.

2025-01-15 09:41 UTC, pyrollo requested changes
Quelques dernières bricoles

2025-01-15 09:41 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        assertThrows(IllegalArgumentException.class, new MetadataParsePostProcessorParams("", "integer")::validate);
Tu peux ajouter un test pour vérifier qu'un `as` invalide remonte bien l'exception.

2025-01-15 09:41 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorTest.java
> +public class MetadataDefaultPostProcessorTest {
```suggestion
public class MetadataDefaultPostProcessorParamsTest {
```

2025-01-15 09:41 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorTest.java
> +        assertThrows(IllegalArgumentException.class, new MetadataDefaultPostProcessorParams("", "5", "integer")::validate);
Manque le cas où "as" n'est pas valide (trois sorties dans validate() -> trois tests)

2025-01-15 09:41 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsersTest.java
> +        assertThrows(IllegalArgumentException.class, () -> parser.apply(Double.valueOf(1)));
```suggestion
        assertThrows(IllegalArgumentException.class, () -> parser.apply(1.0));
```

2025-01-15 09:41 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsersTest.java
> +        result = (Double) assertDoesNotThrow(() -> parser.apply(Integer.valueOf(1234567890)));
```suggestion
        result = (Double) assertDoesNotThrow(() -> parser.apply(1234567890));
```

2025-01-15 09:41 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsersTest.java
> +        assertThrows(NumberFormatException.class, () -> parser.apply(Double.valueOf(12345.6789)));
```suggestion
        assertThrows(NumberFormatException.class, () -> parser.apply(12345.6789));
```

2025-01-15 09:41 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsersTest.java
> +        assertThrows(IllegalArgumentException.class, () -> ValueParsers.addParser("dummy", Dummy.class, parser));
Plus simple et teste exactement la même chose:
```suggestion
        assertDoesNotThrow(() -> ValueParsers.addParser("dummy", String.class, Object::toString));
        assertThrows(IllegalArgumentException.class, () -> ValueParsers.addParser("dummy", String.class, Object::toString));
```
Tu peux éventuellement ajouter un test pour vérifier que le parseur est bien reconnu:
```java
        assertDoesNotThrow(() -> ValueParsers.validate("dummy"));
```

2025-01-15 09:49 UTC, pyrollo requested changes
Ajouter les tests sur `MetadataDefaultPostProcessor` (au moins sur `process`, deux cas).

2025-01-15 10:47 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/processors/post/MetadataDefaultPostProcessorTest.java
> +        };
Ouch, ça pique :D
Tu peux utiliser `TestingModel` c'est fait pour: 
```java
        model = new TestingModel(Map.of(
            "string", "value",
            "int", 7
        ));
```

2025-01-15 12:04 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/processors/post/MetadataDefaultPostProcessorTest.java
> +        assertEquals(1, (Integer) model.getMetadata("toto"));
Juste pour éviter une modif si on change le comportement du seMetadata null:

```suggestion
        assertDoesNotThrow(() -> processor.process(model));
        assertEquals(1, (Integer) model.getMetadata("toto"));

        model.setMetadata("toto", 10);
        assertDoesNotThrow(() -> processor.process(model));
        assertEquals(10, (Integer) model.getMetadata("toto"));
```

2025-01-15 12:38 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +`error` | An error occurs, and the generation stops.
J'imagine que ça marche mais normalement, la syntaxe c'est avec des pipes à droite et à gauche:
```suggestion

| Failure policy | Explanation |
| :--- | :--- |
| `discardModel` | The model is discarded. |
| `removeMetadata` | The metadata is removed. |
| `ignore` | Failure is ignored, nothing is done. |
| `error` | An error occurs, and the generation stops. |
```

2025-01-15 13:16 UTC, indyteo commented
@naulan-chrzaszcz il te reste ces conversations non résolues (du moins sur GitHub), je te laisse voir si elles sont toujours d'actualité ou non :

https://github.com/ignfab/minalac-generator/pull/62#discussion_r1913361349
https://github.com/ignfab/minalac-generator/pull/62#discussion_r1904306007
https://github.com/ignfab/minalac-generator/pull/62#discussion_r1903999618

2025-01-15 13:37 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataDefaultPostProcessorTest.java
> +        assertDoesNotThrow(new MetadataDefaultPostProcessorParams("toto", "yes", "boolean")::validate);
Suggestion résolu : 
```java
    @Test
    public void testValidate() {
        assertThrows(IllegalArgumentException.class, new MetadataDefaultPostProcessorParams("", "5", "integer")::validate);
        assertThrows(IllegalArgumentException.class, new MetadataDefaultPostProcessorParams("toto", "5", "invalid")::validate);
        assertDoesNotThrow(new MetadataDefaultPostProcessorParams("toto", "5", "integer")::validate);
    }
```

2025-01-15 13:41 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        });
@pyrollo, j'ai mis à jour les tests pour couvrir toutes les combinaisons possibles lors de la désérialisation du parser dans un fichier YAML.
Penses-tu que cela suffit ou vois-tu encore un problème dans mes tests unitaires ?

2025-01-15 13:42 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/processors/post/MetadataParsePostProcessorParamsTest.java
> +        assertDoesNotThrow(params::create);
Le déterrage de Théo m'a fait relire ici, en fait ce dernier test ne sert à rien. On a déjà tester ce cas (on a testé ifNotParsable vide et ifMissing vide séparément, inutile de tester ensemble, ça n'apporte rien de plus).

2025-01-15 13:52 UTC, pyrollo submitted a review, later dismissed

2025-01-15 14:59 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +                return (Boolean) obj;
Je viens de voir ici, ça n'est pas nécessaire car le post-processeur de parsing vérifie déjà cette condition, et au pire c'est pas grave ça fait juste une conversion inutile.

Indépendemment, si vous voulez vraiment gardez ça :
```suggestion
            if (obj instanceof Boolean bool)
                return bool;
```

2025-01-16 08:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +            if (!"true".equalsIgnoreCase(str) && !"false".equalsIgnoreCase(str))
```suggestion
            if (!"true".equals(str) && !"false".equals(str))
```
Je crois qu'on avait dit qu'on n'acceptait que "true" et "false"

2025-01-16 08:40 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +        });
Peut être un peu plus bourrin ? Moins de tests, pas sûr que ce soit mieux
```suggestion
     switch (str) {
         case "true":
               return true;
         case "false":
              return false;
         default:
             throw new IllegalArgumentException("The value : " + str + " isn't a boolean.");
     }
```

2025-01-16 08:51 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +        });
```java
return switch (str) {
    case "true" -> true;
    case "false" -> false;
    default -> throw ...;
};

2025-01-16 09:10 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +        });
EDIT: je n'avais pas vu le commentaire de Théo qui est encore mieux

Sinon, si c'est trop long, l'équivalent avec des ifs:
```suggestion
            if ("true".equals(str))
                return true;
            if ("false".equals(str))
                return false;
            throw new IllegalArgumentException("The value : " + str + " isn't a boolean.");
```

2025-01-16 09:24 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +        });
Ça s'appelle un "Switch Expression" : https://docs.oracle.com/en/java/javase/17/language/switch-expressions-and-statements.html

2025-01-16 09:48 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +        });
Avant d'avoir une autre remarque : fais un `switch(obj.toString())` directement, pas besoin de variable intermédiaire.

2025-01-16 09:51 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +        });
Je me suis fait plaisir, j'ai mis une condition ternaire.
![image](https://github.com/user-attachments/assets/a0a637f4-18da-47a5-86cd-f3e9ca0e761e)

2025-01-16 09:52 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +        });
Est-ce que c'est bon pour vous ?

2025-01-16 10:11 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/processors/post/parsers/ValueParsers.java
> +        });
Yes ça me parait bien.
Il n'y a pas de tests sur ce parser avec l'objet Boolean (genre parse(true)) mais je pense que ce n'est pas grave (Jackson semble comprendre la valeur "true" (sans guillemets) comme un String et ne pas la désérialiser comme un booléen).

2025-01-16 10:11 UTC, pyrollo submitted a review, later dismissed

2025-01-16 11:19 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +    private final Class<?> type;
Pardon j'ai pas suivi pourquoi on est revenu sur un `Class<?>` ici ?

On ce code compile à nouveau :
```java
new MetadataParsePostProcessor<>(
    "dummy",
    Integer.class,
    Object::toString,
    MetadataParsePostProcessor.ParsingFailurePolicy.ERROR,
    MetadataParsePostProcessor.ParsingFailurePolicy.ERROR
);
```

2025-01-16 11:20 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/processors/post/MetadataParsePostProcessor.java
> +    private final Class<?> type;
Avec `Class<T>` c'est correct en revanche

2025-01-16 12:52 UTC, indyteo submitted a review, later dismissed

2025-01-16 12:57 UTC, naulan-chrzaszcz commented
@indyteo, mb, j'ai poussé trop vite.
Il y avait quelques soucis de style dans mes Javadoc de `ValueParsers`.
Édit : J'ai trouvé des simplifications à apporter dans les tests de `ValueParsers`.

2025-01-16 13:09 UTC, naulan-chrzaszcz commented
Je ne vois plus rien à faire, je ne touche plus au code sauf s'il y a des suggestions.

2025-01-16 13:28 UTC, indyteo approved these changes

2025-01-16 15:05 UTC, merged