Improve ModelSelection with metadata filtering, and filter combination - MINALAC-94
ignfab/voxatile pull request #69
Opened 2024-12-20 16:29 UTC by pyrollo

### Issue
MINALAC-94

### Changes

This implementation of `ModelSelection` allows to filter models on various criteria or combination of criteria.

#### Feature description

Add possibility to narrow down model selection with criteria.

For now, two main types of criteria are available: 
* Metadata selection : metadata value or metadata presence;
* Criteria combination/logic : and, or, not

#### Technical changes

##### `ValueParsers`

`ValueParsers` class has been moved out of processors/post and replaced by `ValueParser`, a self-deserializing class, easier to use.

##### `ModelSelection`

Main changes are on `ModelSelection` class.

Model type filter is kept mandatory for performances reasons (and it looks like selections will always be on a type).
An optional model filter is added (`ModelFilter` interface) to selection. Five model filters are implemented in that PR.

This PR includes Yaml deserialization for these `ModelFilter`s.

##### `ModelRenderer`

`ModelRenderer` has been modified in order to declare accepted `Model` class in renderers class definition, getting rid of class testing in all rendering loops.

A renderer rendering only `MyModel` models now needs to extend `ModelRenderer<MyModel>`yet in order to get only `MyModel` instances in `render` method.

#### Showcase

Updated `default.yaml` file gives a good example on building rendering:
```
  building:
    after:
      - renderer:altitude
      - source:bati
    type: vector
    models:
      type: building
      filter:
        hasMetadata: hauteur
    heightmap: ground
    inside: default:cobble
    edge: default:stone
```

### TODOs

- [X] Fill PR form !

### Self-checks

- [x] The code has unit tests associated
- [x] The code has Javadoc Comments associated
- [x] Complex / Unexpected code is explained / justified with a small comment
- [x] Relevant documentation inside the `/docs` folder has been updated
- ~~All examples in `docs/usage/Examples.md` work the same (or have been adapted if subject to changes in this PR)~~
- [x] Git history is clean (each commit accomplish a single task and describe it accordingly)
- [x] The texts have been proofread (documentation, error messages, logs, comments...)

2025-01-07 09:11 UTC, naulan-chrzaszcz requested changes

2025-01-07 09:11 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterAnd.java
> +    @Override
J'ai un vague souvenir sur le fait qu'on voulais plus voir `@Override` sur le code ? Ou, c'était a propos d'une autre annotation en Java 🤔

2025-01-07 09:11 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterOr.java
> +        return false;
```suggestion
        return this.filters.stream().anyMatch(filter -> filter.isSelected(model));
```
(Je suggère uniquement ce bout de code car souvenir tu m'avais dit que c'était pas opti niveau perf)

2025-01-07 09:11 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterAndParams.java
> +            return new ModelFilterAnd(and.stream().map(ModelFilterParams::create).collect(Collectors.toList()));
```suggestion
        return new ModelFilterAnd(and.stream().map(ModelFilterParams::create).collect(Collectors.toList()));
```

2025-01-07 09:11 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/ModelSelection.java
> +            return Iterators.filter(store.getByType(type).iterator(), this.filter::isSelected);
```suggestion
        return Iterators.filter(store.getByType(type).iterator(), this.filter::isSelected);
```

2025-01-07 09:11 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterOrParams.java
> +            return new ModelFilterOr(or.stream().map(ModelFilterParams::create).collect(Collectors.toList()));
```suggestion
        return new ModelFilterOr(or.stream().map(ModelFilterParams::create).collect(Collectors.toList()));
```

2025-01-07 09:59 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterAnd.java
> +    @Override
C'était pour InheritDoc

2025-01-07 12:51 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterOr.java
> +        return false;
Pour comprendre un peu la situation, il faut analyser le fonctionnement d'un `Stream`. C'est moins compliqué que ça en a l'air, pas de panique.

Déjà, clarifions quelque chose :
> C'est quoi un code "pas optimisé" ?

Pour nous, il y a deux critères là dessus : Le temps d'exécution, et la mémoire consommée. Donc un code non optimisé va prendre plus de temps que nécessaire **ET/OU** consommer plus de mémoire que nécessaire. Et parfois (souvent), c'est soit l'un, soit l'autre ! Donc il faut décider si on préfère un code un peu long mais très léger, ou un code rapide mais lourd.

Dans le cas du générateur, on est plutôt parti sur "long mais léger" comme règle générale (après dans un endroit très précis du code ça peut se justifier de faire le contraire, mais ma remarque est là pour t'expliquer la théorie).

Revenons donc à nos moutons. Comme tout en Java, un `Stream` est un objet. Et un objet, ça pèse _un peu_ en mémoire. Alors un objet + un autre objet + encore un objet... = Ça pèse un peu plus lourd en mémoire.

Le problème avec un `Stream`, c'est que quand tu fais un traitement, à chaque opération, tu vas créer plusieurs objets. Alors c'est pas un drame en soit, créer quelques objets pour ensuite pouvoir facilement (et potentiellement rapidement) faire tes traitements. L'ennui c'est quand la création de ton `Stream` est lui-même dans du "code chaud" (code appelé souvent, dans une boucle sur tes données par exemple). Là tu vas souvent créer pleins d'objets pour faire un traitement que tu aurais pu faire sans : Ça devient sous-optimisé.

En bonus, les `Stream` permettent de gagner dans 2 cas de figure : améliorer la lisibilité du code, et optimiser **le temps** d'exécution des traitements massifs (sur un très gros volume de données, en exécutant ces opérations en parallèle par exemple). Donc si ça n'améliores pas spécialement la lisibilité du code en question, et que tu sais que le volume de données est moyen ou faible... Pas un grand avantage d'utiliser un `Stream` !

Voilà en espérant que tu comprends mieux le pourquoi du comment sur ce sujet ^^
N'hésite pas si tu as d'autres questions ou tu veux une clarification supplémentaire

2025-01-07 13:03 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterOr.java
> +        return false;
Merci 🙏🏻

2025-01-08 17:58 UTC, naulan-chrzaszcz reviewed
Une revue avec beaucoup de questions

2025-01-08 17:58 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/models/ModelSelectionParams.java
> +public class ModelSelectionParams {
Les Params doivent pas implémenter une interface ?

2025-01-08 17:58 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterMetadataInParams.java
> +    public List<Object> in;
C'est voulu de comparer une liste vide ?

2025-01-08 17:58 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterNotParams.java
> +    ModelFilterParams not;
```suggestion
    public ModelFilterParams not;
```

2025-01-08 17:58 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterOrParams.java
> +    List<ModelFilterParams> or;
```suggestion
    public List<ModelFilterParams> or;
```

2025-01-08 17:58 UTC, naulan-chrzaszcz commented on src/test/java/com/ignfab/minalac/generator/parameters/models/ModelSelectionParamsTest.java
> +    }
C'est volontaire ?

2025-01-09 09:29 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +  - `filter`: Extra filter (optional, default none)
```suggestion
  - `type` (required): Type of models to select
  - `filter` (optional, default none): Extra filter
```
Dans ma documentation, j'ai utilisé cette disposition.
Je ne sais pas ce qui est le mieux (et si c'est nécessaire d'uniformiser cela).

2025-01-09 10:26 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +  - `filter`: Extra filter (optional, default none)
Comme je vois que ça parle de documentation, à ce sujet moi en réutilisant un peu les différentes briques il y a quelques mois pour construire mes générations, j'ai par moment utilisé la doc pour retrouver les paramètres, et j'ai constaté qu'il y avait vraiment matière à améliorer "l'utilisabilité" (ça doit pas être très français, mais je veux dire "ease of use") de avec juste quelques modifications assez simples :
1. Uniformiser le format des paramètres (comme l'a évoqué Naulan), à plusieurs endroits on utilise des syntaxes différentes (un coup "optional" à la fin, un coup au début de la ligne... j'ai une préférence pour le début personnellement, un coup "required" précisé, un coup implicite... préférence pour implicite, mais il faudrait expliciter que c'est implicite :laughing:).
2. Découper en plusieurs petits fichiers thématiques (options générales, options des sources, des processors, renderers...).
3. Ajouter un sommaire / table des matières avec les liens vers chaque morceau de doc.
4. Insérer des liens vers un fichier d'exemple (avec les numéros de lignes concernés) qui utilise cet élément, pour voir un exemple concret, intégré avec les autres options.
5. Pour les renderers, éventuellement intégrer quelques screenshots de rendu lorsque pertinent pour illustrer l'effet d'une option particulière (une image valant plus que mille mots).
6. Pour ce dernier point je suis moins sûr, mais je me dis que ça peut être un +, ajouter un lien vers le code ou au moins le nom qualifié de la classe, pour pouvoir creuser + loin si on veut. Conjointement, on pourrait aussi faire l'inverse, et décider de supprimer la JavaDoc sur les classes de params, et la remplacer par un lien vers la documentation Markdown associée.

Tout ceci est *simple* (pas forcément *rapide*) à faire, et pourrait faire l'objet d'une PR bien soignée qui passe une fois pour toute sur l'ensemble de la doc, et qui ajoute par la même occasion un fichier `docs/HowToWriteDocs.md` (voire `docs/HowToReadDocs.md` éventuellement si c'est pertinent, mais l'objectif à mes yeux est plutôt d'écrire correctement la doc pour ne pas avoir besoin d'une doc explicative pour la lire).

Du coup, je propose de ne pas spécialement se soucier du format utilisé pour la documentation actuellement, tant qu'elle reste compréhensible pour qu'on puisse l'uniformiser plus tard dans une PR dédiée.

2025-01-09 12:17 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +  - `filter`: Extra filter (optional, default none)
Est-ce que cela vaut le coup de créer une issue pour ne pas oublier ?
(Edit: Ou, un ticket dans Jira)

2025-01-09 12:28 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterMetadataEqualsParams.java
> + * Parameters for a {@link ModelFilterMetadataIn} with an "equals" operator.
C'est un détail, mais, dans mes JavaDocs pour mes Params, je n'ai pas écrit `for a {@link xxxx}` mais plutôt `for {@link xxxx}`.
Est-ce que j'ai fait une erreur d'anglais dans mes commentaires ?

2025-01-09 12:28 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterMetadataEqualsParams.java
> +    public Object equals;
```suggestion
    /**
     * Name of the metadata to test. (required)
     */
    public String metadata;

    /**
     * Value of metadata to test. (required)
     */
    public Object equals;
```
(Probablement pas obligatoire pour cette classe ? Plusieurs classes n'ont pas le `(required)` a la fin de la JavaDoc de la variable)

2025-01-09 12:42 UTC, indyteo reviewed
Je n'ai pas review les tests pour le moment

2025-01-09 12:42 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +A model selection describes a set of models to process.
```suggestion
A model selection describes a set of characteristics that models must match to be processed.
```

2025-01-09 12:42 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +          in: [ Monument, Château, Chapelle, Eglise ]
Shouldn't we stick to English for documentation?
```suggestion
          metadata: classification
          in: [ Monument, Castle, Chapel, Church ]
```

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilter.java
Concrètement, c'est un `Predicate<Model>`, je sais pas si cette classe est utile ou au contraire cela simplifierait la chose d'utiliser [`Predicate`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/function/Predicate.html) (qui a quelques méthodes utiles comme `.negate()`, ou `.or()` et `.and()` même si ce sont des opérateurs binaires et non des listes).

Je me dis que ça permettrait de supprimer 2 ou 4 classes, et les params serait chargés de créer le bon predicate. Par contre ça limiterait nos connaissances au runtime sur ce qui s'exécute vraiment (objet opaque), mais je ne pense pas que ça soit un problème, et on a des solutions pour s'en sortir plus tard si besoin

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterAnd.java
> +        for (ModelFilter filter : this.filters)
```suggestion
        for (ModelFilter filter : filters)
```

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterAnd.java
> +        return true;
Un effet secondaire ici est que ce filtre ET est vrai si la liste des sous-filtres est vide, contrairement au filtre OU qui sera faux. Interdire la liste vide ne me choquerait pas, ou alors documenter ce comportement

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterHasMetadata.java
> +public class ModelFilterHasMetadata implements ModelFilter {
Je me demande si ce filtre ne devrait pas être plus simple (pas de liste), et que la classe de params s'appuie sur le filtre ET dans le cas où il reçoit une liste en paramètre. Parce que la logique de ET est dupliquée, sans optimisation particulière (puisqu'il n'y a pas grand chose d'optimisable ici), aussi basique soit-elle.

Je me fait cette remarque parce qu'il y a la même problématique de filtre vrai si la liste est vide, donc à interdire ou documenter, alors je me dis qu'on peut s'éviter cette redondance

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterNot.java
> +        return !this.filter.isSelected(model);
```suggestion
        return !filter.isSelected(model);
```

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterOr.java
> +        for (ModelFilter filter : this.filters)
```suggestion
        for (ModelFilter filter : filters)
```

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/ModelSelectionParams.java
> +public class ModelSelectionParams {
Tu fais sans doute référence à `PolymorphicParams`, mais non, ça n'est nécessaire que lorsqu'il s'agit d'une classe de params se basant sur un champ `type`, ce qui n'est pas le cas ici (au contraire, le champ `type` ici a une autre signification, c'est le type des modèles à sélectionner, par un type de classe à désérialiser)

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterAndParams.java
> +        return new ModelFilterAnd(and.stream().map(ModelFilterParams::create).collect(Collectors.toList()));
```suggestion
        return new ModelFilterAnd(and.stream().map(ModelFilterParams::create).toList());
```

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterMetadataEqualsParams.java
> +    public Object equals;
Qu'est-ce que Jackson désérialise pour un objet ? Est-ce qu'il ne faudrait pas un peu l'aider pour des valeurs un peu plus complexes ?

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterMetadataIn.java
> +public class ModelFilterMetadataIn implements ModelFilter {
Remarque un peu similaire ici sur le sujet du `in` / (`equals` + `OR`), en revanche ici une optimisation est possible donc ça se discute...

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterMetadataIn.java
> +        return false;
```suggestion
        return values.contains(model.getMetadata(name));
```

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterMetadataInParams.java
> +    public List<Object> in;
Qu'est-ce que tu veux dire par là ? Si on veut autoriser une liste vide ici ? Selon moi ça n'a pas trop de sens non, on pourrait l'interdire

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterOrParams.java
> +        return new ModelFilterOr(or.stream().map(ModelFilterParams::create).collect(Collectors.toList()));
```suggestion
        return new ModelFilterOr(or.stream().map(ModelFilterParams::create).toList());
```

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterParams.java
> +    @JsonSubTypes.Type(value = ModelFilterHasMetadataParams.class)
```suggestion
    @JsonSubTypes.Type(ModelFilterNotParams.class),
    @JsonSubTypes.Type(ModelFilterAndParams.class),
    @JsonSubTypes.Type(ModelFilterOrParams.class),
    @JsonSubTypes.Type(ModelFilterMetadataEqualsParams.class),
    @JsonSubTypes.Type(ModelFilterMetadataInParams.class),
    @JsonSubTypes.Type(ModelFilterHasMetadataParams.class)
```
En Java, si il n'y a qu'une seule valeur renseignée sur une annotation, elle s'appelle `value` automatiquement

Sinon une raison particulière pour avoir enregistré depuis l'annotation au lieu du `main` ?

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterParams.java
> +    public void validate() {};
```suggestion
    public void validate() {}
```

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterParams.java
J'ajouterais bien un `CustomModelFilterParams` dans lequel on peut enregistrer un predicate avec un nom depuis le `main`, et qui puisse se désérialiser ainsi :
```yaml
filter:
  custom: toto
```
Dans le futur on pourrait même imaginer que ça soit une hiérarchie comme le reste, avec des paramètres custom, mais dans un premier temps ça peut servir à étendre avec des filtres custom depuis le code (filtre sur la géométrie par exemple)

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/ModelRenderer.java
> +            return;
Est-ce que ce cas se présente vraiment ? Ça n'a pas trop de sens de ne pas avoir de sélection (une sélection vide ok, mais pas `null` ?)

2025-01-09 12:42 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/ModelRenderer.java
> +            } catch (ClassCastException e) {}
Cette exception ne se produit pas à la ligne 30 mais à la ligne 31 (du coup ça fonctionne, mais ça peut être un peu troublant)

En revanche je suis pas convaincu par cette idée. Du moins, pas comme ça.
Je verrais plutôt un filtre propre pour ne sélectionner que ceux qui ne vont pas causer d'erreur.
Ou alors on veut (notamment en environnement de dev, configuré en fail-fast) faire une erreur si ça se produit, mais on peut aussi le faire via un filtre plus propre.

Note : Ça nécessite de passer le type de modèle (`Class<M>`) en paramètre du constructeur de cette classe, mais ça ne me semble pas un problème du tout

2025-01-09 12:43 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +  - `filter`: Extra filter (optional, default none)
Pourquoi pas faire un ticket oui

2025-01-09 13:57 UTC, naulan-chrzaszcz commented on docs/usage/GenerationParameters.md
> +  - `filter`: Extra filter (optional, default none)
Je résous la conversation. Le ticket créé : MINALAC-95.

2025-01-09 13:59 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterMetadataInParams.java
> +    public List<Object> in;
> Si on veut autoriser une liste vide ici ?

Ouaip, c'est bien ce que je voulais dire (si c'était volontaire).

2025-01-09 16:05 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterMetadataInParams.java
> +    public List<Object> in;
S'il n'y avait eu les effets de bords bizarres, j'aurais dit, tant pis pour la liste vide mais effectivement, vaut mieux interdire.

2025-01-09 16:11 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilter.java
Ça serait pas mal à utiliser mais le fait de ne pas pouvoir faire de liste c'est tout de même dommage. J'imagine bien un jour un paramétrage avec un gros OR ou un AND de 3 ou 4 conditions.

Ou alors, utiliser Predicate mais garder le param avec les listes au quel cas, ça enlève des classes mais ça ne simplifie pas forcément le code.

Faudrait faire un sondage pour décider :D

2025-01-09 16:12 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterAnd.java
> +        return true;
Oui bien vu, je vais interdire les liste vides j'avais pas fait gaffe à ce comportement pas vraiment intuitif.

2025-01-09 16:14 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterHasMetadata.java
> +public class ModelFilterHasMetadata implements ModelFilter {
J'avais hésité. On peut limiter à 1 valeur et si on se retrouve avec un filtre à 15 trucs, on fera mieux à ce moment là.

2025-01-09 16:15 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterMetadataEqualsParams.java
> +    public Object equals;
Faudrait que je teste. J'avais dû vérifier pour les types de base.
Je suppose qu'il utilise les éventuels custom deserializers si on lui donne.

2025-01-09 16:18 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterMetadataIn.java
> +public class ModelFilterMetadataIn implements ModelFilter {
En revanche, je pense que ça peut être bien utile de pouvoir écrire un seul in plutôt que X or/equals (j'imagine que l'on va avoir souvent ce cas).

2025-01-09 16:21 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterParams.java
> +    @JsonSubTypes.Type(value = ModelFilterHasMetadataParams.class)
C'était plutôt pour me simplifier la vie.
Peut être faudrait il mettre les `ModelFilterMetadataInParams`, `ModelFilterMetadataEqualsParams` et `ModelFilterHasMetadataParams` dans le main car c'est customizable mais je garderai bien les And/Or/Not ici car je les trouve plus intrinsèques (pas vraiment de raison de s'en passer).

2025-01-09 16:58 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilter.java
Oui c'est ça, ça supprime beaucoup de classes pas super utiles (et qui ont très peu de code, mais ça conserve les classes de params actuelles pour la désérialisation bien sûr

2025-01-09 17:01 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterMetadataIn.java
> +public class ModelFilterMetadataIn implements ModelFilter {
Je ne sais pas si c'était très clair mais mes deux remarques de simplification de ces filtres (has et in) ne concernent que la partie code, pas les params (et donc la config), qui restent les mêmes en s'appuyant sur d'autres classes de code (ici une version plus simple et le OU)

2025-01-10 10:14 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterMetadataEqualsParams.java
> + * Parameters for a {@link ModelFilterMetadataIn} with an "equals" operator.
J'ai l'impression que "for" = pour la classe, "for a" = pour l'instance.

2025-01-10 10:16 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterMetadataEqualsParams.java
> +    public Object equals;
Pour les params c'est une bonne pratique (ça va rendre plus facile la rédaction/le controle de la doc)

2025-01-10 10:19 UTC, pyrollo commented on docs/usage/GenerationParameters.md
> +          in: [ Monument, Château, Chapelle, Eglise ]
Dilemne : anglais ou vraies données :) Ok ça va être anglais

2025-01-10 10:26 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/renderers/ModelRenderer.java
> +            return;
D'un côté ça donne envie de s'assurer qu'on aura pas de null (strict mode), en même temps, on le fait presque nulle part.

2025-01-10 11:27 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +          in: [ Monument, Château, Chapelle, Eglise ]
On peut trouver des vraies données anglaises si tu préfères 😄 
Dans l'optique de l'ouverture des sources, je suis d'accord je préfère plutôt l'anglais, de toutes façons les vraies données sont déjà présentes dans nos exemples sur la France du coup

2025-01-10 11:31 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/ModelRenderer.java
> +            return;
Selon moi cette vérification n'est pas vraiment à sa place ici, sinon ça veut dire qu'on devrait le faire à plein d'endroits... Et à ce sujet je pencherait plutôt vers une solution d'analyse statique à base d'annotations (non-`null` par défaut et `@Nullable` si besoin, par exemple)

2025-01-10 13:07 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/models/ModelSelectionParamsTest.java
> +    }
?MEMORYERROR

2025-01-10 13:13 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterMetadataIn.java
> +public class ModelFilterMetadataIn implements ModelFilter {
Mmmhh.. Je vais faire un essai, j'ai envie de voir ce que ça donne entre ta proposition (Predicate/"unaire") et l'actuel. Je ne suis pas sûr du plus clair/simple car la désérialisation du paramétrage risque de se compliquer. Je vais réoudre tout ce qui est simple/basique et je ferais peut être une seconde branche si j'hésite entre les deux orientations.

2025-01-10 13:16 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterParams.java
> +    @JsonSubTypes.Type(value = ModelFilterHasMetadataParams.class)
Reste à faire: mettre dans main les filtres MetadataXX

2025-01-10 13:17 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/ModelRenderer.java
> +                render(unchecked, bbox);
Maintenant que tu as la `Class<M>`, plus besoin d'`unchecked`
```suggestion
                render(cls.cast(model), bbox);
```

2025-01-13 13:48 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterParams.java
> +    @JsonSubTypes.Type(value = ModelFilterHasMetadataParams.class)
En me mettant dessus, j'ai un doute sur la déportation des enregistrement des filtres sur metadata dans main.

D'une part parce qu'il nous faudrait une nouvelle méthode d'enregistrement dans ParamParser pour les paramètres non polymorphiques, mais ça, tôt où tard, on va en avoir besoin.

D'autre part parce qu'il s'agit ici de filtres sur des attributs intrinsèques des modèles. Tous nos modèles ont des metadonnées et du coup, j'ai du mal à voir des cas où on ne veut pas de ces filres.

Au pire, faudrait les déclarer en même temps que le paramètrage de `Model`... mais c'est a peu près là qu'on est :D

2025-01-13 14:24 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterParams.java
> +    @JsonSubTypes.Type(value = ModelFilterHasMetadataParams.class)
Je ne pense pas qu'il y ai de situation où on n'en veuille pas, mais plutôt des situation où on veuille en ajouter. Si c'est possible des deux manières (ceux par défaut avec l'annotation, et en rajouter d'autres dans le main ou autre part), ça me dérange pas.

Le seul argument que je pourrais trouver serait d'avoir vraiment tout ce qui est enregistré par défaut au même endroit, pour des questions de lisibilité (pouvoir retrouver tout au même endroit). Je pense pas que ça soit suffisant pour justifier de déplacer ça pour l'instant. On verra quand on aura un endroit peut-être plus propre que le main, éventuellement.

En relisant ma propre remarque, je constate que c'était vraiment une question de "pourquoi" et je ne demandais pas spécialement à ce que ça soit bougé, simplement je voulais l'explication :)

2025-01-13 15:35 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterParams.java
Intéressant mais il manque ce qu'il faut pour lui passer d'éventuels paramètres. Ça marche pour les opérations unaires mais pas pour le reste.

Passer les paramètres signifie donc avoir une classe ..Params, ce qui 'est l'essentiel du code à faire (maintenant les filtres sont de simples Predicate<Model>).

(je réfléchis à l'écrit :D ):

Pour créer un filtre custom, on doit passer par du code:
* Dériver une classe de `ModelFilterParams` pour déséialiser les arguments;
* Faire en sorte que son create renvoie un `Predicate<Model>`;
* Enregistrer cette classe dan Jackson;

On reste avec deux zones à code : les arguments et le corps du predicat.

2025-01-13 15:48 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterParams.java
> Intéressant mais il manque ce qu'il faut pour lui passer d'éventuels paramètres. Ça marche pour les opérations unaires mais pas pour le reste.

Oui c'est ça, je pense que dans un premier temps ça me paraît intéressant d'avoir au moins le mécanisme pour enregistrer le filtre custom, et ensuite dans un second temps les paramètres. Si c'est prêt en même temps tant mieux, c'est du bonus :)

2025-01-13 15:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilter.java
Essayé et adopté!

2025-01-13 16:51 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterParams.java
Pour l'instant je vais laisser comme ça car je ne vois pas de cas d'usage unaire (hasGeometry ? Mais dans ce cas, on le developpe en standard).

2025-01-13 17:02 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterParams.java
Dommage.

Les usages sont justement d'ouvrir la porte à ce qu'on ne voit pas tout de suite :)

En l'occurrence, même si il s'agit par exemple de filtrer les modèles dont l'aire est inférieure à 12, au moins ça permet de faire le filtre avec 12 hardcodé, et plus tard quand les paramètres seront possibles, cela pourra être amélioré.

Typiquement ça permet d'offrir (à un moindre coût) la possibilité de le faire, pour éviter d'être bloqué en attendant que ça soit possible. Par exemple sur un autre sujet mais le principe est le même, je ne peux pas rebase ma branche `indy/demo-digital-twin` car il n'est plus possible de faire des voxels recevant des informations depuis le code. Et c'est dommage parce qu'en attendant je ne profite pas des autres améliorations au final. Bon là c'est pas exactement pareil, puisqu'il n'y avait rien avant, mais je sais pas si tu comprends l'idée.

2025-01-14 07:41 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterParams.java
En même temps, là, créer un filtre hardcodé reste tout à fait possible. Ajouter un custom filter ne simplifie qu'un tout petit peu (coder 1 fonction au lieu d'une classe).

Pour les voxel, faut qu'on en cause, j'ai pas capté.

EDIT: Ah oui, pour ajouter un filtre, manque un petit truc sur ParamParser pour avoir accès au mapper.

2025-01-14 12:25 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterMetadataEqualsParams.java
> +    public Object equals;
Bon a priori, Jackson se débrouille en fonction de ce qui est enregistré. Donc pour l'instant ça fonctionne avec ce que l'on a besoin.
En revanche, une fois la PR de Naulan mergée, cela vaut peut être le coup d'ajouter un "as" pour spécifier le bon type.

2025-01-22 18:36 UTC, naulan-chrzaszcz submitted a review, later dismissed
Je n'ai pas pris le temps de comprendre le code

2025-01-22 18:36 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterHasMetadata.java
> +public class ModelFilterHasMetadata implements Predicate<Model>  {
```suggestion
public class ModelFilterHasMetadata implements Predicate<Model> {
```

2025-01-22 18:36 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterMetadataIn.java
> +public class ModelFilterMetadataIn implements Predicate<Model>  {
```suggestion
public class ModelFilterMetadataIn implements Predicate<Model> {
```
Ta fait plusieurs fois le même soucis de style j'ai l'impression

2025-01-22 18:36 UTC, naulan-chrzaszcz commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +   /**
```suggestion
    /**
```

2025-01-28 10:53 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterMetadataEqualsParams.java
> +    public Object equals;
Le ValueParser est maintenant utilisé pour typer la valeur.

2025-01-28 10:53 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/models/filters/ModelFilterMetadataIn.java
> +public class ModelFilterMetadataIn implements ModelFilter {
Adopté !

2025-01-28 10:54 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterParams.java
Pour l'instant j'arrête là cette PR, cela fera l'objet d'une nouvelle PR.

2025-02-06 13:18 UTC, esgn submitted a review, later dismissed
Done a first review. Will do a second visit.

2025-02-06 13:18 UTC, esgn commented on docs/dev/Parameters.md
> +By parameters we mean input Yaml or Json data describing wanted generation.
desired generation seems more appropriate

2025-02-06 13:18 UTC, esgn commented on docs/dev/Parameters.md
> +class TestParams {
Test like in unit testing ? Don't think so. Maybe change the class name ?

2025-02-06 13:18 UTC, esgn commented on docs/usage/GenerationParameters.md
> +Usual boolean operations can be applied on filter to alter them or combine them.
`on filters` ?

2025-02-06 13:18 UTC, esgn commented on docs/usage/GenerationParameters.md
> +
A more advanced example could be interesting here to wrap it up
```
and:
  - ...filter1...
  - not:
    ...filter2...
  - or:
    - ...filter3...
    - ...filter4... 
```
Which is equivalent to `filter1 AND (NOT filter2) AND (filter3 OR filter4)`

2025-02-06 13:18 UTC, esgn commented on docs/usage/GenerationParameters.md
> +  - `as` (optional, default `text`): Type of value to compare with (`integer`, `decimal`, `text` or `boolean`)
`as` is only applied to the value from the yaml file. The metadata will not be casted using the `as` type. The user will be responsible for making sure the metadata and value type are similar. This could be documented here.

I ran the following test by modifying default.yaml :

```yaml
sources:
  bati:
    modelType: building
    provider:
      type: wfs
      url: https://data.geopf.fr/wfs/wfs
      features: BDTOPO_V3:batiment
    processor:
      type: geoToolsVector
    postProcessors:
    ...
    - type: default
      metadata: bogus
      value: 666
      as: text
  ...
renderers:
  ...
  building:
    type: vector
    models:
      type: building
      filter: 
        metadata: bogus
        equals: 666
        as: integer
 ```   
=> No warning. Buildings are missing from result. Comparison between text and integer results in selecting no building model.


```yaml
sources:
  bati:
    modelType: building
    provider:
      type: wfs
      url: https://data.geopf.fr/wfs/wfs
      features: BDTOPO_V3:batiment
    processor:
      type: geoToolsVector
    postProcessors:
    ...
    - type: default
      metadata: bogus
      value: 666
      as: text
  ...
renderers:
  ...
  building:
    type: vector
    models:
      type: building
      filter: 
        metadata: bogus
        equals: 666
        as: text
 ```   
=> Buildings are in the result as expected

**Do we need to inform the user about the discrepancy between value and metadata type ? Or at least document it ?**

2025-02-06 13:18 UTC, esgn commented on src/main/java/com/ignfab/minalac/generator/models/ModelSelection.java
> +     * @param filter a filter on models to narrow selection
to narrow down

2025-02-06 13:18 UTC, esgn commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +            } catch (IllegalArgumentException e) {}
silent failure ?

2025-02-06 13:18 UTC, esgn commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +            if (!PARSERS.containsKey(name))
duplicated code ?

2025-02-06 13:18 UTC, esgn commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterAndParams.java
> +            throw new IllegalArgumentException("There must be at least one sub-filter (should have been tested with validation!)");
Tested by and.isEmpty() in validate already ? If so why keep this check ?

2025-02-06 13:18 UTC, esgn commented on docs/usage/GenerationParameters.md
> +Models are always selected on their type and that selection could be narrowed by an extra filter. This filter can be a combination of other filters.
selection may be narrowed down using an extra filter

2025-02-06 13:18 UTC, esgn commented on src/test/java/com/ignfab/minalac/generator/models/ModelSelectionTest.java
> -        Model model2 = new ModelImpl();
Why naming these objects model5 and model2 as they are identical and empty ?

2025-02-06 13:18 UTC, esgn commented on src/test/java/com/ignfab/minalac/generator/models/ModelSelectionTest.java
>          store.add("digit", model2);
Why two "digit" objects ? Is one not enough ?

2025-02-06 13:18 UTC, esgn commented on src/test/java/com/ignfab/minalac/generator/models/ModelSelectionTest.java
> -    private static class ModelImpl extends Model {
Should we test filtering on a metadata that do no exist here ? ModelFilterHasMetadata("c") typically

2025-02-06 13:18 UTC, esgn commented on src/test/java/com/ignfab/minalac/generator/parameters/ValueParserTest.java
> +        assertThrows(JsonMappingException.class, () -> ParamsTester.deserialize(ValueParser.class, "yolo"));
toto, dummy, yolo ... a lot of placeholder. Maybe choose one once and for all. dummy ? foo ?

2025-02-06 13:18 UTC, esgn commented on src/test/java/com/ignfab/minalac/generator/parameters/ValueParserTest.java
> +        assertThrows(NumberFormatException.class, () -> ValueParser.INTEGER.parse("12345.67890"));
Misssing a case like `assertThrows(NumberFormatException.class, () -> ValueParser.INTEGER.parse("dummy"));` ?

2025-02-06 17:01 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/ModelSelectionParams.java
> +    public String type;
```suggestion
    @JsonSetter(nulls = Nulls.FAIL)
    public String type;
```

2025-02-06 17:01 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/models/ModelSelectionParamsTest.java
> +        params.filter = new TestingModelFilterParams(false);
Comment these tests

2025-02-06 17:01 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/ValueParserTest.java
> +        assertThrows(NumberFormatException.class, () -> ValueParser.INTEGER.parse("12345.67890"));
"12345.67890" teste déjà ce cas.

2025-02-06 17:02 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/ValueParserTest.java
> +        assertThrows(JsonMappingException.class, () -> ParamsTester.deserialize(ValueParser.class, "yolo"));
Would make testing dull :'(

2025-02-10 10:22 UTC, esgn commented on src/test/java/com/ignfab/minalac/generator/parameters/ValueParserTest.java
> +        assertThrows(JsonMappingException.class, () -> ParamsTester.deserialize(ValueParser.class, "yolo"));
OK. As long as it's not "bruh" or a swear word ;)

2025-02-10 10:57 UTC, indyteo reviewed
J'ai trouvé quelques typos dans la doc au début, et finalement j'ai aussi review les warnings que j'avais de mon côté.
Bref, beaucoup de remarques pour pas grand chose, surtout de la propreté de code

2025-02-10 10:57 UTC, indyteo commented on docs/dev/Parameters.md
> +Built in parsers are :
```suggestion
Built in parsers are:
```

2025-02-10 10:57 UTC, indyteo commented on docs/dev/Parameters.md
> +        // Parse value accroding to as:
```suggestion
        // Parse value according to as:
```

2025-02-10 10:57 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +    ...filter2...
```suggestion
      ...filter2...
```

2025-02-10 10:57 UTC, indyteo commented on docs/usage/GenerationParameters.md
> +**Be carerful with typing!** Value comparison includes type. Values with different type won't be equal. Metadata with text value "5" won't equal to 5 as integer.
```suggestion
**Be careful with typing!** Value comparison includes type. Values with different type won't be equal. Metadata with text value "5" won't equal to 5 as integer.
```

2025-02-10 10:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/models/ModelSelection.java
> +        return Iterators.filter(store.getByType(type).iterator(), this.filter::test);
```suggestion
        if (filter == null)
            return store.getByType(type).iterator();

        return Iterators.filter(store.getByType(type).iterator(), filter);
```

2025-02-10 10:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +    public static final ValueParser<Integer> INTEGER = new ValueParser<Integer>(Integer.class, obj -> Integer.valueOf(obj.toString()));
```suggestion
    public static final ValueParser<Integer> INTEGER = new ValueParser<>(Integer.class, obj -> Integer.valueOf(obj.toString()));
```

2025-02-10 10:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +    public static final ValueParser<Double> DOUBLE = new ValueParser<Double>(Double.class, obj -> Double.valueOf(obj.toString()));
```suggestion
    public static final ValueParser<Double> DOUBLE = new ValueParser<>(Double.class, obj -> Double.valueOf(obj.toString()));
```

2025-02-10 10:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +    public static final ValueParser<String> STRING = new ValueParser<String>(String.class, Object::toString);
```suggestion
    public static final ValueParser<String> STRING = new ValueParser<>(String.class, Object::toString);
```

2025-02-10 10:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +    public static final ValueParser<Boolean> BOOLEAN = new ValueParser<Boolean>(Boolean.class, obj -> (obj instanceof Boolean bool) ? bool : switch (obj.toString()) {
```suggestion
    public static final ValueParser<Boolean> BOOLEAN = new ValueParser<>(Boolean.class, obj -> (obj instanceof Boolean bool) ? bool : switch (obj.toString()) {
```

2025-02-10 10:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +    };
```suggestion
    }
```

2025-02-10 10:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/ValueParser.java
> +            throws IOException, JsonMappingException {
```suggestion
            throws IOException {
```

2025-02-10 10:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/ModelSelectionParams.java
> +    };
```suggestion
    }
```

2025-02-10 10:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterHasMetadataParams.java
> +        throw new IllegalArgumentException("There must be at least one metadata name");
```suggestion
            throw new IllegalArgumentException("There must be at least one metadata name");
```

2025-02-10 10:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/HeightmapRenderer.java
>      private Heightmap heightmap;
```suggestion
    private final Heightmap heightmap;
```

2025-02-10 10:57 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/renderers/HeightmapRenderer.java
>                  heightmap.set(c, (int) Math.round(value.value()));
```suggestion
                heightmap.set(c, Math.round(value.value()));
```

2025-02-10 10:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/models/filters/TestingModelFilter.java
> +    private Model model;
```suggestion
    private final Model model;
```

2025-02-10 10:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/ValueParserTest.java
> +        assertDoesNotThrow(() -> new ValueParser<String>(String.class, Object::toString));
```suggestion
        assertDoesNotThrow(() -> new ValueParser<>(String.class, Object::toString));
```

2025-02-10 10:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/ValueParserTest.java
> +        ValueParser<?> parser = new ValueParser<String>(String.class, Object::toString);
```suggestion
        ValueParser<?> parser = new ValueParser<>(String.class, Object::toString);
```

2025-02-10 10:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/ValueParserTest.java
> +        result = (Integer) assertDoesNotThrow(() -> ValueParser.INTEGER.parse("1234567890"));
```suggestion
        result = assertDoesNotThrow(() -> ValueParser.INTEGER.parse("1234567890"));
```

2025-02-10 10:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/ValueParserTest.java
> +        result = (Integer) assertDoesNotThrow(() -> ValueParser.INTEGER.parse("-3"));
```suggestion
        result = assertDoesNotThrow(() -> ValueParser.INTEGER.parse("-3"));
```

2025-02-10 10:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/ValueParserTest.java
> +        assertEquals(1234567890, result);
```suggestion
        result = assertDoesNotThrow(() -> ValueParser.DOUBLE.parse("12345.67890"));
        assertEquals(12345.6789, result);

        result = assertDoesNotThrow(() -> ValueParser.DOUBLE.parse("-9"));
        assertEquals(-9, result);

        result = assertDoesNotThrow(() -> ValueParser.DOUBLE.parse(1234567890));
        assertEquals(1234567890, result);
```

2025-02-10 10:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/ValueParserTest.java
> +        assertEquals("dummy", (String) ValueParser.STRING.parse("dummy"));
```suggestion
        assertEquals("dummy", ValueParser.STRING.parse("dummy"));
```

2025-02-10 10:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/ValueParserTest.java
> +        assertFalse((Boolean) assertDoesNotThrow(() -> ValueParser.BOOLEAN.parse(false)));
```suggestion
        assertTrue(assertDoesNotThrow(() -> ValueParser.BOOLEAN.parse("true")));
        assertTrue(assertDoesNotThrow(() -> ValueParser.BOOLEAN.parse(true)));
        assertFalse(assertDoesNotThrow(() -> ValueParser.BOOLEAN.parse("false")));
        assertFalse(assertDoesNotThrow(() -> ValueParser.BOOLEAN.parse(false)));
```

2025-02-10 10:57 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterAndParamsTest.java
> +        assertDoesNotThrow(() -> new ModelFilterAndParams(Arrays.asList(
Juste une remarque (pas obligatoire de changer) sur `Arrays.asList(...)`, il existe maintenant en Java `List.of(...)` qui fait relativement la même chose, à part que c'est plus court à écrire, et ça optimise les cas de liste de 0, 1 ou 2 éléments. À noter pour la suite :)

2025-02-10 14:11 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterAndParamsTest.java
> +        assertDoesNotThrow(() -> new ModelFilterAndParams(Arrays.asList(
Ça sonne vachement mieux !

2025-02-10 14:56 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/ValueParserTest.java
> +        assertThrows(JsonMappingException.class, () -> ParamsTester.deserialize(ValueParser.class, "yolo"));
Is "smeg" ok ?

2025-02-10 15:12 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterAndParamsTest.java
> +        assertDoesNotThrow(() -> new ModelFilterAndParams(Arrays.asList(
C'est aussi plus agréable à lire `List.of()` que `Collections.emptyList()`.

2025-02-10 15:33 UTC, indyteo commented on src/test/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterAndParamsTest.java
> +        assertDoesNotThrow(() -> new ModelFilterAndParams(Arrays.asList(
Concernant la liste vide, les avis sont partagés : Il n'y a pas de différence de performance (en réalité, la seule différence de code est quelques détails comme le fait que `List.of().contains(null)` est une erreur, ou encore `Collections.emptyList().addAll(Collections.emptyList())` ne fait rien alors que `List.of().addAll(Collections.emptyList())` lance une `UnsupportedOperationException`)

Personnellement, lorsque l'intention est de passer une liste délibérément vide (et pas qu'on a oublié de remplir...), je préfère `Collections.emptyList()` qui met l'accent sur le côté "vide" de la liste. Quand ça n'a pas d'importance qu'il s'agisse d'une liste vide ou pleine, qu'on a juste besoin d'une liste pour que le test compile, mais que c'est pas vraiment ça le cœur du test, autant rester uniforme avec le reste, c'est à dire `List.of()`.

En pratique, l'un ou l'autre ne change pas non plus la face du monde 😄

2025-02-10 15:42 UTC, indyteo commented on examples/default.yaml
Est-ce que `minecraft.yaml` a été modifié aussi ?

2025-02-10 19:15 UTC, esgn commented on src/test/java/com/ignfab/minalac/generator/parameters/ValueParserTest.java
> +        assertThrows(JsonMappingException.class, () -> ParamsTester.deserialize(ValueParser.class, "yolo"));
_Lister, do you have any conception of the penalty for describing a superior technician as a smeghead?_

2025-02-11 08:13 UTC, pyrollo commented on examples/default.yaml
Nope,  je le fais.
Vivement que l'on ait un truc du genre #78

2025-02-11 08:18 UTC, pyrollo commented on examples/default.yaml
Done !

2025-02-11 08:21 UTC, pyrollo commented on src/test/java/com/ignfab/minalac/generator/parameters/models/filters/ModelFilterAndParamsTest.java
> +        assertDoesNotThrow(() -> new ModelFilterAndParams(Arrays.asList(
Ok, je pense que je vais opter pour List.of() dans les tests, surtout si j'ai déjà d'autres List.of(...) et effecivement peut être continuer avec Collections (mais qui ajoute un import et que je trouve moins lisible) comme tu dis, quand c'est vraiment une liste vide que l'on veut.

2025-02-11 09:29 UTC, indyteo approved these changes

2025-02-11 10:55 UTC, merged