feat(generation): Move projection & conversion stuff to Generation class
ignfab/voxatile pull request #9
Opened 2024-05-29 15:26 UTC by pyrollo

Cette PR déplace une partie du code écrit dans SampleImplementation vers sa classe de destination, Generation.
Des tests ont été ajoutés mais le fonctionnement global n'a pas changé.

2024-05-29 23:27 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            );
Dans le futur, la génération pourrait recevoir directement l'objet des params, non ?

2024-05-30 06:31 UTC, pyrollo commented on src/main/java/com/ignfab/minalac/generator/SampleImplementation.java
> +            );
Oui, la question n'est pas encore tranchée est: Est-ce que le décodage des paramètres produit un objet GenerationParams ou bien directement un objet Generation.
La seconde solution me plait car elle découple complètement le traitement des paramètres. En tout cas, je pars là dessus pour les Renderers, on peut en causer.

2024-05-30 09:53 UTC, indyteo commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +     * @return the {@code WorldCoords2d} of the maximum point.
Copié collé raté

2024-05-30 14:20 UTC, zhak5388 requested changes
Bon, du coup, mes commentaires c'est principalement de la forme/typo (Requested change pour la typo sur world)

2024-05-30 14:20 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +     * Returns geographic envelope (bounding box equivalent) of generated wolrd
*world

2024-05-30 14:20 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/generation/Generation.java
> +    {
Alors, je sais pas si on un code style uniforme mais est ce que il est d'usage d'aller à la ligne avec `{` ?

2024-05-30 14:20 UTC, zhak5388 commented on src/main/java/com/ignfab/minalac/generator/utils/world2d/WorldBBox2d.java
> +     * Returns the minimum point X coordinate.
Ici, je serai tenté de mettre `x-coordinate`au lieu `X coordinate` histoire d'être uniforme au sein de la classe

2024-05-30 14:20 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/generation/TestGeneration.java
> +    public void testGeneration() throws NoSuchAuthorityCodeException, FactoryException, TransformException {
Je pense que `NoSuchAuthorityCodeException` n'est pas nécessaire (C'est une sous exception de `FactoryException` il me semble)

2024-05-30 14:20 UTC, zhak5388 commented on src/test/java/com/ignfab/minalac/generator/generation/TestGeneration.java
> +import com.ignfab.minalac.generator.generation.CoordsConverter;
Les imports de `Generation` et `CoordsConverter` sont nécessaires vu que c'est le même package?

2024-05-30 18:01 UTC, indyteo approved these changes

2024-05-31 08:02 UTC, zhak5388 approved these changes

2024-05-31 08:05 UTC, merged